- bootstrap/bootstrap.go
- bootstrap/tracing.go
- tracetools/span.go
**This PR:** Makes a bunch more changes to the OpenTelemetry implementation (a few of which get backported to the datadog tracing implementation too!). Technically, we [de-experimented opentelemetry](https://github.com/buildkite/agent/pull/1702) a couple of days ago, so _technically_ we shouldn't make any breaking changes, but the de-experimentation hasn't been shipped yet so 🤷
These changes mostly only affect the opentel integration; those that also affect the datadog implementation will be noted in the diff. There shouldn't be any backwards incompatible changes.
The changes we've made are:
- Rename the tracing service name from `buildkite_agent` to `buildkite-agent`
- Trace each part of the artifact upload phase individually - previously we had one chonky span for the whole step, now we …
> Otel polishing 2: Electric Boogaloo

- README.md
- api/agents.go
- clicommand/agent_start.go
**This PR:** Adds a smallish list of feature enabled to the agent register request, allowing us at buildkite a bit more visibility into what features of the agent our users actually used. This telemetry is on by default, but doesn't collect any sensitive info, and can be disabled using the `--no-telemetry` flag.
> Include a list of enabled features in the register request

- bootstrap/bootstrap.go
- hook/scriptwrapper.go
- hook/scriptwrapper_test.go
The ScriptWrapper part of the bootstrap is really hard to understand, but honestly, a large part of that is because the scripts themselves are really hard to read. At current, they use string concatenation nonsense that's just really difficult to decipher.
This PR takes the string concatenation nonsense and replaces it with Go Templates, as well as adding tests to catch regressions in script generation
> Less hideous script wrapper

- CHANGELOG.md
- agent/version.go
**This PR:** Cuts a release for Agent 3.38.0, which promotes opentelemetry to not being an experiment.
> Bump version + changelog for v3.38.0

- .buildkite/docker-compose.yml
- Gemfile.lock
For some reason, after [updating our deployer image](https://github.com/buildkite/agent/pull/1716), debian releases are now failing, as it appears that bundler has gone away as part of that process.
This PR runs `gem install bundler` before running `bundle install` in the debian deploy process.
It'd be nice to get rid of the gemfile completely - this is a go project after all, but that's a problem for tomorrow.
> Update bundler version to be compatible with Ruby 2.7.6 alpine image

- logger/level.go
`ERROR` should have a higher log level than `WARNING`.
Fix https://github.com/buildkite/agent/issues/1720
> Fix warning log level

- logger/level.go
We changed the iota placement of the `logger.Level` const in #1720 to fix log levels, but in doing so forgot to chage the placement in the `levelNames` array. This means that if someone were to use `--log-level error` it would behave like error, but say it was using warning logging.
I really wish that go had real enums.
> Fix order of level names for logger.Level.String()

- agent/artifact_downloader.go
- agent/s3.go
- agent/s3_downloader.go
- agent/s3_downloader_test.go
- agent/s3_uploader.go
- pool/pool.go
**🤔 Problem:** Currently, when downloading multiple artifacts in the agent, we initialise an S3 client for each artifact that we're downloading. This is problematic for a couple of reasons, first of which is that the credential initialisation actually [involves a call to S3](https://github.com/buildkite/agent/blob/main/agent/s3.go#L132-L135), so if there's a lot of artifacts to download, the the `ListObjects` calls made by each credential initialisation will contribute to our rate limits.
The other issue is that we don't need to create an S3 client per call, and it actually hurts us in a couple of ways; first and foremost, as reported by a customer, each client initialisation first has to authenticate with AWS. We've seen evidence that when a lot of artifacts are being uploaded, this …
> Cache S3 clients between artifact downloads

- agent/plugin/plugin_test.go
We had a report on [hackerone (only available to buildkite staff unfortunately!)](https://hackerone.com/reports/1653984#), reporting that one of our plugin definitions in the plugin tests refers to a org/repo combo that doesn't belong to buildkite. 
While this **currently poses no security risk** as we don't actually clone or run the plugins as part of the tests, it's not out of the question that we might run/clone plugins as part of tests in the future, so we should change this reference to something that we own, just in case.
> Fix unowned plugin reference

- agent/plugin/plugin.go
- agent/plugin/plugin_test.go
**Context:** https://github.com/buildkite/agent/pull/1641, https://github.com/buildkite/agent/pull/1744
**🤔 Problem:** Currently, when cloning plugins from Gitlab, we assume that the repo path structure is the same as github (that is, `org/repo`), and consider anything not matching that path to be an invalid plugin reference. The trouble is, in Gitlab, there can be multiple levels of nesting in a repo path, with the pattern `some-org/some/hierarchy/of/teams/repo` - for example `https://gitlab.com/example-corp/devops/aws/lambda/example-buildkite-plugin`. If one of these multi-nested repos is used as a BK plugin reference, we'll erroneously say that it's an invalid plugin path, and fail the pipeline.
**✅ Solution:** This PR adds an additional branch to our plugin reference checking gear, …
> Fix multiple-nested plugin repos on gitlab

- .buildkite/steps/publish-rpm-package.sh
Specify `libcrypto3>=3.0.5-r2` from `https://dl-cdn.alpinelinux.org/alpine/edge/main` so that `createrepo_c` from `https://dl-cdn.alpinelinux.org/alpine/edge/testing` installs without “so:libcrypto.so.3 (no such package)” error.
Currently this release step is broken:
https://buildkite.com/buildkite/agent-release-edge/builds/449#0182ae98-d45d-44fd-b71c-bd90f2085f37
> CI: fix createrepo_c / libcrypto3 Alpine/APK edge breakage

- clicommand/agent_start.go
@moskyb and I spent a few minutes reading the git manual to remember what `-ffxdq` actually tells `git clean` to do. Figured we'd add that knowledge as a code comment to help future travellers on their way.
> Code comment explaining -ffxdq flags for git clean

- agent/agent_worker.go
- agent/integration/job_runner_integration_test.go
- agent/job_runner.go
- api/jobs.go
Ooooh, super spicy secret new feature!
We have a new feature in the works where agents will get assigned a buildkite agent API token for each job that they run, have that token only work on operations for that job, and make that token have a limited lifetime.
This means that if a bad actor exfiltrates a buildkite API token from a job running in your buildkite account, they won't be able to use that token to mess with stuff that's not on that job, and also the token they exfiltrate will expire.
This PR does the agent-side of this feature - consuming a token sent by the `jobs#accept` response, and using that token for operations within the job.
We're still working on the backend side of this work, and we won't merge this until that part of the work is done.
> Consume per-job agent tokens

- agent/gcp_labels.go
- agent/gcp_meta_data.go
Add `gcp:instance-name` tag in `--tags-from-gcp-meta-data` mode. The existing `gcp:instance-id` is numeric (e.g. `6502291863206740772`) and less friendly/useful than the name.
Also, in `--tags-from-gcp-labels` mode, fetch GCP labels by instance _name_, not instance _id_. The [`instances.get` REST API](https://cloud.google.com/compute/docs/reference/rest/v1/instances/get) specifies “Name of the instance” but appears to also accept the numeric ID. However using the name allows GCP IAM condition expressions to match against a prefix of the instance name, as demonstrated in this Terraform example:
```terraform
resource "google_project_iam_member" "compute_viewer" {
project = var.gcp_project
member  = "serviceAccount:${google_service_account.default.email}"
role    = "roles/compute.viewer" …
```
> gcp:instance-name and tweak GCP labels fetching

- agent/agent_worker.go
- agent/agent_worker_test.go
We've had some situations where the Agent Disconnect API call fails (e.g. HTTP 500 or 502), which leaves the agent in a connected state on the server side; this is normally cleared within 5 minutes, but in some situations could take longer. During that time, jobs may be assigned to the “ghost” agent, preventing them actually running on another connected agent.
This pull request retries the Disconnect API call up to 4 times, with a constant 1 second delay between tries. This keeps the total duration under 4-5 seconds; disconnection should remain fast as part of agent shutdown, even if the API fails.
This PR also introduces test coverage for `AgentWorker.Disconnect`, both without and with failure retries.
Alongside this, I've opened an issue at https://github.com/buildkite/roko/issues/2 so …
> Retry Disconnect API calls

- packaging/docker/alpine-linux/entrypoint.sh
- packaging/docker/ubuntu-18.04-linux/entrypoint.sh
- packaging/docker/ubuntu-20.04-linux/entrypoint.sh
Remove the `-g` option from `/sbin/tini` in the entrypoint of the Docker images shipped with the agent.
> By default, Tini only kills its immediate child process.
> With the `-g` option, Tini kills the child process group, so that
> every process in the group gets the signal.
buildkite-agent runs as a direct subprocess of tini, and will propagate the signals appropriately to its subprocesses.
Resolves #1758 (more context in that issue), thanks @com6056!
Related:
- #1758
- #1637
> Docker: run /sbin/tini without -g for graceful termination

- CHANGELOG.md
- agent/version.go
[Full Changelog](https://github.com/buildkite/agent/compare/v3.38.0...v3.39.0)
- gcp:instance-name and tweak GCP labels fetching [#1742](https://github.com/buildkite/agent/pull/1742) (@pda)
- Support for not-yet-released per-job agent tokens [#1745](https://github.com/buildkite/agent/pull/1745) (@moskyb)
- Retry Disconnect API calls [#1761](https://github.com/buildkite/agent/pull/1761) (@pda)
- Only search for finished artifacts [#1728](https://github.com/buildkite/agent/pull/1728) (@moskyb)
- Cache S3 clients between artifact downloads [#1732](https://github.com/buildkite/agent/pull/1732) (@moskyb)
- Document label edge case [#1718](https://github.com/buildkite/agent/pull/1718) (@plaindocs)
- Docker: run /sbin/tini without -g for graceful termination …
> Bump version and CHANGELOG for v3.39.0

- .buildkite/pipeline.yml
This adds arm64 windows binaries to our official build matrix. Originally requested in #1282, but at the time we were nervous about enabling because:
* none of us had access to windows/arm64 systems
* it required a golang 1.17+, and we were compiling the agent with 1.16
These days we're compiling the agent with golang 1.18 so windows/arm64 is a target that Just Works. An arm64 windows environment is also super easy to boot using parallels 18 on an Apple Silicon machine, and we have plenty of those.
I tested this by manually cross compiling compiling a windows/arm64 binary on my linux laptop and then using it inside an arm parallels VM.
Compilation on Linux:
GOOS=windows GOARCH=arm64 go build -o buildkite-agent-win-arm64 .
On buildkite:
Fixes #1282
> build agent binaries for windows/arm64

- agent/job_runner.go
- api/retryable.go
We occasionally see 502 responses from the Agent API when starting a job:
```
Failed to run job: PUT https://agent.buildkite.com/v3/jobs/0183a95c-c17e-4b0f-8058-e405362c6dc7/start: 502
```
Since those responses likely indicate a transient issue, I think it makes sense to attempt to retry those and other 5xx responses for this call rather than failing and having the job be re-scheduled. Open to any suggestions or input y'all might have.
> retry 5xx responses when attempting to start a job

- bootstrap/integration/artifact_integration_test.go
- bootstrap/integration/bootstrap_tester.go
- bootstrap/integration/checkout_integration_test.go
- bootstrap/integration/command_integration_test.go
- bootstrap/integration/docker_integration_test.go
- bootstrap/integration/hooks_integration_test.go
- bootstrap/shell/test.go
- clicommand/env.go
- hook/scriptwrapper.go
- hook/scriptwrapper_test.go
- main.go
> [WIP] Replace export -p with a dedicated agent command for printing env

- CHANGELOG.md
- agent/version.go
[Full Changelog](https://github.com/buildkite/agent/compare/v3.39.0...v3.39.1)
- Fix security issue where in certain situations, agents using bash v5.2 could have some environment variables leak to job logs. See the [issue](https://github.com/buildkite/agent/issues/1780) and [our security advisory](https://buildkite.com/changelog/167-security-advisory-for-buildkite-agent-and-bash-5-dot-2) for more information. [#1781](https://github.com/buildkite/agent/pull/1781) (@moskyb + @triarius + @pda) (@moskyb)
> Bump version and CHANGELOG for 3.39.1

- .buildkite/steps/release-homebrew.sh
Our homebrew release step wasn't working for a little while, because we'd misconfigured the branch protection settings on the homebrew-buildkite repo. The failure only printed out the status code (409? why?), which made it harder to diagnose the issue.
This PR replaces the curl `--fail` flag with `--fail-with-body`, which does the same thing, but means that it'll print the response when the command fails, making issues with this process easier to diagnose in the future.
> When homebrew releases fail, print the body of the API call that failed

- clicommand/env.go
This has consequences for the generated docs. I'm not going to dig too
deeply in to why, but without the right whitespace in the help
text, the docs don't escape the command usage as code.
Before:
```
buildkite-agent env [options]
``
```
After:
```
`buildkite-agent env [options]`
```
But furthermore, this is consistent with the situation for other sub commands.
```
Usage:
buildkite-agent meta-data <command> [options...]
Available commands are:
set     Set data on a build
get     Get data from a build
exists  Check to see if the meta data key exists for a build
keys    Lists all meta-data keys that have been previously set
help    Shows a list of commands or help for one command
Options:
--help, -h  show help
```
Before:
```
Usage:
buildkite-agent env [options]
Description:
Prints out the …
```
> Add line break in env command usage

- agent/gs_uploader.go
- agent/plugin/plugin_test.go
- bootstrap/bootstrap.go
- bootstrap/git.go
- env/environment.go
- env/environment_test.go
- env/export.go
Beyond the usual formatting of `gofmt`, the `-s` flag applies some straightforward simplifications, such as removing redundant types. While useful from time to time, it is usually unnecessary to enforce it on every change, so I left the gofmt test alone.
> Apply `gofmt -s` simplifications

- redaction/redactor.go
- redaction/redactor_test.go
redactor.go:100 ranges over a string (needle), and in Go, ranging over a string iterates each _rune_ each of which can be a single or multibyte code point. But the rest of the redactor deals in bytes, particularly the table array.
This also updates the misleadingly-named test to (a) a better name and (b) actually look at the redacted output.
> redaction: treat needles as byte slices

- bootstrap/shell/shell_test.go
- go.mod
- go.sum
The race in bintest that causes TestInterrupt to fail should now be fixed.
While I'm here, replace uses of io/ioutil (deprecated).
> bootstrap/shell: re-enable TestInterrupt under -race

- .buildkite/steps/tests.sh
This means that every JUnit file will have a unique file name, should stop the test annotate step from failing intermittently
> Key JUnit files with the step ID, rather than the OS

- clicommand/env.go
- env/environment.go
- env/environment_test.go
Windows can have interestingly-named environment variables (#1804). This update changes both the env command and env subpackage to handle variables with names starting with '='.
It is debatable whether to filter out these variables or preserve them. Preserving them feels like the least surprising option to me. I did some brief experimenting on Windows and didn't uncover huge issues. But I'm willing to be convinced otherwise.
I've also taken the opportunity to slightly simplify the env command implementation. 
Fixes #1804
> env: handle '='-prefixed vars

- env/environment.go
- env/environment_test.go
To maintain the same behaviour as before, we've instead decided to drop them instead of preserve them. 
This changes the outcome for #1804, but #1804 remains fixed.
> env: Disallow variables starting with =

- agent/artifactory_uploader.go
- agent/form_uploader_test.go
- agent/gs_uploader.go
- agent/job_runner.go
- agent/plugin/definition.go
- api/client.go
- bootstrap/bootstrap.go
- bootstrap/integration/artifact_integration_test.go
- bootstrap/integration/bootstrap_tester.go
- bootstrap/integration/checkout_integration_test.go
- bootstrap/integration/git.go
- bootstrap/integration/hooks_integration_test.go
- bootstrap/integration/plugin_integration_test.go
- bootstrap/knownhosts_test.go
- bootstrap/shell/logger.go
- bootstrap/shell/tempfile.go
- bootstrap/shell/test.go
- clicommand/agent_start_test.go
- clicommand/annotate.go
- clicommand/meta_data_set.go
- clicommand/pipeline_upload.go
- clicommand/profiler.go
- clicommand/step_update.go
- hook/scriptwrapper_test.go
- logger/log.go
- process/cat.go
- stdin/main_test.go
io/ioutil was deprecated as of Go 1.16. Equivalent functionality is now in the io or os packages. 
Do this cleanup in one go so I stop doing it piece-by-piece.
> Replace deprecated ioutil calls with equivalents

- agent/artifact_downloader_test.go
- agent/artifact_searcher_test.go
- agent/artifact_uploader_test.go
- agent/artifactory_uploader_test.go
- agent/form_uploader.go
- agent/form_uploader_test.go
- agent/gcp_meta_data_test.go
- agent/gs_uploader_test.go
- agent/integration/job_runner_integration_test.go
- agent/pipeline_parser_test.go
- agent/s3_uploader_test.go
- agent/tags_test.go
- go.mod
- go.sum
This is the first chunk in a series of tidy-ups. This one focuses
on tests in the agent subpackage and applying comments from
https://github.com/golang/go/wiki/TestComments
(excluding the comment about assert libraries).
> agent: Tidy up t.Error/t.Fatal (part 1)

- api/client_test.go
- bootstrap/bootstrap.go
- bootstrap/config_test.go
- bootstrap/git_test.go
- bootstrap/integration/artifact_integration_test.go
- bootstrap/integration/bootstrap_tester.go
- bootstrap/integration/checkout_integration_test.go
- bootstrap/knownhosts_test.go
- bootstrap/ssh_test.go
This is the second chunk in a series of tidy-ups. This one focuses on tests in the bootstrap subpackage, including a few tests in bootstrap/integration (but not all), and applying comments from https://github.com/golang/go/wiki/TestComments (excluding the comment about assert libraries, which is a battle to fight later).
`TestCleaningAnExistingCheckout`(checkout_integration_test.go), appears to be buggy: test.txt is seemingly not removed, and existence was not properly checked, so it erroneously passed. It is skipped (for now).
> bootstrap: Tidy up t.Error/t.Fatal (part 2)

- bootstrap/integration/command_integration_test.go
- bootstrap/integration/docker_integration_test.go
- bootstrap/integration/hooks_integration_test.go
- bootstrap/integration/plugin_integration_test.go
- bootstrap/shell/logger_test.go
- bootstrap/shell/shell_test.go
- bootstrap/shell/test.go
This is the third chunk in a series of tidy-ups. This one focuses on
tests in the bootstrap subpackage, and applies some comments from
https://github.com/golang/go/wiki/TestComments.
> bootstrap: Tidy up t.Error/t.Fatal (part 3)

- install.ps1
In #1767 we added windows/arm64 to the official build matrix for the agent. However, the recommended powershell install script in our docs looks like this:
PS> $env:buildkiteAgentToken = "<your_token>"
PS> Set-ExecutionPolicy Bypass -Scope Process -Force
iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/buildkite/agent/main/install.ps1'))
.. and it always decides what binary to download by fetching this URL with a hard coded amd64 arch:
$ curl "https://buildkite.com/agent/releases/latest?platform=windows&arch=amd64"
version=3.39.0
filename=buildkite-agent-windows-amd64-3.39.0.zip
url=https://github.com/buildkite/agent/releases/download/v3.39.0/buildkite-agent-windows-amd64-3.39.0.zip
This PR updates the install.ps1 script to detect the architecture …
> Update windows install script to detect arm64 systems [FDN-1134]

- api/oidc.go
- api/oidc_test.go
- clicommand/oidc_request_token.go
This adds a `--lifetime` parameter to the `buidlkite-agent oidc request-token` command. This will be interpreted as an integer number of seconds. The API will add this to the current time (at the API server) and use this value for the `exp` claim in the OIDC token. Note that specifying `0` (or omitting) will result in the API's default lifetime being used instead.
> Add support for requesting custom lifetime to `buildkite-agent oidc request-token`

- bootstrap/bootstrap.go
- bootstrap/integration/plugin_integration_test.go
Passes `--recursive` to `git clone` when cloning a plugin, if submodules are enabled for the bootstrap.
Fixes #1807.
> bootstrap: Clone plugins with `--recursive`

- agent/agent_pool.go
- agent/agent_worker.go
- agent/integration/job_runner_integration_test.go
- agent/job_runner.go
- bootstrap/bootstrap.go
- bootstrap/bootstrap_test.go
- bootstrap/docker.go
- bootstrap/git.go
- bootstrap/git_test.go
- bootstrap/knownhosts.go
- bootstrap/knownhosts_test.go
- bootstrap/shell/shell.go
- bootstrap/shell/shell_test.go
- bootstrap/ssh.go
- bootstrap/ssh_test.go
- clicommand/agent_start.go
- process/process.go
- process/process_test.go
Some of the core code (shell.go, process.go) stored contexts and cancellation funcs in structs. The context package doc is clear about not doing this: https://pkg.go.dev/context. This PR removes context fields, and then makes all the consequent changes to pass context through function args instead.
> Tidy up context.Context

- main.go
We have started to use the cli.Context's App.ErrWriter in some places
now, but it is created to be nil. This results in runtime panics if we
try to write to it.
> Set ErrWriter

- clicommand/oidc_request_token.go
The API does not allow non-positive lifetimes. However, a combination of the cli framework we depend on, and the configuration parsing we have written means that there is no good way to distinguish between omitted configuration values and those that are set to the zero value for their type (e.g. 0 for integers). So we have to let the cli take a 0 valued lifetime, but that will not be passed on the API.
> Add restrictions on possible lifetime values at the clicommand level

- packaging/docker/alpine-linux-k8s/Dockerfile
- packaging/docker/alpine-linux/Dockerfile
The `docker-compose` alpine package contains docker compose v1 as a standalone tool.
The `docker-cli-compose` alpine package contains docker compose v2 as a docker plugin.
Not having `docker-cli-compose` in the agent docker image causes it to fail with the docker compose buildkite plugin when using `cli-version: 2`.
> Install docker compose plugin in agent alpine docker images

- README.md
- agent/doc.go
- api/doc.go
- bootstrap/bootstrap.go
- bootstrap/integration/doc.go
- bootstrap/shell/shell.go
- clicommand/doc.go
- cliconfig/loader.go
- env/environment.go
- experiments/experiments.go
- hook/hook.go
- logger/log.go
- main.go
- metrics/metrics.go
- mime/generate.go
- mime/mime.go
- pool/pool.go
- process/process.go
- race/doc.go
- redaction/redactor.go
- stdin/stdin.go
- system/doc.go
- tracetools/doc.go
- utils/doc.go
- yamltojson/yaml.go
This adds package comments, briefly explaining what each subpackage does. Where a package `foo` has a `foo.go`, the comment is added to the top of that file, otherwise I have added a new `doc.go` for the comment.
I've also added a pkg.go.dev badge. To make it look neater, I moved the build status badge out of the heading.
> Add package comments and pkg.go.dev badge

- clicommand/annotate.go
- clicommand/annotate_test.go
- clicommand/artifact_shasum_test.go
Buildkite imposes a maximum body size of 1MiB. Return a fatal error early instead of waiting for a round-trip API request.
I borrowed the `annotate` function and tests pattern from `ArtifactShasumCommand`.
(The diff is easier to see with [whitespace changes turned off](https://github.com/buildkite/agent/pull/1844/files?diff=unified&w=1))
> Early exit when annotation exceeds max body size

- agent/plugin/definition.go
- agent/plugin/definition_test.go
- agent/plugin/plugin.go
- agent/plugin/plugin_test.go
This PR adds a package comment and doc comments to all exported top-level identifiers to the plugin package. It also makes some opportunistic cleanups:
- All the tests are more consistent, using table-driven tests throughout
- ValidateResult stores errors directly rather than error strings, so as to be more useful under the forthcoming Go 1.20 multi-errors Unwrap convention
- New sentinel error values enable more semantic error checking
- Consolidated regexps: declaration and compilation are within single var block, and previously duplicated regexps are un-duplicated.
> agent/plugin: Doc comments and cleanups

- go.mod
- go.sum
See [CVE-2020-9283](https://www.cve.org/CVERecord?id=CVE-2020-9283) and [Snyk entry](https://security.snyk.io/vuln/SNYK-GOLANG-GOLANGORGXCRYPTOSSH-551923) for more information.
Note that as far as we can tell, **the buildkite agent is not vulnerable to the issue posted above.**
Fixes #1856
> Update x/crypto/ssh to 0.3.0, patching CVE-2020-9283

- agent/agent_worker.go
- api/retryable.go
**Context:** A [recent incident](https://www.buildkitestatus.com/incidents/m8f0dnxtmjbz) at Buildkite caused an issue to occur with some agents where their connection state was invalidated,  and were marked as ‘lost’ in the buildkite backend. 
this caused them to get into a halfway-between state where the agent is still alive, but still unsuccessfully trying to talk to the buildkite agent API. because the agent is already past the point in its code where it would usually try to authenticate with the API, it just loops trying to connect to an API that will never successfully authenticate its requests.
the buildkite API was returning a 401 to all requests from the agent, and the agent would say "okay :)" and then retry a bit later, blissfully unaware that no requests would ever succeed. …
> Ensure that unrecoverable errors for Hearbeat and Ping stop the agent

- .buildkite/Dockerfile-compile
- .buildkite/build/ssh.conf
- bootstrap/docker.go
- bootstrap/git.go
- bootstrap/git_test.go
- bootstrap/shell/test.go
- process/process.go
This mainly changes a test from invoking a bintest mock, to invoking the real `ssh` and testing the string parsing logic separately. 
`resolveGitHost` is refactored into two parts: "invoking `ssh -G`" and "parsing the output" (`hostFromSSHG`).
The new tests will detect if SSH ever formats its output differently in a breaking way, and removes two instances of bintest, which may be the source of test flakes.
> bootstrap: Replace mock ssh with container preparation

- bootstrap/bootstrap.go
- bootstrap/knownhosts.go
- bootstrap/shell/shell.go
- go.mod
github.com/pkg/errors is archived, and the README says it is in maintenance mode. The standard library `errors` package is built-in.
> Use stdlib errors instead of github.com/pkg/errors

- bootstrap/bootstrap.go
- bootstrap/config.go
- bootstrap/integration/bootstrap_tester.go
- bootstrap/integration/checkout_integration_test.go
- clicommand/bootstrap.go
This was disabled upstream due to a [security vulnerability in git](https://github.blog/2022-10-18-git-security-vulnerabilities-announced/#cve-2022-39253). That caused the test TestCheckingOutLocalGitProjectWithSubmodules to fail. It has only been passing in CI because we run a version of git in CI that did not receive the patch.
One solution would have been to set `protocol.file.allow=always` globally. However, that would mean that anyone who ran the tests would expose their environment to that vulnerability, and permanently if the global config were not unset afterwards.
Thus, in this PR, the config is only applied for the commands that need it. As one such command was in the default checkout hook, a configuration option was added so that the config would only be enabled in the test …
> Add git config protocol.file.allow=always to tests

- bootstrap/knownhosts_test.go
- go.mod
- go.sum
TestAddingToKnownHosts was (a) a bit flaky, because of the use of bintest, which still seems to fail sometimes, and (b) not self-contained, as it key-scanned hosts on the internet.
This PR:
* Removes the mock ssh command
* Remove implicitly testing aliases - it is already tested elsewhere
* Run a fake SSH server for keyscanning instead of scanning GitHub.
Fixes #1890
> bootstrap: TestAddingToKnownHosts flake and isolation fixes

- agent/ecs_meta_data.go
- agent/tags.go
- agent/tags_test.go
- clicommand/agent_start.go
- go.mod
- go.sum
Adds selected ECS metadata as agent tags. The metadata that I felt was useful to add was:
- Container name
- Docker image
- ECS task ARN
Tested a custom build on our infrastructure:
> Add agent tags from ECS container metadata

- CHANGELOG.md
I just realised I made a typo in the CHANGELOG.md title for the v.3.42.0 release 🙁.
> Update CHANGELOG title for v3.42.0

- clicommand/bootstrap.go
There's a very narrow use case for this env variable, so let's suggest
an alternative that is more suitable for what people are likely to want.
> Update help text for an Env varible

- agent/pipeline_parser.go
- agent/pipeline_parser_test.go
- agent/plugin/definition.go
- agent/plugin/definition_test.go
- agent/plugin/plugin.go
- agent/plugin/plugin_test.go
- api/client.go
- api/pipelines.go
- bootstrap/integration/checkout_integration_test.go
- bootstrap/integration/docker_integration_test.go
- bootstrap/integration/git.go
- bootstrap/integration/plugin_integration_test.go
- bootstrap/shell/logger.go
- clicommand/global.go
- cliconfig/loader.go
- logger/buffer.go
- logger/field.go
- logger/log.go
- logger/log_test.go
- mime/generate.go
- tracetools/span_test.go
- yamltojson/yaml.go
We currently use a mix of `interface{}` and `any` to refer to values of any type in our codebase. For the sake of consistency, i've run an `s/interface{}/any/g` over the codebase.
This is the world's most useless change, i'm not really fussed if it doesn't make it in, but i do much prefer `any` over `interface{}`. Knowing that the empty interface means any type (and, indeed that the type `interface{}` refers to an empty interface and not something else, and that an empty interface matches any type) requires a bit more go knowledge than seeing the word `any` and thinking "oh that can be any type"
> Replace all usages of interface{} with any

- .github/dependabot.yml
We could pin the major and minor versions, but that may not work https://github.com/dependabot/dependabot-core/pull/6115.
Instead, because there is no patch version, dependabot should actually
never make a PR for these Dockerfiles. Thus, we can ignore them entirely
> Make dependabot ignore ubuntu docker image versions 

- bootstrap/integration/bootstrap_tester.go
- clicommand/env_dump.go
- hook/scriptwrapper.go
- hook/scriptwrapper_test.go
- main.go
Move the `buildkite-agent env` command (which dumps environment to stdout) to `buildkite-agent env dump`, making `buildkite-agent env` just a container for this and any future subcommands relating to environment.
As suggested by @sj26 in October: https://github.com/buildkite/agent/pull/1803#issuecomment-1296327269
More recently the idea of a `buildkite-agent env set <key> <value>` command came up in [Re: 💡 Agent sockets - Pipelines Dispatch ⚙️](https://3.basecamp.com/3453178/buckets/27608512/messages/5721116595#__recording_5725223825)
It's relatively safe to assume that the only usage of the existing `buildkite-agent env` command is by the agent itself, making it essentially a private/internal API which we can safely change.
> CLI: 'env' command moved to 'env dump' subcommand

- .buildkite/steps/test-docker-image.sh
- packaging/docker/ubuntu-20.04/Dockerfile
Tini used to be downloaded from github to /usr/sbin/tini. Now we install it
from the ubuntu repositories which installs to /usr/bin/tini.
Both are in the $PATH, so there should be no issue if a user invokes the
command as `tini`. Also, the default entrypoint is using the new path to
tini, so users starting the docker container without overriding the default
entrypoint should not have experienced any issues.
Fixes: #1928
> Restore old tini path on ubuntu 20.04

- agent/pipeline_parser.go
- agent/pipeline_parser_test.go
- agent/plugin/definition.go
- clicommand/pipeline_upload.go
- go.mod
- go.sum
- yamltojson/yaml.go
- yamltojson/yaml_test.go
I took a crack at upgrading to v3 of the YAML package, gopkg.in/yaml.v3. This removes the need for our own fork of v2, at the expense of some hairy processing code. I think this is a win, because the new code exposes exactly how we are handling the YAML, rather than hiding it in an unmaintained fork.
yaml.v3 replaces `yaml.MapSlice` and `yaml.MapItem` with a far more flexible type, `yaml.Node`. Unmarshalling into `yaml.Node` provides just about all possible information contained in the input YAML, but replacing `MapSlice` with `Node` is definitely not straightforward. A mapping node's contents is no longer represented by a slice of `MapItem`s (key/value pairs) but rather a slice of `Node`s [key, value, key, value... ]. Using `Node` directly necessitates a bunch of helper code, as seen in …
> Upgrade to yaml.v3

- clicommand/agent_start.go
- cliconfig/file.go
- cliconfig/loader.go
Closes #1936 
**This PR:** Generally gives the error handling for config loading a lick of paint, using error wrapping appropriately, and giving much more context when config loading fails.
As reported in #1936, previously, a malformed config file would cause the agent to simply print "Can't separate key from value" (to stdout).
Now, the same malformed config file prints out
```
Error loading config: loading config file: parsing config line: can't separate key from value in string "        \"AWSCURRENT\"", no valid separators (= or :) found
```
to stderr.
This should give users more info to be able to fix their configuration issues.
Additionally in this PR, i've modified a couple of the existing error messages to be a bit clearer, and made them all lowercase, so that go vet stops giving …
> Give better errors when config loading fails

- bootstrap/shell/shell.go
This was added in go1.12. Presumably, the replaced code may have originated prior to that. That code only claims support on Unixes, but the method from the standard library we are replacing it with should be more portable. Indeed, the [file](https://github.com/golang/go/blob/de4748c47c67392a57f250714509f590f68ad395/src/os/exec_posix.go#L130-L136) that defines the method is headed with `//go:build unix || (js && wasm) || windows`, so it should be available for windows as well. And it looks like it is [implemented for Plan 9](https://github.com/golang/go/blob/de4748c47c67392a57f250714509f590f68ad395/src/os/exec_plan9.go#L143-L149) as well.
From the [discussions](https://groups.google.com/g/golang-nuts/c/sFmzNL-0zq4) [around](https://github.com/golang/go/issues/26539) introducing the …
> Use ExitCode method from standard library to inspect the exit code of a process

- clicommand/agent_start.go
- clicommand/annotate.go
- clicommand/annotation_remove.go
- clicommand/artifact_download.go
- clicommand/artifact_search.go
- clicommand/artifact_shasum.go
- clicommand/artifact_upload.go
- clicommand/bootstrap.go
- clicommand/env_dump.go
- clicommand/meta_data_exists.go
- clicommand/meta_data_get.go
- clicommand/meta_data_keys.go
- clicommand/meta_data_set.go
- clicommand/pipeline_upload.go
- clicommand/step_get.go
- clicommand/step_update.go
- main.go
The CLI command descriptions aren't ever changed, nor are they used outside the clicommand package.
For consistency, the templates in main.go are updated the same way.
> clicommand: Descriptions unexported and const

- agent/agent_configuration.go
- agent/job_runner.go
- bootstrap/bootstrap.go
- bootstrap/config.go
- clicommand/agent_start.go
- clicommand/bootstrap.go
Unfortunately, turns out `git checkout` doesn't have a `--no-verify` option, so not immediately useful to me. Opening in case it's useful for others.
Closes #1888
> add git-checkout-flags

- .gitignore
- agent/agent_worker.go
- agent/job_runner.go
- bootstrap/bootstrap.go
- bootstrap/shell/shell.go
- kubernetes/kubernetes.go
- kubernetes/kubernetes_test.go
- kubernetes/umask.go
- kubernetes/umask_windows.go
- process/process.go
Building this out as part of our work in https://github.com/buildkite/agent-stack-k8s/tree/v2
This changes the agent `start` and `bootstrap` commands to be able to operate in a client/server model, rather than a parent process/child process model.
This is what a successful run would look like, imagining `bootstrap 1` and `bootstrap 2` are running commands like cloning the git repository, running tests:
```mermaid
sequenceDiagram
participant bapi as Buildkite API
participant server as agent/server
participant c1 as bootstrap 1
participant c2 as bootstrap 2
server->>server: listen
server->>bapi: acquire job
c1->>server: connect
c2->>server: connect
c1->>server: wait for start
c2->>server: wait for start
server->>c1: start
c1->>c1: run to completion
c1->>server: exit 0
server->>c2: start …
```
> Kubernetes job runner

- clicommand/pipeline_upload.go
In all cases where the pipeline cannot be marshaled to JSON, there is no point to retry the upload.
Retries will keep the agent busy for about 5 min, which is a waste of customers' compute time.
> Check that a pipeline upload error actually comes from the JSON marshaller and exit early

- agent/s3.go
At this point in `NewS3Client`, `sess` is unset, leading to a fun and useful panic if no region is discoverable (e.g. you aren't using AWS.)
> agent/s3.go: Fix nil pointer dereference

- templates/launchd.plist
fix 353 see https://github.com/buildkite/docs/issues/353#issuecomment-1435758739
edit: 
The Error occurs because by default (without LimitLoadToSessionType) launchd tries to load the agent into the Aqua context but this context doesnt exist when you are only logged in using ssh. 
The -S Background option tells launchd to load the agent into the Background Context. See changes in this PR for matching changes to the docs: https://github.com/buildkite/docs/pull/1875#issue-1590513215
> fix 353 - fix this Error when using ssh : 'launchctl on macos fails with "Could not find domain for"'

- .buildkite/pipeline.bk-test.yml
- .buildkite/steps/test-bk.sh
- agent/api.go
- agent/pipeline_uploader.go
- agent/pipeline_uploader_test.go
- api/client.go
- api/pipelines.go
- clicommand/pipeline_upload.go
This is a new method of uploading pipelines introduced in the agent API 
which will reduce long held connections between client and server. It works
by first uploading the Pipeline with a client generated UUID to the same
route as before, but with the query parameter `async=true` set.
Unlike waiting up to 15 seconds as before, this will return status 202 immediately 
with a `Location` header set to where to check the status of the upload.
The API will also set a `Retry-After` header to inform the client to sleep for this duration. 
The agent will then poll the route returned as the `Location` header until the status of the upload is "applied".
If the API does not support the Async Upload Flow, it will return 200 for the initial pipeline upload instead of 202. Then the agent will revert to …
> Implement Async Pipeline Upload Flow

- .buildkite/pipeline.yml
- .buildkite/steps/build-docker-image.sh
- .buildkite/steps/extract-agent-version-metadata.sh
- .buildkite/steps/publish-docker-image.sh
- .buildkite/steps/publish-docker-images.sh
- .buildkite/steps/upload-release-steps.sh
- .github/dependabot.yml
- README.md
- packaging/docker/ubuntu-22.04/Dockerfile
- packaging/docker/ubuntu-22.04/buildkite-agent.cfg
- packaging/docker/ubuntu-22.04/entrypoint.sh
Provide the agent on an Ubuntu 22.04 image.
There were some complications with building a multiarch image for Ubuntu 22.04.
The version of qemu on the agent's instance is out of date an this is the most likely reason for the failure.
We attempted to solve this at the Elastic CI Stack level, but to no avail.
We had more success with upgrading binfmt in the build script, so that is what we do in this PR.
For more details about the solution see https://github.com/docker/buildx/issues/314.
> Ubuntu 22.04 Docker Image

- bootstrap/bootstrap.go
- bootstrap/integration/checkout_integration_test.go
Add support for using reference repositories for submodules in addition to regular repositories.
This is an improved version of #1935 which was reverted in #1949.
It fixes the following issues discovered after #1935 was merged:
* Each submodule repo would append the arguments `submodule update --init --recursive --force` to the git command.
* The reference repos for submodules didn't seem to be be created on the first run. This is in contrast to what happens when using a reference repo for the top level.
* Submodule checkout behavior was affected even when the `git-mirrors` experiment wasn't enabled
A brief overview of other changes:
* `updateGitMirror` now takes the repository to update as a parameter.
* Since we need it in two places now, I pulled the code for getting and/or updating …
> use reference clones for submodules redux

- bootstrap/shell/shell.go
To allow building in docker images without bash (e.g. alpine). While this should respect `BUILDKITE_SHELL`, it did not before, so I'm not going to make it do so here.
> Use sh instead of bash in RunScript

- api/oidc.go
- clicommand/oidc_request_token.go
This adds a new `claim` flag that may be specified multiple times to add elements to a `claims` field to the JSON body of the OIDC token request to buildkite.com.
> Allow adding claims to the OIDC token request

- agent/pipeline_uploader.go
- agent/pipeline_uploader_test.go
I made a snafu in https://github.com/buildkite/agent/pull/1927 that meant that if the API only supported the old upload flow, the pipeline would be uploaded once more than necessary.
This is evidenced by the failure of the test in this build: https://buildkite.com/buildkite/agent/builds/5316.
This is not impacting the correctness of uploads, as they are deduped by a UUID would have been the same between all the uploads. However, it is not necessary to perform the extra upload, so let's remove it.
> Fix extra pipeline uploaded in fallback upload flow

- CHANGELOG.md
- bootstrap/shell/shell.go
Reverts buildkite/agent#1974
This might need further consideration.
When testing on a (what I consider fairly stock-standard) Debian machine I have handy, my (what I consider perfectly reasonable) command hook:
```shell
#!/bin/bash
set -euo pipefail
...snip...
```
fails with the error:
```
/tmp/buildkite-agent-bootstrap-hook-runner-3400400749: 2: set: Illegal option -o pipefail
```
because it turns out that `/bin/sh` is symlinked to `dash`, not `bash`, and I think `RunScript` passes scripts directly to whatever shell binary it picks.
> Revert "Use sh instead of bash in RunScript"

- clicommand/bootstrap.go
> clicommand/bootstrap.go: Change backticks to primes

- agent/s3.go
**This introduces a new `BUILDKITE_S3_ENDPOINT` environment variable** to configure the S3 client used by artifact upload/download to use an alternate [endpoint](https://docs.aws.amazon.com/sdk-for-go/api/aws/endpoints/), e.g. a [MinIO](https://min.io/) server.
Note that this is distinct from `BUILDKITE_S3_ACCESS_URL` which is intended to specify e.g. a proxy _in front of_ S3 to e.g. access artifacts from a private bucket via some other HTTP auth scheme.
~It also introduces `BUILDKITE_S3_FORCE_PATH_STYLE` environment variable~ _(`S3ForcePathStyle` is implicit now when `BUILDKITE_S3_ENDPOINT` is set)_; setting this to a [truthy](https://pkg.go.dev/strconv#ParseBool) value enables [`S3ForcePathStyle`](https://github.com/aws/aws-sdk-go/blob/v1.44.181/aws/config.go#L118-L127) on the S3 client …
> BUILDKITE_S3_ENDPOINT env var (e.g. MinIO support)

- .buildkite/steps/build-docker-image.sh
There was a race contition in the previous code that caused test flake. More details are in the comment.
> Use flock to lock qemu-binfmt installation

- .buildkite/steps/build-docker-image.sh
The race condition mentioned in https://github.com/buildkite/agent/pull/1990 can also happen while one worker is building an image (on a non-native architecture) and other is installing qemu-binfmt. So this PR protects those operations with flock as well.
> Extend lock to image building

- bootstrap/bootstrap.go
- bootstrap/integration/checkout_integration_test.go
Hi, it's me again :wave:
After rolling out v3.44.0 of the agent in our production environment, I found yet another bug in my latest attempt at the deceptively complex task of supporting reference repositories for submodules. It's less bad than the previous ones, but still! :cry: [This call](https://github.com/buildkite/agent/blob/ccbe12d16daf6760779bc26ad99c3330b902cfed/bootstrap/bootstrap.go#L1440) to `getOrUpdateMirrorDir` can return an empty string for `mirrorDir` if the mirror doesn't exist, and then we don't check the value of `mirrorDir` before we attempt to use it [here](https://github.com/buildkite/agent/blob/ccbe12d16daf6760779bc26ad99c3330b902cfed/bootstrap/bootstrap.go#L1449).
Luckily it seems like that's only a problem in the case that someone:
1. has enabled the `git-mirror` …
> remove remote add from ref repo submodule handling

- agent/artifact_uploader.go
- agent/s3.go
- bootstrap/bootstrap.go
While investigating #2001, we ran into an issue where a direct error comparison `err == os.ErrNotExist` was causing test failures, where `errors.Is(err, os.ErrNotExist)` was okay. This is because `errors.Is` will unwrap errors, and return true if any of the unwrapped errors match the second arg.
**This PR:** Replaces most of the usages of `err == <whatever>` with `errors.Is(err, <whatever>)`. This makes these comparisons more robust, and establishes a better SOP within the agent codebase.
It also adds error wrapping to the artifact uploader, which also didn't quite fit in #2001, and is kinda-sorta more relevant to this PR.
> Prefer `errors.Is(err, <whatever>)` over `err == <whatever>`

- bootstrap/tracing.go
We're seeing this in our job logs:
```
2023/03/10 00:53:18 Datadog Tracer v1.46.0 WARN: ddtrace/tracer: deprecated config WithServiceName should not be used with `WithService` or `DD_SERVICE`; integration service name will not be set.
```
> Fix DD trace setup warning

- agent/k8s_tags.go
- agent/k8s_tags_test.go
- agent/tags.go
These are set by the controller in the companion PR: https://github.com/buildkite/agent-stack-k8s/pull/137
> Add tags from env variables provided by the controller in agent-stack-k8s if kuberenetes-exec experiment is enabled

- .buildkite/steps/test-docker-image.sh
- packaging/docker/alpine-k8s/Dockerfile
- packaging/docker/alpine/Dockerfile
- packaging/docker/ubuntu-18.04/Dockerfile
- packaging/docker/ubuntu-20.04/Dockerfile
- packaging/docker/ubuntu-22.04/Dockerfile
Some of the docker image building solutions on Kubernetes involve a [buildkit](https://docs.docker.com/build/buildkit/) service. The plugin `buildx` is used to give the docker CLI access to these, but it is not installed on our default agent image, even though the docker CLI is. If it were, we could instruct customers to use the agent image as the image in their image building step.
> Add buildx to docker images

- agent/job_runner.go
- agent/log_streamer.go
- api/chunks.go
- process/buffer.go
- process/buffer_test.go
- process/scanner.go
The `String` method on `bytes.Buffer` does not consume the buffer in the same way that `Read` does - it leaves the contents in place. Because `output` is never `Read` or `Truncate`-d, it never shrinks. Also Go almost certainly copies the internal `[]byte` into a new `string` (or vice-versa).
It appears the agent never needs the whole copy of the logs, though.
This replaces the buffer implementation with a new one (in a new file, with a test) that _only_ has `Write` and `ReadAndTruncate` methods. This implementation, directly working on a byte slice, is (imo) at least as simple as a `bytes.Buffer` (but then you have to know how much you want to read, which, yes, you can get with `Len`, or you can use `io.ReadAll`, but it's about the same).
The output chunking logic is reworked, since it no …
> Avoid holding full job logs

- go.mod
we now have two groups of go modules, one for direct dependencies and one for indirect, as ~~god~~ rsc intended
> Why did we have three groups of go modules?

- clicommand/env_get.go
- clicommand/env_set.go
- clicommand/env_unset.go
- jobapi/client.go
- jobapi/client_test.go
- main.go
This is the "client half" of #1943. It adds a client for the socket-based current-job API, and three new subcommands that exercise the Get, Update, and Delete methods:
```shell
buildkite-agent env get
buildkite-agent env set ...
buildkite-agent env unset ...
```
Edit 1: renamed "delete" to "unset"
> Add subcommands to modify env vars using Job API

- agent/job_runner.go
- process/prefixer.go
- process/prefixer_test.go
Looking at some of the log display code, we may need ANSI timestamps to reflect the start of each line, rather than the end. (sigh)
Fortunately, this admits a buffer-free implementation!
This PR should avoid the over-eager computation of the _next_ line's prefix, which was the main bug fixed with #1940.
> ansi-timestamps: Compute prefixes at start of line

- agent/job_runner.go
- kubernetes/kubernetes.go
If a job is cancelled via the Buildkite API, for example, by clicking the cancel button on the website and the bootstrap container in the Kubernetes pod has not started, the exit status will be 0. This causes the build to pass in situations where it should not.
In this PR, we detect if child containers of the agent start container have not run and provide a non-zero exit status. In addition, the agent start container will emit a faked job log that informs the user that a container may not have run. Otherwise, if the Buildkite job was automatically cancelled, as will be the case after https://github.com/buildkite/agent-stack-k8s/pull/143 is merged, the user would not have a good idea what the cause of the cancellation was.
> Set a non-zero exit status when a job is cancelled in Kubernetes

- bootstrap/bootstrap.go
- bootstrap/shell/shell.go
- env/environment.go
- env/environment_test.go
- hook/scriptwrapper_test.go
This prevents the bootstrap from accidentally copying the environment when processing the output of a scriptwrapper, which was preventing environment updates from the job api from showing up
> Make env.Environment.Merge and .Apply operate in-place

- agent/api.go
- agent/pipeline_uploader.go
- api/pipelines.go
I've decided to keep the fallback mechanism. While the API current does NOT support falling back to a sync pipeline upload if the `?async=true` param is provided, we could decided to re-impliment it in the future. While this is unlikely, I think it is a good idea to leave this in the agent code base in cases users are stuck on a version that won't support such fallback.
> Remove code for non async pipeline upload

- agent/artifact_batch_creator.go
- agent/artifact_uploader.go
When ArtifactUploader calls `UpdateArtifacts` (`PUT /v3/jobs/{uuid}/artifacts`), in the uncommon event of something stalling server-side or network-wise, the server and the client each take 60 seconds to time out, and the retry would wait a further 5 seconds. `UpdateArtifacts` is idempotent and called inside a retry loop, so we're better off timing out sooner and retrying sooner.
The p99 response time for this endpoint is ~50ms, so timing out after 5 seconds (100x the p99) seems more than reasonable. And reducing the initial retry delay (but backing off exponentially) also keeps things moving faster.
This means if `buildkite-agent artifact upload …` is invoked with a reasonable _external_ timeout of e.g. 30 or 60 seconds, a single server/network stall won't use up all that time, and a …
> ArtifactUploader API calls: faster timeout & retry

- agent/ec2_meta_data.go
- agent/ecs_meta_data.go
- go.sum
Add some more meta-data tags to agents running on aws.
This switches ec2 meta-data to a single instance identity document which should be slightly more efficient, and adds some more useful meta-data including region and az when running on ec2.
This also upgrades the ecs metadata library we were using so it can grab task meta-data as well as container meta-data, and uses that to add availability zone, launch type (fargate or not) and cpu/memory limits ("size") there as well.
AWS have some example data here:
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-metadata-endpoint-v3.html#task-metadata-endpoint-v3-examples
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-metadata-endpoint-v4.html#task-metadata-endpoint-v4-examples
and the ecs meta-data module is a …
> More aws tags

- clicommand/bootstrap.go
- clicommand/global.go
- experiments/experiments.go
**This PR:** Makes it so that if a user enables an unknown experiment (ie, one that's not in the codebase), we'll emit a warning on the logger.
Additionally, for us, it creates a canonical list of available experiments in code, meaning that to find which experiments are in progress, we no longer have to do a global search across the repo for `experiments.IsEnbabled(` to find all of them.
> Warn on unknown experiments

- clicommand/env_dump.go
- clicommand/env_get.go
- clicommand/env_set.go
- clicommand/env_unset.go
During the collaboration to merge the docs PR https://github.com/buildkite/docs/pull/1954, some changes were made that need to be backported.
This DO NOT cover all of the changes, just a managable chunk of them. We will need to refine the docs generation process to reconcile some of the remainging differences.
> Backport fixes from docs

- clicommand/global.go
Private keys are private! We should avoid leaking them into the logs if possible. Potentially we should just redact anything that ends with `*_KEY`? We can get to that later
> Add *_PRIVATE_KEY to auto-redacted vars

- EXPERIMENTS.md
- bootstrap/bootstrap.go
- experiments/experiments.go
We've received reports that when an agent is checking out a commit and the job is canceled, that the agent does not gracefully respond to the interrupt signal, and instead will retry the git checkout and continue with the job. This means that the job is forcibly killed.
My understanding of job cancelation is that:
JobRunner polls the Agent API for the [state of the job](https://github.com/buildkite/agent/blob/cancelation_for_checkout/agent/job_runner.go#L890:L891) and calls [JobRunner.cancel()](https://github.com/buildkite/agent/blob/v3.45.0/agent/job_runner.go#L499) which then [interrupts](https://github.com/buildkite/agent/blob/cancelation_for_checkout/agent/job_runner.go#L542:L543) the bootstrap process [with](https://github.com/buildkite/agent/blob/cancelation_for_checkout/process/proc …
> Prevent job cancellation during checkout from retrying

- go.mod
- go.sum
This gives us access to the new `ExponentialSubsecond` strategy, as well as the ability to manually set the next interval.
> Update roko v1.0.3 -> v1.1.0

- .buildkite/steps/test-acknowledgements-diff.sh
- ACKNOWLEDGEMENTS.md
- scripts/generate-acknowledgements.sh
Show the delta of `ACKNOWLEDGEMENTS.md` changes when changes are detected in CI.
This makes it easier to understand why it's changed when looking at a failed build, e.g. when dependabot is bumping a dependency.
> CI: test-acknowledgements-diff shows the diff output

- bootstrap/bootstrap.go
- bootstrap/integration/checkout_integration_test.go
Reformat the `git show` data sent to `buildkite-agent meta-data set buildkite:git:commit` so that it includes the abbreviated commit hash as `abbrev-commit`.
This could be used to help Buildkite server-side know the commit SHA abbreviation short length suitable for this repository, without having access to the repository. The default short length increases as commits are added and probability of prefix-collision increases.
The existing `commit` and `Author` fields that Buildkite uses are also still included. The `AuthorDate`, `Commit` (author) and `CommitDate` from the old `--format=fuller` that Buildkite ignores are no longer included. This is arguably a breaking change for customers parsing that extra information out of `buildkite:git:commit`, although I think that's only an API in the …
> Include abbrev-commit in `buildkite:git:commit` meta-data

- agent/job_runner.go
- agent/tags.go
- bootstrap/api.go
- bootstrap/bootstrap.go
- bootstrap/integration/bootstrap_tester.go
- bootstrap/integration/checkout_integration_test.go
- bootstrap/integration/job_api_integration_test.go
- bootstrap/shell/shell.go
- bootstrap/shell/shell_test.go
- clicommand/agent_start.go
- experiments/experiments.go
Refactors all experiment strings into constants in the `experiments` package. Protects us from misspellings and the like.
> Experiment constants

- bootstrap/config.go
Ran into this when trying to get clone flags working in mirror mode. I tried using the environment variable listed in the docs (https://buildkite.com/docs/agent/v3/configuration), but it wasn't working.
I got the `BUILDKITE_GIT_CLONE_FLAGS` working properly in the same method and when I ran a regular clean it worked just fine, but the `BUILDKITE_GIT_CLONE_MIRROR_FLAGS` never worked. Dug through the agent code and saw this `env` was missed during a refactor so I figured that was the issue.
> BUILDKITE_GIT_CLONE_MIRROR_FLAGS not working

- scripts/build-binary.sh
The version.go file was moved in a previous PR, but the linker flag packing the build version in at build-time was still pointing at the old path
> Pack the build version into the right package

- EXPERIMENTS.md
- bootstrap/bootstrap.go
- experiments/experiments.go
This feature/fix was originally committed as an experiment, but we want to turn it on by default - it seems fairly safe
> Gracefully cancel checkout by default

- agent/artifact_batch_creator.go
- agent/artifact_uploader.go
For `ArtifactBatchCreator` & `ArtifactUploader` retries, use the new `roko.ExponentialSubsecond` from https://github.com/buildkite/roko/pull/8 as intended in https://github.com/buildkite/agent/pull/2028 (at that point `ExponentialSubsecond` wasn't merged into roko yet).
This means more retries happen sooner, with a gentler growth curve, and the retry limit is reached sooner; the total retry wait across 10 attempts is ~33 seconds. Assuming the requests are timing out after 10 seconds, that's 100+33 = 133 seconds (just over 2 minutes). I think that's a good amount of time to try for.
[Here's](https://www.wolframalpha.com/input?i=y%3D500%5E%28x%2F16+%2B+1%29+for+x+from+0+to+8) the **new curve** of `ExponentialSubsecond` for 10 attempts (9 “between” delays) with a 500ms start, growing to ~10 …
> ArtifactBatchCreator & ArtifactUploader: use roko.ExponentialSubsecond

- bootstrap/bootstrap.go
- bootstrap/integration/checkout_integration_test.go
#2054 replaced `git show … -s`… with `git show … --no-patch …` to be more self-documenting. The long form of that option was added a decade ago in Git 1.8.4 in 2013, and breaks in even-older versions. Some still-supported operating systems like CentOS 7 (EOL June 2024) still use Git 1.8.3 (_presumably_ with backported security fixes 😅) so we should keep using the old short arg for now.
Related:
- #2054 
- #2073 
- Git adding `--no-patch`:
- https://lwn.net/Articles/565031/
- https://github.com/git/git/releases/tag/v1.8.4
- https://github.com/git/git/commit/d09cd15d19de23aca532a85f6d27a71b2baceb3f
> bootstrap: avoid --no-patch, support old git (pre v1.8.4; 2013)

- agent/artifact_uploader.go
- agent/artifact_uploader_test.go
- bootstrap/bootstrap.go
- experiments/experiments.go
We are seeing this warning in our Buildkite jobs:
```
WARN   Unknown experiment enabled: "normalised-upload-paths"
```
It looks like the experiment is present and does do something.
I would hypothesize that this is just an accidental oversight to leave this out of the list.
> fix: 🪶 experiment `normalised-upload-paths` was left out of the list of available experiments

- .buildkite/docker-compose.yml
To speed up tests, store the Go module cache in a common bind mount. Given the design of Go modules, I expect this to be safe and robust.
While it would work in a named volume with a fixed name, the Docker compose plugin helpfully cleans up named volumes in its exit hook.
> Persist Go module cache in a bind mount

- agent/artifact_uploader.go
- agent/artifact_uploader_test.go
- clicommand/artifact_upload.go
TL;DR: There is a new flag `--upload-skip-symlinks` that prevents files that are symlinks from being uploaded. The flag `--follow-symlinks` has been deprecated and renamed to `--glob-resolve-follow-symlinks`.
Some users may misinterpret specifying `false` to the `--follow-symlinks` flag to mean that the agent will not upload symlinks.
However, this is not the case. Until this PR, the agent will always upload all files that match the glob provided to the `artifact upload` subcommand. The `--follow-symlinks` flag only affected whether symlinked directories would be followed when resolving the glob.
However, I think it is a reasonable expectation that `--follow-symlinks=false` WOULD prevent symlinked files from being uploaded. Indeed, on the `aws s3 sync` command, [that is the …
> Add a flag to `artifact upload` to allow skipping symlinks when uploading files

- packaging/docker/alpine-k8s/Dockerfile
- packaging/docker/alpine/Dockerfile
- packaging/docker/sidecar/Dockerfile
Also, remove docker-compose v1 and replace it with a symlink to docker compose v2. docker-compose v1 is no longer offered on the apkn registry on alpine versions >3.18, so we'll have to make do.
> Update all alpine images to 3.18

- .buildkite/Dockerfile-compile
- bootstrap/bootstrap.go
- bootstrap/integration/checkout_integration_test.go
- bootstrap/integration/hooks_integration_test.go
- bootstrap/integration/job_api_integration_test.go
- bootstrap/integration/test-binary-hook/main.go
- bootstrap/shell/shell.go
- clicommand/env_set.go
- env/environment.go
- experiments/experiments.go
- hook/binary.go
- hook/hook.go
- hook/scriptwrapper.go
- hook/scriptwrapper_test.go
- hook/type.go
- hook/type_test.go
- jobapi/client_test.go
- jobapi/payloads.go
- jobapi/routes.go
- jobapi/server_test.go
- scripts/generate-test-binaries.sh
- shellscript/shellscript.go
- test/fixtures/hook/hook.rb
- test/fixtures/hook/main.go
- test/fixtures/hook/shebanged.sh
- test/fixtures/hook/un-shebanged.sh
**This PR:** Removes the requirement that hooks for the buildkite-agent be written in a shell scripting language a la bash. With the use of this branch, hooks can also either be compiled executable binaries (ie those produced by languages like Golang or Rust), or any interpreted scripting language (ie python, ruby, lua), so long as an appropriate shebang is specified at the top of the file.
note that neither binary hooks nor non-shell script hooks have environment variable changes captured as bash script hooks do; they _must_ use the Job API to modify the environment of the job.
> Experiment: Polyglot hooks

- .buildkite/steps/tests.sh
- EXPERIMENTS.md
- bootstrap/bootstrap.go
- bootstrap/integration/bootstrap_tester.go
- bootstrap/integration/checkout_git_mirrors_integration_test.go
- bootstrap/integration/checkout_integration_test.go
- clicommand/agent_start.go
- clicommand/bootstrap.go
- clicommand/global.go
- experiments/experiments.go
Use of the git mirrors experiment will now be solely controlled by the --git-mirrors-dir flag
> Promote git-mirrors experiment to full functionality

- bootstrap/bootstrap.go
It was a very weird decision for me to call it `TRIGGERED_FROM`, idk why i did that ¯\\\_(ツ)_/¯
> Rename polyglot hook env BUILDKITE_HOOK_TRIGGERED_FROM -> BUILDKITE_HOOK_SCOPE

- agent/plugin/definition.go
- agent/plugin/definition_test.go
- bootstrap/bootstrap.go
- go.mod
- go.sum
This is #2027 redone with contexts passed in via arg, and including the config via `% #v` in the test error output.
Supersedes #2027
> Update github.com/qri-io/jsonschema to 0.2.1

- internal/socket/server.go
- jobapi/socket.go
Unless `job-api` was used previously, there's little chance of the socket directory existing. If the directory doesn't exist, enabling `agent-api` crashes the agent on startup. Using `MkdirAll` in `NewServer` ensures the directory exists.
> Move os.MkdirAll to socket.NewServer

- bootstrap/integration/checkout_integration_test.go
This should fix the test failures on Windows.
> Integration tests: Use filepath.Clean in the subDirMatcher

- internal/system/version_dump.go
- internal/system/version_dump_windows.go
This commit adds a `//go:build windows` tag to `internal/system/version_dump_windows.go`, which *technically* isn't necessary, as golang interprets a `_windows.go` suffix on a filename as a build tag, but that's super weird behaviour, so this commit adds that tag in explicitly.
It also removes the old-style `// +build` style tag on `internal/system/version_dump.go`
> Clean up system build tags

- agent/plugin/error.go
- agent/plugin/error_test.go
- agent/plugin/plugin.go
- agent/plugin/plugin_test.go
- bootstrap/bootstrap.go
When an env var name, that was derived from a plugin config, had consecutive underscores, the consecutive underscores were replaced by a single one. (For later reference, this will be called the underscore collapsing transformation). Now, both versions of the variable before and after this transformation are exported.
We also log a warning about this and log both the deprecated variable name and its replacement.
We need to keep the deprecated version around, as these environment variables are how plugins read their config without depending on a tool like `jq` to parse the config.
So removing them would mean that plugins could be inadvertently misconfigured, and they would have to be rewritten to start using the replacement environment variables instead.
Implementing this was not that …
> Preserve plugin config env var names with consecutive underscores

- agent/agent_configuration.go
- agent/job_runner.go
- clicommand/agent_start.go
- experiments/experiments.go
Instead of enabling the current ANSI timestamp behaviour with no opt-out, this one provide an escape hatch to the old defaults with --no-ansi-timestamps.
I thought for a bit about how to make ANSI timestamps and TimestampLines work together. It could avoid having a header times streamer for the purpose of streaming header times, but would still need the logic in the header times streamer to distinguish headers from non-headers, as well as something else to buffer the first few bytes of each line (at least). That bit needs more thought, so for now, continue to not mix ANSI timestamps and TimestampLines.
> De-experimentify ansi-timestamps (take 2)

- bootstrap/bootstrap.go
- bootstrap/git.go
- bootstrap/integration/bootstrap_tester.go
- bootstrap/integration/checkout_integration_test.go
There are a certain class of errors from git in the `defaultCheckoutPhase` that would cause a retry, but before the retry, the checkout directory would be removed. This allows cleaning up in case an unclean exit from git had left the checkout directory in an unrecoverable state.
This PR adds failures in `git fetch` and `git checkout` when the exit code is 128 to that class of error. It also fixes the detection of errors for which the check directory needed to be clean, as previously, the detection would fail if the errors were wrapped, and they are wrapped in the `defaultCheckoutPhase` method.
I've done some refactoring to reduce the indentation level of the code, so I recommend reviewing with whitespace changes hidden.
> Wipe checkout directory on `git checkout` and `git fetch` failure and retry

- bootstrap/bootstrap.go
In `defaultCheckoutPhase`, if there are mirrored submodules, the `repository` arg to `getOrUpdateMirrorDir` varies (per submodule). The clone in `updateGitMirror` uses the arg, but if the mirror exists and the commit is not present, the origin is replaced with `b.Repository`, pointing the mirror at the wrong remote before fetching.
Fixes a bug introduced in #1959
> Fix origin for mirrored submodules

- clicommand/lock_acquire.go
- clicommand/lock_common.go
- clicommand/lock_do.go
- clicommand/lock_done.go
- clicommand/lock_get.go
- clicommand/lock_release.go
- internal/agentapi/client_server_test.go
- lock/lock.go
- lock/lock_test.go
The agent API exists not only to implement the lock subcommands, but to provide a service useful for agent internal locking purposes, build commands, hooks, and plugins. Some of that might be implemented in Go, therefore there should be a useful library available. 
While writing the library, I recalled that the previous implementation does not handle double-releasing a lock appropriately - suppose `lock release` is called manually as well as on an EXIT trap, while another process acquires the same lock. To fix this, the lock package generates a token stored in the lock when acquired, and must match in order to unlock. This is printed by `lock acquire` and is now a required argument to `lock release`.
> Lock library

- bootstrap/bootstrap.go
I think this was just a typo that I happened to notice a week or two ago; the updated name now matches the other names near it:
https://github.com/buildkite/agent/blob/581a104634fa5749934a15613c230bdf390f5908/bootstrap/bootstrap.go#L1278
https://github.com/buildkite/agent/blob/581a104634fa5749934a15613c230bdf390f5908/bootstrap/bootstrap.go#L1313
> var name typo: s/pluginCheckoutHook/pluginCheckoutLock/

- bootstrap/bootstrap.go
Followup to https://github.com/buildkite/agent/pull/1959.
Upon updating to 3.44, we started seeing the new submodule mirror directories having their `origin` remote set to the URL of the pipeline's repo instead of the submodule's repo. This is causing a double `git fetch` of the main repo to happen, once when checking out the commit to build and once when updating submodules.
We also don't want to be running any fetches in the submodule mirror repo since the only branch or PR information the agent has is for the main repo, and those fetches would most likely fail in the submodule mirror.
Reproed in https://github.com/francoiscampbell/buildkite-submodule-test:
```
--
  | # Using flock-file-locks experiment 🧪
  | $ git --git-dir /nvme/reference_repos/https---github-com-apache-incubator-airfl …
```
> Fix submodule mirror repository remote using main repo URL

- agent/agent_worker_test.go
- api/client.go
A customer was running into an error:
```
POST https://agent.buildkite.com/v3/register: 400 Agents can only be part of a single queue when registering to a cluster (Attempt 14/30 Retrying in 10s)
```
which due to a set of quite funny coincidences, makes it seem like there can only be 400 agents per cluster queue, when what's actually happening is that the log is telling us that that POST got a 400 Bad Request response code, and was telling the user that each agent is only allowed to be part of a single cluster queue.
This commit adjusts the error so that it will now be:
```
POST https://agent.buildkite.com/v3/register: 400 Bad Request: Agents can only be part of a single queue when registering to a cluster (Attempt 14/30 Retrying in 10s)
```
hopefully making the various clauses in that …
> Adjust HTTP response errors to separate the response code and the error

- agent/pipeline_uploader_test.go
- clicommand/pipeline_upload.go
- internal/pipeline/doc.go
- internal/pipeline/parser.go
- internal/pipeline/parser_test.go
`agent` is overloaded with stuff. Making a separate `pipeline` package improves the spelling IMO (`pipeline.Parser` vs `agent.PipelineParser`). 
Since it's not intended for external consumption (in current form, anyway), hide it in `internal`.
> Internalise pipeline parser

- packaging/docker/alpine-k8s/Dockerfile
- packaging/docker/alpine/Dockerfile
It looks like the package on alpine linux is doing this for us now:
```bash
/ # apk add docker-cli docker-compose
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
(1/3) Installing ca-certificates (20230506-r0)
(2/3) Installing docker-cli (23.0.6-r2)
(3/3) Installing docker-cli-compose (2.17.3-r3)
Executing busybox-1.36.1-r0.trigger
Executing ca-certificates-20230506-r0.trigger
OK: 83 MiB in 18 packages
/ # ls -lA /usr/bin/docker-compose
lrwxrwxrwx    1 root     root            44 Jun 21 02:42 /usr/bin/docker-compose -> ../libexec/docker/cli-plugins/docker-compose
```
We have tests that `docker-compose` is executable in these docker images, so I'm pretty comfortable dropping the …
> Stop linking docker compose to docker-compose

- api/api_internal_test.go
- api/client.go
Introduce a new `Buildkite-Timeout-Milliseconds` request header, set as a positive integer by `api.Client.newRequest()` when its context has a deadline in the future.
This allows the server to be aware of the client-side timeout/deadline (e.g. in #2028), and e.g. configure its own downstream timeouts accordingly.
Thanks @mhaylock for the idea behind this.
Related:
- #2028
> `Buildkite-Timeout-Milliseconds` request header

- EXPERIMENTS.md
We missed adding this in the original PR, whoops.
> ### `polyglot-hooks`
> 
> Allows the agent to run hooks written in languages other than bash. This enables the agent to run hooks written in any language, as long as the language has a runtime available on the agent. In non-windows environments, polyglot hooks can be in interpreted languages, so long as they have a valid shebang, and the interpreter specified in the shebang is installed on the agent.
> 
> This experiment also allows the agent to run compiled binaries (such as those produced by Go, Rust, Zig, C et al.) as hooks, so long as they are executable.
> Hooks are run in a subshell, so they can't modify the environment of the agent process. However, they can use the [job-api](#job-api) to modify the environment of the job.
> 
> …
> Add polyglot-hooks to EXPERIMENTS.md

- internal/ordered/map.go
- internal/ordered/map_test.go
- internal/ordered/tuple.go
In the process of trying to parse pipelines with a greater semantic understanding (in order to do things with them, like sign command steps), but retain compatibility, I kept hitting the need for YAML unmarshaling into an *ordered* map. For example, even though the "env" block is essentially unordered, we step through it *in order* so that variables can interpolate into one another *in order*. Another example is plugin config: we reflect it to plugins both via env vars, but also as a JSON blob, and there's a fair chance some plugin is going to be (maybe even deliberately) relying on ordering within its config.
So I implemented an ordered map. It's the next evolution of yamltojson, in that it provides the same sort of order-preserving translation when you unmarshal YAML and marshal JSON, …
> Add ordered.Map

- agent/pipeline_uploader_test.go
- clicommand/pipeline_upload.go
- internal/ordered/slice.go
- internal/pipeline/doc.go
- internal/pipeline/interpolate.go
- internal/pipeline/parser.go
- internal/pipeline/parser_test.go
- internal/pipeline/pipeline.go
`Pipeline` uses an `ordered.Map[string, string]` for `Env`, and a new
`ordered.Slice` for `Steps`. Unmarshaling into `ordered.Slice` prefers
`ordered.Map[string, any]` over `map[string]any`.
Why not `[]*ordered.Map[string, any]`? Because of steps like `"wait"`, which are
scalars.
`Pipeline` stores anything else in a `RemainingFields` which is an ordinary map.
I can't think of a reason to preserve ordering in fields that are not `Env` or
`Steps`, but if there is something, I would like to hear about it!
Plus a couple of related things:
* Interpolation is updated to work with the new types.
* Interpolating keys in the `Env` map is moved to `interpolateEnvBlock` and
interpolated keys replace the old keys, rather than preserving uninterpolated keys into the output.
* Changed the parser API …
> Replace ParserResult with Pipeline

- agent/agent_configuration.go
- agent/job_runner.go
- clicommand/agent_start.go
Extending from this job log tmp feature https://github.com/buildkite/agent/pull/1564
We need the ability to move job log files into a different folder than tmp to share them. This will allow us to use different containers between job and runner and pre-exit hooks for example.
> Add option to configure location of Job Log tmp file

- internal/ordered/map.go
- internal/pipeline/parser_test.go
- internal/pipeline/pipeline.go
- internal/pipeline/plugin.go
- internal/pipeline/plugins.go
- internal/pipeline/step.go
- internal/pipeline/steps.go
Adds:
- a `Step` interface,
- five implementing step types,
- `Steps`, responsible for fingerprinting each step to pick the right type for each,
- `Plugin`, which represents individual plugin configs, and
- `Plugins`, which handles unmarshaling either sequences or maps.
This PR throws out most ordering for our own types (though explicitly preserving plugin config ordering). This is most of the churn in the `wantJSON` test data. Normalising plugin maps into "sequence of one-item maps" form accounts for one test. 
Because `Steps` is responsible for fingerprinting step types, I've added diff checks against typed parser output.
This also adds a `Contains` method to `ordered.Map`, and a partial unmarshaling mode to handle `ordered.Map[string, *yaml.Node]`. (It gets given the raw value nodes. …
> Model steps and plugins

- process/process.go
- process/signal.go
- process/signal_windows.go
This PR should be a no-op.
When the agent creates processes (for bootstrap, hooks or commands)
it creates a process group for the process. This is done so that
signals can be sent to the process group without affecting the process
that created the process group.
However, when launching a process in a pseudo-terminal (a PTY), there
was an error caused by explicit telling the process to be created in a
group, because the library that creates the PTY also creates a process
group (by some other means, see [here](https://github.com/creack/pty/blob/0d412c9fbeb14954aa65830dcfdb84005cd0cd96/start.go#L22)).
So we created a check for if the process was in a PTY before
doing this. But we appear to be checking this twice on non-windows
systems - both inside and outside the `setupProcessGroup` method. …
> Clarify code around creating a process group

- .buildkite/pipeline.yml
TL;DR i saw https://github.com/buildkite/buildkite/pull/13006 and figured we should do that here too
We're using a wild number of versions of the docker compose plugin, all the way back to v1. This PR upgrades them all to the latest v4.14, and opts us into using docker compose v2
> Upgrade docker compose plugin to v4.14, use docker compose v2

- internal/ordered/strings.go
- internal/ordered/strings_test.go
- internal/pipeline/parser_test.go
- internal/pipeline/step.go
The docs say `commands` is an alias for `command`. So one could write `command`’s value as multiple strings in a sequence, or write `commands`’ value as a single string.
Something that parses either single strings or sequences of strings into `[]string` is too generic for `pipeline`, so I put it in `ordered`.
> Parse command and commands the same

- internal/mime/mime.go
- internal/pipeline/sign.go
- internal/pipeline/sign_test.go
- internal/pipeline/step.go
The main design consideration was how to get objects to describe their default set of fields to sign, and to fetch ~arbitrary values for verifying, because Signature includes the list of signed fields. The rest pretty much flows from that.
Signatures can be attached to command steps (to begin with) and cover just the command itself. The core piece (throwing fields and values at a hash) is the same between Sign and Verify, so I implemented both.
I made the algorithm interface big enough to handle both symmetric and asymmetric schemes, but have only implemented HMAC-SHA256 here.
> Add Signature, Sign, and Verify

- internal/pipeline/interpolate.go
- internal/pipeline/parser_test.go
- internal/pipeline/plugin.go
- internal/pipeline/plugins.go
- internal/pipeline/step.go
The bug is: `Plugins` was `[]Plugin`, but `*Plugin` was the thing that was `selfInterpolator`, so `interpolateAny` never called `*Plugin.interpolate`. Changing `Plugins` to be `[]*Plugin` neatly resolves that.
Plus various tweaks and comments on interpolation generally.
@moskyb was right about making `interpolateAny` generic, it was a matter of moving the type assertion.
> Fix plugin interpolation

- clicommand/bootstrap.go
- internal/job/api.go
- internal/job/config.go
- internal/job/config_test.go
- internal/job/executor.go
- internal/job/executor_test.go
- internal/job/integration/doc.go
- internal/job/integration/docker_integration_test.go
- internal/job/integration/executor_tester.go
- internal/job/integration/job_api_integration_test.go
- internal/job/tracing.go
- jobapi/server_test.go
**This PR follows from #2187**
**This PR:** Renames the `job.Bootstrap` struct to `job.Executor`, as well as a couple of its friends. it also updates comments and associated variable names etc to be appropriately named.
> Die, bootstrap, die: Rename `Bootstrap` struct (and friends) to `Executor`

- internal/job/executor.go
- internal/job/integration/checkout_integration_test.go
I'm not certain yet, but the submodule-mirror-wrong-remote bug in older agents (see #2144) _might_ be related to recent "bad object" / "did not send all necessary objects" issues.
For submodules, older agents set the wrong remote URL in the directory. v3.49 (#2144) fixed it to set the correct remote. However, once upgraded to v3.49, the mirror dir is probably broken: the remote URL is updated correctly, but the local repo would still contain objects for the wrong remote. Afterwards, the repo is only fetched if it is the main repo. Woe betide you if you have multiple agents of different versions fighting over the mirror!
So this PR:
- uses `get-url` before using `set-url`, so that we can log a message
- if the remote URL changed, do a `fetch` for non-main repos to try to get out of bad …
> Update URL for remote: look before leap

- clicommand/pipeline_upload.go
- internal/pipeline/pipeline.go
- internal/pipeline/sign.go
- internal/pipeline/sign_test.go
- internal/pipeline/steps.go
- The pipeline can sign itself, given a signer. 
- `Signer` and `Verifier` now exposes more of `hash.Hash`, particularly so it can be `Reset`.
- pipeline upload `--dry-run` no longer requires the agent access token (which wasn't used in that path)
- pipeline upload now has a `--format` flag
Question: Is it time for `pipeline sign` ?
> Add signatures

- internal/job/executor.go
- internal/job/integration/command_integration_test.go
In preparation for some other work I intend to do in this area, simplify the CommandPhase method.
I aimed to make this PR a no-op, but technically, I've changed the order of some of the statements, which does change the internal state and the order of some log statements. But there should be minimal externally visible effects.
I recommend you review this PR with a side-by-side diff.
> Simplify command phase

- packaging/linux/root/usr/share/buildkite-agent/systemd/buildkite-agent@.service
Relates to https://github.com/buildkite/docs/issues/2252.
The docs currently advise users that they can [run multiple agents using the same configuration](https://buildkite.com/docs/agent/v3/ubuntu#running-multiple-agents) by using the systemd template unit file.
However, this results in starting multiple agents with the same name, which the [configuration docs](https://buildkite.com/docs/agent/v3/configuration#name) advise against doing.
This PR uses [unit file specifiers](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Specifiers) to give each agent a unique name based on the hostname and the systemd service instance name.
> Use a unique name for each agent started using the systemd template unit file

- logger/log.go
- version/version.go
These are already pretty spammy, so I don't think this will make it much worse.
This is what it looks like:
```
2023-07-17 16:05:44 DEBUG  GET https://agent.buildkite.com/v3/ping agent_version=3.49.0 agent_build=x
2023-07-17 16:05:45 DEBUG  ↳ GET https://agent.buildkite.com/v3/ping agent_version=3.49.0 agent_build=x
```
> Print agent version and build in debug logs

- experiments/experiments.go
- internal/job/executor.go
Some jobs are run as a bash script of the form:
```bash
trap "kill -- $$" INT TERM QUIT; <command>
```
We now understand this causes a bug (see the code comments), and we want to avoid it.
This PR adds an experiment to avoid adding the trap to the script.
> Add experiment to avoid a recursive trap

- .editorconfig
This controls how wide tabs are in some text editors. The rest of the
org uses two space tabs in the backend, so lets be consistent with them.
> Switch to 2-space tabs

- packaging/docker/ubuntu-22.04/Dockerfile
Python dependency snafus mean we have to constrain pyyaml to an older version, see: https://github.com/yaml/pyyaml/issues/724
> Fix docker builds for Ubuntu 22.04

- internal/pipeline/json.go
- internal/pipeline/json_test.go
- internal/pipeline/pipeline.go
- internal/pipeline/step.go
The pipeline is actually marshalled to json by the agent, and then back to yaml again on the backend, as it turns out.
> Add signatures when marshalling steps to json

- internal/job/executor.go
- internal/job/git.go
On the theory that mirrors sometimes have objects gc-ed that are still referred to by existing checkout directories, make `fatal: bad object` an error that we can try to recover from by deleting the checkout directory and re-cloning.
I made `gitErrorFetchBadObject` its own enum value, in case we want to apply the recovery only when git mirrors are enabled.
cc #2208
> Clean-retry on "fatal: bad object"

- internal/pipeline/pipeline.go
- internal/pipeline/steps.go
Some (usually automatically-produced) pipelines have no steps. Previously we didn't error on this case, but while changing the pipeline parser I added these checks. There's no reason for the agent to care about it, so remove the check.
> Allow empty steps

- internal/pipeline/parser_test.go
- internal/pipeline/step.go
- internal/pipeline/steps.go
"group" was in `RemainingFields`, but is written in YAML with no value, which is parsed as null, represented as nil, but `GroupStep.MarshalJSON` filtered out nil values. 
We have better technology: `inlineFriendlyMarshalJSON`.
This also adds a test for empty steps.
> Fix missing group key

- agent/job_runner.go
`JobStatusInterval` is already a duration. Casting it to a duration again is a no-op. However, multiplying it by `time.Second` is not.
This is because the `time.Duration` type is an alias for `int64` and represents nanoseconds. `time.Second` is therefore a constant `1_000_000_000`. Thus, multiplying `JobStatusInterval` by `time.Second` makes it a billion times longer.
See https://go.dev/play/p/PNlEW_b-8YF
> Fix parsing an interval as another interval

- agent/integration/job_runner_integration_test.go
- agent/job_runner.go
- agent/run_job.go
tl;dr before:
```Go
defer cancel()
defer r.cleanup(cctx, &wg, exit)
```
after:
```Go
defer func(ctx context.Context, wg *sync.WaitGroup) {
cancel()
r.cleanup(ctx, wg, exit)
}(ctx, &wg)
```
previously we were capturing the value of `exit` at the time of the call to `defer`, now we're capturing the value at the time the defer is actually executed, which is what we wanted in the first place.
this PR also adds a regression test to ensure that this doesn't happen again
> Fix an error where exit status wasn't getting captured by the cleanup process

- .buildkite/steps/build-docker-image.sh
It's baked into v6 of the Elastic CI Stack that the builders are now dogfooding
> Remove installing qemu-binfmt from agent pipeline

- internal/ordered/map.go
- internal/ordered/slice.go
- internal/ordered/yaml.go
- internal/pipeline/parser.go
- internal/pipeline/parser_test.go
- internal/pipeline/pipeline.go
- internal/pipeline/plugin.go
- internal/pipeline/plugins.go
- internal/pipeline/sign.go
- internal/pipeline/step.go
- internal/pipeline/steps.go
There's a bug where multiple [map merges](https://yaml.org/type/merge.html) aren't unmarshaled into structs in the way we've supported them.
To address this we need to go back to having greater control over the YAML unmarshaling process. It will also help if we, say, want to switch YAML library later on - if a new library supports the things we need to do, then we can simplify, and if it doesn't (or has subtle differences) then the intermediate processing can be the place where we make up the gap.
The key change here is from allowing `yaml.v3` to unmarshal into structs using its reflective logic to:
- Use yaml.v3 to parse into `*yaml.Node`, which provides all the relevant information in the document without further processing.
- Unmarshal that node using `ordered`, which handles merges …
> Two-phase pipeline parsing

- .buildkite/steps/test-go-fmt.sh
- go.mod
- go.sum
i accidentally committed a go.mod with [`kr/pretty`](https://github.com/kr/pretty) (which i often use for debugging) the other day. this PR makes it so that committing a non-tidy go.mod file will fail CI
> Check that go.mod is tidy in CI

- agent/s3.go
It should mention `BUILDKITE_S3_PROFILE` and `AWS_PROFILE`.
> Tweak authentication failure error

- .buildkite/steps/build-docker-image.sh
- packaging/.gitignore
- packaging/docker/alpine-k8s/Dockerfile
- packaging/docker/alpine/Dockerfile
- packaging/docker/common/docker-compose
- packaging/docker/ubuntu-22.04/Dockerfile
Docker Compose V1 is very much deprecated. We don't offer it on the latest major version of the Elastic CI Stack (v6) and on the alpine docker images, we have been symlinking it to docker-compose v2.
This PR removes docker-compose v1 from the ubuntu 22.04 docker image and replaces it with the compatibility script that calls docker compose v2 with the `--compatbility` flag prepended to the arguments.
Also, it replaces the symlink in the alpine docker images with that script.
Fixes: \#2232
Closes: \#2241
> Remove docker-compose v1 from ubuntu 22.04 and replace with compatibility script

- internal/job/executor.go
I always have to do a double take when I read this code. But finally
found a reason to remove it! `Executor.hasLocalHook` calls
`Executor.localHookPath`, so in this method,
`Executor.executeLocalHook`, we are calling `Executor.localHookPath` twice.
This PR removes that and adds some logging to the job logs for when the hook
is not found (in debug mode).
> Remove a double check for the existence of a local hook and log when it is missing in debug

- .buildkite/docker-compose.yml
This should enable test caching between runs on the same machine, which should slightly reduce time to run the pipeline.
> Store GOCACHE outside container

- process/process.go
- process/process_test.go
- process/signal_test.go
More details available commit by commit
> Refactor some code in process.go

- .buildkite/steps/test-go-fmt.sh
- internal/pipeline/maybe_scalar_steps.go
- internal/pipeline/parser_test.go
- internal/pipeline/pipeline.go
- internal/pipeline/step.go
- internal/pipeline/steps.go
**This PR:** Fixes two issues in the pipeline parser:
> Even More Pipeline Parsing Fixes

- internal/pipeline/parser_test.go
- internal/pipeline/sign_test.go
- internal/pipeline/steps.go
- internal/pipeline/unknown_step.go
It occurred to me that the new parser has no way of representing steps that we haven't invented yet.
> Add future-proofing UnknownStep type

- internal/ordered/map.go
- internal/ordered/map_test.go
- internal/pipeline/parser_test.go
- internal/pipeline/pipeline.go
- internal/pipeline/steps.go
- Someone could write `env: null`, and this should be handled appropriately.
- Most of `Steps.unmarshalAny` should be skipped if `o == nil`, not just if `*s == nil` also.
- `ToMap` should handle nil receiver (like all the other methods).
> Nil handling tweaks

- .buildkite/steps/test-go-fmt.sh
It will output if it needs to download modules to compute their hashes,
and this caused a false negative as we only tested if the output length
were non-zero.
> Fix flaky go mod tidyness check

- internal/pipeline/parser_test.go
- internal/pipeline/plugin.go
- internal/pipeline/plugins.go
Because plugins is a list, each list item could be a single string and not necessarily a map.
> Fix scalar plugin parsing

- agent/agent_configuration.go
- agent/agent_worker.go
- agent/job_runner.go
- clicommand/agent_start.go
- clicommand/bootstrap.go
- clicommand/cancel_signal.go
- internal/job/config.go
- internal/job/executor.go
- internal/job/shell/shell.go
- process/main_test.go
- process/process.go
- process/process_test.go
The agent start process already does something similar to the job executor process when it detects that the buildkite job had been cancelled. However, every other process launched by the agent is unceremoniously killed with a SIGKILL when the job is cancelled. This has been causing issues with the checkout directory becoming corrupted if the job is cancelled during checkout.
This PR makes the agent first send a SIGTERM (which is configurable by the `cancel-signal` config option) and give the process a grace period to clean up before sending a SIGKILL. The grace period is also configurable, but it needs to be smaller than the grace period allowed to the job executor by the agent start process. I've tried to avoid confusion between the two - the grace period for the job executor is …
> Make the the agent send a SIGTERM (configurable) before a SIGKILL to subprocesses

- agent/plugin/error.go
- internal/job/executor.go
I was doing some "light reading" of the go standard library, and noticed [this](https://cs.opensource.google/go/go/+/refs/tags/go1.20.7:src/errors/wrap.go;drc=4a0a2b33dfa3c99250efa222439f2c27d6780e4a;l=41):
```
// ... An Is method should only shallowly
// compare err and the target and not call Unwrap on either.
```
In the former implementations, calling `errors.As` could unwrap the errors, so this PR fixes this.
> Remove unwrapping in error `Is` methods

- agent/job_runner.go
- agent/log_streamer.go
- api/chunks.go
- api/jobs.go
- process/buffer.go
- process/buffer_test.go
Since [removing the need to hold the whole log in memory](https://github.com/buildkite/agent/pull/2014), there have been a few cases of long-running jobs logging lots of logs. This adds a (server-specified) limit, with a default of 1GiB. 
Why not just limit it server side? Because the job itself should get some kind of pushback once it approaches or hits the limit. Returning errors when writing to the buffer feels like the right place.
> Add a job log length limit

- agent/agent_configuration.go
- agent/integration/job_runner_integration_test.go
- agent/integration/job_verification_integration_test.go
- agent/integration/test_helpers.go
- agent/job_runner.go
- agent/run_job.go
- agent/verify_job.go
- api/jobs.go
- clicommand/agent_start.go
- internal/pipeline/json.go
- internal/pipeline/json_test.go
- internal/pipeline/sign.go
- internal/pipeline/sign_test_helpers.go
- internal/pipeline/step_command.go
- internal/pipeline/steps.go
**This PR:** Enables the buildkite-agent to verify incoming jobs against signatures uploaded in their pipeline uploads.
This is done by a process (vaguely):
- When accepting a job, the `Job` sent by the backend will (WIP) now include a `step` attribute, which contains a subset of information contained in the step upload - at current, it's the step's command and signature, though as we sign more elements of the signature, this will expand to include other elements
- After accepting the job, but before kicking off the bootstrap process, the agent computes a signature for the `step`, and compares it to the signature shipped in the accept payload
- With the step verified, we need to check that the `Job`'s elements match the `Step`'s
- If they match, run the job
- If they don't (or there's a …
> Verify step signatures

- main.go
This corrects...
```
buildkite-agent --help
Usage:
buildkite-agent <command> [options...]
...
annotation        Make changes an annotation on the currently running build
...
```
To read...
```
buildkite-agent --help
Usage:
buildkite-agent <command> [options...]
...
annotation        Make changes to an annotation on the currently running build
...
```
> add missing 'an' in annotation help

- clicommand/pipeline_upload.go
I assume this is what @moskyb intended to do here... but didn't.
([I, too, like to make values and never use them.](https://github.com/buildkite/agent/pull/2257))
> Use capacity hint in `concat`

- internal/ordered/unmarshal.go
- internal/ordered/unmarshal_test.go
- internal/pipeline/parser.go
- internal/pipeline/parser_test.go
- internal/pipeline/pipeline.go
- internal/pipeline/plugins.go
- internal/pipeline/sign.go
- internal/pipeline/step.go
- internal/pipeline/step_command.go
- internal/pipeline/step_group.go
- internal/pipeline/step_input.go
- internal/pipeline/step_trigger.go
- internal/pipeline/step_unknown.go
- internal/pipeline/step_wait.go
- internal/pipeline/steps.go
The main affordance of `encoding/json`, `gopkg.in/yaml.v3`, etc is the ability to unmarshal data into a struct. This PR adds similar functionality to the `ordered` package.
Because `DecodeYAML` returns a variety of types, `Unmarshal` handles `*MapSA`, `[]any`, and a variety of scalars as sources.
The second commit applies the new `ordered.Unmarshal` to pipeline parsing.
> Add ordered.Unmarshal, and use it

- agent/integration/job_verification_integration_test.go
- api/jobs.go
- internal/pipeline/sign.go
- internal/pipeline/sign_test.go
- internal/pipeline/step_command.go
Plugins alter the execution of a step completely, so the list of plugins and their configurations must be included in the signature for it to be secure.
This PR currently encodes plugin configs into JSON. This is potentially not a great encoding (what stability guarantees do we really have?), but because this is how the whole pipeline is uploaded, it ought to round-trip well enough.
> Include plugins in command step signatures

- clicommand/global.go
Terminal programs should always print a new line when they exit so that the new prompt can start at the left.
Since in #2281, we consolidated all the configuration error printing into a single location, this PR can fix it just here. There might be a more systematic way to do this, for all situations where the agent exits, but for now, this is a quick fix for a place where we noticed it happening.
Before:
```shell
❯ buildkite-agent --version
buildkite-agent version 3.49.0, build x
agent (9619ad6) [$] via 🐹 v1.21.0 via 💎 v3.2.2 on ☁️
❯ buildkite-agent artifact upload f
Missing job. See: `buildkite-agent artifact upload --help`⏎
```
After:
```shell
❯ buildkite-agent --version
buildkite-agent version 3.51.0, build x
agent on  pdp-1466-fix-new-missing-args-needs-newline [$!+] via 🐹 v1.21.0 …
```
> Add a newline after printing errors from the config parser

- .buildkite/steps/test-bk.sh
The main branch is going to undergo some changes. We should pin to a commit while this happens so that the agent CI pipeline does not break.
> Pin bk cli used in agent pipeline to a commit

- .buildkite/pipeline.release-experimental.yml
- .buildkite/pipeline.release-stable.yml
- .buildkite/pipeline.release-unstable.yml
- internal/pipeline/parser_test.go
ecr#v2.0.0 fails with the newer AWS CLI.
I updated a few other things while I'm here: docker from v3.5.0 to v5.8.0, and the agent image used for deply to ~~v3.50.4~~ v3.51.0.
> Update ecr, docker plugins, and agent image ver

- .buildkite/pipeline.release-experimental.yml
- .buildkite/pipeline.release-stable.yml
- .buildkite/pipeline.release-unstable.yml
The default changed in docker#v5.0.0 from true (on Linux) to false.
Enabling this propagates the agent access token as well as bind-mounts
the host agent into the container.
(So the agent container version didn't really matter.)
> Enable mount-buildkite-agent in release containers

- clicommand/step_get.go
Apologies for this, everyone. I made a typo.
> Fix step get is printing the address of the stdout stream at the start

- internal/pipeline/interpolate.go
- internal/pipeline/parser_test.go
- internal/pipeline/step_group.go
This fixes the missing interpolation, ~~but does not make `GroupStep.Group` more type-safe~~ changes the type to `*string`, and adds support for interpolating `*string`s.
> Fix missing group interpolation

- EXPERIMENTS.md
- experiments/experiments.go
- internal/job/executor.go
- internal/job/integration/isolated_plugin_integration_test.go
Previously, we took out an exclusive, filesystem lock while the plugin directory was being checked out or deleted. However, this is not sufficient, as one agent worker could be reading from the plugin directory while another is checking it out. This is likely to happen when jobs that use the same plugin at different versions are running on the same agent process, in separate workers. Or, when the `BUILDKITE_PLUGINS_ALWAYS_CLONE_FRESH` variable is set. This race condition can appear as plugins running hooks that are from different versions of the plugin, or not at all, and has been reported by customers.
To fix it, I have namespaced the plugin directory with the agent name. Then, the agent workers will have their own copy of the plugin. At the moment, most plugins are a collection of bash …
> Add experimental fix for agent workers can read plugin directories while they are being written to by other agent workers

- .buildkite/steps/publish-rpm-package.sh
The core idea is to use `--recycle-pkglist` to skip recalculating metadata for all the old packages, which avoids the need to have the old packages there to begin with.
> Publish RPMs: sync less data

- internal/job/shell/main_test.go
- internal/job/shell/shell_test.go
The shell test ran the test binary in a separate process. The test binary is supposed to sleep forever, but the go runtime terminates it because all its goroutines are idle. This is because the test binary is not doing anything in the main goroutine. This PR fixes the issue by making the test binary do something in the main goroutine.
I've also kept the changes I made to make the test more debuggable. Here is the output from when I debugged. Note the output `fatal error: all goroutines are asleep - deadlock!`.
```shell
DONE 1 tests in 3.267s
gotestsum -- -count=1 -v ./internal/job/shell -run ^TestLockFileRetriesAndTimesOut$
✖  internal/job/shell (14ms)
=== Failed
=== FAIL: internal/job/shell TestLockFileRetriesAndTimesOut (0.01s)
shell_test.go:319: acquiring lock in other process: …
```
> Fix a flaky shell test

- clicommand/agent_start.go
- clicommand/cancel_signal.go
- clicommand/env_unset.go
- clicommand/lock_acquire.go
- clicommand/lock_do.go
- clicommand/lock_done.go
- clicommand/lock_get.go
- clicommand/lock_release.go
You may be wondering about the removal of line breaks from the code examples. This was done to reflected changes in the docs. It seems to still look good for the cli:
```shell
Usage:
buildkite-agent lock release [key] [token]
Description:
Releases the lock for the given key. This should only be called by the
process that acquired the lock. To help prevent different processes unlocking
each other unintentionally, the output from ′lock acquire′ is required as the
second argument.
Note that this subcommand is only available when an agent has been started
with the ′agent-api′ experiment enabled.
Examples:
#!/bin/bash
token=$(buildkite-agent lock acquire llama)
buildkite-agent lock release llama "${token}"
Options:
--no-color            Don't show colors in logging [$BUILDKITE_AGENT_NO_COLOR] …
```
> Update help text with suggestions from docs code review

- agent/integration/job_verification_integration_test.go
- clicommand/agent_start.go
- internal/ordered/unmarshal.go
- internal/ordered/unmarshal_test.go
- internal/pipeline/parser_test.go
- internal/pipeline/plugin.go
- internal/pipeline/plugin_test.go
- internal/pipeline/plugins.go
- internal/pipeline/sign_test.go
- internal/pipeline/step_command.go
- internal/pipeline/step_command_test.go
The first part of this PR enables `CommandStep` to be unmarshaled directly from JSON consistently. This is mainly needed because `Plugin` wasn't set up to be unmarshaled from JSON, but reusing the YAML -> ordered path keeps it consistent.
The second part of this PR changes how `Plugin` is marshaled back to JSON. `FullSource` applies similar normalisations that the backend should be applying to plugin sources, and comes with the ~same suite of tests. 
Source normalisation of plugins is better suited to the marshaling phase than the parsing/unmarshaling phase, because:
* interpolation applies to plugin sources and configs, so putting it in the parsing phase would require reworking interpolation
* if/when `pipeline` is spun out into its own library, users would be writing `Plugin` literals …
> Fix signature mismatches when steps have plugins

- internal/pipeline/plugins.go
Previously, when unmarshalling a step that had no plugins, it would fail to accept the job:
```
2023-08-25 10:27:47 WARN   Bens-Macbook-Pro-1 Buildkite rejected the call to accept the job (unmarshalling CommandStep: unmarshaling plugins: got <nil>, want []any or *ordered.Map[string, any])
```
> Handle the case when unmarshalling a step where there aren't any plugins

- internal/job/git.go
I upgraded from 3.31 to 3.52 and started seeing 'reference is not a tree' errors in CI. Something in the Buildkite code was not catching this properly and causing the agent to recreate the repo.
In my case, this was being caused by force pushes to branches with open PRs happening soon after a previous push.
```
$ git fetch -v --prune -- origin refs/pull/123/head
...
From github.com:my/repo
* branch                    refs/pull/123/head -> FETCH_HEAD
$ git checkout -f 7890000000
fatal: reference is not a tree: 7890000000
⚠️ Warning: Checkout failed! checking out commit "7890000000": exit status 128 (Attempt 1/3 Retrying in 2s)
$ git clone -v -- git@github.com:my/repo.git .
Cloning into '.'...
...
$ git clean -fdqx -e /.local
$ git fetch -v --prune -- origin refs/pull/123/head
```
Based on …
> Fix detection of missing commits on checkout

- hook/scriptwrapper.go
- internal/file/is_opened.go
- internal/file/opened_by.go
- internal/job/executor.go
- internal/job/shell/shell.go
A customer reported that their jobs were unable to run a hook because the hook wrapper script was locked.
The hooks should have collision avoidant names, and they should have closed by the agent worker goroutine that created them prior to execution, which is in the same goroutine. So it's a bit of a mystery how the script wrapper could remain open.
We could just add more retry to work around this, but it would like to find the cause. So, I've done two things in this PR:
- Retry executing the hook if we get a fork/exec error
- If the retry is exhausted, log the error and try to determine what process has the file open
That latter will only work if:
- the process that has the file open is long-lived enough for the error handling to catch it with the file open, and
- the agent has permission …
> Retry fork/exec errors when running hook

- .buildkite/steps/publish-docker-image.sh
https://github.com/containers/podman/discussions/19796
Perhaps we should just use `stable:v1`?
> Update skopeo to v1.13.2

- .buildkite/steps/publish-docker-image.sh
https://github.com/containers/skopeo/issues/1909 summary:
Skopeo 1.11 changed behavior - when an `--authfile` flag or `REGISTRY_AUTH_FILE` env var is present, it read only that file for creds. We weren't setting that flag/var ourselves but the skopeo container does: 
https://github.com/containers/skopeo/blob/7f2f46e1b97df36b2b82d1b1d87c81b8b3d21601/contrib/skopeoimage/stable/Containerfile#L44
> Fix ECR authentication failure

- api/jobs.go
- internal/ordered/map.go
- internal/ordered/map_test.go
- internal/pipeline/parser_test.go
- internal/pipeline/plugin.go
- internal/pipeline/plugins.go
- internal/pipeline/plugins_test.go
- internal/pipeline/sign.go
- internal/pipeline/sign_test.go
- internal/pipeline/step_command_test.go
Dogfooding showed that signed steps with plugins still tended to fail verification. After digging around with `--debug-http`, it turns out that plugin config maps/hashes tend to be reordered by the backend.
On the plus side: we're free to reorder keys within plugin configs! 🎉
Changes here:
- `pipeline.Plugins` can now be unmarshaled directly from JSON. For consistency it reuses the underlying `UnmarshalOrdered` using the same technique as for `CommandStep`.
- `ordered` now has `ToMapRecursive`, which replaces `*Map[string, any]` with `map[string]any` recursively.
- Each `Plugin` is unmarshaled using `ToMapRecursive`.
- `api.Job.ValuesForFields` now passes `BUILDKITE_PLUGINS` through a JSON unmarshal-marshal round-trip. The JSON marshaler writes (plain) map keys in sorted order. 
Net …
> Fix verification for steps with plugins, part 2

- agent/integration/job_verification_integration_test.go
- agent/verify_job.go
#2339 opened a possible edge case where if a job includes a step with an env var, but that env wasn't copied to the job, then the job could verify successfully with a different env than was intended during signing.
Even without #2339, this seems like a good defensive check to add anyway.
> Catch step env/job env edge case

- internal/job/checkout.go
- internal/job/integration/checkout_git_mirrors_integration_test.go
- internal/job/integration/checkout_integration_test.go
We have very large repositories at Cruise. And I found it's very slow to `Preparing working directory` when the commit is a merge commit that contains a lots of changes as below:
( I can send a build link in private if you need)
More investigation shows that's the `git show` during agent bootstrap that's taking more of the time to do `git diff` underneath. Since the AFAIK, buildkite agent know needs to get the HEAD commit's commit information rather than the actual `git diff`. we can simply replace the `git show` with `git log`, which prints out identical information for this purpose.
**Testing**
using git log
```
$ git --no-pager log -1 HEAD -s --format=fuller --no-color
commit 7bfab5fd5419feeeb6d3e9a21ad165fc2eb332be (HEAD -> cheng/step0-git-log, origin/cheng/step0-git-log)
Author: …
```
> Use git log to get commit information

- EXPERIMENTS.md
- agent/artifact_uploader.go
- agent/artifact_uploader_test.go
- go.mod
- go.sum
- internal/experiments/experiments.go
Why a new glob library? 
- We've had issues reported where `artifact upload` tries to walk into subdirectories it has no permissions to enter, despite the pattern not matching those subdirectories at all.
- It's also inconvenient to have the glob bomb out half way with ambiguous-sounding errors.
- Syntax problems, e.g. #2305
Why _write_ a new glob library?
- I have doubts about the use of `fastwalk` (which is vendored in go-zglob).
- I have doubts that go-zglob could be adapted to fix some of the problems above (it translates glob patterns into regexes under the hood, which makes partial matching for candidate directories difficult, and the code harder to read).
- There are probably other glob libraries that would work, but wheee I'd already started
I realise I'm sneaking in a significant …
> Provide new glob library with experiment

- README.md
- docs/macos.md
- EOL platforms may be dropped from new minor releases
- Fix lies in the macOS versions table (e.g. Go 1.12 was the last Go to support Yosemite - not 1.13. Go 1.13 required El Capitan. This also impacts agent versions, etc) and add links
- Add linebreaks
- Fix Markdown lints
- Refresh `buildkite-agent --help` output
- Update copyright year
- Change `[here]` to something else
- Change telemetry features link
> README and macOS versions update

- api/annotations.go
- api/artifacts.go
- api/chunks.go
- api/client.go
- api/client_internal_test.go
- api/header_times.go
- api/jobs.go
- api/meta_data.go
- api/oidc.go
- api/oidc_test.go
- api/pipelines.go
- api/steps.go
Making up URLs with `fmt.Sprintf` can be dicey. 
Most of these are no-ops in the normal case because job IDs and build IDs have nice formats. However, annotation contexts are arbitrary strings. 
Currently, an annotation context containing `.` can be created (passed through a JSON encoded request body) but not deleted (passed through the URL path). The reason was a bit surprising: Rails handles `.` in path segments specially. So `.` also needs to be escaped. Fortunately, this seems to be sufficient to fix the bug without any backend changes.
> Escape path segments in URLs made with fmt.Sprintf

- agent/agent_configuration.go
- agent/job_runner.go
- agent/job_runner_test.go
- agent/run_job.go
- clicommand/agent_start.go
The `allowed-repositories` command line param allows users to specify an allow-list of regular expression strings. E.g.:
```
buildkite-agent start \
--build-path=/tmp/buildkite-builds \
--token 123 \
--allowed-repositories "^git@github.com:buildkite/.*"
```
If the `allowed-repositories` param is used and a job arrives with a `BUILDKITE_REPO` value that doesn't match an entry in the list then the job is rejected. 
If the `allowed-repositories` param is unused then the behaviour is unchanged from current.
> Add `allow-repositories` param to enable repository allow-listing

- .github/dependabot.yml
- go.mod
This PR adds three new [groups](https://github.blog/2023-08-24-a-faster-way-to-manage-version-updates-with-dependabot/) to our dependabot config - this means that updates to the following:
- Opentelemetry libs
- "extended stdlib" `golang.org/x/*` libraries
- Cloud provider (aws, gcp, azure) libraries
will be grouped together into PRs (per group) when they come in
While i'm here, this PR updates the `go` directive in our `go.mod` file from `1.18` to `1.20`. **This is not a go version update**, it just tells the go toolchain what features are available.
> Dependabot groups

- .buildkite/steps/publish-rpm-package.sh
It installs tzdata, which by default prompts for input when it can't discover what timezone you're in. We fix this by passing the magic variable DEBIAN_FRONTEND=noninteractive
> Fix apt install awscli

- internal/job/checkout.go
- internal/job/knownhosts.go
- internal/job/plugin.go
- internal/job/shell/main_test.go
- internal/job/shell/shell.go
- internal/job/shell/shell_test.go
The flake is probably because the `os.Stat` loop exits when the lock file exists, but not when it is locked, because [`flock(2)`](https://linux.die.net/man/2/flock) is a separate syscall to `open(2)`.
This also:
- changes the API for `LockFile` to remove the timeout arg in favour of context cancellation
- changes from `time.Sleep` to a timer, allowing the lock loop to be cancelled more quickly
- exits from the retry loop when `TryLock` returns an error
> Fix flaky TestLockFileRetriesAndTimesOut

- internal/pipeline/parser_matrix_test.go
- internal/pipeline/step_command_matrix.go
Also, demote SoftFail on matrix adjustments to being a RemainingField, as it's unused by the agent
> Fix parsing pipelines what use a string as the skip key in a matrix adjustment

- packaging/docker/alpine-k8s/Dockerfile
- packaging/docker/alpine/Dockerfile
- packaging/docker/ubuntu-18.04/Dockerfile
- packaging/docker/ubuntu-20.04/Dockerfile
- packaging/docker/ubuntu-22.04/Dockerfile
Sometimes, the upstream distro will release a package but we had to wait
until they made a new image before our images would get the new package.
This means the security scanners will report fixable vulnerabilities that a
rebuild would not fix. With this change, we just have to make a new
build to pull in the patched packages.
Fixes: \#2408
> Upgrade pre-installed packages in docker images

- clicommand/agent_start.go
- clicommand/pipeline_upload.go
We emit the warning when pipeline signing is actually used, but the flags themselves aren't marked as experimental, which is confusing especially when reading the docs online.
> Add `EXPERIMENTAL:` to the help text for all pipeline signing flags

- agent/verify_job.go
- api/jobs.go
- go.mod
- go.sum
- internal/pipeline/sign.go
- internal/pipeline/sign_test.go
- internal/pipeline/step_command.go
This does a couple of things, the main one being removal of `writeFields` and `writeLengthPrefixed` and using JCS (RFC 8785) instead. 
Rather than keeping the JSON encoding for plugins separate, this changes the `SignedFielder` to  work with `map[string]any` and puts `Plugins` in there directly, so that when the canonical payload is encoded, it only needs to encode JSON and transform it once.
Changing `SignedFielder` implies making some changes to `verifyJob`. `Job` adopted the `ValuesForFields` approach as a way to simplify `verifyJob`. But `Plugins` doesn't neatly compare against `string`. I think that really, `ValuesForFields` isn't a good abstraction for `Job`, because each field needs a slightly different approach for consistency checking, and that should be more obvious.
> Use canonicalised JSON as signature payload

- agent/verify_job.go
- internal/pipeline/sign_test.go
- internal/pipeline/step_command.go
This includes matrix in the signature. However, any matrix that is not `nil` will (still) fail to verify.
Matrix is required (sneaking in a matrix could alter how a step should be interpreted), which will invalidate any existing signatures. ~~so I'm also taking this opportunity to centralise the canonicalisation of data that gets signed. `writeCanonical` is a bit ASN.1-inspired, but I hate ASN.1, so you get this instead.~~ We went with [JCS](https://rfc-editor.org/rfc/rfc8785.html) instead.
Like `Plugins`, `Matrix` is included in the signed data wholesale. Reasons this is up for debate:
- Data from a future form of matrix (new fields that would unmarshal into `RemainingFields` today) might or might not affect valid matrix combinations in the future, so to be safe we should include …
> Matrix signing

- go.mod
- go.sum
We updated roko to avoid a dependency. But the agent uses that dependency itself (testify), so it looks like not much happened in go.mod.
> Update roko to v1.1.1

- internal/pipeline/interpolate.go
- internal/pipeline/pipeline.go
- internal/pipeline/plugin.go
- internal/pipeline/step_command.go
- internal/pipeline/step_command_matrix.go
- internal/pipeline/step_group.go
- internal/pipeline/step_input.go
- internal/pipeline/step_trigger.go
- internal/pipeline/step_unknown.go
- internal/pipeline/step_wait.go
- internal/pipeline/steps.go
The current approach to interpolation assumes `${VAR}`-style interpolation, but we also want to do basically the same thing with the template-like `{{matrix}}` tokens. 
I considered using a func type like in #2395, but if we want to exclude matrix from interpolating into itself, it might make sense to do that by introspecting the type of the string transformer.
> Make interpolation helpers transform-agnostic

- agent/integration/job_verification_integration_test.go
- agent/verify_job.go
- internal/pipeline/interpolate.go
- internal/pipeline/sign.go
- internal/pipeline/sign_test.go
- internal/pipeline/step_command.go
- internal/pipeline/step_command_test.go
Matrix interpolation is going to thwart the existing `env::` scheme. Splitting pipeline and step env checks should get ahead of the problem.
**The problem:** in the existing scheme, all vars (step and pipeline) are combined into the one "namespace" of signed fields. This happens "pre-matrix". Pipeline env vars should make it through unscathed, but step env vars will have matrix interpolation applied in the backend. So any step env var (~~not overridden by the pipeline env~~ lol turns out step vars should take precedence over pipeline vars) containing a matrix token is going to have a different value in the job env than it had when it was signed, and will fail to verify.
**The solution:** Preserve the step env as its own field, and keep it separate from pipeline env during signing. …
> Separate step/pipeline env vars for job validation

- agent/integration/job_verification_integration_test.go
- agent/verify_job.go
The old errors are detailed, which is nice if you are working on the agent a lot and debugging verification failures. There is too much information for ordinary users to bother with, and potentially a trove of data that a hypothetical attacker might take advantage of.
> Reduce information in verification errors

- agent/integration/job_verification_integration_test.go
- agent/verify_job.go
- api/jobs.go
- internal/pipeline/step_command.go
- internal/pipeline/step_command_matrix.go
- internal/pipeline/step_command_matrix_test.go
- internal/pipeline/steps.go
> Enable matrixes for step signing

- agent/integration/job_verification_integration_test.go
- internal/pipeline/interpolate_matrix.go
- internal/pipeline/interpolate_matrix_test.go
- internal/pipeline/parser_matrix_test.go
- internal/pipeline/plugin_test.go
- internal/pipeline/step_command_matrix.go
- internal/pipeline/step_command_matrix_test.go
- internal/pipeline/step_command_test.go
This PR does two things:
1. (Fixes a verification bug) All scalars inside `Matrix` are stored as strings. During parsing they are all `fmt.Sprint`-ed. `MatrixScalars` is gone. `MatrixSetup` is now `map[string][]string` and `MatrixAdjustmentWith` is now `map[string]string`. This should fix verification when non-string scalars are used, because the backend at some point stringifies them all, before they are reflected back in the job payload, meaning that the JSONified `Matrix`es are different during verification, manifesting as a signature verification failure. Stringifying everything in advance should be no issue, because there is no difference between the results of interpolating `47` and `"47"` into a matrix token.
2. (Willing to go back on this) `MatrixPermutation` is now …
> All scalars in matrixes are now strings

- .buildkite/pipeline.release-experimental.yml
- .buildkite/steps/publish-rpm-packagecloud.sh
I'd like to try uploading new agent packages to packagecloud repositories. I'd also like to get it working using OIDC tokens, so we can avoid storing or transmitting long-lived secrets during the exchange.
This introduces a step which uploads new rpms to [a new agent-experimental repository](https://packagecloud.io/buildkite/agent-experimental). It's set to soft fail because I expect this to fail at first, but I'll be pushing through [the OIDC support](https://github.com/computology/packagecloud.io/pull/1815) to make this work.
Fixes PKG-5934.
> Add packagecloud upload step for rpms

- .buildkite/Dockerfile-compile
- .buildkite/Dockerfile-github-release
- packaging/docker/alpine-k8s/Dockerfile
- packaging/docker/alpine/Dockerfile
- packaging/docker/sidecar/Dockerfile
- packaging/docker/ubuntu-18.04/Dockerfile
- packaging/docker/ubuntu-20.04/Dockerfile
- packaging/docker/ubuntu-22.04/Dockerfile
In #2410 I responded to a report that the system packages in our docker images were out of date by upgrading the system packages at build time. However, this has a notable disadvantage - the version in an image is now determined both by the commit of the build and the time that the build ran. So we have lost some reproducibility. So in this PR, we revert that.
However, we can do a bit better than the situation before. Previously, we only pinned the tags of the base image, for example we pinned the `ubuntu` image to the tag `22.04`. Dependabot would only update the image when a newer tag emerged, which is very infrequent in the case of `ubuntu`. However, maintainers of the base image regularly push newer images to the tag that we have pinned. This mutates the "digest" of the image, and …
> Revert "Upgrade pre-installed packages in docker images" and Pin docker images by digest

- .buildkite/pipeline.release-experimental.yml
This reverts commit 0d7bd6c50dc54bc9ed6783d74c0a7ba74f6ba702.
Due to a misconfiguration in branch protection settings, this commit was erroneously pushed straight to main. We've fixed the issue across this and other repos, and will re-submit this change with review.
> Revert "Hotfix: Try ruby image"

- .buildkite/pipeline.release-experimental.yml
Turns out the agent image doesn't have ruby, so can't gem install. The ruby image seems to work great in a dry-run, though.
> Update packagecloud RPM release step to use `ruby:3.0` image

- .buildkite/pipeline.release-experimental.yml
- .buildkite/pipeline.release-stable.yml
- .buildkite/pipeline.release-unstable.yml
- .buildkite/steps/publish-debian-packagecloud.sh
Now that the step from #2438 is [functional](https://buildkite.com/buildkite/agent-release-edge/builds/987#018b4563-e579-4417-a557-2d9e6ec2f59c), this should complete coverage over stable, unstable and experimental repositories for both debian and rpm.
The appropriate policies have been set up for these package repositories ahead of time.
Fixes PKG-5934.
> Push all new agent packages to Packagecloud

- agent/header_times_streamer.go
- agent/job_runner.go
headerRegex (now headerRE) was used to find headers. Because it was anchored on both ends (^...$), it (morally) had to run through the whole string in order to match, though I hope that the RE2-like regexp engine optimises (.+)?$ to nothing.
We can say the same for headerExpansionRE. Matching `\s+` in between ^^^ and +++ just seems unnecessary - we document it as "^^^ +++". So I changed it to `\s`.
In both cases the new regexps only need to process either 4 or 7 bytes in order to match. 
The argument for removing matches of ansiColourRE applies to header expansions as well, so the fact that isHeaderExpansion didn't do the same thing is arguably a bug. Instead, I rearranged things so headerExpansionRE can test the same decolourised line (inside Scan), removing both isHeader and …
> Reduce header regexps

- EXPERIMENTS.md
- go.mod
- internal/experiments/experiments.go
- process/main_test.go
- process/process.go
- process/process_test.go
The command inside a build job is allocated and attached to a [Pseudoterminal](https://en.wikipedia.org/wiki/Pseudoterminal) so that programs detect that their output will be interpreted by a terminal emulator, and so they default to emitting colours, cursor movement, and other escape sequences.
This pull request sets that PTY into raw mode, disabling any default processing of the input/output streams, most specifically the [`ONLCR` flag](https://man.archlinux.org/man/termios.h.0p#ONLCR): “Map NL to CR-NL on output”.
Otherwise the PTY driver in the kernel will map `LF` (`\n`) to `CR` `LF` (`\r\n`), and possibly do other unwanted processing of the output stream. This is particularly vexing when programs intentionally (misguidedly?) emit `CR LF` newlines which get mapped to `CR CR LF`.
This …
> experiment: pty-raw avoids LF→CRLF mapping by setting PTY to raw mode

- internal/redact/redact.go
As opposed to a log line per short variable.
> Log warning about short vars once

- agent/integration/job_verification_integration_test.go
- agent/verify_job.go
- clicommand/commands.go
- clicommand/config_completeness_test.go
- clicommand/pipeline_upload.go
- clicommand/tool_keygen.go
- clicommand/tool_sign.go
- env/environment.go
- internal/pipeline/pipeline.go
- internal/pipeline/pipeline_invariants.go
- internal/pipeline/sign.go
- internal/pipeline/sign_test.go
- internal/pipeline/step_command.go
- internal/pipeline/steps.go
The pipeline invariants are:
- pipeline slug
- organization slug
- repository
An agent configured to verify signatures will now check that the pipeline slug, organization slug and repository in the accepted job definition are the same as the ones in the signature.
The cli subcommand
```
buildkite-agnet tool sign --jwks-file-path <keyfile> --signing-key-id <key-id> --pipeline-slug <pipeline-slug> --organization-slug <organization-slug> --repo <repository> <pipeline-yaml-file>
```
can be used to sign the initial pipeline. Its output may be pasted into the Steps Editor in the Buildkite Web UI so that the initial pipeline may be verified as well.
I created a new struct `CommandStepWithInvariants` and moved the `SignedFielder` implementation from `CommandStep` to it. I went back and forth on a …
> Add some pipeline invariants to the signature and create a cli subcommand to sign a pipeline

- agent/artifact_uploader.go
It's possible to configure `Paths` with a lot of separate globs. It's not unreasonable that each of these could be of the form `**/something`, and each one requires walking the entire directory tree. `go-zglob` is not terribly slow because it uses a parallel walker under the hood (`fastwalk`). While I think about how to speed up `zzglob`, this is a reasonable first step.
This also fixes a bug where `wd` is replaced with `"/"` (or `filepath.VolumeName(absolutePath) + "/"` on Windows) on the first glob path in the list that is is absolute, changing `wd` for later glob paths that might not be absolute.
> Parallelise artifact collection

- internal/job/checkout.go
- internal/job/git.go
- internal/job/integration/checkout_integration_test.go
- internal/job/integration/git.go
When `BUILDKITE_COMMIT` is set to a short commit hash, the agent will first attempt to just fetch that hash, but this will not work and git will return an error. Recently we changed the behaviour so that this error would delete the checkout directory, and try again, but it would still attempt to fetch the short hash. After a few attempts, the checkout would fail.
Instead, the old behaviour allowed the agent to fetch all heads and tags, and then checkout (instead of fetch) the short commit hash. This successfully sets the state of the build directory to the commit that was intended to be checked out.
In this PR, we use the `olefactor` to read the error message that git prints when the `fetch` fails and fall through from retrying the checkout to fetching all the heads and tags. I've also …
> Fix checkout of short commit hashes

- agent/artifact_uploader.go
The loop starts a bunch of goroutines, so there's unlikely to be an error immediately. It needs to wait.
Not sure why I got this wrong lol
> Fix wg.Wait / error check out of order

- agent/agent_configuration.go
- agent/job_runner.go
- agent/job_runner_test.go
- agent/run_job.go
- clicommand/agent_start.go
Protection from malicious plugins - An allowed-plugins command line param accepting an allow-list of regular expression strings. e.g.: ^github.com/buildkite/.*$. If the param is used and a job arrives with BUILDKITE_PLUGINS containing a plugin that doesn't match an entry in the list then the job is rejected.
Work is a part of the https://github.com/buildkite/agent/issues/2368
I made some big git mistake in the https://github.com/buildkite/agent/pull/2394... 🤦
> Add allowed-plugin param to enable plugins allow-list

- agent/integration/job_verification_integration_test.go
- agent/job_runner.go
- agent/log_streamer.go
- agent/run_job.go
- agent/verify_job.go
- jobapi/server.go
I had to also add a header to the Job API logs as otherwise they would appear to be part of the verification log group.
There are probably other such logs like this, we need to weed them out eventually.
I also simplified some of the logging, in particular, the signature is not printed as part of the log group header, but in a subsequent line.
As the log group will be collapsed unless there is a failure and the agent is configured to block, the signature will not be immediately visible.
Also, for the agent logs, I tried to add fields using the `logger.WithFields` method. These will be displayed in the logfmt format (or json if configured to do so). This will make the logs more structured.
Finally, I've removed the use of `(*JobRunner).logStreamer.Process` to send logs directly to the API …
> Add log group headers and timestamps to job verification success and failure logs

- agent/header_times_streamer.go
(Auto-merge and I raced; auto-merge won.)
Also, 100 should be plenty, but why not 1000? That much memory doesn't cost much.
> Add more comment about channel capacity

- agent/agent_configuration.go
- agent/agent_worker.go
- agent/integration/job_verification_integration_test.go
- agent/job_runner.go
- clicommand/agent_start.go
- clicommand/pipeline_upload.go
- clicommand/pipeline_upload_test.go
- clicommand/tool_keygen.go
- clicommand/tool_sign.go
- internal/jwkutil/doc.go
- internal/jwkutil/generate.go
- internal/jwkutil/key_in_jwks_file.go
- internal/jwkutil/load_key.go
- internal/jwkutil/validate.go
- internal/jwkutil/validate_test.go
- internal/jwkutil/validate_test_helpers_test.go
It will be inferred from the key set if the key set has only one key. I decided to move most of the common parts of key signing shared between `pipeline upload` and `tool sign` to the `jwkutils` module.
Also, I made some of the arguments a bit shorter.
In `pipeline upload` and `tool sign`, the following arguments were changed:
- `jwks-file-path` -> `jwks-file`
- `signing-key-id` -> `jwks-key-id`
I've preferred `file` to `path` because `path` suggests that a directory may be given, but that's not the case. It's also obvious that the key id is used for signing in these sub-commands.
In `start`, there remains a need to distinguish the signing key and verification key to discourage users from distributing both keys everywhere. However, I make the follow changes:
- `job-signing-jwks-path` -> …
> Allow omitting the key ID when signing pipelines

- agent/artifact_uploader.go
- agent/artifact_uploader_test.go
`MultiGlob` can take care of coalescing multiple patterns that have the same root into a single directory walk, as well as parallelising walks.
Since `GlobPath` isn't used in the backend, and it is unclear which pattern a file could have matched, drop `GlobPath` from the `Artifact`.
A small tweak is to grab the file size from the result of `io.Copy` (instead of doing another `Stat`), and also check its error.
> Use zzglob.MultiGlob, drop GlobPath field

- internal/jwkutil/validate.go
This new method was added in https://github.com/lestrrat-go/jwx/releases/tag/v2.0.16, and might not be called automatically.
Same as buildkite/go-pipeline#6
> Add key.Validate call

- scripts/build-binary.sh
- version/version.go
scripts/build-binary.sh was setting buildVersion, but the variable is now buildNumber.
Plus an opportunistic shell style cleanup.
> Fix build number incorporation

- agent/artifact_uploader.go
- agent/download.go
- agent/log_streamer.go
When displaying byte quantities, use IEC / base-2 (1024 → KiB etc) rather than SI / base-10 (1000 → KB etc) units.
Using IEC / base-2 units matches our server-side display; consistency reduces confusion.
(Rails defaults to IEC / base-2, although it labels them e.g. “KB” not “KiB”).
Related:
- https://en.wikipedia.org/wiki/Byte#Multiple-byte_units
- https://pkg.go.dev/github.com/dustin/go-humanize#IBytes
> Humanize bytes to IEC (1024 → KiB etc) not SI (1000 → KB etc)

- agent/log_streamer.go
- agent/log_streamer_test.go
- agent/run_job.go
- Use the WaitGroup to count workers instead of pending log uploads, averting any potential races on the WaitGroup
- Signal to workers that work is complete by closing the channel, instead of sending nil several times
- Handle context cancellation in worker with a select
- Add context arg to Process, and a select to handle it there, too
- Track whether the streamer has been stopped, and use that to return an error from Process after Stop
- Reinstate error handling inside streamJobLogsAfterProcessStart and output buffer closing (with explanatory comment)
- Neaten up core of Process loop
- Doc comments
- A test!
Handling context cancellation in a select with the channel operations is, strictly speaking, a bug fix (context should be available as a lever to cancel blocked operations), but …
> More log streamer cleanups

- clicommand/meta_data_set.go
Retry longer in `buildkite-agent meta-data set <key> <value>`
Was 10x5 sec constant:
> 5, 5, 5, 5, 5, 5, 5, 5, 5, 5 seconds (total delay: 45 seconds)
Now 10x2 sec exp (see https://github.com/buildkite/roko/pull/15):
> 2, 3, 5, 8, 13, 21, 34, 55, 89 seconds (total delay: 233 seconds)
This means if the meta-data set endpoint is rate-limited for a whole minute, there's a much higher chance of the operation eventually succeeding in one of the next few one-minute rate limit buckets, rather than failing the job it's running in.
> MetaDataSetCommand: retry longer (exponential backoff)

- clicommand/pipeline_upload.go
- clicommand/tool_keygen.go
- clicommand/tool_sign.go
- go.mod
- go.sum
**This PR:** Updates go-pipeline to [v0.3.0](https://github.com/buildkite/go-pipeline/releases/tag/v0.3.0). This removes several signing algos (HS**, **256 and **384).
It also marks pipeline signing as GA! Woo!
> Go pipeline 0.3.0

- process/process.go
- process/process_test.go
- process/signal.go
The process can start, run, and output "Ready" before `p.pid` is set. Use of `p.pid` in `Interrupt` and `Terminate` is guarded by `p.mu`, but setting `p.pid` was not guarded. Even with the guard, it is still possible that `Interrupt` is called before `p.pid` is set, so I restored `<-p.Started()` (that I removed in #1852).
> Fix data race on Process.pid

- clicommand/agent_start.go
i came across this when reviewing https://github.com/buildkite/agent/pull/2406 - i'm kind of shocked that this made it through review. i blame the reviewer (me).
sigh. this is technically a breaking change. what do we do about that?
cc/ @jakubm-canva @david-poirier
> Fix typo in environment variable name for allowed-plugins

- internal/tempfile/tempfile_test.go
Because the tests are parallel, using the same directory would cause flakes. So also use a different directory for each test.
> Use os.RemoveAll in cleanup

- process/process.go
A customer is seeing errors trying to start a process on an exotic platform that we currently don't support. They are getting an error from `(*Process).Run`. Let's add some debug logging and error wrapping to see what's going on.
> Add more debug logging and error wrapping for running processes

- internal/job/executor_test.go
We've had several hacker one reports telling us we have leaked credentials in this codebase. Let's pop in a comment to make it clear these are example values, not leaks.
> Make it clear these are not leaked credentials

- install.ps1
When using the very helpful `buildkite-agent` installation powershell script, it is occasionally necessary to install some other version, rather than the current latest release.  While it would be cool to support specifying an actual version, the simplest method of this is to simply provide the exact URL to be downloaded.  Example invocation:
```
$env:buildkiteAgentUrl = "https://github.com/buildkite/agent/releases/download/v3.39.0/buildkite-agent-windows-amd64-3.39.0.zip"
iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/staticfloat/agent/patch-1/install.ps1'))
```
> Enable overriding buildkite-agent url in `install.ps1`

- install.ps1
The script is throwing "page not found" error due to the changes to the $version parameter. the string interpolation is also not working as expected due to the "?" after $version parameter in the request URL variable
> [2558] Buildkite build script is broken due to missing version default value

- agent/job_runner.go
Adding build number and id to the log fields otherwise it's difficult to debug.
> Add more fields to job logger

- agent/job_runner.go
- agent/run_job.go
Occasionally something goes wrong and the agent gets stuck retrying job log uploads or job finish calls forever (eg because the agent's access token is revoked). Forever is a really long time. Instead just retry for ~24 hours. I also changed these to exponential backoff rather than constant time because if a request fails, it's likely to either be fixed very quickly (network blip) or take a long time (incident). So no point retrying every second if it's already failed a hundred times. I also made them both the same and 2 seconds initial interval to match other parts of the code.
Using the `ExponentialSubsecond` algorithm with a 2 second initial interval, this is what the retry intervals looks like:
Retry attempt | Delay | Cumulative delay
-- | -- | --
0 | 0:00:02 | 0:00:02
1 | 0:00:03 | …
> Replace roko.TryForever with exponential backoff for ~24 hours

- README.md
we change public method signatures all the time, and we should call it out to users in the readme. i more or less crammed this in the first place in the readme i thought would fit it, but i'm happy for it to go elsewhere
> Add readme note about go module versioning

- agent/job_runner.go
- agent/run_job.go
https://linear.app/buildkite/issue/PDP-2032/on-the-agent-side-we-need-to-not-retry-on-a-401
This PR is related to job tokens
When the agent receives a 401 from the api due to invalid tokens we don't want to keep retrying. Below is a screen shot of what happens when the token expires
This PR is my very poor attempt to stop the agent retrying when it gets a 401. The screenshot below gives a bit more detail
Testing on Localhost
Now when a token expires (buildkite returns a 401) the agent will eventually stop trying however it does seem to repeatedly loop thru the whole process (assigned..started..process is running..job token error..finished..and then back to assigned again). In my test I have a job that has timed out but I'm worried if a job doesn't have `timeout_in_minutes:` would it just …
> PDP-2032 when api returns a 401 stop retrying and bail out

- clicommand/artifact_download.go
Docs said that either name or job id was okay, but in this context 'name' is unclear. In reality, any of the step's key or label are okay, as is a job id
> Clear up artifact downlad step flag docs

- clicommand/agent_start.go
We only have one example for `--allowed-environment-variables` so fix the grammar appropriately. I think one example is enough so I didn't add a second example.
> Fix docs for --allowed-environment-variables

- scripts/build-github-release.sh
Opportunistic improvements to this one file.
Makes the tarball less susceptible to generating reports like #2612
* Shell style tidyups, mostly double-quoting and curly braces
* Avoiding tarballing `.`
> build-github-release.sh tidyups

- .buildkite/pipeline.yml
- .buildkite/steps/upload-release-steps.sh
Remove the first `$DRY_RUN` and branch check from the script, and make it a pipeline conditional instead.
This means one less script for an agent to run, when cycling on a PR.
None, it's just something I spotted.
I did some archaeology: the `$DRY_RUN` check was added to the script (and `branches` removed from the pipeline step) in 341b1f4 (March 2018), but pipeline conditionals were introduced later.
See Description.
> Move check from upload-release-steps.sh to pipeline.yml

- internal/job/executor.go
When a hook changes an environment variable, and the environment
variable is on an allow list of known non-secrets, the change is logged
as
```
<env var> is now <new value>
```
At least that was the intention. However, what was actually logged was
```
<env var> is now {<old value> <new value>}
```
This changes it to
```
<env var> was <old value> and is now <new value>
```
https://coda.io/d/Escalations-Feedback_dHnUHNps1YO/Pipelines-Escalations_su7FT#Pipelines-Escalations-Board_tu__K/r252&view=modal
> Fix environment variable changes in hooks logged incorrectly

- clicommand/pipeline_upload.go
- clicommand/pipeline_upload_test.go
- env/environment.go
- go.mod
- go.sum
On windows, we should allow interpolation of runtime environment variables into pipeline YAML to be case insensitive, as that's what would happen if the commands ruan in a Windows shell.
https://coda.io/d/Escalations-Feedback_dHnUHNps1YO/Pipelines-Escalations_su7FT#Pipelines-Escalations-Board_tu__K/r251&view=modal
Use a [v0.4.0](https://github.com/buildkite/go-pipeline/releases/tag/v0.4.0) of `go-pipeline`, which has a fix for case sensitivity on Windows. This version also rectifies the [precedence](https://buildkite.com/docs/pipelines/environment-variables#environment-variable-precedence) of runtime environment variables over pipeline environment variable when interpolating a pipeline.
> Fix pipeline interpolation case sensitivity on Windows, and runtime environment variable precedence

- api/client.go
- api/github_code_access_token.go
a minor refactoring slipup in #2599 meant that the json package was complaining when trying to decode into a `GithubCodeAccessTokenResponse` struct. 
this PR fixes that issue.
#2599
> Fix NPE when decoding token response

- .buildkite/pipeline.release-experimental.yml
- .buildkite/pipeline.release-stable.yml
- .buildkite/pipeline.release-unstable.yml
@moskyb pointed out that the packagecloud steps have been unhappy for a while:
We made a change a while back that repos are now restricted to one package type, so they need to be split apart. This should help.
I'm a bit unsure exactly where the failure is coming from, though. It's just saying "failed." Let's see if this much fixes it, or if we need to dig a bit deeper.
> Use separate repos for each package type

- clicommand/agent_start.go
- internal/experiments/experiments.go
I often find myself wanting to know which experiments are known and enabled on an agent. While this information is in the debug logs, I think having it also available in the info logs would be useful.
None
The agent startup now looks like this:
> Add an info log of which experiments are known and enabled on agent start

- clicommand/agent_start.go
which queue the agent listens for work on is an important part of the agent's lifecycle, especially with queues being made more explicit as part of our work to make clusters the default in buildkite. however, getting the agent to listen on a particular queue is a bit of an odd experience, it's a super special option in the `--tags` flag
```
buildkite-agent start /* ... */ --tags "queue=deploy"
```
this PR brings queue up to being a first-class citizen in the agent's CLI, giving it its own flag, so now it's `buildkite-agent start --queue deploy`. much nicer!
behind the scenes, we're still munging the queue into the tags that the agent sends to the buildkite mothership when it registers, as that's what the backend expects, but the CLI flag makes things nicer to use.
> Add explicit queue flag to the agent

- EXPERIMENTS.md
- clicommand/bootstrap.go
- internal/experiments/experiments.go
- internal/job/api.go
- internal/job/config.go
- internal/job/executor.go
- internal/job/integration/hooks_integration_test.go
- internal/job/integration/job_api_integration_test.go
The Job API experiment has been running for a while and we have decided to promote it to a stable feature. This PR removes the experiment flag from the Job API and updates the `EXPERIMENTS.md` file to promote the JobAPI.
I've also added a toggle on `buildkite-agent bootstrap` to enable/disable the Job API. Let's dicuss the merits of this in this PR.
A meeting we had
- Remove the `job-api` experiment
- Add a flag to enable/disable the Job API on `buildkite-agent bootstrap`
> De-experimentify Job API

- agent/api.go
- api/secrets.go
- api/secrets_test.go
- clicommand/commands.go
- clicommand/config_completeness_test.go
- clicommand/secret_get.go
Pipelines Secrets will allow an agent to read a secret by key from the Agent API. This adds a cli command that wraps that API call and prints the secret to stdout.
In a future PR we will add support for redacting that from the job logs.
This feature is currently under development and is not yet generally available in the Agent API.
You can see it in action with my local bk/bk here:
https://linear.app/buildkite/issue/COMP-199/read-secret-from-agent
- Add `agent secret get` command
> Add cli command to read from Pipelines Secrets

- api/annotations.go
- clicommand/annotate.go
- clicommand/annotate_test.go
Introduce a new `--priority` flag for `buildkite-agent annotate` that allows setting a priority on annotations. This allows customers to influence the ordering of annotations. Annotations have a default priority of 3 and a manual priority can be set with `buildkite-agent annotate --body "Test Annotation" --priority 5` to influence the ordering of annotations. GraphQL and Agent API changes have been merged to support this new flag.
There's a feature flag that enables the new ordering in the UI. We'll need to time enabling that feature flag with this agent version being released.
Fixes COMP-175.
I've added `priority` to the existing tests. I've also tested the feature against a locally running copy of Buildkite.
Here's a test running against the production Buildkite Agent API, with the …
> Add flag for setting annotation priority

- clicommand/git_credentials_helper.go
This PR makes two changes to the git credential helper:
- It makes it only respond to the `get` git credential helper action, reducing the number of calls we have to do to the backend - previously, we were still pinging the buildkite backend when git asked us to store and erase credentials, which this helper isn't able to do. now, it'll just exit 0 when git sends us those actions. [this is what git recommends you do](https://git-scm.com/docs/gitcredentials#Documentation/gitcredentials.txt-codegetcode:~:text=If%20it%20does%20not%20support%20the%20requested%20operation%20(e.g.%2C%20a%20read%2Donly%20store%20or%20generator)%2C%20it%20should%20silently%20ignore%20the%20request.).
- It chills out a lot of the logging, bumping everything down to `debug` level. we also include a little more …
> Chill out credential helper logging

- jobapi/client.go
- jobapi/client_test.go
When this test was run locally, it always passed. However, when run is
run in CI, it can fail as the BUILDKITE_AGENT_JOB_API_SOCKET will be set
for the buildkite job that the test is run in!
https://buildkite-corp.slack.com/archives/C061U5PG9K5/p1708649091079859
Fixed a test
> Fix test of JobAPI requiring socket set

- internal/job/checkout.go
- internal/job/executor.go
When using buildkite's git-credential-helper, the agent may still attempt to checkout with ssh. But users who use the git-credential-helper would have set up the Github App that provides code access. This only works with https URLs. So, here, we force git to use https URLs instead of the ssh ones. We also disable the ssh key scan in this case.
I've limited this to all of GitHub. We may expand it for other SCM providers in the future.
There's a risk that this will break existing setups of self-hosted agents that already have a ssh key that works for some repos that the GitHub App with code access has not been set up for. As the git-credential-helper is not supported on self-hosted agents at the moment, and this circumstance is expected to be rare, we think that risk is acceptable. Users …
> Force GitHub URLs to use HTTPS if the agent's git-credential-helper if it is enabled

- internal/job/api.go
- jobapi/routes.go
- jobapi/server.go
The Job API would always log that a request occurred because of some middleware. This clutters the logs.
I think it should not be necessary to see this in the logs unless the server is in debug mode.
Much of the time, the server will be called by our own cli commands, which often log that they are running as well, so this will be redundant.
> Remove requests logging in the Job API unless if in debug mode

- EXPERIMENTS.md
- internal/experiments/experiments.go
- internal/job/executor.go
This has been operating for some time in our dogfood stacks and we have not
noticed any issues. It is time to promote experiment. I have not added any
code to invert the experiment, as I believe it is safe to promote without
that.
https://3.basecamp.com/3453178/buckets/27608512/messages/6299400220
> Promote `avoid-recursive-trap` experiment

- agent/agent_configuration.go
- agent/job_runner.go
- clicommand/agent_start.go
- clicommand/bootstrap.go
- internal/job/api.go
- internal/job/checkout.go
- internal/job/config.go
- internal/job/executor.go
- internal/job/shell/logger.go
- internal/job/shell/shell.go
there's a subset of warnings in the agent that are essentially us trying to clippy the users, saying "Hmm, something about this setup looks a little bit weird, but we'll proceed anyway" - notably a message about when [submodules are disabled, but the repo the agent is cloning containing submodules](https://github.com/buildkite/agent/issues/1773).
he somewhat frequently get feedback from users that when you know that you're doing the right thing - for example, if you know you're not going to need the submodules that aren't being cloned - these warnings are annoying, and pop open a large log group in the job log that isn't useful.
however, we're usually a bit reluctant to add flags to disable individual warnings - for example, a hypothetical `--disable-warning-about-submodules`, because the …
> Configurably optional warnings

- agent/job_runner.go
- internal/job/executor.go
We want to be able to gracefully cancel all phases of a job.
The graceful job cancellation feature introduced [here](https://github.com/buildkite/agent/pull/2250) is great but only applies to the checkout phase of a job.
- Use a cancellable context in all phases where processes are being run
- Pass `BUILDKITE_SIGNAL_GRACE_PERIOD_SECONDS` between the agent and executor
> Extend graceful cancellation to all job phases

- clicommand/tool_sign.go
For the pipeline signing, `buildkite-agent` uses `buildkite-agent tool sign.` However, the command's usage description prints `buildkite-agent tool sign-pipeline,` which can confuse people when there is an error.
Like the above screenshot, it's something minor but can be pretty confusing. 😅 
This PR updates the usage text in the code to match the actual command.
> [Update] Updating `tool sign` usage description to match actual command

- jobapi/server.go
The Job API prints a log group whenever it starts, which is usually once
per job, but can be more than on agent-stack-k8s. However, I think the
Job API should be transparent to the user: it is not that relevant to
them unless they are developing against it, which should the minority of
the time they are using buildkite. This removes the log group appearing in
the job logs unless debug is enabled.
This is a screenshot showing multiple job api log groups in a k8s job. It's a bit spammy.
> Silence Job API Log Group

- agent/run_job.go
The `job-` prefix was used during development/beta but when it was made stable it was dropped and the name changed. This message was just not updated then.
> Update outdated option name

- clicommand/agent_start.go
- clicommand/cancel_signal.go
When a job is cancelled, the agent sends a SIGTERM to the bootstrap process of the job. This immediately sends a SIGTERM[^1] to child processes of the bootstrap process. After the signal-grace-period, a SIGKILL is sent to these child processes and the bootstrap process exits. Currently, the signal-grace-period, though configurable, defaulted to 0s. This was done to simulate the previous behaviour where a SIGKILL was sent immediately. This PR changes the default to 9s. This value was chosen because it is the largest integer less than 10, which is the default value of the cancel-grace-period. That is the time the bootstrap process has to exit before it is itself sent a SIGKILL by the agent worker process.
[^1]: It's SIGTERM by default but that's configurable. …
> Extend default signal grace period to 9 seconds

- internal/agentapi/lock_server.go
- jobapi/server.go
- jobapi/server_test.go
I've made a few PRs to reduce the amount of logging that the job api does. But I kept missing a few places. This PR should fix that, and for good measure I've added a test to make sure that the job api doesn't log anything unless in debug mode. To test that the tests work, the commit that introduces the tests should fail and that failure should be fixed by the next commit.
In particular, it should stop printing the message that the Job API server has shut down. This was difficult to see if log headers (e.g. `+++`, `~~~`, etc) are being used in a job as it's often hidden in the last log group. But it's still an annoyance if log groups are not being used.
https://github.com/buildkite/agent/pull/2690
https://github.com/buildkite/agent/pull/2662
- The Job API should no longer print *anything* …
> Even more silent Job API

- internal/job/checkout.go
- internal/job/integration/artifact_integration_test.go
- internal/job/integration/checkout_git_mirrors_integration_test.go
- internal/job/integration/checkout_integration_test.go
- internal/job/integration/command_integration_test.go
- internal/job/integration/docker_integration_test.go
- internal/job/integration/executor_tester.go
- internal/job/integration/hooks_integration_test.go
As a part of the checkout process, the agent sets a special metadata key called `buildkite:git:commit` to a string containing information about the commit that the agent has checked out. This metadata is used by the buildkite backend to populate VCS-related information on the build, like the commit message, author and commit hash - highlighted below:
(note that in some cases this information can come from webhooks when builds are triggered that way, but not all builds are triggered by webhooks)
this information is also used set the commit used for the rest of the build; often a build will get triggered at the HEAD of a specific branch, but the HEAD of a branch will change if extra commits are added over time, so the agent needs to know the "canonical" commit for the build, which is stored …
> Always set git commit

- agent/form_uploader.go
If the agent isn't configured with a custom artifact storage location, it defaults to uploading them to an S3 bucket provided by Buildkite. The upload is performed by FormUploader, which wasn't setting a User-Agent header.
This PR adds the header, using the same tooling we have for setting User-Agent on requests to the Buildkite API.
The header is primarily for debugging. It is occasionally helpful for us to see which version of the agent was used for particular uploaded artifacts.
I have not attempted to set the User-Agent header on uploads when a custom artifact storage location (S3, GCS, Artifactory, etc) is in use. That might be a useful thing to do, but we can consider it separately.
Fixes PLT-2222
> Add a User-Agent header when uploading artifacts to Buildkite's default location

- agent/artifact_batch_creator.go
There's a debate around which 4xx code we're going to use. #2697 mentions 422 in the title but adds handling for 403. Some people think 429 is better.
Rather than playing whack-a-mole with all the 4xx codes across multiple releases, I think we should do the same thing as the log uploader and break on any of them.
> Artifact creation: Break retry on any 4xx code except 429

- agent/artifact_batch_creator.go
If the server returns an error when uploading artifacts (i.e. 400 Bad Request) then the agent will retry 10 times. 
If the artifacts uploaded exceed the service quota the server will return a 403 and we don't want the agent to retry (link to server [PR](https://github.com/buildkite/buildkite/pull/16071))
The screenshot below is from local, the service quota for max artifacts per job is not really 2 :)
**Before changes**
**After changes**
(https://linear.app/buildkite/issue/CORE-103/artifacts-per-job-communicate-when-limit-is-exceeded)
> core-103 break from retrying if we get a 422

- internal/job/executor.go
- internal/job/integration/hooks_integration_test.go
The k8s stack uses phases to split job execution between multiple containers. In particular, the checkout phase happens in a separate container to the command phase. This makes pre-exit hook execute twice, once in each container - this is usually not what is intended by plugin authors, and often breaks when the different phase have different configs or environment variables.
Changing it so pre-exit hooks only run if the command phase is enabled makes it work, and is unlikely to break anybody (who isn't deep in the agent fiddling with phases).
https://linear.app/buildkite/issue/PENT-10/make-hooks-configurable
* Refactor `includePhase` from inline closure to method
* Change pre-exit hooks to only run if phases includes `command`
* Add an integration test
> Don't run pre-exit hooks without command phase

- clicommand/pipeline_upload.go
- clicommand/tool_sign.go
- go.mod
- go.sum
* Update go-pipeline to v0.5.0
* Display new parser warnings produced by go-pipeline
https://linear.app/buildkite/issue/PS-46/json-valued-env-vars-in-pipelineyml-silently-dropped
> Handle warnings from go-pipeline `Parse`

- clicommand/agent_start.go
- internal/job/executor.go
- internal/job/shell/logger.go
- internal/job/shell/logger_test.go
- internal/job/shell/shell_test.go
- jobapi/server_test.go
In #2674, we added a feature to the agent where some warnings would be "dismissable" through CLI flags - for example, one could disable this warning:
by passing `--disable-warnings-for "submodules-disabled"`.
However, due to an oversight, this feature wasn't working on Kubernetes agents. This PR fixes that issue by correctly passing the config down the the customised logger that K8s pods use, and making it harder for developers to miss this kind of thing in the future.
#2674
> Ensure that disabled warnings get passed to the logger in kubernetes agents

- agent/integration/job_environment_integration_test.go
In #2720, we added functionality to allow buildkite to send a list of cache paths to be mounted to the agent, and plumb those through to the job executor as an environment variable.
This PR adds a test to ensure that this functionality doesn't regress.
#2720
> Add integration test ensuring that cache paths are passed to the bootstrap correctly

- .buildkite/steps/publish-docker-image.sh
- .buildkite/steps/publish-docker-images.sh
Make agent images accessible directly from GHCR.
This relates to pinning agent versions used by the k8s stack, which currently publishes images and helm charts to GHCR. Some customers might also be interested in pulling from GHCR instead of Docker Hub.
https://linear.app/buildkite/issue/PENT-9/pin-the-version-of-the-buildkite-agent-used-by-agent-stack-k8s
- `docker login` to GitHub using the existing credential
- `skopeo copy` the image to ghcr.io/buildkite/agent
I also ran a modified release pipeline to verify that it works.
> Upload agent images to GHCR

- clicommand/annotate.go
Client-side validation of the annotation body length (< 1MiB) isn't working when the annotation body is read from STDIN - instead it always falls through to the server-side validation.
Before:
```
$ /bin/bash -e -c "ruby -e \"a = ('A'..'Z').to_a; (2 * 1024 * 1024).times { putc a.sample }\" | buildkite-agent annotate"
2024-04-12 09:23:30 INFO   Reading annotation body from STDIN command=annotate
fatal: failed to annotate build: POST https://agent.buildkite.com/v3/jobs/018ecf79-1b8c-48a7-9252-7a33cd980743/annotations: 400 Bad Request: The annotation body must be less than 1 MB
```
After:
```
$ /bin/bash -e -c "ruby -e \"a = ('A'..'Z').to_a; (2 * 1024 * 1024).times { putc a.sample }\" | buildkite-agent annotate"
2024-04-12 09:24:54 INFO   Reading annotation body from STDIN command=annotate …
```
> Fix annotate client-side length check

- clicommand/agent_start.go
When setting up the agent config some setups may not have the number of CPUs available but want to spawn one worker per CPU. In this case we can interpret 0 to mean all CPUs.
Other options I considered were treating spawn as a string and doing some simple math but this seems saner (not to mention simpler). 
I'd like to run 1 agent worker per process running under NixOS, declaratively so can't use `nproc` other means.
> Support spawn setting of 0 to mean number of cpus

- internal/job/executor.go
Since #2325, we learned that the "text file busy" error reported by the customer was probably https://github.com/golang/go/issues/22315.
This change makes the retry and log pathway more specific to that error, and retries more times more frequently. It also adds a new log pathway for ENOENT, which can happen for reasons that the existing log messages obscure (e.g. the error log says something like `fork/exec /tmp/buildkite-agent-hook-wrapper/hook-script-wrapper-XYZ: no such file or directory`, but the _real_ cause is that the script starts with `#!/bin/bash` but Bash isn't there).
* Fixes #2734
> Tweak ETXTBSY retry, and be helpful for ENOENT

- EXPERIMENTS.md
- agent/run_job.go
- internal/experiments/experiments.go
Fixes #1489
* Add a new experiment, `override-zero-exit-on-cancel`
* If the job is cancelled, and the exit status of the process is 0, override it to be 1 instead.
> Experiment: override zero exit code on cancel

- internal/job/executor.go
- kubernetes/kubernetes.go
- kubernetes/kubernetes_test.go
Retry the socket connection several times.
Thanks to @bpoland for raising #2745
Fixes #2744
> Use roko to retry k8s socket dial

- EXPERIMENTS.md
- clicommand/agent_start.go
- clicommand/pipeline_upload.go
- clicommand/pipeline_upload_test.go
- go.mod
- go.sum
- internal/experiments/experiments.go
In v3.63.0 we made a breaking change to how pipelines were parsed, specifically the precedence of environment variables in a pipeline upload step.
This undoes that breaking change to restore the original behaviour (see https://github.com/buildkite/go-pipeline/pull/35)
The following pipeline example exhibits the breaking change (Credit to @lizrabuya for the reproducible test case).
Pipeline Steps:
```yaml
env:
HEADER_ENV: "123"
​
steps:
- command:
- buildkite-agent pipeline upload pipeline.yml
```
pipeline.yml:
```yaml
env:
HEADER_ENV: "789" 
NEW_ENV: "NEW-${HEADER_ENV:-}"
steps: 
- label: "Fixed Values ENV: ${NEW_ENV}" 
commands: echo "Checking fixed env values ${NEW_ENV} "
- label: "Fixed Values Runtime ENV"
commands: echo "Checking fixed env values $${NEW_ENV} "
```
Prior to agent …
> Make preferring runtime env default off

- agent/agent_worker.go
It's a bit deceiving at first glance
Add some code comments
> Document IdleMonitor

- .buildkite/pipeline.release-experimental.yml
- .buildkite/pipeline.release-stable.yml
- .buildkite/pipeline.release-unstable.yml
We are sunsetting the `deploy` queue that the agent release pipelines currently use. 
This PR moves release steps to the default queue, using OIDC assumable roles to access the required AWS resources.
https://github.com/buildkite/ops/pull/2306 created OIDC assumable roles for the `edge` `beta` and `stable` pipelines. 
There's a risk that the roles are missing some permissions required by the release steps. Platform team can be available to help. 
More info:
https://3.basecamp.com/3453178/buckets/34063888/messages/7327195755
> Use oidc roles in release pipelines

- agent/agent_pool.go
- agent/agent_worker.go
- clicommand/agent_start.go
This PR adds a new endpoint to the healthcheck server, `/status.json`. the idea is that this endpoint will be a very cut-down version of the information available at `/status`, but in a format (JSON) that's easily machine-readable.
A sample of this output is:
```JSONC
{
"health": "ok",
"aggregate_status": "busy", # One of the workers below is busy, so the "aggregate status" of the agent is busy
"worker_statuses": [
{
"status": "idle",
"id": "018f2d68-1d0c-42cd-be6c-c1a89bda6453",
"spawn_index": 1
},
{
"status": "idle",
"id": "018f2d68-1e33-4f09-ae1e-8b962f4e4e77",
"spawn_index": 2
},
{
"status": "busy",
"current_job_id": "018f2d68-5e54-4255-a99e-829aa4691dc1", # only busy agents have a current job ID
"id": "018f2d68-1f57-4374-9dbe-ec033f915c75",
"spawn_index": 3
},
{
"status": "idle", …
```
> Add status.json endpoint to health check endpoints

- .buildkite/pipeline.release-experimental.yml
We made some changes to our build pipeline, such that we no longer use the build agent's IAM role when pushing packages to S3.
Because our credentials now come from the environment instead of the Instance Metadata API, we need to pass them through explicitly.
> release: Pass AWS credentials to Docker containers

- agent/agent_worker.go
- agent/artifact_uploader.go
- agent/artifactory_uploader.go
- agent/download.go
- agent/s3.go
- agent/s3_downloader.go
- agent/s3_uploader.go
- api/client.go
- clicommand/git_credentials_helper.go
- clicommand/pipeline_upload.go
- internal/artifact/azure_blob_uploader.go
- internal/job/api.go
- internal/job/checkout.go
- internal/job/executor.go
- internal/job/integration/git.go
- internal/job/shell/shell.go
- internal/job/ssh.go
- process/cat.go
The `%w` formatting verb has been available forever<sup>[citation needed]</sup> now, and it's frustrating to use `errors.Is`, expecting to find a wrapped error, only to find out that a call to `%v` in a `fmt.Errorf` call (instead of `%w`) has eaten all of the error decoration.
This PR casts a wide brush across the codebase, and attempts to replace many (most? all?) uses of `%v` for errors in calls to `fmt.Errorf` with `%w`, properly wrapping those errors
> Replace calls to %v for error values in fmt.Errorf with %w

- agent/integration/config_allowlisting_integration_test.go
- agent/integration/job_environment_integration_test.go
- agent/integration/job_runner_integration_test.go
- agent/integration/job_verification_integration_test.go
- agent/integration/test_helpers.go
The agent integration tests use a mock server to pretend to be the Buildkite Agent API, but it's extremely brittle, and quite frankly, some of the worst code i've ever written. it's difficult to add new endpoints, and callers of the server can't modify its behaviour in any way, which is frustrating when you need to test against specific behaviour.
This PR refactors that server to use Go 1.22's new `http.HandleFunc("GET /some/path/{with}/path/params")` gear, cleans up the handler code to not be godawful, and allows callers to add endpoints, and override the existing ones.
It also adds an error return to the `runJob` helper that gets used in agent integration tests, as we might in future want to test failures of this code
> Refactor agent integration test API

- agent/agent_worker.go
- agent/agent_worker_test.go
- clicommand/agent_start.go
When the agent is running in acquire mode - that is, by specifying a job UUID for the agent to pick up, "inverting" the normal dispatch process - sometimes, the job it's been instructed to pick up in unavailable. Perhaps it's already running on another agent, or maybe the job was cancelled, but made its way to the agent anyway.
In these situations, the agent prints the error to stdout, and returns an exit code of `1`, indicating failure.
However, acquisition can fail for both recoverable- and non-recoverable reasons, and the agent doesn't differentiate between these in its status code. Users can grep through the logs for things unrecoverable-sounding things, but this is way more work than it needs to be.
This PR makes it so that if acquiring the job fails in such a way that the error is …
> Make failed job acquisitions return a specific exit code (27)

- .buildkite/pipeline.release-stable.yml
- .buildkite/pipeline.release-unstable.yml
This PR updates the role name assumed in the unstable/beta release pipeline, and passes the AWS creds for that role through to docker containers.
A fix to changes introduced to the pipeline in #2755
> Plt 2360 fix OIDC role name

- clicommand/git_credentials_helper.go
one of the things that came up in a security chat the other day was the worry that when using buildkite hosted compute, using `--debug --debug-http` on the agent could get the agent’s git credential helper to print out the response body of the request asking for a code access token, and leak it into job logs. i’ve verified that this probably can’t happen right now, for a couple of reasons:
- first, buildkite's compute layer controls the agents, and doesn’t allow users to set specific flags on the agent. malicious (or negligent) users wouldn’t be able to set the two flags that could cause the response body to be leaked into job logs
- regardless of this, even when those options are set, the output of the git credential helper is eaten by git itself, and so wouldn’t be visible to users …
> Remove the --debug-http flag from the git credential helper

- internal/job/checkout.go
- internal/job/integration/checkout_integration_test.go
The agent has a [special case for GitHub PRs](https://github.com/buildkite/agent/blob/3ebb9d6ff79364ba4329713f1616520022898de8/internal/job/checkout.go#L545-L558), where it fetches `refs/pull/{id}/head`, instead of [directly fetching the commit](https://github.com/buildkite/agent/blob/3ebb9d6ff79364ba4329713f1616520022898de8/internal/job/checkout.go#L570) we want to build.
This can cause the build to fail if there is a force push to the PR branch, as the commit that we wanted to build will no longer be a parent of the current `refs/pull/{id}/head` and so won't be fetched. That causes the checkout to fail with "reference is not a tree".
1. Set up a Buildkite pipeline that triggers on GitHub pull requests
2. Ensure no agents are connected
3. Create a pull request (a Buildkite build will be …
> Fix checkout race condition on GitHub PR builds

- clicommand/secret_get.go
This PR expands the `buildkite-agent secret get` command with a more useful description for both the output and the docs.
The aim is to flesh out this description so that the current extremely brief one we have here:
https://buildkite.com/docs/agent/v3/cli-secret
Contains more info (i.e. separate **Usage**, **Description** and **Example** sections) like the one here:
https://buildkite.com/docs/agent/v3/cli-step#updating-a-step
This edited description (in this PR) affects the wording on https://buildkite.com/docs/agent/v3/cli-secret, which is auto-generated from this content.
Just the description, which will be surfaced through the CLI command: 
`buildkite-agent secret get --help`.
I have tested the output locally with the command:
`go run *.go secret get --help --debug`
and the output is …
> Expand buildkite-agent secret command with a more useful description.

- clicommand/redactor_add.go
Just fixes a minor typo in the help output for the `buildkite-agent redactor add` command, which is also propagated across to the docs.
I have a plan to reformat the description, similar to https://github.com/buildkite/agent/pull/2775, but this is a lower priority thing I'll do once I have more time.
> Fix typo in 'buildkite-agent redactor add' description.

- process/ansi.go
- process/ansi_test.go
- process/timestamper.go
- process/timestamper_test.go
Prevent the insertion of BK timestamp APCs in the middle of other ANSI sequences.
https://github.com/buildkite/terminal-to-html/issues/143 among other examples
Prior to #2447, BK APCs were only added immediately after new lines or "line clear" codes. In #2447 I made it insert extra timestamps, based on time-since-last timestamp. This made it possible to insert a timestamp within another ANSI sequence, but it seemed unlikely to happen, because a process typically outputs an entire ANSI sequence in one write call (or so I must have thought). This ignores buffers in the middle. If a process writes ANSI sequences into a buffer, and the buffer is written out in multiple write calls, then two write calls could occur on either side of the last-timestamp check. While this still seems unlikely, …
> Fix poorly-timed timestamp insertions

- agent/run_job.go
- internal/job/executor.go
- kubernetes/kubernetes.go
Improve the messaging when running in the Kubernetes stack when one of the other containers never connect to the "server" container socket.
https://linear.app/buildkite/issue/PENT-50/investigate-the-difficulty-of-showing-more-descriptive-error-messages
* Put the existing error message in a new pre-expanded section, so it's not hidden inside another section accidentally
* Tweak the wording (ImagePullBackoff = container image couldn't be pulled)
* Drive-by improvement to the Await loop to make the sleep context-aware
* Drive-by improvement to an error string (`%q`)
> Write "unknown exit status" in expanded section

- jobapi/client.go
- jobapi/client_test.go
At the moment, if the job api is missing a token, we emit an error about something completely different:
```
fatal: failed to create Job API client: BUILDKITE_AGENT_JOB_API_SOCKET empty or undefined
```
This PR changes it so that we emit an error that doesn't actively lead users astray:
```
fatal: failed to create Job API client: BUILDKITE_AGENT_JOB_API_TOKEN empty or undefined
```
[Slack convo](https://buildkite-corp.slack.com/archives/C05R3MTRK38/p1716339404757909)
> Emit a better error if the job API token is missing

- clicommand/agent_start.go
- clicommand/cancel_signal.go
When a job is canceled, parent processes send a SIGTERM (by default) to child processes to try and gracefully fail. If a child doesn't finish after a period of time, we SIGKILL it. The grace periods are configured by two options:
* `--cancel-grace-period` - used by the `start` process when canceling the `bootstrap`
* `--signal-grace-period-seconds` - used by the `bootstrap` process when canceling its children (command/hooks/plugins etc)
In https://github.com/buildkite/agent/pull/2654, the signal grace period was extended to cover all job phases. Which means the effective grace period for a job changed from the cancel grace period to the minimum of the two periods.
In https://github.com/buildkite/agent/pull/2696, we changed the default signal grace period to be one second less than the …
> Default signal grace period to slightly less than cancel grace period

- go.mod
- go.sum
1.1.20 and 1.1.21 appear to have a bug where occasionally, running processes under the pty will return a fork/exec: operation not permitted error
fixes #2790 
#2790 
Coda escalations [1](https://coda.io/d/Escalations-Feedback_dHnUHNps1YO/Pipelines-Escalations_su7FT#Pipelines-Escalations-Board_tu__K/r449&view=modal) and [2](https://coda.io/d/Escalations-Feedback_dHnUHNps1YO/Pipelines-Escalations_su7FT#Pipelines-Escalations-Board_tu__K/r448&view=modal)
> Downgrade pty to v1.1.19

- agent/agent_worker.go
- agent/plugin/error_test.go
- jobapi/client_test.go
- jobapi/socket.go
I noticed a deprecated call to `rand.Seed`, and figured a quick upgrade to rand/v2 is in order.
Opportunistic drive-by improvement.
* Remove deprecated `rand.Seed`
* Use new v2 package (many improvements)
> Upgrade math/rand to v2

- clicommand/bootstrap.go
- internal/job/executor.go
- internal/job/integration/artifact_integration_test.go
- internal/job/integration/checkout_git_mirrors_integration_test.go
- internal/job/integration/checkout_integration_test.go
- internal/job/integration/command_integration_test.go
- internal/job/integration/docker_integration_test.go
- internal/job/integration/executor_tester.go
- internal/job/integration/hooks_integration_test.go
- internal/job/integration/job_api_integration_test.go
- internal/job/integration/plugin_integration_test.go
- internal/job/integration/redaction_integration_test.go
**This PR is best reviewed commit-by-commit**
There's currently an edge case with with the agent's sensitive value redaction, where if the agent is started with an empty value for the `--redact-vars` flag (which in most cases has a sensible default), no redactions would happen. this is to be expected - it's what the user explicitly asked for, after all! however, doing this also prevents the user from dynamically adding values to redact using the `buildkite-agent redactor add` command, or automatically via the `buildkite-agent secret get` command. 
This behaviour was due to a bug where if upon startup, the job executor [found no values to redact](https://github.com/buildkite/agent/blob/0aa38aa4bd5e780296df293d220f78a796351958/internal/job/executor.go#L1130-L1133) - ie if the value of the …
> Fix redaction when no initial redactors are present

- agent/plugin/error_test.go
rand.Rands are not threadsafe and only one should be used per goroutine, so one should be used per parallel tests, and shouldn't be shared between them
> Use Rand per-test in agent/plugin/error_test.go

- clicommand/tool_sign.go
- go.mod
- go.sum
There are two types of signed pipelines supported by the agent:
- "Dynamic" signing of pipelines uploaded by the agent
- "Static" signing of initial steps of a project, stored in buildkite. This signing is done by either the `buildkite-agent tool sign` tool, or by the [terraform provider](https://registry.terraform.io/providers/buildkite/buildkite/latest/docs/data-sources/signed_pipeline_steps)
Due to limitations in the Buildkite backend, the second type of signed pipelines cannot contain variable interpolations - the backend attempts to perform these interpolations, and in so doing, changes the content of the steps, causing any signature verifications to fail.
This PR updates the `buildkite-agent tool sign` command to reject signing any pipelines that have variable interpolations in them …
> Dont sign initial steps with interpolations

- logger/log.go
`golang.org/x/crypto/ssh/terminal` is now `golang.org/x/term`
Drive-by cleanup.
- Replace deprecated package path with new equivalent.
> Update deprecated import

- clicommand/agent_start.go
A handy log line, which supports a process of enabling allowed repo and plugins on buildkite-agent.
My first attempt of enabling buildkite allowed-repo and allowed-plugins failed. I'm not entirely sure if I'm propagating the variables correctly, so this log line would be pretty useful in debugging.
> Add logs to allowed-[repositories|plugins]

- clicommand/tool_sign.go
- go.mod
- go.sum
Reverts buildkite/agent#2807
This PR had an issue where escaped dollar signs that aren't interpolations (now i know that those exist! 🫠) would fail to parse as pipeline uploads, as interpolate would try to parse them as an expansion, which they were not.
we were alerted to this by the agent pipeline, which contains as its final line:
```
if: build.env("DRY_RUN") == "true" || build.branch =~ /^(main|.*-.*-stable)$$/
```
there's a double-dollar there being used as an escaped literal dollar sign for the end of a regex, but the change to the interpolate library was attempting to parse it as an expansion `$$/`, but `/` is not a valid identifier, so the interpolate library was getting confused. the initial error message can be found [here](https://buildkite.com/buildkite/agent/builds/8536#018fe2 …
> Revert "Dont sign initial steps with interpolations"

- process/pty.go
The size of the fake PTY allocated to build jobs was previously unspecified, which generally led to a default of 80x24. That meant programs which checked the size of the terminal would assume it was very small, and that programs which default to using a pager (e.g. less/more) for long output, lines would be truncated at 80 characters, and showing more than ~24 lines of text would often result in a blocking prompt to show more.
Increasing the cols by 2x and rows/lines by ~4x seems reasonable, it comes _closer_ to matching actual modern terminal window sizes, shows longer lines, and is less likely to trigger a blocking pager. Perhaps larger values would be good, especially for Rows. Maybe there's no harm and some upside to e.g. 1,000 rows?
This doesn't fundamentally solve the issue, but …
> PTY rows/cols increased

- internal/job/shell/logger.go
- internal/job/shell/logger_test.go
`fmt.Fprintf(w, "%s", fmt.Sprintf(format, v...))` seems silly - and following it with `fmt.Fprintln(w)` also seems silly.
`fmt.Fprintf(w, format+"\n", v...)` is faster and does less allocations:
```plain
goos: darwin
goarch: arm64
pkg: github.com/buildkite/agent/v3/internal/job/shell
│ doublefmt.txt │            fmtconcat.txt            │
│    sec/op     │   sec/op     vs base                │
Printf-10    140.80n ± 0%   87.05n ± 0%  -38.17% (p=0.000 n=30)
│ doublefmt.txt │           fmtconcat.txt            │
│     B/op      │   B/op     vs base                 │
Printf-10      40.00 ± 0%   0.00 ± 0%  -100.00% (p=0.000 n=30)
│ doublefmt.txt │            fmtconcat.txt            │
│   allocs/op   │ allocs/op   vs base                 │
Printf-10      2.000 ± 0%   0.000 ± 0%  -100.00% …
```
> shell logger: Use fmt functions once

- internal/job/executor.go
There's a spurious error in some k8s job logs: 
> 🚨 Error: Error waiting for client interrupt: context canceled
This happens when a job is ending normally. The cause is the surrounding context is being closed, and the goroutine that logs it then races the closure of the log writer.
While I'm here, I noticed that `cancelCh` is unbuffered, but there is a mismatch between sends and receives which would lead to leaking the goroutine that logs the message. So I fixed that by using a "close-with-guard pattern" (that's what I'm calling it, anyway).
Noticed a bug, and it was pretty easy to fix.
- Don't log the error if the context was cancelled
- Add some explanatory comments
- Change the `cancelCh` usage from sending to closing
> Fix error in k8s after job completes

- EXPERIMENTS.md
- agent/agent_configuration.go
- agent/agent_worker.go
- agent/job_runner.go
- agent/tags.go
- clicommand/agent_start.go
- clicommand/bootstrap.go
- clicommand/global.go
- internal/experiments/experiments.go
- internal/job/config.go
- internal/job/executor.go
Replaces the `kubernetes-exec` "experiment" with a proper flag, environment variable, etc.
The `kubernetes-exec` "experiment" was not really an experiment, but rather misused the experiments system as a way to pass a Boolean flag into various parts of the agent without setting up a flag, environment variable, etc.
> kubernetes-exec is now a flag

- clicommand/tool_sign.go
- go.mod
- go.sum
Reverts buildkite/agent#2812
This is reviving a reverted PR #2807.
In addition to the original change, this PR upgrades the version of `buildkite/interpolate` to avoid the bug mentioned in the revert PR #2812.
> Revive "Dont sign initial steps with interpolations"

- .buildkite/pipeline.release-experimental.yml
- .buildkite/pipeline.release-stable.yml
- .buildkite/pipeline.release-unstable.yml
The new steps introduced in #2824 are failing because they're running on the deploy queue. Looks like I copy pasta'd the wrong queues across branches. The deploy queue isn't allowed to run jobs from the agent repository. But these jobs should run fine on regular elastic runners.
> Publish buildkite packages from regular queue

- .buildkite/pipeline.release-experimental.yml
- .buildkite/pipeline.release-stable.yml
- .buildkite/pipeline.release-unstable.yml
Following on from #2824 and #2824, it looks like the deploytools image is only available when authenticated to ECR:
I started by copy/pasting the auth gear from the other steps which use deploytools .. but then realised all these steps need are bash, buildkite-agent, and curl .. and those are all available on the host. So just remove all the docker plugin stuff and let it run on the host.
> Publish Buildkite Packages without Docker

- .buildkite/steps/publish-buildkite-packages.sh
Gotta love the push merge deploy cycle. This time [failed](https://buildkite.com/buildkite/agent-release-edge/builds/1278#01900b53-ec4a-4f7e-9a61-915e102aa4a4/194-195) because I have fat fingers.
(Follow up to #2824.)
> Publish Buildkite Packages — Fix Typo

- .buildkite/steps/publish-buildkite-packages.sh
Continuing from #2824, it's now failing with a "not found":
I found the matching trace in Datadog APM:
https://app.datadoghq.com/apm/trace/1355574743850893837
which revealed the request path was:
/v2/packages/organizations/buildkite/agent-rpm-experimental/registries/buildkite/agent-rpm-experimental/packages
The problem is the organization and registry slug weren't being split up quite right. The glob was the wrong way around 🤦
Given:
REGISTRY="acme-inc/widgets"
Before:
ORGANIZATION_SLUG="${REGISTRY%*/}"
REGISTRY_SLUG="${REGISTRY#/*}"
After:
ORGANIZATION_SLUG="${REGISTRY%/*}"
REGISTRY_SLUG="${REGISTRY#*/}"
(I swear I tested these to check they were the right way around, but clearly have done something silly along the way.)
I've also adjusted the curl command to exit non-zero on HTTP error …
> Publish Buildkite Packages — Fix Urls

- internal/job/api.go
- internal/job/executor_test.go
- internal/redact/redact.go
- internal/redact/redact_test.go
Reduce confusion around having a `_TOKEN` env var around that should be redacted as configured, even though the risks associated with it leaking should be minimal.
https://linear.app/buildkite/issue/PS-71/job-api-token-not-redacted-is-confusing-customers
* Add the Job API token to the redactors if the name would have matched the configured redacted vars patterns
* Move tests
> Redact Job API token like other env vars

- clicommand/tool_sign.go
- internal/bkgql/client.go
Currently, the `tool sign` command, when being used with graphQL, can't be used against a local development setup.
This PR adds a flag `--graphql-endpoint` to that command, allowing the graphql endpoint that it uses to get and update pipeline definitions to be user-defined
https://buildkite-corp.slack.com/archives/C061U5PG9K5/p1718679622959369
> Make the graphql endpoint for `buildkite-agent tool sign` configurable

- agent/job_runner.go
- clicommand/bootstrap.go
- internal/job/config.go
- internal/job/executor.go
- kubernetes/kubernetes.go
Pass environment vars through the k8s socket
https://linear.app/buildkite/issue/PS-72/make-buildkite-agent-id-available-within-k8s-stack-containers
* In kubernetes/kubernetes.go: Replace `AccessToken string` with `Env []string`
* In agent/job_runner.go: Provide `processEnv` to the Kubernetes socket server
* In clicommand/bootstrap.go: Connect the socket as the very first thing it does, to get env vars in time for configuring the executor
* Some cleanup
>  Convey env vars between k8s containers

- clicommand/bootstrap.go
- internal/job/config.go
- internal/job/executor.go
After some testing, I discovered that the env vars can't be set early enough to affect the bootstrap config, so this moves back to doing most of the socket setup in executor.go
* Undo most of 36940e5
> Don't try to early-set env vars

- .buildkite/steps/publish-docker-image.sh
- .buildkite/steps/publish-docker-images.sh
Pushing our images to Buildkite Packages to a great example of dogfooding out own product. However, while we're building confidence that everything works correctly we don't want the entire build to fail if there is an issue with Buildkite Packages so I've set it to soft fail.
[PKG-7137](https://github.com/buildkite/agent/pull/2837)
I ran `checkshell` locally. The only error was unrelated to these changes.
> Release Docker images on Buildkite Packages

- .buildkite/steps/publish-docker-image.sh
- .buildkite/steps/publish-docker-images.sh
The target repo but be named "buildkite/agent" as this is used for all images.
I've renamed the repo to match.
PKG-7137
> Fix image name when pushing to Buildkite packages

- .buildkite/steps/publish-docker-image.sh
Hopefully this will fix the deploys 🤞🏻
Fixes an issue from 0f9efccda and b8fd08133.
Dockerhub and Github use a container path of:
> registry/image
However, in Packages we use:
> org/registry/image
This PR fixes the path to support this.
PKG-7137
Passes `shellcheck`.
> Include repo name in Packages image path

- .buildkite/steps/publish-docker-images.sh
In 48df9f77659545a8a77307393daa92404c9656f1 I renamed the registry from "agent" to "agent-docker" but forgot to update the login command.
> Fix the Packages registry name

- agent/download.go
While investigating the artifact download process a bit more, I discovered some fairly low-hanging fruit in the existing downloader.
Fixes #2774 by making one or another artifact the "winner", and printing a SHA256 sum of the content that it downloaded.
https://coda.io/d/_dHnUHNps1YO#View-3-of-Escalations-Table_tu3KF/r437&view=modal
- Write to a temp file and move it to the destination name when ready
- Check the error return from Close
- Print a SHA256 sum of the content
- Add ability to verify SHA256 checksum (not yet used)
- Make error strings more Gothic
> Fix some common artifact download bugs

- .buildkite/pipeline.yml
- .buildkite/steps/build-debian-packages.sh
- .buildkite/steps/build-rpm-packages.sh
- install.sh
- scripts/build-debian-package.sh
- scripts/build-rpm-package.sh
Add `riscv64` DEB and RPM packaging logic.
Relate to: #2876
> Introduce `riscv64` architecture

- clicommand/step_get.go
The "retry" attribute is not a valid for using with `buildkite-agent step get` command.
Updating the docs on the `buildkite-agent step` commands to provide a list of valid attributes - see https://github.com/buildkite/docs/pull/2872 - and ran the following, so see that "retry" is not a valid attribute for a Step:
```bash
$ buildkite-agent step get --format json
{
"label": "label",
"type": "command",
"if": null,
"state": "running",
"key": "key",
"outcome": null,
"notify": [
],
"command": "buildkite-agent step get --format json",
"parallelism": null,
"env": null,
"timeout": 1,
"concurrency_limit": null,
"concurrency_key": null,
"agents": null,
"depends_on": [
]
}
```
and when running the following Pipeline:
```yaml
steps:
- label: "label"
key: "key"
command: buildkite-agent step get "retry" …
```
> SUP-2343: remove "retry" example from "buildkite-agent step get" as not valid

- clicommand/pipeline_upload.go
- clicommand/pipeline_upload_test.go
- clicommand/tool_sign.go
- env/environment.go
- internal/job/api.go
- internal/job/executor.go
- internal/redact/redact.go
- internal/redact/redact_test.go
Reject secrets originating from more places (e.g. within the pipeline YAML being uploaded)
With the flag enabled, env vars containing secrets are already rejected, but only if they are in the process env of the agent uploading a pipeline.
A pipeline generator might accidentally insert secrets as env vars within the pipeline env block or a step env block. These are still secrets, so they should be found and rejected.
Each commit should be fairly self contained. 
Main changes that ought to be reasoned about:
- Considering all env maps for secrets. This is the main change, and involves recursively inspecting the pipeline for things with `env` blocks (pipeline or command), then adding the vars and values found to the input to `redact.Vars`.
- Not scanning for pipeline / step env vars. By …
> Reject more secrets

- .buildkite/steps/build-github-release.sh
Adds another place to get SHA256SUMS for releases.
cc #500 #2796
> Add a SHA256SUMS file

- .buildkite/steps/publish-docker-image.sh
- .buildkite/steps/publish-docker-images.sh
Currently, we `docker login` to the buildkite packages container registry in the same place as all the other docker logins, in [`.buildkite/steps/publish_docker_images.sh`](https://github.com/buildkite/agent/blob/main/.buildkite/steps/publish-docker-images.sh). However, because this docker login is done using an OIDC token, it's timed, and only lasts five minutes.
If pushing the docker images to registries before BK packages takes longer than five minutes, the push to BK packages will fail, as the token will expire - see [here](https://buildkite.com/buildkite/agent-release-edge/builds/1315#0190c3aa-4ada-4828-ba5e-46765578cb1b).
This PR updates the docker push process so that we log in to buildkite packages as close as possible to push-time.
> Log in to buildkite packages right before pushing images

- agent/download.go
- agent/download_unix.go
The change from `os.Create` to `os.CreateTemp` changed the file permissions of the created file (from 0o666 to 0o600). This was unintentional. 
#2878
> Fix downloaded artifact permissions

- clicommand/agent_start.go
- clicommand/bootstrap.go
- clicommand/cancel_signal.go
- internal/job/executor.go
- internal/job/grace.go
Artifact phase (the built-in artifact upload performed by the agent) and post-command hooks are now allowed to run in the signal grace period (a configurable length of time after job cancellation).
The signal grace period is also now enforced within the job executor (as well as outside of it when run normally as a subprocess of the agent).
Artifacts uploaded this way can be relevant to user debugging job timeouts, so we should try a bit harder to upload them. 
A similar argument applies to post-command hooks, which can be used for post-job cleanup.
Both of these (and usual job teardown) are still subject to the executor being SIGKILL-ed by the agent parent process. However, some use-cases run `buildkite-agent bootstrap` separately to the agent ("standalone `bootstrap`", which happens for …
> Let artifact phase and post-command run in grace period

- api/client.go
- api/client_test.go
At some point the agent HTTP client configuration was updated however this resulted in it falling back to HTTP/1.1. Ideally we would take advantage of HTTP/2 to improve overall performance, especially for agents who are connecting from locations outside the US.
This will also lead to less TLS handshakes, and connections overall, which in turn should reduce the likelyhood of stalls uploading artifacts.
The defaulting to HTTP 1.1 was discovered while debugging higher than expected latency while uploading artifacts.
Use the default transport to ensure that the `ForceAttemptHTTP2` is set and we use HTTP/2.0. Cloning the default transport is the simplest approach to ensure you get the most up to date configuration. 
See https://github.com/golang/go/issues/26013 for some background on the …
> fix enable http/2 by default as intended by flags

- agent/agent_worker.go
- agent/job_runner.go
- agent/pipeline_uploader.go
- clicommand/agent_start.go
- internal/job/executor.go
- process/signal.go
The `buildkite-agent bootstrap` forked from `buildkite-agent start` needs both cancel-grace-period and signal-grace-period.
In #2899 the cancel grace period was added as a flag and env var read by the bootstrap subcommand, but I forgot to set it from the job runner.
* Pass the value through an env var just like `BUILDKITE_SIGNAL_GRACE_PERIOD_SECONDS`
* Also a small cleanup across the whole agent codebase to replace `fmt.Sprintf("%d", ...)` with `strconv.Itoa(...)` (does the same thing, but it doesn't need the `fmt` package to parse a format string).
Note: the two env vars are different due to historical reasons. See https://github.com/buildkite/agent/blob/main/clicommand/cancel_signal.go
> Pass cancel grace period to bootstrap

- api/client.go
A hopefully minor bug: `TLSClientConfig` is overridden with `conf.TLSConfig` in all cases, when we should only really override it if it is set.
If `DisableHTTP2` is enabled, we want the default `TLSClientConfig` with `NextProtos` set in a particular way. But the unconditional override with `conf.TLSConfig` nukes it.
> Only override TLSClientConfig if set

- api/client.go
- core/controller.go
- core/doc.go
- core/options.go
The default endpoint string was missing `v3`. `v3` is visible in `clicommand/global.go`, which has the proper default value.
Add `v3` to the end of the endpoint strings used as defaults.
> Fix default endpoint string

- agent/verify_job.go
Working with customers to debug signature verification and one issue found was it could be hard to locate debug messages which highlight specific failure cases. 
This is security code, so we need to be suitably vague when reporting errors while in production, however for those looking to enable debugging and troubleshoot issues it would be good to provide some consistent patterns to look for in logs.
Following existing log messages within the agent I have added a bit more context to the debug logging prefix making it easier to filter and locate in logs.
> Add a bit more context to the debugging for failing signature verify

- internal/job/shell/logger.go
- internal/job/shell/logger_test.go
When the group expansion characters are printed `^^^ +++`  whilst also using ansi colours, our log rendering in the UI does not expand the group, so the message is hidden.
Changes in https://github.com/buildkite/agent/pull/2805 a while back adjusted the structure of the messages slightly when using ansi color, this resulted in some formatting issues.
With @tessereth expert guidance we found the issue and added a test to validate it.
Just moved the `^^^ +++` sequence out of the ansi formatting.
> fix for layout issues with log messages

- clicommand/annotate.go
Update the description for the `--priority` option for the `buildkite-agent annotate` command.
Minor wording tweak to be surfaced through the Buildkite Docs based on https://github.com/buildkite/docs/pull/2934.
An option description for the `buildkite-agent annotate` command.
Also, set the agent's client-side default to `3`.
Not done.
> Update description for the 'priority' option for the 'buildkite-agent annotate' command.

- internal/job/executor.go
When a job in k8s completes, the job output will often contain the line `# Received cancellation signal, interrupting` even though the job itself has already completed. This appears to be a problem with the way the `Cancel()` method is called during the k8s job execution, and isn't validating that there's any error generated to warrant its execution.
For those looking at logs, this makes the job appear to have failed, when in all other circumstances it has succeeded.
https://coda.io/d/Escalations-Feedback_dHnUHNps1YO/Pipelines-Escalations_su7FT#Pipelines-Escalations-Board_tu__K/r634&view=modal
A small logic tweak to when `Cancel()` is triggered based on the `k8sAgentSocket.Await()` call. Currently `Cancel()` will always be called regardless of what happens, where it should only be called …
> Prevent Cancel from running when a k8s job is cancelled already

- internal/job/executor.go
Unconditionally set `BUILDKITE_AGENT_ACCESS_TOKEN`, regardless of whether it is already set.
This matches pre-#2851 behaviour.
Manually setting `BUILDKITE_AGENT_ACCESS_TOKEN` within the command container was found to break uses of many agent subcommands (e.g. `meta-data set`) within jobs run on newer agents (v3.74.1 and later) in the k8s stack.
https://coda.io/d/Escalations-Feedback_dHnUHNps1YO/Pipelines-Escalations_su7FT#Pipelines-Escalations-Board_tu__K/r597&view=modal
> k8s: Unconditionally set BUILDKITE_AGENT_ACCESS_TOKEN

- internal/job/executor.go
There is a missing value in the formatted string for the error, it is passing the interpreter as the string value for the hook name, and is then printing an empty `%q` for the interpreter value.
There is an addition of the `hookName` passed as a string to the `logMissingHookInfo` function. This value is passed from the `runWrappedShellScriptHook` function on [534](https://github.com/buildkite/agent/blob/65ed6aaf3dd3e50f88dee3fbd27714120e558965/internal/job/executor.go#L534).
>  Fix error when hook cannot be run due to missing interpreter

- agent/agent_configuration.go
- agent/job_runner.go
- clicommand/agent_start.go
- clicommand/bootstrap.go
- clicommand/global.go
- internal/job/config.go
- internal/job/executor.go
- internal/job/shell/shell.go
- internal/job/tracing.go
- tracetools/propagate.go
- tracetools/propagate_example_test.go
- tracetools/propagate_test.go
This is part merge-conflict-resolution, part refinement of #1775. The main differences to #1775 are: specifying the encoding with a string flag rather than bool, represented internally with a `Codec` interface, and some tweaks to the tests.
Closes #1775
###
* Add `--trace-context-encoding` flag and `BUILDKITE_TRACE_CONTEXT_ENCODING` env var, accepting the values `gob` and `json`, defaulting to `gob`.
* Parse the new flag/var and plumb the resulting codec through agent start, job runner, and bootstrap.
* Use the codec to perform encoding/decoding of the trace context.
* Add tests.
> Support for multiple trace context encodings

- go.mod
- go.sum
Full Changelog: https://github.com/buildkite/go-pipeline/compare/v0.11.0...v0.12.0
> Bump github.com/buildkite/go-pipeline from 0.11.0 to 0.12.0

- api/artifacts.go
Currently when the content_type isn't getting passed to the server. This PR is a fix for that. 
With this change when the content type is passed in via 
```
command: "echo hi > tmp.txt; buildkite-agent artifact upload --debug --debug-http --content-type 'text/html' tmp.txt"
```
content type is now being passed to the server (bk/bk)
ps you can see the content_type at the end of the line
```
{"id":"f569d9cf-391c-4014-b6a7-91e3b246ae23","artifacts":[{"id":"","path":"tmp.txt","absolute_path":"/tmp/buildkite-builds/Sorchas-MacBook-Pro-local-1/test/trigger-repo1/tmp.txt","glob_path":"","file_size":3,"sha1sum":"55ca6286e3e4f4fba5d0448333fa99fc5a404a73","sha256sum":"98ea6e4f216f2fb4b69fff9b3a44842c38686ca685f3f55dc48c5d3fb1107be4","job_id":"","created_at":"0001-01-01T00:00:00Z","content_type":"tex …
```
> coda-content-type pass content-type to the server when specified

- internal/cryptosigner/aws/kms.go
This reduces the support for key types to just `ECC_NIST_P256` for the initial release.
The reason I removed the other key types are:
1. The RSA types are more complex to configure and use as they support multiple signing algorythms, some of which have issues as identified in https://buildkite.com/docs/agent/v3/signed-pipelines regarding RSASSA-PKCS1 v1.5 signatures.
2. Currently the `ECC_NIST_P256` is the only ECDSA KMS key type tested for `crypto.Signing` with KMS in our JWS library, I will need to raise this upstream to figure out why.
So given the `ECC_NIST_P256` is widely used I think it is fine as a starting point for KMS signing support.
> Updated to support only ECC_NIST_P256 keyspec for initial release

- clicommand/artifact_search.go
When running `artifact shasum` you can optionally print the SHA256 checksum for a single artifact.
But if you're trying to list multiple artifacts using the `search` subcommand, we only support printing the SHA1 checksum
Add new formatting option, `%T`, for SHA256. I chose t because it's the next letter in the alphabet and both `%s` and `%S` are taken. Open to suggestions!
> Add sha256 checksum output to the formatting options

- .buildkite/pipeline.yml
> Best reviewed with whitespace hidden: https://github.com/buildkite/agent/pull/2976/files?w=1
Using the new [Generate Build Provenance](https://github.com/buildkite-plugins/generate-build-provenance-buildkite-plugin) plugin to generate [SLSA Build Provenance documents](https://slsa.dev/spec/v1.0/provenance) on the following steps in CI:
- Build binaries matrix
- Debian package build step
- RPM package build step
- Github release step
The Build Provenance documents are not immediately used anywhere - this will be followed up later.
Buildkite has released an [exciting new plugin](https://github.com/buildkite-plugins/generate-build-provenance-buildkite-plugin) that generates SLSA Build Provenance documents for pipeline steps. We'd really like to give it a go in the Agent CI pipelines.
- No …
> [PKG-7587] Generate build provenance on binary-build and packaging steps in CI

- agent/awsv2.go
- clicommand/agent_start.go
- clicommand/pipeline_upload.go
- clicommand/tool_sign.go
- go.mod
The new KMS signing support uses aws sdkv2, this automatically discovers region from environment or local configuration files, however it doesn't automatically use imds. This code replicates the v1 local configuration preference with fall back to imds service.
> Fix for region discovery issue with aws sdkv2 when running in ec2

- clicommand/agent_start.go
Fix the usage string to list more cases where "warn" mode continues with the job.
Got side-tracked and ended up looking at what the behaviour actually was.
> Explain verification-failure-behavior in more detail

- .buildkite/pipeline.release-experimental.yml
- .buildkite/pipeline.release-stable.yml
- .buildkite/pipeline.release-unstable.yml
- .buildkite/pipeline.yml
Bump publish-to-packages plugin to version v2.0.0 to get all the cool new features introduced here: https://github.com/buildkite-plugins/publish-to-packages-buildkite-plugin/pull/4
> [PKG-7596] Bump publish-to-packages plugin to v2.0.0

- agent/job_runner.go
- agent/job_runner_test.go
- agent/run_job.go
- internal/mime/mime.go
Two changes, since they touch similar code, done in one:
- Alongside `BUILDKITE_ENV_FILE`, write a `BUILDKITE_ENV_JSON_FILE` which has better-understood escaping and canonicalisation qualities.
- Set enough environment variables in `pre-bootstrap` hook to enable `buildkite-agent annotate` to work.
Opportunistic fixes:
- Turns out `BUILDKITE_NO_HTTP2` wasn't being passed to the bootstrap subcommand. That's fixed too.
- Globally replace `fmt.Sprintf("%t", someBool)` with the equivalent `fmt.Sprint(someBool)`.
- Tweaks to `job_runner_test.go`, including regexes and getting rid of assert/require.
Fixes #2962
Fixes #2966
I've also manually tested with a pre-bootstrap hook that reads `$BUILDKITE_ENV_JSON_FILE` with `jq .`, and annotates the build with it. :+1:
> Add JSON-format env file, allow annotations from pre-bootstrap

- packaging/docker/alpine-k8s/Dockerfile
main build is failing
The latest k8s release hasn't been uploaded to the GCP bucket yet, which is causing our build to fail
Pin the k8s version for now
> Temporarily pin kubectl version

- clicommand/agent_start.go
- go.mod
- go.sum
- internal/job/integration/executor_tester.go
- internal/job/knownhosts.go
- internal/job/shell/test.go
[Go has caught up to the functionality](https://github.com/mitchellh/go-homedir/issues/34#issuecomment-2011915588) of [mitchellh/go-homedir](https://github.com/mitchellh/go-homedir) since 1.20, and go-homedir has been archived since June. No time like the present to drop a dependency!
> Remove mitchellh/go-homedir; it's archived

- api/client.go
- clicommand/agent_start.go
- clicommand/global.go
- internal/mime/mime.go
When debugging network timeouts it can be useful to have detailed timings to know where specifically the time being consumed.
Add a TraceHTTP flag (only on agent start for now).
Use http trace to capture timings between each network event In the case of a network error emit this to error log. Otherwise emit it to the debug logs.
Example:
```
2024-09-17 09:31:11 DEBUG  HTTP Timing Trace uri=https://agent.buildkite.com/v3/ping method=GET hostPort=agent.buildkite.com:443 getConn=746.458µs dnsStart=773.625µs dnsDone=5.492208ms connectStart.tcp.3.168.86.46:443=5.502791ms connectDone.tcp.3.168.86.46:443=169.197333ms tlsHandshakeStart=169.207541ms tlsHandshakeDone=337.926125ms gotConn=337.964208ms reused=false idle=false idleTime=0s wroteHeaders=337.995208ms wroteRequest=337.995791ms …
```
> Emit HTTP timings

- agent/integration/config_allowlisting_integration_test.go
- agent/integration/job_environment_integration_test.go
- agent/integration/job_runner_integration_test.go
- agent/integration/job_verification_integration_test.go
- agent/integration/test_helpers.go
- agent/job_runner.go
In https://github.com/buildkite/agent/pull/2915 we refactored a bunch of this code. In the process, we now take a copy of the `apiClient` object in `NewJobRunner` _before_ we replace the `apiClient` with a new one that uses the job token rather than the session token. We then use the copy for log streaming. This means agents since v3.77.0 use session tokens rather than job tokens for chunk uploads.
~I've tested it locally and this change fixes the problem. I'm not sure how to add regression tests for this though.~ This is tested by updating the fake bk server in the integration tests to require job tokens for everything.
> Use job tokens for log chunk uploads

- clicommand/agent_start.go
- cliconfig/file.go
- cliconfig/loader.go
- internal/job/checkout.go
- internal/job/executor.go
- internal/job/hook/hook.go
- internal/job/knownhosts.go
- internal/job/plugin.go
- internal/osutil/doc.go
- internal/osutil/file.go
- internal/osutil/homedir.go
- internal/osutil/homedir_test.go
- internal/osutil/path.go
- internal/osutil/path_test.go
- internal/osutil/path_windows_test.go
- internal/utils/doc.go
#2990 is good, but is likely to be a breaking change on Windows particularly. For instance the Elastic CI Stack runs the agent with [`HOME=C:\buildkite-agent`](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/41363708a4231dd801e4c30d4ae2b4b5a6c8ff7c/packer/windows/conf/bin/bk-install-elastic-stack.ps1#L231).
Rather than revert #2990, in the spirit of Go Proverbs I propose we do [a little copying instead of a little dependency](https://www.youtube.com/watch?v=PAAkCSZUG1c&t=9m28s).
* Rename internal/utils to internal/osutil, which suits it a little better.
* Add `osutil.UserHomeDir`, which wraps `os.UserHomeDir` and prefers `$HOME` when available.
> Prefer $HOME on all platforms

- .buildkite/pipeline.yml
[Generate Build Provenance](https://github.com/buildkite-plugins/generate-build-provenance-buildkite-plugin) plugin has been renamed to [Generate Provenance Attestation](https://github.com/buildkite-plugins/generate-provenance-attestation-buildkite-plugin). 
This PR updates the pipeline to use the new plugin name/repository. Also, the version tag has been reset to v1.0.0 as part of the rename, and `provenance_filename` field has been changed to `attestation_name`.
> Replace generate-build-provenance with generate-provenance-attestation

- api/auth.go
- api/client.go
- go.mod
Work around a Go bug in HTTP/2 on Linux.
Various reports of connection failures.
Steps to reproduce:
1. Launch the agent on a linux machine
2. Obtain the source ports being used using `netstat -anp`
3. Block traffic destined for the agent source ports `iptables -I INPUT -p tcp --dport $PORT -j DROP`
**Expected behaviour:**
After the initial connection times out a new connection is established. The old connections no longer show as `ESTABLISHED` and communications to agent.buildkite.com are restored 
**Observed behaviour:**
The agent hangs for a long period of time (>3 minutes) and continuosly prints errors communicating with the agent backend:
```
2024-09-23 12:44:54 ERROR  HTTP Timing Trace uri=https://agent.buildkite.com/v3/ping method=GET hostPort=agent.buildkite.com:443 …
```
> Work around golang/go#59690

- agent/agent_worker.go
Fix a data race on `AgentWorker.stopping` by guarding the read with the same mutex that already guards the write.
Noticed when running an agent build with `-race` enabled.
> Fix data race on worker stop

- api/oidc.go
- api/oidc_test.go
- clicommand/oidc_request_token.go
Teach the agent how to request OIDC tokens including aws session tags:
```
buildkite-agent oidc request-token --audience sts.amazonaws.com --aws-session-tag pipeline_id
```
Claims are then added to the returned token as aws session tags using their prescribed format:
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_session-tags.html#id_session-tags_adding-assume-role-idp
which can then be used to grant permission to aws resources using attribute based access control (ABAC):
https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_attribute-based-access-control.html
This is a finer grained control than the subject condition based option currently available:
https://buildkite.com/docs/pipelines/security/oidc/aws#step-2-create-a-new-or-update-an-existing-iam-role-to-use-with-your-pipeline …
> Add support for oidc aws session tags

- .buildkite/pipeline.yml
Internally at Buildkite we're refactoring our clusters and will be moving the agent pipeline to a new cluster. This PR makes the queue names override-able to allow running the pipeline in both the previous and new cluster. 
https://3.basecamp.com/3453178/buckets/1933834/messages/7835428487
Queues can be overridden using environment variables from the Pipeline Steps configuration. This allows running the agent pipeline simultaneously in the Agent and existing cluster.
Assumes an OIDC role to publish docker images to internal registry.
Successful builds in both the current and new cluster.
> Migrate Agent Pipeline to Agent Cluster

- .buildkite/pipeline.release-experimental.yml
- .buildkite/pipeline.release-stable.yml
- .buildkite/pipeline.release-unstable.yml
- .buildkite/pipeline.yml
This PR updates the release pipelines to upload SLSA Provenance attestations when publishing packages to Buildkite Packages.
The actual release steps have been broken out into a matrixed group of steps so that each package can be uploaded with the relevant attestation per architecture.
- **Publish to Buildkite Packages** steps in the release pipelines have been reimplemented as groups of matrixed steps per-arch, and are now uploading relevant attestations along with the packages.
- Upgrade [Publish to Packages](https://github.com/buildkite-plugins/publish-to-packages-buildkite-plugin/) plugin to v2.2.0 for new `attestations:` functionality.
- Upgrade [Generate Provenance Attestation](https://github.com/buildkite-plugins/generate-provenance-attestation-buildkite-plugin) plugin.
> [PKG-7630] Publish packages with attestations to Buildkite Packages

- clicommand/oidc_request_token.go
- cliconfig/loader.go
This allows users to use:
```
buildkite-agent oidc request-token --claim 'this, that, the-other'
```
where previously, even if `that` and `the-other` were allowed optional claims, they'd be rejected, as they'd be sent to buildkite with their preceeding whitespace
> Ensure all string slice args have whitespace cleaned off of each element

- agent/agent_configuration.go
- agent/api.go
- agent/job_runner.go
- api/artifacts.go
- clicommand/agent_start.go
- clicommand/artifact_upload.go
- clicommand/global.go
- internal/artifact/api_client.go
- internal/artifact/artifactory_uploader.go
- internal/artifact/azure_blob_uploader.go
- internal/artifact/batch_creator.go
- internal/artifact/bk_uploader.go
- internal/artifact/bk_uploader_test.go
- internal/artifact/form_uploader.go
- internal/artifact/form_uploader_test.go
- internal/artifact/gs_uploader.go
- internal/artifact/s3_uploader.go
- internal/artifact/uploader.go
- internal/artifact/uploader_test.go
Add a multipart-upload mechanism for Buildkite-hosted artifacts, and upload parts in parallel (with each other, and with other artifacts).
https://linear.app/buildkite/issue/PIPE-180/implement-agent-half-of-multipart-uploads
The changes to artifact uploading is substantial, but basically:
* Some tidyups to the existing code, such as context propagation, un-exporting the `Collect` method
* `FormUploader` is renamed to `BKUploader`, since it will manage both form uploads and multipart uploads to BK
* Changing all the existing uploaders to return one or more units of work, which are ultimately responsible for performing an upload
* Running work units concurrently on a pool of worker goroutines, and communicating between goroutines using channels
* Actually implementing multipart uploads:
* …
> Multipart artifact upload

- internal/job/executor.go
Make it so that, in certain places where env vars from the job might be passed through to the bootstrap incorrectly, the warning message can at least be suppressed.
https://coda.io/d/Escalations-Feedback_dHnUHNps1YO/Pipelines-Escalations_suQ4B7FT#Pipelines-Escalations-Board_tu66S__K/r638
Change from printing the message if `BUILDKITE_IGNORED_ENV` merely exists, to printing the message if the var exists and is non-empty.
> Tweak BUILDKITE_IGNORED_ENV handling

- internal/job/checkout.go
- internal/job/integration/checkout_integration_test.go
Bug: When using skip-checkout plugin, the build title and commit details will match the previously checked out commit details (rather than taking it from the webhook details). 
See video below. I trigger a build via webhook (with skip checkout). It starts off with the correct details, but changes to to the details of `HEAD`
https://github.com/user-attachments/assets/db0f159c-433f-436f-a22c-ca8d98f82f58
Ensure agent gets correct commit message associated with webhook-triggered build, rather than reading it from git repo's `HEAD`. 
Modified function `sendCommitToBuildkite` in `internal/job/checkout.go` to extract the message from `e.Commit` rather than `HEAD`
**To reproduce bug**
- Set up a pipeline (or use an existing one). 
- Ensure a webhook triggers the build on push events (when you …
> BUG FIX: Ensure Build Title Is Correct When Checkout Is Skipped

- internal/job/checkout.go
- internal/job/executor.go
- internal/job/shell/shell.go
Lockfiles (used for serialising access to git mirrors) aren't totally reliable in the face of agents dying without releasing them. As a stopgap, if a lockfile can't be acquired before the timeout, exit with a distinctive code (94, chosen randomly).
https://coda.io/d/_dHnUHNps1YO#Escalations-Pipelines_tuQbCBf6/r711
* Create a new error type, `ErrTimedOutAcquiringLock`.
* Return it if the git mirror lockfiles fail for `context.DeadlineExceeded`
* Check for it in the checkout phase, and wrap it in a `shell.ExitError`
* Update the one other use of `shell.ExitError`
> Exit 94 if a mirror lock times out

- agent/ecs_meta_data.go
- agent/tags.go
- api/client.go
- clicommand/artifact_download.go
- clicommand/artifact_upload.go
- internal/agenthttp/auth.go
- internal/agenthttp/client.go
- internal/agenthttp/do.go
- internal/artifact/artifactory_downloader.go
- internal/artifact/artifactory_uploader.go
- internal/artifact/azure_blob_downloader.go
- internal/artifact/bk_uploader.go
- internal/artifact/download.go
- internal/artifact/downloader.go
- internal/artifact/gs_downloader.go
- internal/artifact/gs_uploader.go
- internal/artifact/s3_downloader.go
- internal/artifact/s3_uploader.go
- internal/artifact/uploader.go
- internal/bkgql/client.go
It'd sure be be nice to do HTTP clients consistently the same way in the agent. Then we could reuse Pat's trace work, disable HTTP/2 consistently, ...
Noticed while working on artifacts, which create blank `&http.Client{}`s or use `http.DefaultClient`.
* Moves client and transport creation into a new internal package with functional options
* Provide a single wrapper for `Do`, again with functional options
* Use it everywhere
* Some opportunistic removals of `context.Background` and a deprecated method
* Removed some unused `DebugHTTP` fields
Not changed:
* Some artifact upload/download code uses specific clients, e.g. `GSUploader` and `GSDownloader` make use of `google.DefaultClient`. These remain.
> Refactor the various agent HTTP clients

- internal/agenthttp/client.go
- internal/artifact/artifactory_downloader.go
- internal/artifact/artifactory_uploader.go
- internal/artifact/bk_uploader.go
- internal/artifact/downloader.go
- internal/artifact/s3_downloader.go
Disable the HTTP client timeout for artifact clients.
When refactoring the HTTP clients in #3017, I set a default timeout of 60 seconds. This is a change from the default HTTP client previously used for artifact operations, which had no timeout.
https://coda.io/d/Escalations-Feedback_dHnUHNps1YO/Pipelines-Escalations_suQ4B7FT#Pipelines-Escalations-Board_tu66S__K/r748
https://coda.io/d/Escalations-Feedback_dHnUHNps1YO/Pipelines-Escalations_suQ4B7FT#Pipelines-Escalations-Board_tu66S__K/r747
> Fix artifact up/download timeouts

- .buildkite/pipeline.release-experimental.yml
- .buildkite/pipeline.release-stable.yml
- .buildkite/pipeline.release-unstable.yml
- .buildkite/steps/publish-docker-image.sh
- .buildkite/steps/publish-docker-images.sh
Push container images to each registry in a separate job (using matrices).
We keep getting 500 errors from the different registries, possibly because the process takes over 5 minutes. Maybe this will help?
> Parallel container image uploads

- install.sh
install.sh is in need of some love. I borrowed some ideas from https://getmic.ro
https://coda.io/d/Escalations-Feedback_dHnUHNps1YO/Pipelines-In-Progress-Board_suIFKYEb#Escalations-Pipelines_tuQbCBf6/r732&view=modal
* More quotes and handlebars
* Refactor picking the HTTP client program (wget/curl)
* Use `mktemp -d`, and a cleanup trap
* Heredoc
* Use the new-ish SHA256SUMS file to checksum the file, with an escape hatch
> install.sh tidyups

- internal/artifact/bk_uploader.go
Set headers in the request that S3 is happy with.
`Content-Range` isn't necessary for the request (it was a flourish I added for debugging purposes), and `Transfer-Encoding` is added by Go when `ContentLength` isn't set.
Testing showed that AWS rejects `Content-Range` and `Transfer-Encoding` headers with 501 Not Implemented. 
* Remove `Content-Range`
* Set `req.ContentLength`
* Update the comment
> Fix request headers for multipart

- agent/job_runner.go
- agent/run_job.go
- kubernetes/client.go
- kubernetes/kubernetes_test.go
- kubernetes/runner.go
Add a mechanism for terminating if a client stops communicating.
Sometimes, a container will just die (e.g. it is OOM-killed). If that happens, the agent can sit around happily until the heat death of the universe waiting for `Exit` to be called by something that isn't running any more.
* Some code rearrangement
* Store clients in a slice instead of a map, since they're keyed by sequential int
* Finer-grained locking
* Locking around channel close inside a `sync.Once.Do` is pointless, given nothing else writes to the channels. The existing locking only prevented data races on the clients, and the clients map/slice never changes, so the mutexes can be made client-specific.
* Add a goroutine that inspects client states and terminates the job if a client that should be connected goes silent …
> k8s exec: Perform liveness check of clients

- internal/replacer/replacer.go
- internal/replacer/replacer_test.go
Make the string replacer engine match `\r` as part of `\n`.
https://coda.io/d/Escalations-Feedback_dHnUHNps1YO/Pipelines-In-Progress-Board_suIFKYEb#Escalations-Pipelines_tuQbCBf6/r774&view=modal
* Partial matches now track string position and matched byte count separately. This is because, if `\r\n` is treated as a variation of `\n`, the number of matched bytes will be off by the number of `\r` bytes that were swallowed.
* Special-case the byte comparison when the needle byte is `\n` and the incoming byte doesn't match the needle byte. If the incoming byte is `\r` in this case, then keep the partial match for the next byte but don't increment the position in the needle (so the next byte to match should be `\n`, but could be another `\r`).
* Add a test.
> Fix multiline secret redaction when output with \r\n

- internal/agenthttp/auth.go
Fixes `tool sign` when using `--graphql-token`.
Running `tool sign --graphql-endpoint http://graphql.buildkite.localhost/v1 --graphql-token this_is_not_the_actual_token` kept returning an error `fatal: Error signing pipeline: couldn't retrieve pipeline: Post "http://graphql.buildkite.localhost/v1": Invalid token, empty string supplied`
> Allow token to be empty if graphql-token is provided

- packaging/docker/alpine-k8s/Dockerfile
- packaging/docker/alpine/Dockerfile
Install both `tini` and `tini-static` in `alpine` and `alpine-k8s`.
This is the easiest way to make `tini-static` available to `agent-stack-k8s`, which will be needed for defunct-process-reaping within arbitrary container images. `agent-stack-k8s` by default uses the agent `alpine` image, not `alpine-k8s`, but I think they should be somewhat consistent.
> Add tini-static to alpine images

- agent/api.go
- api/builds.go
- clicommand/build_cancel.go
- clicommand/build_cancel_test.go
- clicommand/commands.go
- clicommand/config_completeness_test.go
This PR drops in a new CLI command for canceling a running build. 
**Note: Currently blocked on agent endpoint being added**
Example usage:
```sh
BUILDKITE_BUILD_ID=1234 buildkite-agent build cancel
```
> Add command for canceling a running a build

- clicommand/redactor_add.go
In the 'redactor' CLI command examples, this PR removes the equal signs from the `--format` options, to match options table in docs, where the option is specified as `--format value`.
It's better to keep examples and options tables consistent, to avoid customer/reader confusion.
Nevertheless, using an equal sign in this context, or not, should make no functional difference to the way this option is used.
> Minor update to the 'redactor' CLI command examples.

- install.sh
Older version of openssl (e.g. 1.0.2) don't use sha256 as default
option for the openssl dgst so make it explicit.
> Use sha256 in the checksum verification

- internal/experiments/experiments.go
- internal/job/executor.go
- internal/job/integration/hooks_integration_test.go
Promote polyglot-hooks 🎉 
Polyglot hooks was [added as an experiment in May 2023](https://github.com/buildkite/agent/pull/2040). It's high time this was just made default.
* Move the experiment into "promoted"
* Remove the conditional
* Remove the experiment setup in tests
> Promote polyglot-hooks experiment to default

- .editorconfig
- .gitignore
I think that Go code should _not_ use 2 space tabs, especially if it's just to be consistent with Ruby backend code. Personally I am used to 4 or 8 space tabs. But I also think that `.editorconfig` is a matter of personal preference: if you want to use 2 space tabs you go ahead and configure your editor that way. We shouldn't be supplying an `.editorconfig` for you.
The editor I've been using started respecting this file ahead of my other config, so I'm inclined to remove the file.
> Remove .editorconfig

- install.ps1
- install.sh
Add support for specifying agent version when installing via `install.sh` or `install.ps1`. Pulled upstream from https://github.com/elastic/buildkite-agent thanks to @esenmarti!
To set the agent version use the following before running the install script.
- Windows
- `$env:buildkiteAgentVersion = "3.84.0"`
- Linux
- `BUILDKITE_AGENT_VERSION = "3.84.0"`
> Support installing specific versions via script

- agent/api.go
- api/steps.go
- clicommand/commands.go
- clicommand/config_completeness_test.go
- clicommand/step_cancel.go
- clicommand/step_cancel_test.go
Creates a new subcommand `buildkite-agent step cancel --step "key"`. This subcommand can be used to cancel all unfinished jobs for a command step. We optionally allow a `--force` flag which will mean that we don't wait for an agent running a job to finish it before cancelling the job in Buildkite.
> Create `buildkite-agent step cancel` subcommand

- internal/job/executor.go
`kubernetesSetup` used `e.shell` to log before `e.shell` was created. Oops.
https://coda.io/d/Escalations-Feedback_dHnUHNps1YO/Pipelines-Escalations_suQ4B7FT#Pipelines-Escalations-Board_tu66S__K/r822&view=center
* Don't log anything in `kubernetesSetup`
* Move the temporary logger up from `setupRedactors` and use that.
> Fix nil pointer panic in k8s mode

- internal/job/executor.go
`kubernetesSetup` tries to mutate `e.shell.Env`, but `e.shell` isn't set yet. Oops.
https://coda.io/d/Escalations-Feedback_dHnUHNps1YO/Pipelines-In-Progress-Board_suIFKYEb#Escalations-Pipelines_tuQbCBf6/r822&view=modal
* Move the `environ` up
* Pass it into `kubernetesSetup` in order to change it.
> Fix another nil pointer panic in k8s mode

- .github/dependabot.yml
Docker rebuilds take a while, and Dependabot has been failing to pull images, so try to group updates.
Recent build times.
> dependabot: Group Dockerfiles

- internal/job/git.go
We have code to handle the case where we can't fetch a short remote ref and fall back to fetching all tags. However the case of this error changed in git v2.21.0 (2019) and we only caught the new lowercase version. Handle the old title case version to support customers running old versions of git.
Linear PS-179
> Handle older version of remote ref error message

- api/steps.go
- clicommand/step_cancel.go
- clicommand/step_cancel_test.go
We recently introduced a [`buildkite-agent step cancel` subcommand](https://github.com/buildkite/agent/pull/3070). The command can accept a flag `--force`, which will immediately cancel unfinished jobs **_in Buildkite_** (i.e. mark jobs as 'canceled') without waiting for the agents running the jobs to finish. Any subsequent artifact uploads to Buildkite by these agent running this job will begin to fail.
Now this `--force` flag might feel a little counter-intuitive when you think about how agents have a `cancel-grace-period` argument - you could _not_ use the `--force` flag, marking the jobs as 'canceling' and then rely on agents to SIGKILL their process once their `cancel-grace-period` has elapsed.
Imagine though that an agent isn't responding to Buildkite's request to cancel the job …
> Add `force-grace-period-seconds` argument to `step cancel` command

- clicommand/step_cancel.go
Meant to include  https://github.com/buildkite/agent/commit/a3b8339605d826de15f8ca5ce85e148c6c313b19 in https://github.com/buildkite/agent/pull/3084 but messed up the rebase. `BUILDKITE_STEP_CANCEL_FORCE_GRACE_PERIOD_SECONDS ` feels like a better name for this env variable.
> Rename env var to `BUILDKITE_STEP_CANCEL_FORCE_GRACE_PERIOD_SECONDS`

- internal/artifact/s3_uploader.go
- internal/artifact/uploader.go
We received a report that during network flakiness, artifact uploads were failing. This PR adds retries around NewS3Client to mitigate this.
[PIPE-389]
> Add retry around NewS3Client

- .buildkite/pipeline.release-experimental.yml
- .buildkite/pipeline.release-stable.yml
- .buildkite/pipeline.release-unstable.yml
Packages upload of docker images isn't on the critical path until we build custom domains, if any errors occur we shouldn't block agent deploys. When agents are served by buildkite packages soft_fail should be removed. Other steps are already soft fail but this needs an update on the docker to packages specific variation on the matrix.
When this build failed https://buildkite.com/buildkite/agent-release-stable/builds/149#01930ac6-f742-4aca-a10e-74aeb7456373 - it was on the upload to docker step for packages and actively blocked a critical release for Shopify.
https://linear.app/buildkite/issue/PKG-7830/change-agent-pipeline-to-soft-fail-on-packages-uploads
Changes docker deploy step to make packages.buildkite.com step to be `soft_fail`
Pretty sure this is the right way to do it, but I've …
> Soft fail upload of packages docker images

- .github/dependabot.yml
- packaging/docker/ubuntu-20.04/Dockerfile
- packaging/docker/ubuntu-22.04/Dockerfile
- packaging/docker/ubuntu-24.04/Dockerfile
Stop Dependabot attempting upgrades of Ubuntu images to the latest LTS. 
See #3099, #3100
* Use new image tags added in buildkite/agent-base-images#1
* Use a group in Dependabot to make it do one PR for all images
> Use Ubuntu codename labels for base images

- internal/shell/shell.go
Fix duplicate command output when debug mode is enabled.
Fixes #3107
https://linear.app/buildkite/issue/PS-200/duplicate-logs-in-agent-with-debug-mode-enabled
The bug was added in #3068 - at the time, I didn't think through all the consequences of changing to "tee-ing" command output.
* Instead of tee-ing output to the log streamer when debug is enabled, substitute stdout or stderr (or both) if set to `io.Discard`.
> Fix duplicated output when debug is enabled

- internal/job/checkout.go
A small bit of hardening - if `BUILDKITE_GIT_SUBMODULE_CLONE_CONFIG` is set but empty, then `GitSubmoduleCloneConfig` can be a slice with one element `""`, causing an invalid Git flag to be appended.
https://coda.io/d/_dHnUHNps1YO#Escalations-by-Assignee_tugT4T3x/r883&view=center
> Ignore empty submodule clone configs

- clicommand/agent_start.go
- version/version.go
During agent startup check if the bootstrap agent path matches the startup agent path. This is to avoid confusion during development when changes are made to the agent but the bootstrap agent still uses the default agent on the `$PATH`. Usually this results in changes being made to the agent, but then those changes not being observed when running the updated agent locally.
For example if I 
1. `go build -o buildkite-agent .` then
2. `./buildkite-agent start --spawn 2 --endpoint http://agent.buildkite.localhost/v3 --token buildkite`
By default the above will result in `./buildkite-agent` starting up and waiting for jobs, when a job is run, if that job uploads a pipeline it will use (in my case) `/opt/homebrew/bin/buildkite-agent`, not `./buildkite-agent`, so any changes I've made to …
> Notify when host and bootstrap agent paths mismatch

- clicommand/errors.go
When the agent exits and prints an error message prefix the message with `buildkite-agent: ` to provide clarity as to where the error came from. Our buildkite-agent cli is often used in scripts and when it exits with an error it isn't always obvious to the user what printed the error. It is common practice for cli tools to prefix error messages with the tool name.
https://linear.app/buildkite/issue/PS-217/prefix-fatal-error-messages-with-buildkite-agent
> Prefix fatal error message with 'buildkite-agent:'

- agent/agent_configuration.go
- agent/job_runner.go
- clicommand/agent_start.go
- clicommand/agent_start_test.go
- clicommand/bootstrap.go
- internal/job/config.go
- internal/job/executor.go
- packaging/docker/alpine-k8s/buildkite-agent.cfg
- packaging/docker/alpine/buildkite-agent.cfg
- packaging/docker/sidecar/buildkite-agent.cfg
- packaging/docker/ubuntu-20.04/buildkite-agent.cfg
- packaging/docker/ubuntu-22.04/buildkite-agent.cfg
- packaging/docker/ubuntu-24.04/buildkite-agent.cfg
- packaging/github/linux/buildkite-agent.cfg
- packaging/github/windows/buildkite-agent.cfg
- packaging/linux/root/usr/share/buildkite-agent/buildkite-agent.cfg
We would like to provide the ability to place hooks in multiple locations, meaning there can be multiple hooks of the same type, and they can be provided under different circumstances. These additional hooks are comma separated list, and ordered as they are provided in terms of how multiple hooks are executed. Those in `hooks-path` are always first, and then sequentially through `additional-hooks-paths`.
There are 2 places where we pull in these hooks:
1. During the agent startup phase
2. Through the job execution phases
We don't currently support the `pre-bootstrap` hook with additional paths.
There is no change to any default behaviour included, nor is there any change in existing functionality when configuration is not changed. The only way to have any impact from this change is to set …
> Adding support for Additional Hooks Paths

- internal/job/executor.go
`e.shell` isn't set yet.
#3149 
Use `tempLog` instead of `e.shell` to log the error.
> Fix nil pointer deref on executor.go:103

- agent/agent_worker.go
- agent/agent_worker_test.go
- core/client.go
- go.mod
- go.sum
During recent incidents, we've run into situations where when in acquire-job mode, the agent can tend to be a bit of a thundering herd - we retry every 3 seconds, and don't jitter. This means that if a lot of jobs are acquired all at once, and Buildkite is having a bad time, it'll tell them all to go away all at once, and then they'll all come back 3 seconds later, with the load all happening all at once.
This PR updates the retry strategy the agent uses when acquiring jobs, making the following changes:
- The basic strategy used in `roko` has been updated from 
```Go
roko.WithMaxAttempts(9)
roko.WithStrategy(roko.Constant(3*time.Second))
```
to
```Go
roko.WithMaxAttempts(7)
roko.WithStrategy(roko.Exponential(2*time.Second, 0))
```
effectively, this means that we'll make fewer requests …
> PIPE-631 Backoff exponentially when job acquisition fails

- core/client.go
- go.mod
- go.sum
This PR fixes two issues introduced in https://github.com/buildkite/agent/pull/3153:
- The roko retrier would lie about the time it was going to retry in when jitter was enabled - see https://github.com/buildkite/roko/pull/18. This problem is solved by updating to roko v1.3.1, which includes the PR linked.
- In the acquire-job retry loop, in some cases, the server can set the amount of time that the retrier can retry in. However, because the `Retrying in...` message was logged prior to setting the next interval, the retrier would log the interval it calculated instead of the interval that the backend told it to use. This issue is resolved by simply logging after we set the next retry interval.
> Roko v1.3.1

- .github/dependabot.yml
`.buildkite` has Dockerfiles, but the directory was forgotten when rearranging the dependabot config.
Noticed that `.buildkite/Dockerfile-build` wasn't up to date.
> Add /.buildkite dir for Dockerfile updates

- agent/agent_worker.go
- agent/integration/test_helpers.go
- agent/job_runner.go
- agent/run_job.go
More techniques to avoid thundering herds - introduce jittering inside fixed interval loops.
This is a change I've wanted to make for a while, but never really got around to it.
The job status checker loop (used to stop a job cancelled server-side) uses a sleep on a fixed interval between requests, meaning it is susceptible to spontaneous synchronisation between agents. 
The log processing loop is similar to the job status loop, with fixed 1 second wait. It's not directly connected to a network request, but the pipeline is tight.
The ping loop uses a ticker, which has internal mechanisms for keeping a fixed pace. But this therefore preserves initial synchronisation between agents (e.g. multiple machines come up at once due to, say, a power outage, and they proceed to start the agent at …
> Jitter within ping, status, log loops

- internal/job/plugin.go
Fixes #3090 
- Change the temp directory pattern to be less reminiscent of a plugin directory
- Log the `mktemp` and `mv` operations similarly to the `cd` operation
To think about: these new logged operations should probably appear different on Windows 🤔
> Better plugin checkout logging

- core/client.go
When there is a failure between a customer and buildkite we "could" hold onto compute for up to 48 hours.
I am starting with these two calls as they are important calls which can block agent shutting down.
If the buildkite API, or intermediate network devices, such as nat GW trigger drop outs and timeouts of requests over an extended period of time we can tie up compute resources, this isn't ideal as it can hold onto expensive resources.
Reducing these two values avoids surprising outcomes for customers when things go wrong.
> Reduce timeout for these two operations to avoid holding up compute

- agent/job_runner.go
- bazel-agent
- bazel-bin
- bazel-out
- bazel-testlogs
- kubernetes/client.go
- kubernetes/kubernetes_test.go
- kubernetes/runner.go
Ensure the agent process does not wait forever for the client containers to connect.
Addresses one cause of agent containers continuing to run, as reported in buildkite/agent-stack-k8s#479
Adds a `startupCheck` that waits for all client containers to connect. If one or more fail to connect within a timeout, an error is returned.
> Timeout waiting for client containers

- .gitignore
- bazel-agent
- bazel-bin
- bazel-out
- bazel-testlogs
Clean up Bazel cruft accidentally merged in #3172
> rm bazel-*, add to .gitignore

- clicommand/step_cancel_test.go
- tracetools/propagate_example_test.go
These two tests take 40 - 50 seconds each. They can be short-circuited a bit (without affecting their fidelity).
Noticed by @pda here: https://buildkite-corp.slack.com/archives/C061U5PG9K5/p1738728903252739
* Instead of trying to send traces to a non-existent DD agent (and timing out), use `mocktracer`.
* Instead of trying to cancel a job against a fake server that always returns HTTP 500, return HTTP 400 which aborts the retry quickly.
> Speed up needlessly slow tests

- agent/log_streamer.go
- agent/log_streamer_test.go
- agent/run_job.go
Currently if the agent is sent a sigterm the log streamer will wait for all chunks to be uploaded, and even if a second sigterm is sent we still wait.
Other components of the agent honor the a graceful=false flag which allows operators to force the agent to stop.
This change adds that graceful option to the log streamer stop.
This change introduces immediate cancellation to the log streamer when the agent is forced to stop.
If customers egress is overloaded, or there is a large backlog of chunks to upload, and that is blocked due to internet connectivity issues, the agent can block for extended periods waiting to upload chuncks even if has been "forced" to quit.
Adds a simple way to signal to the uploader workers to stop work and quite immediately when the agent has been told to exit and …
> Ensure the log streamer respects forced shutdown of the agent

- agent/log_streamer.go
- agent/log_streamer_test.go
- agent/run_job.go
* What it says on the title
* Also switches to `atomic.Int32` for `chunksFailedCount`.
> Fix data race on exitImmediately

- agent/log_streamer.go
- agent/log_streamer_test.go
- agent/run_job.go
Reverts buildkite/agent#3187
This is being reverted because log output is being truncated by this change on #3180
> Revert "Fix data race on exitImmediately"

- agent/log_streamer.go
- agent/log_streamer_test.go
- agent/run_job.go
Reverts buildkite/agent#3180
This is being reverted because log output is being truncated by this change.
> Revert "Ensure the log streamer respects forced shutdown of the agent"

- clicommand/agent_start.go
Agent registration requests include an array of "features" that are enabled on the agent. To assist with debugging, it would be helpful to know if a particular agent:
* has opted into HTTP 1.1 only
* is using a HTTP proxy
* has set GODEBUG, which [can be used to change the behaviour of net/http](https://pkg.go.dev/net/http)
We're submitting a boolean only, to indicate the feature is active. We don't submit values, such as the address of the HTTP proxy.
It would also be quite helpful to have the agent log out the state of its connection pool to agent.buildkite.com, but that's quite a different change to this so I've left it out and kept this PR simple.
> Capture some HTTP client details from registering agents

- clicommand/agent_start.go
As an extension to https://github.com/buildkite/agent/pull/3193 would be good to capture the use of datadog metrics.
As with the previous PR, we're submitting a boolean only, to indicate the feature is active.
> Capture datadog metrics usage from registering agents

- agent/api.go
- api/agents.go
- clicommand/agent_stop.go
- clicommand/agent_stop_test.go
- clicommand/commands.go
- clicommand/config_completeness_test.go
Add a `buildkite-agent stop [--force]` command.
The main use case is to allow customers to write "health checks" in agent and job hooks which can tell the agent to stop before or after the current job. For example, a `pre-command` agent hook could detect a spot instance has been asked to terminate and forcefully stop the agent, and allowing the use of an `AGENT_STOP` signal reason to automatically retry in that case. Or a `post-command` agent hook could detect a 95% full disk and tell the agent to stop after the current job completes.
Implementation is mostly extrapolated from what exists, I'm not here to set up new patterns 🙈
This PR only adds a basic test to make sure the plumbing works. There's not a lot of maturity in the testing, so this felt like a nice add without going full ham on …
> Add agent stop command

- process/process.go
- process/process_test.go
While testing a number of failure scenarios which simulate network failures I can across this error, which occurs if an agent is sent a `SIGTERM` and tries to kill a process which is already exited.
This sort of race condition is caused by outages of the buildkite api, or network interuptions.
One open question I have is the switch linked below in the correct order? Given the error being raised skips the timeout, and the done check being after this timeout which seems odd.
https://github.com/buildkite/agent/blob/fix_dont_fail_interrupt_if_pid_exited/agent/run_job.go#L504-L520
> Don't fail if the interrupt fails when the PID is already exited

- clicommand/agent_start.go
- internal/job/executor.go
- internal/job/grace.go
This uses two new calls to which are only triggered after the second quit attempt to ensure the agent exits:
1. After half the cancel grace period (defaults to at least 10s) the agent will cancel the context.
2. At the end of the cancel grace period, if the agent is stuck it will call os.Exit(1).
The pool stop with graceful false should, if at all possible, trigger disconnect calls for all the agents. 
> [!NOTE]
> This code logic is only invoked after a second exit signal.
If the agent is unable to commicate with the agent API it can take almost an hour to stop.
Adds more logic to the signal handler to ensure the agent exits.
To test this logic I used https://github.com/smarty/cproxy as a HTTP proxy with the agent configured to use it, then once a job was started and the process was …
> Change the signal handler to ensure the agent quits after the grace period

- internal/job/checkout.go
- internal/job/integration/checkout_git_mirrors_integration_test.go
- internal/job/integration/checkout_integration_test.go
During the checkout phase the agent will validate the `BUILDKITE_COMMIT` environment variable has been set knowingly within the build already, or push the data within this job. The first job in a build is likely to be the only time this needs to actually happen, as once it is and `BUILDKITE_COMMIT` has been set it will be available to remaining jobs within the build. We use the meta-data API to track this, which means we're making many API calls back to `buildkite.com` when really, we shouldn't need to do this by checking the value ourselves.
**Disclaimer:** This is quite naive in how the value of `BUILDKITE_COMMIT` is trusted, where we assume that if the value is 40 characters long and the characters match the accepted values of a SHA then we use it.
The value for `BUILDKITE_COMMIT` …
> Skip pushing the git commit metadata if BUILDKITE_COMMIT_RESOLVED=true

- clicommand/agent_start.go
- clicommand/pipeline_upload.go
- go.mod
- go.sum
- jobapi/env.go
- tracetools/propagate_test.go
I, a bad and evil person, introduced the `exp/maps` library into this project before it was introduced to the stdlib. As penance, i give to you this gift: `exp` has been excised from this repo and cast into the fires that birthed it.
> Kill exp/maps and replace with stdlib maps

- agent/integration/config_allowlisting_integration_test.go
- agent/job_runner.go
- api/oidc_test.go
- internal/job/checkout.go
- internal/job/docker.go
- internal/job/tracing.go
- internal/replacer/bm_redactor_test.go
- internal/socket/middleware.go
- status/status.go
Fixes from the new modernize analyzer from the Go team #3209 
https://github.com/golang/tools/releases/tag/gopls%2Fv0.18.0 for more details.
> [!NOTE]
> I had to fix all the imports manually.  
There are quite a few small optimisations which can be introduced to the codebase to "modernize" it.
Just some linting fixes.
> Fixes from the new modernize analyzer from the Go team

- agent/agent_worker.go
- agent/agent_worker_test.go
- agent/dummy_bootstrap.sh
- agent/idle_monitor.go
- go.mod
- logger/log.go
Handle "pause" as a ping action.
https://linear.app/buildkite/issue/PIPE-747/agent-prevent-paused-agent-terminating-in-one-shot-modes
Important bits:
* Don't return early when using acquire-job, so that there's a ping loop after it, but exit from the ping loop instead
* Add "pause" as an action returned from ping, use it to `continue` the ping loop (avoiding either running a job or exiting the loop)
Refactoring/cleanup:
* Rearrange Ping so that it returns the action, and handle the action in the ping loop
* Move idle monitor to its own file
* Replace sync.Mutex+bool+channel with sync.Once+channel for tracking stopping
> Handle pause actions

- internal/job/executor.go
So that hook behaviour can change when the job has cancelled, either from the platform or because the agent is being stopped, and so its result is likely inconsequential. We have some customers who would like to use this to avoid sending a notification to a system about a result that doesn't matter because it is either incomplete or will be retried.
Alternative to #3201 / PIPE-481.
This could use an additional automated test but I'm not sure how complicated that'll be. But this seems a pretty low-risk change in any case.
I manually tested by adding a post-command hook like this:
```bash
if [[ "$BUILDKITE_JOB_CANCELLED" == "true" ]]; then
echo "Job was cancelled, skipping notifications!"
exit
fi
echo "Sending notifications ..."
```
and it worked a treat:
That should also cover when the …
> Set env when job cancelled for hooks

- agent/run_job.go
As Developer Productivity engineers, we are sometimes tasked with troubleshooting misbehaving agents. To do this, we collect agent metrics and the logs in our o11y platform. This PR is a QoL improvement to record build URL in the buildkite-agent log in addition to the job ID. If the agent has been around for a while and has executed several jobs, it would be great to have easier traceability to see what has been executed on the agent. Having the build URL will allow to quickly locate the executed job in Buildkite UI.
> Record build URL in the buildkite-agent log for easier traceability

- agent/agent_pool.go
An endless stream of "GET /" is not very useful unless you already know where it's coming from.
From trying to understand odd agent logs while investigating another issue.
The log itself is something I added in #1873, and must have forgotten to clean up at the time.
`Info` -> `Debug` and add some missing context
> Change healthHandler to log requests at debug level

- process/ansi.go
- process/ansi_test.go
- process/fixtures/npm.sh.raw
- process/timestamper.go
Significant speed savings:
```
❯ benchstat ansi-parser-{maps,arrays}.txt
goos: darwin
goarch: arm64
pkg: github.com/buildkite/agent/v3/process
cpu: Apple M1 Max
│ ansi-parser-maps.txt │       ansi-parser-arrays.txt        │
│        sec/op        │   sec/op     vs base                │
ANSIParser-10           2322.3µ ± 0%   565.3µ ± 1%  -75.66% (p=0.000 n=30)
```
The secret redactor was sped up a bit by switching away from a map, and I remembered this used maps too.
* Add a benchmark
* Rename `feed` to `Write` in case we want to e.g. `io.Copy` or `MultiWriter` into it
* Use `[256]*ansiParserState` instead of `map[byte]ansiParserState`
> ANSI parser speedup

- internal/experiments/experiments.go
`PTYRaw` is in the "available" const block but not in the "available" map.
Found while working on other stuff
> fix: experiment missing from available

- agent/agent_worker.go
- agent/agent_worker_test.go
Make agent pausing effective at keeping `disconnect-after-job` and `disconnect-after-idle-timeout` agents alive.
Noticed while investigating a different bug related to job acquisition in these modes.
* Rearrange ping loop to check `DisconnectAfterJob` and `DisconnectAfterIdleTimeout` conditions before running the job.
* `DisconnectAfterJob` requires knowing that a job has run, so that is now tracked as a bool.
* `DisconnectAfterIdleTimeout` does not care whether a job ran or not, but checking it before  job execution allows a ping to happen.
* Doing both of these enables changing `if job != nil { ... big block ... }` into `if job == nil { continue } ...big block now outdented 1 level...` which is nice
> Ping before disconnect in disconnect-after-* modes

- clicommand/annotate.go
- internal/job/executor.go
- internal/redact/redact.go
- internal/replacer/replacer_test.go
- jobapi/server_test.go
Annotations are as visible as job logs, and can just as easily have secrets leaked into them accidentally, so apply redaction to them.
https://3.basecamp.com/3453178/buckets/23112918/messages/8443739637
* internal/redact: Some helper refactoring 
* clicommand: Pass the annotation body through `redact.String`.
> Redact annotations

- clicommand/annotate.go
- clicommand/meta_data_set.go
- clicommand/step_update.go
Apply redaction to meta-data and step updates. 
When redaction happens in these cases, log a warning (also for annotations).
https://3.basecamp.com/3453178/buckets/23112918/messages/8443739637
> Redact meta-data values and step attribute updates with warnings

- internal/redact/redact.go
- internal/redact/redact_test.go
Fixes the operations that recently had redaction added (annotate, meta-data set, step update) where the final character(s) would be missing.
The cause was a missing call to `Flush` on the string replacer, combined with one or more secrets that started with the missing character.
https://linear.app/buildkite/issue/PS-485
> Fix incomplete processing in newly-redacted operations

- agent/agent_worker.go
- api/client.go
- api/client_test.go
- clicommand/agent_start.go
- core/controller.go
These local vars were previously named `a`, `ag`, `resp`, and `regResp` in different places.
I was anticipating some upcoming work on agent registration responses, and renamed these while exploring the code. That work doesn't need to happen after all, so this is just a tiny stand-alone refactor.
> refactor: rename `AgentRegisterResponse` local vars to `reg` consistently

- agent/agent_worker.go
- agent/agent_worker_test.go
The minimum valid server-specified ping interval is 1 second, which means tests that run the ping loop through multiple pings spend multiple seconds waiting.
This introduces a private `AgentWorker.noWaitBetweenPingsForTesting bool` field that tests within package agent can set, which will skip the delay between pings by immediately returning from the `select { … }` due to a closed channel.
This speeds up the existing agent tests by ~5 seconds when run with single parallelism. The benefits are presumably less when running the entire suite in parallel, but this remains useful when iterating on a single test (milliseconds instead of seconds).
Context: I'm working on [some changes](https://github.com/buildkite/agent/pull/3263) that introduce new tests which use the ping loop.
> `AgentWorker` has `noWaitBetweenPingsForTesting` field

- agent/agent_worker_test.go
- agent/fake_api_server_test.go
Follow through on an earlier ~~threat~~ TODO comment.
Reminded of it while discussing #3263 
- Refactor the `httptest.Server` used in the two recently added agent tests into its own thing, `FakeAPIServer`
- Update the tests to use the new fake
> Refactor fake API server

- agent/agent_worker_test.go
- api/client.go
This functionality has existed for a long time, but hasn't had test coverage.
Uses the nice new `FakeAPIServer` from https://github.com/buildkite/agent/pull/3264
This also introduces `(api.Config).Timeout time.Duration` so that the timeout on a known-broken endpoint in tests can be reduced to milliseconds instead of the default 60 seconds.
These tests are extracted and adapted from ~#3263~ #3268, so that/those PRs can be rebased after this is merged to shrink them to their actual intent.
> agent_worker_test: tests for endpoint switching during register/ping

- agent/agent_worker_test.go
- agent/fake_api_server_test.go
This allows `PingHandler`s to make decisions/assertions on HTTP headers etc, which I need in #3268.
Related:
- #3268
- #3264
> `FakeAPIServer`'s `PingHandler` is passed the `*http.Request`

- .buildkite/Dockerfile-lint
- .buildkite/docker-compose.yml
- .buildkite/pipeline.yml
- .buildkite/steps/check-code-committed.sh
Use a more powerful lint tool to find issues.
Since it finds numerous violations in the existing codebase, ignore its exit code (for now).
Noticed during #3273
> chore: Use golangci-lint for code checks

- agent/agent_worker_test.go
- agent/api.go
- agent/integration/job_environment_integration_test.go
- agent/integration/test_helpers.go
- agent/job_runner.go
- api/agents.go
- api/client.go
- api/client_private_test.go
- api/pings.go
Allow Buildkite server to add `Buildkite-*` request headers to an agent's session, and then use those subsequent request headers to e.g. improve routing, performance, and reliability of requests. Specifically, we intend to use these headers to extend the resilience of our sharded architecture.
The request headers would be included in an optional `request_headers` field of /v3/register and /v3/ping responses:
{
"…": "…",
"request_headers": {
"Buildkite-Hello": "world!"
}
}
- The API client has a new internal map of server-specified headers to include in every request (`api.Client.requestHeaders`).
- Only headers beginning with `Buildkite-` are accepted by the agent, so general HTTP behaviour cannot be impacted by this mechanism.
- The presence of `request_headers` in register/ping …
> `api.Client` sends request headers specified by server in register & ping

- agent/agent_worker.go
Since a change in 3.95.0 (#3238) to ping after a job is finished we've had reports that jobs are assigned to agents that are about to be disconnected. While this could happen before this change, we believe waiting for the ping interval has made it more frequent and it's likely to happen multiple times for the same job.
This change ensures we don't wait up to 10s before disconnecting, making it as likely as before
Reset the ping interval if disconnectAfterJob is set.
> Ignore the ping interval if agent will disconnect after job

- internal/mime/generate.go
- internal/mime/mime.types
In https://github.com/buildkite/agent/pull/3283 I received an error when generating the mime types.
https://hg.nginx.org/nginx/raw-file/default/conf/mime.types is returning a 503, this copy was retrieved from archive.org and generates the same output
cache nginx mime types locally
> locally cache nginx mime types

- .buildkite/docker-compose.yml
- .buildkite/pipeline.yml
- .buildkite/steps/tests.sh
Use bktec to run go test for agent, this bring following benefits: 
* auto package level splitting: slightly reducing test duration -> not too obvious though. 
* auto retry. 
* Automatic test state management, flaky test will get muted automatically. You can also manually control test state via buildkite UI. 
* Dogfooding helping Test Engine 😉 
TE-3708
> TE-3708: use bktec on agent

- .buildkite/pipeline.yml
- .buildkite/steps/test-coverage-report.sh
- .buildkite/steps/tests.sh
As we adopted `bktec` auto retry, test splitting for agent, the old single file coverage reporting mechanism will report incorrect data.
This PR:
* use go 1.20's `go test -cover` to generate test coverage binary data, submit to artifact. 
* add a test coverage step in CI, it collects all submitted coverage binary data, merge them into a single report. 
* Only make the ARM64 test step generating coverage, this accelerate test runs in all other platforms. 
part of TE-3708
> TE-3708-follow-up: Use go test -cover to generate coverage report

- internal/job/checkout_test.go
- internal/job/githttptest/githttptest.go
This PR introduces a githttptest package which provides a [Git smart http server](https://git-scm.com/book/en/v2/Git-on-the-Server-Smart-HTTP) used for testing, along with an array of utility methods to manipulate a git repository.
The checkout logic is a bit of a blind spot at the moment as there isn't any test coverage for this code. The goal of this PR is to change that by adding some tools which verify behavour, testing both the git command execution and the go code.
This will allow us to test some of the changes in #3294 
This increases the test coverage for executor targeting the `defaultCheckoutPhase` method to start with.
> Introduce a structure where coverage can increase on githttp checkout code

- agent/agent_worker.go
- agent/agent_worker_test.go
- agent/api.go
- agent/fake_api_server_test.go
- agent/integration/test_helpers.go
- agent/job_runner.go
- agent/run_job.go
- api/jobs.go
- core/api_client.go
- core/client.go
- core/job_controller.go
- internal/ptr/to.go
- kubernetes/kubernetes_test.go
Prevent jobs being dispatched to agents that are finishing up by passing a newly-available flag in the finish call.
https://linear.app/buildkite/issue/PS-554
- Thread the new flag through the call stack
- Pass it when disconnect-after-job is enabled
> Set ignore_agent_in_dispatches when finishing with disconnect-after-job

- clicommand/agent_start.go
The `BUILDKITE_AGENT_TAGS_FROM_EC2_TAGS` env var is assigned to set both `tags-from-ec2-tags` and its deprecated duplicate `meta-data-ec2-tags`. The agent [errors][1] when both the deprecated and new version of an option are set, which makes `BUILDKITE_AGENT_TAGS_FROM_EC2_TAGS` unusable.
Following the naming of other deprecated `meta-data-*` it seems `BUILDKITE_AGENT_META_DATA_EC2_TAGS` was meant to be used for `meta-data-ec2-tags`.
[1]: https://github.com/buildkite/agent/blob/fd239e03db6abffdb562ef0963459ab90203b763/cliconfig/loader.go#L120
> Fix unusable `BUILDKITE_AGENT_TAGS_FROM_EC2_TAGS` env var

- agent/agent_worker.go
Fixes bug introduced in #3238.
https://linear.app/buildkite/issue/PS-554
- Only apply disconnect-after-idle-timeout check if the ping did not yield a job.
- Log if a job was yielded in states where it is unexpected (acquire-job, disconnect-after-job after job)
> fix: Don't disconnect-after-idle when just given a job

- agent/job_runner.go
- clicommand/agent_start.go
- clicommand/bootstrap.go
- clicommand/cancel_signal.go
- clicommand/commands.go
- clicommand/config_completeness_test.go
- clicommand/global.go
- clicommand/kubernetes_bootstrap.go
- clicommand/lock_common.go
- clicommand/step_cancel.go
- env/environment.go
Reduce Kubernetes resource size (when using agent-stack-k8s) by applying more environment variables from the socket.
A customer had feedback that having a lot of env vars repeated across containers in the pod spec can consume a lot of space in etcd.
- Add a `kubernetes-bootstrap` subcommand. This allows fetching the env vars from the socket before the `bootstrap` subcommand runs, which was the fatal flaw in commit 36940e5
- Filter out the kubernetes plugin when creating the bootstrap env
- Some small-scale refactoring of flags and env helpers
> Add kubernetes-bootstrap

- clicommand/kubernetes_bootstrap.go
- internal/job/executor.go
The registration response env vars are meant to be read to find out `BUILDKITE_PTY`, etc, but these were being added to `environ` after. 
Found during testing.
- Merge the registration response vars into `environ` before reading them.
- A tiny simplification to `$PATH` computation found when trying to understand it.
> Fix env loading order in kubernetes-bootstrap

- agent/job_runner.go
- clicommand/kubernetes_bootstrap.go
- process/process.go
Refine `kubernetes-bootstrap` based on things learned during testing.
buildkite/agent-stack-k8s#595
- Reorder the construction of `environ` so `os.Environ()` takes precedence over the registration env, which eliminates some of the previous hand-holding via config.
- Replace `BUILDKITE_BIN_PATH` with the directory of `os.Executable`
- Enforce `BUILDKITE_SOCKETS_PATH` based on what agent-stack-k8s provides
- Remove redundant call to `filepath.Abs` (in job_runner.go)
- Remove unused `Timestamp` field (in process.go)
> kubernetes-bootstrap refinements

- agent/job_runner.go
- clicommand/agent_start.go
- internal/artifact/bk_uploader_test.go
- internal/artifact/download.go
- internal/job/checkout.go
- internal/job/githttptest/githttptest.go
- internal/job/integration/artifact_integration_test.go
- internal/job/integration/checkout_git_mirrors_integration_test.go
- internal/job/integration/checkout_integration_test.go
- internal/job/integration/hooks_integration_test.go
- internal/job/integration/plugin_integration_test.go
- internal/job/knownhosts.go
- internal/osutil/file.go
- internal/shell/lookpath.go
- internal/shell/shell_test.go
- internal/socket/server.go
- kubernetes/runner.go
- **Make job log tempfile world-readable**
Currently, when users use the `--job-log-tempfile` flag on the agent, the tempfile is created with `600` permissions (ie, readable and writable by the current user, unavailable to everyone else). This can be frustrating, as a primary use case for this file is ingestion by a log ingestion framework a la Cloudwatch/Stackdriver/Loki, which often run as different users.
To fix this, this PR sets the permissions on the job log tempfile to `644` (readable and writable by us, readable by everyone else). This is relatively in line with the unix permissions policy for files created by the agent, which are generally created with relatively permissive permissions (usually 777), to be reduced by the umask. Given that job logs can be somewhat sensitive, I've …
> Set job log tempfile permissions to 644 (was 600)

- internal/job/checkout.go
- internal/job/git.go
Currently, when a PR triggers a build, we trigger two `git fetch`. This PR merges these two `git fetch` into one.
PS-624
> Reduce git fetch from twice to once for typical Github PR build

- clicommand/agent_pause.go
- clicommand/agent_resume.go
- clicommand/agent_stop.go
- clicommand/annotate.go
- clicommand/bootstrap.go
- clicommand/commands.go
- clicommand/git_credentials_helper.go
- clicommand/kubernetes_bootstrap.go
- main.go
<details>
<summary>Before</summary>
```
$ buildkite-agent --help
Usage:
buildkite-agent <command> [options...]
Available commands are:
start                   Starts a Buildkite agent
bootstrap               Run a Buildkite job locally
acknowledgements        Prints the licenses and notices of open source software incorporated into this software.
annotate                Annotate the build page within the Buildkite UI with text from within a Buildkite job
annotation              Make changes to an annotation on the currently running build
artifact                Upload/download artifacts from Buildkite jobs
build                   Interact with a Buildkite build
env                     Process environment subcommands
git-credentials-helper  Ask buildkite for credentials to use to …
```
> Better helptext

- internal/job/checkout.go
- internal/job/checkout_test.go
- internal/job/git.go
- internal/job/git_test.go
In #3294, we introduced behaviour to retry `git fetch`es during the default checkout hook for checkouts using git mirrors. This is because during the checkout process for a PR build we fetch the `refs/pull/<some number>/head` ref that GitHub creates. The creation of this ref happens asynchronously to the PR being opened though, so in some cases a build will have started before the ref has been created. In this situation we're trying to fetch a ref that doesn't (yet) exist, which will fail the fetch, so we wait around and retry for a bit until either the ref exists, or we run out our retry loop, which tries 10 times over about 2 minutes.
However, #3294 also introduced a couple of bugs and oddities in this flow, primarily that:
1. The retry loop for fetching PR refs was nested inside …
> Fix PR ref retry logic

- clicommand/pipeline_upload.go
- clicommand/pipeline_upload_test.go
- go.mod
- go.sum
Allow pipeline YAML containing more than one document. When using `buildkite-agent pipeline upload` with such an input, upload all of them.
https://linear.app/buildkite/issue/PS-795
- Update go-pipeline to v0.14.0
- Change `parseAndInterpolate` to use `pipeline.ParseAll` and return an iterator
- Change the action to put most of the work in a loop
- Move dry-run output setup outside of the loop so that the output YAML will consist of multiple correctly-separated documents
> Upload all pipelines present in the input

- agent/agent_worker.go
- agent/agent_worker_test.go
This change https://github.com/buildkite/agent/commit/77fc7dc04462183d29d44217a18d13fa710fabd7 introduced a regression which resulted in acquire job not triggering a exit code 27 for jobs when acquire job API calls are rejected by buildkite.
https://linear.app/buildkite/issue/MDC-493/regression-in-agent-behavior-not-reporting-non-eligible-jobs
Do the same sentinel error check on the return from AcquireAndRunJob and returning early to restore the previous exit code behaviour.
> [!WARNING]  
> This change resolves a regression, if you encounter issues with this release rollback raise an issue or contact support@buildkite.com
> Fix AquireJob to return early and trigger a sentinal error for rejection

- clicommand/agent_start.go
- clicommand/bootstrap.go
- internal/job/artifacts.go
- internal/job/checkout.go
- internal/job/integration/artifact_integration_test.go
- internal/job/integration/checkout_git_mirrors_integration_test.go
- internal/job/integration/checkout_integration_test.go
- internal/job/integration/command_integration_test.go
- internal/job/integration/docker_integration_test.go
- internal/job/integration/executor_tester.go
- internal/job/integration/hooks_integration_test.go
- internal/job/integration/job_api_integration_test.go
- internal/job/integration/plugin_integration_test.go
- internal/self/self.go
- version/version.go
Remove `checkBinaryPaths`, and self-execute using the result from `os.Executable` in more places.
Unfortunately we can't yet totally solve the sorry-Mario-your-`buildkite-agent`-is-in-another-castle problem (`buildkite-agent` within a command or script run as part of a step can still be a separate binary). 
`checkBinaryPaths` creates the need for some ugly workarounds elsewhere for those who build the agent themselves.
https://linear.app/buildkite/issue/PS-732
- Revert #3123 
- Add a `self` internal package for managing path to self, and provide a way to override during tests
- Use `self.Path` for artifact phase, setting metadata, and the credential helper.
- Use `self.OverridePath` within the bootstrap subcommand, if a magic combination of undocumented env vars is present
> Self-execute the path from os.Executable in more places

- go.mod
- go.sum
- internal/job/tracing.go
The OpenTelemetry integration currently, only supports sending tracing with the grpc transport, but with a small amount of juggling it can support http/protobuf transport also.
PB-116
- Add support for http/protobuf transport for OpenTelemetry
> [PB-116] Add support for http/protobuf transport for OTLP

- agent/agent_configuration.go
- agent/agent_worker.go
- agent/agent_worker_test.go
- clicommand/agent_start.go
We want our buildkite agent fleet to regularly cycle out machines, but we always have at least some jobs running in our cluster which leads to some agents staying up for a long period of time, even with disconnect-after-idle-timeout set. This PR adds an additional config option to set a max lifetime for the buildkite agent, after which time it will shut itself down.
I am not super familiar with Golang, but I modeled this after the existing disconnect-after-timeout flag. I tested this locally and it seems to perform as desired.
* Added new config option disconnect-after-uptime
* Added a test for the new functionality
```
--disconnect-after-uptime value          The maximum uptime in seconds before the agent stops accepting ne
w jobs and shuts down after any running jobs complete. The …
```
> Add disconnect-after-uptime flag to set a max lifetime for agents

- logger/log.go
- logger/log_test.go
When setting the agent log output to JSON, the output is sometimes not valid JSON. For instance, when using ANSI links or colours (`"\e]1339;url=#{url};content=#{caption}\a"` or `"\e[#{color_code}m#{text}\e[0m"`).
> Print valid json

- agent/agent_worker.go
- agent/agent_worker_test.go
- agent/dummy_bootstrap.sh
- agent/run_job.go
- clicommand/agent_start.go
- core/process_exit.go
- internal/job/executor.go
For acquire-job cases, making the agent reflect the exit code makes it easier to integrate the agent into more things.
Fixes #3369
- Make `core.ProcessExit` a kind of `error`, so that it can be returned easily. 
- If a `core.ProcessExit` lands in the `start` command, exit with the same status.
- Return the `core.ProcessExit` from the job runner if the agent is set to acquire job and the exit status was non-zero.
- Fix the "seems like a bug" issue where the exit code of a process within the bootstrap would be swallowed following being signaled.
- Remove "dummy_bootstrap.sh" in favour of a small (OS-dependent) no-op command, and ensure the build and hooks subdirs exist. Turns out the "dummy_bootstrap.sh" approach didn't actually work, and now that the process error is propagating in some …
> Exit with same code in acquire-job mode

- clicommand/annotate.go
We had a customer hitting the limit of the annotation's context. So adding the limit in our docs would help future travellers be aware that such limit exits.
> Adding a reference  in our docs the limit of an annotation's contexts

- clicommand/redactor_add.go
The documentation update script expects 4 space indents for shell examples.
I noticed this while updating the docs.
Make the indentation consistently 4 spaces.
> Normalise indentation in redactor add usage

- clicommand/agent_start.go
It was pointed out that #3376 was a breaking change, and particularly, it changed some behaviour people were relying on. 
Make the new behaviour opt-in via flag.
https://linear.app/buildkite/issue/PS-896
- Introduce a new flag, `reflect-exit-status`
- Exit with the job exit status only if the new flag is enabled.
> Add reflect-exit-status flag to control exiting with job status

- clicommand/agent_start.go
Cherry-pick #3392 to v3.102 branch.
https://linear.app/buildkite/issue/PS-896
- #3392
> Fix to reflect-exit-status flag

- .buildkite/pipeline.yml
Roll out using session tags for OIDC assumable IAM role trust policy. 
Follow on from the work to support session tags in https://github.com/buildkite-plugins/aws-assume-role-with-web-identity-buildkite-plugin/pull/18
Requires matching update to the IAM role in PR: https://github.com/buildkite/aws-buildkite-dev/pull/474
This is only changing the one pipeline, which uses an IAM role in `buildkite-dev` account. Additional pipelines defined in this repo will be updated when I move on to working on the `ops` repo roles.
> Update to use OIDC session tokens on AWS role assumption

- internal/job/executor.go
- internal/job/plugin.go
In the docs, we say:
but then in job logs, we say:
also, `local` and `global` as names are pretty meaningless. `agent` and `repository` are much clearer, so this PR updates the the hook scopes to be formally named `agent` and `repository`.
There's a wee punchout for the datadog tracing implementation, which expects hook scopes to be called the old names in span attributes, so we've retained them there and there only.
**Before:**
**After**
https://buildkite-corp.slack.com/archives/C07LSRYCPSR/p1752753127654479
> Rename local -> repository hooks, global -> agent hooks

- .buildkite/pipeline.yml
- .buildkite/steps/check-code-committed.sh
Make the linter findings more obvious by putting them in an annotation.
https://github.com/buildkite/agent/pull/3399#pullrequestreview-3031410174
- Mount `buildkite-agent` into the linter container
- Capture the linter output and pass it to `buildkite-agent annotate`
> Annotate with lint findings

- agent/agent_worker_test.go
- clicommand/agent_start.go
- clicommand/agent_start_test.go
- core/client.go
When a Job fails to be Acquired, if that Job is locked due to dependencies then retry for a short time. If this wait continues for too long, exit with a unique code that will allow a scheduler to take specific behaviour for that scenario. There will be another webhook once the Job has moved back to Scheduled so the Job won't be lost.
At present a scheduler is given no indication on whether the failed acquisition was for any particular purpose, and in this scenario where the job is locked the behaviour can be better handled with a new code.
- Exit with a unique code (`28`) when the Job being Acquired is Locked.
- Pepper the error message generated with the Locked detail to surface this in the Job log.
- Add test cases to handle the expected error codes for different Job statuses.
> Exit with a specific code when the Job being Acquired is Locked

- .buildkite/pipeline.yml
Reduce the number of steps that run if no Go code (or their non-code dependencies) has changed.
Dogfood `if_changed` support
- Group Tests and Coverage
- Make Lint step only run if code or the script that runs it has changed
- Make Tests and Coverage group only run if code or related scripts changed
Pipeline change only - but particularly, these are _not_ run because the code didn't change!
- ~~[] Tests have run locally (with `go test ./...`). Buildkite employees may check this if the pipeline has run automatically.~~ 
- ~~[] Code is formatted (with `go fmt ./...`)~~
> Only run tests if code has changed

- agent/integration/job_verification_integration_test.go
- agent/verify_job.go
- go.mod
- go.sum
Upgrade a dependency.
I changed go-pipeline to have a slightly better step verification API.
- `go get github.com/buildkite/go-pipeline@v0.15.0`
- `go mod tidy`
- Fix the code so that it uses the new `VerifyStep` function
- Fix the tests the same way
> Upgrade to go-pipeline v0.15.0

- .buildkite/pipeline.release-experimental.yml
- .buildkite/pipeline.release-stable.yml
- .buildkite/pipeline.release-unstable.yml
Roll out using session tags for OIDC assumable IAM role trust policy. 
Follow on from the work to support session tags in https://github.com/buildkite-plugins/aws-assume-role-with-web-identity-buildkite-plugin/pull/18
Requires matching update to the IAM role in PR: https://github.com/buildkite/aws-buildkite-dev/pull/474
https://linear.app/buildkite/issue/PLT-4154/update-oidc-assumable-roles-to-use-session-tokens 
This is only changing the one pipeline, which uses an IAM role in `buildkite-dev` account. Additional pipelines defined in this repo will be updated when I move on to working on the `ops` repo roles.
> Update to use OIDC session tags on AWS role assumption

- agent/pipeline_uploader.go
Fixes https://github.com/buildkite/agent/issues/3418
> Make the 'Pipeline upload not yet applied: processing' message info, not warning

- go.mod
- go.sum
- internal/artifact/uploader.go
- internal/artifact/uploader_test.go
- internal/experiments/experiments.go
Promote `use-zzglob` to default.
Well it's about time.
- Mark `use-zzglob` as promoted
- Remove the old zglob library.
- Remove doubled tests.
> Promote use-zzglob experiment

- .github/pull_request_template.md
- CONTRIBUTING.md
For various reasons, we'd like to know when AI tools contribute to contributions. 
Inspired by https://github.com/ghostty-org/ghostty/pull/8289
- Adds a Disclosures / Credits section to the PR template
- ~~[ ] Tests have run locally (with `go test ./...`). Buildkite employees may check this if the pipeline has run automatically.~~ N/A
- ~~[ ] Code is formatted (with `go fmt ./...`)~~ N/A
I wrote all this myself, but was inspired by the new Ghostty policy to kick this off.
> Add disclosures/credits to PR template

- clicommand/bootstrap.go
One piece of information that the Buildkite Agent reports about the jobs it runs is what signal was used to terminate them, if any. However, under POSIX, the wait status of a process (as reported by [the `wait` syscall](https://www.man7.org/linux/man-pages/man2/wait.2.html)) only reports the terminating signal of a process if that signal is unhandled -- ie, if it's not captured by `trap`, `signal.Notify` and friends.
The bootstrap process does catch signals using `signal.Notify` so as to gracefully shut down jobs, but it still needs to report the signal that terminated it, so it does a little bit of sorcery to pull this off. When the bootstrap process recieves a signal, it:
- Catches the signal using `signal.Notify`
- Gracefully terminates the job process
- Shuts down its signal notifier …
> Ensure that bootstrap waits for its self-signal to propagate before exiting

- .buildkite/Dockerfile-compile
Revert to 1.24 series of Go versions for the builder container.
Until we're ready to make a conscious decision to bump to Go 1.25, we should continue using Go 1.24 containers to stop us accidentally merging code that would be incompatible with Go 1.24 (e.g. that uses recently added stdlib functionality).
See description.
Thanks to `docker` for printing the `sha256` hash when pulling an image.
> Lower Go containers back to 1.24

- agent/job_runner.go
- internal/experiments/experiments.go
Add an experiment that enables various agent config vars to be named in the env file.
Closes #3430
- Add a new experiment, `propagate-agent-config-vars`
- When the experiment is enabled, write an extra preamble to the env file, consisting of various env var names that could be usefully propagated.
I did not use AI tools at all. I copied the list of env vars from #3430.
> Experiment for propagating agent config env vars

- .github/dependabot.yml
Make dependabot raise two separate PRs for container updates:
- Updates to containers that we release
- Updates to containers needed for builds, tests, etc.
It'd be great to easily hold back the Go container version, but doing it all in one PR means editing the PR instead of telling Dependabot to back off. e.g. https://github.com/buildkite/agent/pull/3476
Divide the dependabot configuration for Docker into two.
- N/A ~~[ ] Tests have run locally (with `go test ./...`). Buildkite employees may check this if the pipeline has run automatically.~~
- N/A ~~[ ] Code is formatted (with `go fmt ./...`)~~
I did not use AI tools at all
> Split Dependabot container updates

- go.mod
- go.sum
We previously relied on a dependency, [`shellwords`](https://github.com/buildkite/shellwords), that required that the Agent to be on a very specific version of Go (1.24.3). In Shellwords [v1.0.1](https://github.com/buildkite/shellwords/releases/tag/v1.0.1), we relaxed this requirement to 1.24, so we should continue up the stream and make the agent as a go module a little more usable
> Note that in general, we don't recommend that people use the agent as a go module, and don't consider it to be versioned at all. However, people are going to be doing it anyway, and we should endeavour to not make their lives needlessly difficult.
This PR also adds a `toolchain` directive to the `go.mod`, which will do the work of actually selecting a go version to run commands like `go test` etc, where that …
> Update shellwords to v1.0.1, relax Go version directive

- clicommand/pipeline_upload.go
When reviewing this [document](https://buildkite.com/docs/agent/v3/cli-pipeline#apply-if-changed) the minimum agent version required is not displayed 
Users may get errors when trying to use the `--apply-if-changed` flag until they notice it is required to have their agent be on at least `v3.99` as described [ here](https://buildkite.com/docs/pipelines/configure/step-types/command-step#agent-applied-attributes)
Added minimum agent version required information for `--apply-if-changed` flag as this will help users with older than  v3.99 version quickly identify and upgrade to the minimum version required for their agent before they can use this flag
> Update apply-if-changed information with agent minimum version

- agent/plugin/plugin.go
- internal/job/integration/plugin_integration_test.go
- internal/job/plugin.go
Currently it's not possible to specify subdirectories of Plugins to be used, meaning it's not possible for an user to have a monorepo with multiple Plugins inside and use them by referencing the subdirectory in e.g.,
```yml
- label: "subdir plugin with .git"
command: exit 0
plugins:
- ssh://git@github.com/tomowatt/test-plugin.git/subdir: ~
```
Adds functionality to allow the Agent to clone Plugin repositories that specify a sub directory in their URL and then update the Plugin Dir and Hook paths so that the hooks from the sub directories can be used instead of those at root i.e., `./hooks`
Testing Pipeline with Test Plugin Repository, testing out the following:
* `.git` suffix on repositories
* multiple plugins at same level
* plugin deeper within directories
```yml
env: …
```
> Ability to checkout subdirectories of Plugins
