- templates/bootstrap.sh
> Bootstrap Upgrades

- buildkite/s3_uploader.go
Basically we just need to use the aws.GetAuth method, and not do our own thing.
> Fix to re-allow S3 auth using IAM credentials

- templates/launchd.plist
- templates/launchd_local_with_gui.plist
Using this for my own needs (so i can autoupdate the beta agent via boxen), close if you don't need/want it :)
> Use Buildkite beta agent for plist templates

- templates/bootstrap.sh
> Remove support for Fig

- scripts/utils/build-linux-package.sh
- templates/linux-package/docker-cleanup.sh
This adds a cleanup script for Docker which people can use to keep their builds snappy and disk space under control
> Add a docker cleanup script to the linux packages

- buildkite/configuration.go
- command/agent_start.go
For: https://github.com/buildkite/agent/issues/144
> Try to find a config file automatically

- buildkite/artifact.go
- buildkite/client.go
- buildkite/ec2_tags.go
- buildkite/job.go
- buildkite/s3_uploader.go
- buildkite/script.go
- buildkite/version.go
- command/agent_start.go
- commands.go
@keithpitt is there a method for setting the bucket name for automatic step-uploaded artifacts?
> Update custom S3 artifact upload usage docs

- templates/bootstrap.sh
This would help me to respond to successful artifact uploads, particularly with deployment.
> Added post-artifact hooks

- agent/artifact_uploader.go
- api/artifacts.go
> Upload artifact states in batches as artifacts are uploading.

- templates/bootstrap.sh
> Handle repository URL updates

- templates/bootstrap.bat
> Add Github pull request testing to Windows

- agent/agent_configuration.go
- agent/agent_pool.go
- agent/bootstrap.go
- agent/job_runner.go
- agent/plugin.go
- agent/plugin_test.go
- clicommand/agent_start.go
- clicommand/bootstrap.go
- shell/environment.go
- shell/environment_test.go
Initial cut of a plugin implementation for the agent. Still very much a WIP.
> Added experimental support for plugins

- agent/s3_downloader.go
- agent/s3_uploader.go
See http://stackoverflow.com/questions/29187086/why-trimleft-doesnt-work-as-expected
Fixes #202 
NOT TESTED (by me)
> Use TrimPrefix instead of TrimLeft

- templates/launchd.plist
- templates/launchd_local_with_gui.plist
Should match dir structure created by https://raw.githubusercontent.com/buildkite/agent/master/install.sh
> Update launchd templates to use .buildkite-agent dir

- README.md
Not much more to say, really :-)
> Link to docker agent 404'd

- agent/bootstrap.go
- shell/environment.go
- shell/environment_test.go
> Apply bootstrap config changes after hooks

- packaging/linux/scripts/after-install-and-upgrade.sh
Amazon Linux has broken upstart which doesn't gracefully terminate the agent, so fall back to using the sysv script instead on any amazon linux system.
Closes #234, #242.
/cc @lox
> Avoid upstart on Amazon Linux

- agent/bootstrap.go
- clicommand/bootstrap.go
- templates/bootstrap.sh
This applies the tweaks from #243 on master to both the bootstrap script and the go boostrap. It also includes custom refspecs from #237 which are related.
Here are some examples:
/cc @keithpitt
> Bootstrap tweaks (on master)

- agent/agent_pool.go
- agent/job_runner.go
- agent/log_streamer.go
- api/chunks.go
This means we'll be able to experiment with sparse log storage.
> Send log chunk offset and size

- agent/agent_pool.go
- agent/agent_worker.go
- agent/api_client.go
- agent/artifact_batch_creator.go
- agent/artifact_uploader.go
- agent/download.go
- agent/job_runner.go
- clicommand/meta_data_exists.go
- clicommand/meta_data_get.go
- clicommand/meta_data_set.go
> Increased timeouts for 2.1 stable

- agent/s3_uploader.go
> Allow BUILDKITE_S3_ACCESS_URL to override S3 host URL

- install.sh
Mostly just changing legacy back-ticks and unquoted variable use.
Closes #227
> Clean up bashisms

- install.sh
> Bash lint install cleanups for 2.1

- agent/s3_uploader.go
> Make S3 URLs HTTPS by default

- agent/s3_uploader.go
> Make S3 URLs HTTPS by default for 2.1 stable

- templates/bootstrap.sh
> Move buildkite bin to end of path 2.1 stable

- templates/bootstrap.sh
> Git clean flags for 2.1 stable

- templates/bootstrap.sh
> Add BUILDKITE_DOCKER_COMPOSE_LEAVE_VOLUMES to 2.1 stable

- agent/header_times_streamer.go
If you have a header in build logs that looks like this:
```
\x1b[0m--- assets\r
```
Currently we'll ignore it because it's got a "clear the line of colors" character at the beginning. This change strips colors before we check to see if it's a header.
> Strip ANSI colors when checking to see if a line is a header

- templates/bootstrap.sh
> Fix BUILDKITE_DOCKER_COMPOSE_LEAVE_VOLUMES 2.1 stable

- templates/bootstrap.sh
Backports to #285 to 2.1 stable
> Backport only building the docker compose container

- templates/bootstrap.sh
Ports the bootstrap changes from #300 to master
> Add docker compose 1.7 support

- templates/bootstrap.sh
A nice catch by @npaufler
We should consider adding -u as well
> Add pipefail to generated scripts

- packaging/linux/root/usr/share/buildkite-agent/lsb/buildkite-agent.sh
Fix .pid and lock file handling
> CentOS-6/Amazon Linux initscript

- packaging/linux/root/usr/share/buildkite-agent/lsb/buildkite-agent.sh
- packaging/linux/scripts/after-install-and-upgrade.sh
- packaging/linux/scripts/after-remove.sh
- packaging/linux/scripts/before-remove.sh
Ports #290 and #305 to master.
Can I get a review please @jnewbigin?
> Port Amazon/CentOS 6 fixes to master

- packaging/github/linux/buildkite-agent.cfg
- packaging/linux/root/usr/share/buildkite-agent/buildkite-agent.cfg
- scripts/utils/build-github-release.sh
- scripts/utils/build-linux-package.sh
A few things for #303 that weren't caught via tests
> Remove old bootstrap.sh references

- agent/bootstrap.go
Also renames folder -> directory for consistency
> Output the build directory in the log

- agent/bootstrap.go
Until we have #315 we shouldn't be outputting the secrets…
> Don't show env key values

- agent/agent_pool.go
- agent/ec2_meta_data.go
- clicommand/agent_start.go
- packaging/github/linux/buildkite-agent.cfg
- packaging/linux/root/usr/share/buildkite-agent/buildkite-agent.cfg
> Backport --meta-data-ec2 to 2.1

- agent/agent_configuration.go
- agent/job_runner.go
- clicommand/agent_start.go
- templates/bootstrap.sh
> Add BUILDKITE_GIT_CLONE_FLAGS

- agent/agent_configuration.go
- agent/bootstrap.go
- agent/job_runner.go
- clicommand/agent_start.go
- clicommand/bootstrap.go
- packaging/github/linux/buildkite-agent.cfg
- packaging/github/windows/buildkite-agent.cfg
- packaging/linux/root/usr/share/buildkite-agent/buildkite-agent.cfg
- vendor/github.com/flynn-archive/go-shlex/COPYING
- vendor/github.com/flynn-archive/go-shlex/Makefile
- vendor/github.com/flynn-archive/go-shlex/README.md
- vendor/github.com/flynn-archive/go-shlex/shlex.go
- vendor/github.com/flynn-archive/go-shlex/shlex_test.go
`git-clone-flags` and `git-clean-flags` can now also be configured in the `.conf` file
> Added `GitCloneFlags` support to the Golang version of Bootstrap

- agent/bootstrap.go
> Revert "Commit fetch means we can checkout fetch head"

- clicommand/pipeline_upload.go
We need to translate relative paths like this for use on Windows. This should fix #328.
> Use correct slashes on Windows

- agent/bootstrap.go
- shell/process.go
Fixes https://github.com/buildkite/agent/issues/228
> Fix handling of relative paths in `buildkite-agent bootstrap`

- clicommand/agent_start.go
> Add env vars for ec2 config options (2.1.x)

- agent/api_client.go
This will hopefully make the agent api interactions even faster! The agent endpoint should soon have http2-aware layer 7 load balancing.
> Enable http2 for Agent API

- agent/agent_pool.go
- agent/job_runner.go
- api/agents.go
> Get the job status interval from the Agents API

- process/process.go
We have a potential race condition when uploading header times to BK. I believe the follow backtrace is saying: "You tried to call .Add() on a wait group that is already waiting".
Looking a the stack trace `[HeaderTimesStreamer] Waiting for all the lines to be scanned` is called, then another header time is found, so I believe the line callbacks are still being fired even after the process has finished.
This change ensures that all the line callbacks have fired before finishing the process. Even if the line callback in itself fires off another go-routine that's ok, because that code usually has it's own waiters setup.
```
Nov 24 23:42:31 buildkite-agent-b06ec88b buildkite-agent: 2016-11-24 23:42:31 DEBUG  [LineScanner] Encountered EOF
Nov 24 23:42:31 buildkite-agent-b06ec88b …
```
> Wait for line callbacks to finish before finishing process

- process/process.go
Backporting the fix from #413 to the 2.3.x stable
> Backport #413

- agent/bootstrap.go
Coincidentally, my first go code!
Resolves #417
> Git clean before and after checkout

- templates/bootstrap.sh
This is a 2.1 backport of #448
> Use /bin/sh instead of /bin/bash (2.1 stable)

- templates/bootstrap.sh
> Use /bin/sh instead of /bin/bash

- agent/bootstrap.go
> Revert "Use /bin/sh instead of /bin/bash"

- .buildkite/pipeline.yml
- proctitle/proctitle.go
As requested by @derekmarcotte, this adds OpenBSD builds.
> Add OpenBSD builds

- agent/agent_pool.go
- retry/retry.go
> Backport #301: Retries for grabbing EC2 metadata

- .buildkite/pipeline.yml
- proctitle/proctitle.go
Similar to #462, this adds DragonflyBSD arch support for @derekmarcotte
> Add DragonflyBSD

- packaging/linux/root/usr/share/buildkite-agent/hooks/post-artifact.sample
- packaging/linux/root/usr/share/buildkite-agent/hooks/pre-artifact.sample
- packaging/linux/root/usr/share/buildkite-agent/hooks/pre-exit.sample
- templates/bootstrap.sh
> Backport pre-exit hook support to 2.6

- bootstrap/bootstrap.go
> Show the file it tried to find when sowing the no-command-eval error message.

- agent/agent_pool.go
- agent/agent_worker.go
- agent/api_client.go
- agent/log_streamer.go
- agent/plugin_test.go
- clicommand/agent_start.go
- clicommand/global.go
- cliconfig/loader.go
- retry/retry.go
Looks like some things are out of whack!
> Apply `govendor fmt +l` to current source tree

- agent/agent_pool.go
- agent/job_runner.go
Currently you can get into a situation where you have to kill -9 the worker process.
> Ctrl-c twice will force kill the agent

- agent/agent_configuration.go
- agent/header_times_streamer.go
- agent/job_runner.go
- clicommand/agent_start.go
- process/process.go
Port #430 and #438 to master. 
Originally from https://github.com/buildkite/feedback/issues/80
> Port timestamp lines from stable

- agent/s3_downloader.go
This fixes a bug where a path in BUILDKITE_ARTIFACT_UPLOAD_DESTINATION caused an error.
> Support paths in BUILDKITE_ARTIFACT_UPLOAD_DESTINATION

- bootstrap/bootstrap.go
- bootstrap/knownhosts.go
- bootstrap/knownhosts_test.go
- bootstrap/lock.go
- bootstrap/lock_test.go
I'm trying to pull apart the bootstrap package into some smaller pieces and add some tests. This is the first chunk. It's possible that this is just me applying my "style" of golang, so keen on feedback, even if it's "hmm, it was simpler before".
What's changed in this is:
* I've extracted the lock acquiring code and used the new context.Context stuff to make it testable
* Extracted the ssh known_hosts handling into a struct and it's own file
> Refactor bootstrap into knownhosts.go and locks.go

- bootstrap/knownhosts.go
My previous PR #514 broke the running of ssh-keyscan, as it used exec.Command, which returns an error object with the exit status in it.
> Fix bug where ssh-keygen error causes agent to block

- bootstrap/bootstrap.go
- bootstrap/docker.go
- bootstrap/integration/bootstrap_tester.go
- bootstrap/integration/docker_integration_test.go
- bootstrap/shell/shell.go
- env/environment.go
- env/environment_test.go
- process/format.go
- process/process.go
This adds support for everything in https://buildkite.com/docs/builds/docker-containerized-builds, but also displays warnings.
> Support docker environment vars from v2

- bootstrap/bootstrap.go
- bootstrap/docker.go
- bootstrap/hook_test.go
- bootstrap/integration/bootstrap_tester.go
- bootstrap/integration/git.go
- bootstrap/integration/hooks_integration_test.go
- bootstrap/integration/plugin_integration_test.go
- bootstrap/shell/shell.go
Adds a basic plugin test (so hard to test) and some testing for hooks. 
Also fixes the bug with environment not getting to git clone that we saw the other day.
> Add tests for plugins and fix env related bugs

- agent/artifact_uploader_test.go
- agent/gs_uploader_test.go
- agent/plugin_test.go
- agent/s3_downloader_test.go
- bootstrap/bootstrap_test.go
- bootstrap/config_test.go
- bootstrap/hook_test.go
- bootstrap/integration/artifact_integration_test.go
- bootstrap/integration/checkout_integration_test.go
- bootstrap/integration/hooks_integration_test.go
- bootstrap/integration/plugin_integration_test.go
- bootstrap/knownhosts_test.go
- env/environment.go
- env/environment_test.go
- env/interpolator_test.go
Mark most of our tests as able to be run in parallel for speed.
> Run tests in parallel

- agent/pipeline_parser.go
- agent/pipeline_parser_test.go
- env/environment.go
- env/interpolator.go
- env/interpolator_test.go
This removes another spot where we rely on system environment variables. Makes testing lots easier.
> Make Interpolate a method of Environment

- agent/pipeline_parser.go
- agent/pipeline_parser_test.go
A quick implementation of #544
> Interpolate env block first

- bootstrap/bootstrap.go
I started looking at how to modify the logic around checking out plugin versions. As part of that I've created a `pluginCheckout` that the bootstrap keeps to track the directory that it checks out `agent.Plugin`'s to.
> Move plugin logic in bootstrap to a pluginCheckout object

- process/process.go
> Fallback to task kill on windows

- bootstrap/bootstrap.go
- bootstrap/git.go
- bootstrap/integration/bootstrap_tester.go
- bootstrap/integration/checkout_integration_test.go
> Remove corrupted previous checkouts (port to master)

- agent/artifact_uploader.go
- agent/artifact_uploader_test.go
> Fix a regression where artifact uploader returns error on no match

- bootstrap/bootstrap.go
There are several situations in which checkouts can be flakey, sometimes it's a overloaded central server and sometimes it's something like XCode being slow to release file locks (causing git clean to fail). 
This adds a generalized exponential backoff on checkouts. It is off by default.
> Add a config option to retry checkouts

- Gemfile.lock
This doesn't affect us as far as I can tell, but better safe than sorry?!
> Bundle update for nokogiri CVE 2017-9050

- scripts/utils/publish-debian-package.sh
Looks like the recent bundle update pulled in a new version of deb-s3 which needs different parsing of bucket names and prefixes.
> Update deb publish script for new version of deb-s3

- bootstrap/shell/shell.go
> shell.Run captures stderr, RunAndCapture doesn't

- bootstrap/bootstrap.go
- bootstrap/integration/plugin_integration_test.go
> Bootstrap shouldn't panic if plugin checkout fails

- agent/agent_configuration.go
- agent/agent_pool.go
- agent/job_runner.go
- bootstrap/bootstrap.go
- bootstrap/config.go
- bootstrap/integration/checkout_integration_test.go
- clicommand/agent_start.go
- clicommand/bootstrap.go
> Rename no-automatic-ssh-fingerprint-verification to no-ssh-keyscan

- bootstrap/bootstrap.go
- bootstrap/integration/checkout_integration_test.go
@keithpitt finally convinced me that we should be doing checkout retries by default. 
Closes #477.
> Retry failed checkouts

- agent/artifact_downloader.go
> Exit when artifacts can't be found for downloading

- bootstrap/bootstrap.go
Fixes https://github.com/buildkite/agent/issues/656
> Don't bother looking for powershell hooks since we don't support them yet

- bootstrap/bootstrap.go
Fixes https://github.com/buildkite/agent/issues/591
> Fail the job when no command is provided in the default command phase

- bootstrap/integration/checkout_integration_test.go
- bootstrap/ssh.go
- bootstrap/ssh_test.go
> Retry ssh-keyscans on error or blank output

- bootstrap/bootstrap.go
- bootstrap/git.go
> Show plugin commit if it's already installed

- agent/plugin.go
Fixes https://github.com/buildkite/agent/issues/689
> Support plugins that have a `null` config

- scripts/build-docker-images.sh
- scripts/publish-docker-images.sh
- scripts/publish-rpm-package.sh
- scripts/upload-release-steps.sh
Pass the prebuilt docker image via metadata and into triggered builds.
> Use meta data for docker build image name

- scripts/publish-docker-images.sh
> Fix undefined $DOCKER_PULL

- .buildkite/pipeline.yml
- scripts/build-docker-images.sh
- scripts/extract-agent-version-metadata.sh
- scripts/publish-docker-images.sh
- scripts/upload-release-steps.sh
This is take 3 on #703 and #705.
> Fix docker release script

- bootstrap/bootstrap.go
- bootstrap/shell/shell.go
Lots of cleanup on messages for debug and non-debug mode.
> Prettier bootstrap output 💅🏻

- bootstrap/hook_test.go
- bootstrap/integration/checkout_integration_test.go
- bootstrap/ssh.go
- bootstrap/ssh_test.go
- utils/path_test.go
Fix some minor failing windows tests. This should get them back to green.
> Fix failing windows tests

- proctitle/proctitle.go
Cannot build on linux ppc64le, and wish to.  Seems to work fine with this.
> Added linux,ppc64le as valid build target.

- stdin/main_test.go
- stdin/stdin.go
Closes https://github.com/buildkite/agent/issues/735.
> Fix stdin detection for output redirection

- agent/job_runner.go
When we run a job we start two background goroutines — one polling for new logs to upload, and the other polling the job status to see if a job is cancelled during execution. They sleep in between polling. The job status sleep interval is set by buildkite.com through the agent api, and starts at 5 seconds increasing to 30 seconds when there are many agents connected. So these goroutines may sleep for up to 30 seconds.
When a job finishes, we tell the Buildkite agent api that the job is finished, then we wait for these background goroutines to exit. In the meantime, the Buildkite agent api might notice we're no longer running a job — we finished it — and assign us new work to do, but we're still waiting on those goroutines to finish for up to 30 seconds.
This change creates a context to …
> Avoid pausing after job has finished

- process/process.go
The bufio.Reader is a low-level primitive, and it should be a bufio.Scanner. 
Originally part of https://github.com/buildkite/agent/pull/599.
> Replace process.Process's bufio.Reader with a bufio.Scanner

- clicommand/pipeline_upload.go
This is a follow on of https://github.com/buildkite/agent/pull/765. 
It adds a `buildkite-agent pipeline upload --dry-run` command that outputs the pretty-printed pipeline json rather than uploading it. This works locally with no configuration required.
> Add a --dry-run to pipeline upload that dumps json

- vendor/github.com/kr/pty/ztypes_openbsd_386.go
- vendor/vendor.json
Fixes new breakage in https://github.com/buildkite/agent/pull/785
> Added OpenBSD 386 support.

- agent/agent_worker.go
Often when there are network issues it's hard to tell from the agent non-debug output whether failed pings and heartbeats are intermittent or consistent. 
This adds an atomic timestamp that tracks the last successful hb / ping, which is included in errors. This makes it possible to figure out if any requests are making it through or if there is a complete network outage.
> Add time since last successful heartbeat/ping

- bootstrap/shell/logger.go
- packaging/github/linux/buildkite-agent.cfg
- packaging/github/windows/buildkite-agent.cfg
- packaging/linux/root/usr/share/buildkite-agent/buildkite-agent.cfg
Fixes a typo (_boostrap_ to _bootstrap_).
> Fix boostrap typo

- process/process.go
- process/process_test.go
Introduced a bug in #856 due to a bad merge, this fixes the issue and adds tests.
> Add tests around gracefully killing processes

- agent/log_streamer.go
The offset and size of a new chunk are incorrect.
> Fix bug where a new chunk is created

- process/process_test.go
Hopefully prevent this test being flakey.
> Avoid race conditions in process test

- install.sh
> ppc64le option added to install.sh

- logger/init_windows.go
- logger/log.go
> Support log output colors on newer windows

- agent/artifact_uploader.go
- clicommand/agent_start.go
> Add a missing logger that was causing a segfault

- agent/artifact_downloader.go
- agent/artifact_downloader_test.go
Found another one, added some tests to cover this area of the code superficially.
> Fix and test another seg fault in the artifact searcher

- agent/job_runner.go
> Ensure BUILDKITE_AGENT_TOKEN doesn't appear in job env

- bootstrap/bootstrap.go
After thinking about #866 a bit more, this fix ensures that the checkout directory really was removed. It retries deletion several times to try and work around various windows issues.
> Make sure checkout is removed on failure

- agent/job_runner.go
- process/process.go
- process/process_test.go
For a while I've been working on making `process.Process` a general process runner that can be used for executing `bootstrap`, but also inside `bootstrap/shell`. 
This extracts the last two bits. Process now runs with just the `env` that it's given and it takes a `io.Writer` for output. The line scanning behaviour is inside `process.Scanner`, which can be wired into `process.Process` with an `io.Pipe`.
> Extract env and handler from process.Process

- agent/job_runner.go
- clicommand/bootstrap.go
- experiments/experiments.go
This allows for experiments to be used in the bootstrap.
> Pass experiment environment vars to bootstrap

- clicommand/bootstrap.go
> Actually enable experiments in the bootstrap command

- agent/job_runner.go
If an agent goes away and the job its running is reaped and we archive away the logs and header times, allow the agent api to reject header times from the agent which will never succeed.
This is the same logic from chunks upload.
> Allow the Agent API to reject header times

- .buildkite/pipeline.yml
- .buildkite/steps/tests.sh
An experiment with junit output and annotations for the agent builds.
> Use gotestsum and the junit annotation plugin

- .buildkite/pipeline.bk-test.yml
- .buildkite/pipeline.yml
- .buildkite/steps/test-bk.sh
This adds a final test of the agent with `bk` and a local pipeline that exercises all the main commands of the agent and checks an end-to-end test works.
> Check the agent works with bk cli

- agent/agent_worker.go
We introduced a bug in #971 where the heartbeats would stop when the agent received a signal. Instead, heartbeats should run until the agent stops, otherwise it will be marked as lost at the 5 minute mark.
> Ensure heartbeats run until agent is stopped

- agent/agent_worker.go
Remove the unused AgentWorker.running flag.
> Remove the unused running flag

- agent/agent_pool.go
Pull request #998 stopped listening for signals correctly as the signal channel was closed immediately. 🤦🏼‍♂️
This has been broken since v3.11.3 (also v3.11.4) from the looks of it, which means those versions will be terminating immediately vs correctly gracefully shutting down in those versions.
> Fix broken signal handling

- agent/agent_worker.go
Previously the agent ran a variety of timers to track our timeouts. This moves everything into the main run loop so that it's no longer concurrent, which makes the variety of race conditions that were possible now impossible. 
Closes #1006.
> Simplify how we handle idle timeouts

- agent/agent_pool.go
- clicommand/agent_start.go
This further thins the things the `agent.AgentPool` does  and moves signal handling out to the start command. 
I think this API boundary makes more sense, and it lets us in future handle other signals like `SIGHUP` different.
> Move signal handling out of AgentPool

- agent/arty_downloader_test.go
Looks like #1014 caused a test failure. 
@MartinRudzki can you confirm this change is correct?
> Fix failing artifactory downloader tests

- agent/form_uploader.go
We've had reports of out of memory errors when uploading artifacts (when not using a custom s3 bucket).
This fixes an issue where we were buffering the entire artifact into memory in the FormUploader.
> Fix memory leak in artifact uploading with FormUploader

- agent/artifact_downloader_test.go
- agent/form_uploader.go
- agent/form_uploader_test.go
Fixes https://github.com/buildkite/agent/issues/1043
> Fix buildkite-agent upload with absolute path

- agent/form_uploader.go
- agent/form_uploader_test.go
@lox I think this will solve the issue you mentioned in #1043 and adds test coverage for it.
> Fix artifact upload relative path

- agent/register.go
> Fix panic on incorrect token

- README.md
- main.go
> Updated `--help` output in the README and include more stuff in the "Development" section

- agent/job_runner.go
This fixes a leaking goroutine issue, which resulted in a memory leak.
> Fix goroutine leak after job finishes

- clicommand/artifact_download.go
- clicommand/artifact_shasum.go
- experiments/experiments.go
> Less pats, more parts

- agent/artifact_downloader.go
Currently, a file uploaded on a windows agent named `my\folder\blah.txt` will be downloaded on a UNIX agent as the literal file of the same name vs the folders and file structure implied. 
This is the minimal change to fix that. It preserves the file separator that the file is uploaded with and just normalizes it on non-windows hosts on download. 
Closes #354.
> Convert windows paths to unix ones on artifact download

- .buildkite/Dockerfile-github-release
- .buildkite/Dockerfile-windows
Signed-off-by: Daniel Sutton <daniel@ducksecops.uk>
> bump to alpine and servercore

- bootstrap/bootstrap.go
The agent [ignores multiple checkout and command hooks](https://buildkite.com/docs/agent/v3/hooks#available-hooks), and in #1055 we extended that to plugins as well for consistency (the previous behaviour was undefined).
This extends the previous PR to add the same check for the `checkout` hook, and adds a warning message for any people that might have been using the now-unsupported behaviour.
> Ignore multiple checkout plugin hooks

- agent/artifact_uploader.go
Fixes a couple spelling mistakes
> Fix spelling errors in artifact_uploader.go

- agent/form_uploader.go
This completes the implementation of the `DebugHTTP` option, which we describe as "dumps all request and response bodies to the log".
It previously did not dump request bodies made by the form_uploader, only their responses.
Implementation borrowed from `api/client`, which already handled this similarly.
> agent/form_uploader: Implement HTTP Request debug

- bootstrap/bootstrap.go
- bootstrap/integration/plugin_integration_test.go
Summary: This PR rolls back some changes released over the past few months regarding whether multiple checkout and command plugin hooks will run or be skipped. As a result of this PR, if multiple plugins had checkout or command hooks, they would all run. But as always, if any plugin has one of those hook types, the corresponding repo-local / agent-global and bootstrap-builtin hook would not run.
----
Hooks are documented here: https://buildkite.com/docs/agent/v3/hooks#available-hooks
Historically (since the beginning? maybe some adjustments to ordering) the agent has partially avoided running multiple `checkout` and `command` hooks by doing the following;
- If there are _any_ plugins with a `checkout` hook, run all plugin `checkout` hooks,
- else, if there's a global (agent) `checkout` …
> RFC: rollback changes preventing multiple checkout/command plugin hooks

- agent/artifact_searcher.go
This will have the agent retry 502 errors during artifact search, which should make it more resilient to upstream faults.
> Add a retry for errors during artifact search

- agent/agent_worker.go
While doing some testing I ran into a few instances where no-prior-ping and no-prior-heartbeat states would emit a confusing message. This updates these instances with a "No heartbeat/ping yet" message, and ensures they're all using durations ("Failed to ping" was emitting "{the last ping time} ago")
> Improve some outputs for error timers

- .buildkite/steps/publish-rpm-package.sh
Follow on from #1241 
To enable public edge release testing for Red Hat ARM packages (see #1162) I've updated the publish-rpm-packages script to publish `aarch64` too. Abiding by the campfire principle I did a small amount of tidying too.
> Experimental: Publish RPM package for aarch64

- clicommand/artifact_shasum.go
This is to accompany a larger change to the docs in https://github.com/buildkite/docs/pull/746.
> Reword artifact shasum documentation

- agent/form_uploader.go
We get occasional reports of slow and/or failed S3 uploads. One possibility is that there's networking issues between the agent and us-east-1 (where the default buildkite-managed artifacts bucket lives).
The IP address for s3.amazonaws.com rotates every 5 seconds, so from upload to upload it's impossible for us to guess the server IP that was used after the fact. This will output a log line for each upload (when `BUILDKITE_AGENT_DEBUG_HTTP=true`) with the exact server IP address that was used.
If we see upload issues in the future that sound like a networking issue, at least we'll an address to debug with.
the log output looks like this:
```
2020-07-23 21:21:56 DEBUG  artifact 8d67fb1c-83c6-4006-8a3b-17c438918197 uploading to: 52.216.237.165:443
```
> log the S3 IP used during artifact uploads

- agent/artifact_uploader.go
- agent/artifact_uploader_test.go
If a path is specified twice, either directly or via globs with overlapping results, deduplicate them.
This prevents multiple uploads of the same files, which is otherwise inefficient and can results in difficulty downloading:
400 Multiple artifacts were found for query: `...`. Try scoping by the job ID or name.
This closes #803 where multiple paths are specified as part of a single upload.
It does not attempt to resolve cases where separate uploads throughout a build upload to the same path.
Note that when a build YAML step lists multiple `artifact_paths`, they are joined together with `;` before being placed into `BUILDKITE_ARTIFACT_PATHS` of the job environment, and so they're evaluated as a single `buildkite-agent artifact upload`.
> ArtifactUploader: deduplicate upload file paths

- EXPERIMENTS.md
- bootstrap/bootstrap.go
- bootstrap/integration/checkout_integration_test.go
Adds the same gear in https://github.com/buildkite/agent/pull/871 into the bootstrap under an experiment to address issue https://github.com/buildkite/agent/issues/1188
> Commit after checkout experiment

- agent/artifact_uploader_test.go
There was a bug in the artifact_uploader_test  test code only, which caused it to fail in some windows scenarios.
The test was deriving the codebase root directory in a way that used OS-native path separators (back-slashes on Windows), and then forward-slashed components were added to the end.
This would not have been noticed if the codebase was in a top-level directory like `C:\buildkite-agent`.
I imagine it crept in during #1211 /cc @ticky 
Previously:
C:\pda\agent>go test ./agent -run TestCollect
--- FAIL: TestCollect (0.01s)
artifact_uploader_test.go:31: C:\pda\agent\agent
--- FAIL: TestCollect/Smile.gif#01 (0.00s)
artifact_uploader_test.go:140:
Error Trace:    artifact_uploader_test.go:140
Error:          Not equal:
expected: "pda\\agent/test/fixtures/artifacts/gifs/Smile.gif"
actual …
> artifact_uploader_test fixed for Windows.

- clicommand/agent_start.go
- clicommand/agent_start_test.go
#1275 introduced an agent-wide `shutdown` hook, with iterations in #1322 and #1326. Those pull requests are merged, but not yet released.
This pull request renamed the hook from `shutdown` to `agent-shutdown`, making it clear that it's different to existing job/bootstrap hooks, and setting a precedent for any future agent-level hooks (e.g. #1057).
/cc @goodspark
> Rename (not yet released) shutdown hook to agent-shutdown.

- bootstrap/bootstrap.go
- bootstrap/integration/checkout_integration_test.go
- bootstrap/integration/git.go
Duplicating this PR so that we can run CI for #1308; tests, please ignore
> (CI Run For) Use normal fetch commands for mirror

- bootstrap/bootstrap.go
- bootstrap/integration/checkout_integration_test.go
- bootstrap/integration/git.go
Build is failing, reverts buildkite/agent#1308 first, then fix it later.
cc @ticky
> Revert "Handle pull requests with git-mirrors"

- CHANGELOG.md
- agent/version.go
* Update changelog
* Bump version number
> prepare to release 3.26.0

- bootstrap/bootstrap.go
- bootstrap/integration/checkout_integration_test.go
- bootstrap/integration/git.go
Reverts buildkite/agent#1344, restoring #1308
> Restore "Handle pull requests with git-mirrors"

- agent/s3.go
This adds support for the WebIdentityRoleProvider for S3 uploads.
Currently the buildkite-agent artifact upload code doesn't support using the new AWS IAM Roles for Service Accounts (IRSA) feature. When running the Buildkite agent in a container on EKS the current behavior is to look for custom credentials, environment variables, and EC2 Role / Metadata.
This PR adds the WebIdentityRoleProvider which is used by IRSA to take preference over the EC2 Role / Metadata credentials
> Add support for Web Identity Role Provider

- README.md
- clicommand/agent_start.go
- clicommand/annotate.go
- clicommand/artifact_shasum.go
- clicommand/bootstrap.go
- clicommand/meta_data_exists.go
- clicommand/meta_data_get.go
- clicommand/meta_data_keys.go
- clicommand/meta_data_set.go
- clicommand/pipeline_upload.go
- clicommand/step_get.go
- clicommand/step_update.go
- main.go
As mentioned by one of our users there is a bit of a mix-match between using arguments and options through the agent.
Closes https://github.com/buildkite/agent/issues/1375
> Use options for consistency

- CHANGELOG.md
Sam Schlegel got the ball started on this (he's also on the initial commits), so feels right to credit him.
> Credit another for tracing feature

- CHANGELOG.md
Added a changelog for the forthcoming v3.29.0 release.
> Prepare for v3.29.0 release

- .buildkite/pipeline.yml
Prompted by the discussion in #1431
> add netbsd to the build matrix

- agent/job_runner.go
- api/jobs.go
Some discussed tweaks to #1434 to get it into tomorrow’s release.
> Send queue metrics to Datadog when job received

- clicommand/agent_start.go
This reverts PR #1440. As discussed in the comments of that PR we found it introduced a new issue and we'd like some more time to evaluate the best response without holding up releasing 3.30.0
> Revert "Merge pull request #1440 from buildkite/resolve-absolute-agent-path

- CHANGELOG.md
- agent/version.go
Update changelog and version number for 3.32.0.
> Release 3.32.0

- hook/scriptwrapper.go
Alternate to #1206 which doesn’t change the quote syntax.
> Add missing quote in PowerShell hook

- hook/scriptwrapper.go
I thought I could get away with just the quote change in https://github.com/buildkite/agent/pull/1494 but missed the newlines were literals rather than interpreted. Maybe I should have just merged #1206 😅
> Add actual newlines not literal \n's to the strings

- .buildkite/pipeline.yml
- .buildkite/steps/tests.sh
> Run linux tests on amd64 and arm64

- CHANGELOG.md
- agent/version.go
Third (/fourth) time is the charm.
> Bump changelog and version for v3.33.3

- bootstrap/bootstrap.go
- bootstrap/integration/plugin_integration_test.go
Add option to retry on clone steps #1198
> Add retry option on clone step for plugins

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
Add issue templates for bug reports and feature suggestions. Thanks here to the GitHub Wizard 😂
> Add issue templates

- clicommand/agent_start.go
- clicommand/annotate.go
- clicommand/global.go
- clicommand/prime-signs.md
Minor docs fixup before 3.36 goes out.
> Docs fixes

- packaging/github/linux/buildkite-agent.cfg
Very minor nit.
I think it might make a little more sense for the key and value numbers to match.
> Update proposed comment.

- bootstrap/bootstrap.go
> Remove mirror dir if clone fails

- agent/tags.go
> Add processor architecture to tags-from-host

- .buildkite/pipeline.release-experimental.yml
- .buildkite/pipeline.release-stable.yml
- .buildkite/pipeline.release-unstable.yml
- .buildkite/pipeline.yml
- .buildkite/steps/upload-release-steps.sh
Pop quiz! What do you think this CI step does, based on its name?
If you answered "Run the tests in a linux ARM64 environment with the race detector enabled", you're correct! You win the prize of knowing deep inside that you're a very intelligent person.
In all seriousness, the names of our CI steps are a bit crap at the moment, the high amount of emoji and the low amount of text means that it all turns into heiroglyphics, a little bit.
This PR removes some of the emoji (leaving a reasonable number in, for flavour), and gives each step a relatively descriptive name in english, as well.
Suggestions more than welcome on better step names!
> Use more words, less emoji in pipeline step names

- EXPERIMENTS.md
- bootstrap/tracing.go
- clicommand/agent_start.go
🎉
**This PR:** Promotes opentelemetry tracing from being an experimental feature to being... a feature. It's here! We'll continue to iterate on this over time, but we're happy enough with the implementation as it stands to make it a mainline feature.
> Promote opentelemetry tracing to mainline feature status

- .buildkite/pipeline.release-experimental.yml
- .buildkite/pipeline.release-stable.yml
- .buildkite/pipeline.release-unstable.yml
This should hopefully fix a minor deploy issue we've been having.
> Update deploytools image 2020.03 -> 2022.07

- clicommand/step_update.go
A customer ran into this issue. 
@jradtilbrook FYI
> Document label edge case

- bootstrap/integration/artifact_integration_test.go
- bootstrap/integration/bootstrap_tester.go
- bootstrap/integration/checkout_integration_test.go
- bootstrap/integration/command_integration_test.go
- bootstrap/integration/docker_integration_test.go
- bootstrap/integration/hooks_integration_test.go
- bootstrap/shell/test.go
- clicommand/env.go
- hook/scriptwrapper.go
- hook/scriptwrapper_test.go
- main.go
> Backport #1781 to 3.39

- agent/agent_worker_test.go
- go.mod
- go.sum
This fixes the "Retrying in -500 years" issue
> Update roko to v1.0.1

- bootstrap/integration/artifact_integration_test.go
- bootstrap/integration/checkout_integration_test.go
- bootstrap/shell/lookpath.go
- hook/scriptwrapper_test.go
- process/prefixer_test.go
- process/process_test.go
- process/scanner_test.go
- redaction/redactor_test.go
- stdin/main_test.go
This should be the last tidy-up focused on t.Error and t.Fatal calls.
> Tidy up t.Error/t.Fatal (part 4)

- .buildkite/steps/build-docker-image.sh
- packaging/docker/ubuntu-18.04-linux/Dockerfile
- packaging/docker/ubuntu-20.04-linux/Dockerfile
\#1841 Added the docker-compose plugin for alpine based images, this extends it for
the ubuntu based ones.
> Add docker compose for ubuntu docker images

- process/process_test.go
These tests are occasional flakes because they rely on a sleep to let the subprocess set up the signal-catching. The fix instead waits for the subprocess to print "Ready" to stdout before interrupting/cancelling.
> process: Fix flaky "tester-signal" tests

- agent/job_runner.go
This uses `context.WithTimeout` to enforce a timeout on `finishJob` and `onUploadChunk`. 
This is not very different from swapping `roko.TryForever` for `roko.WithMaxAttempts` and a suitable limit, but has two upsides: 1) there is no maths needed to figure out how many attempts to limit to in order to reach a particular duration, and 2) the context will abort both the roko sleep and any (probably doomed) HTTP request in progress.
Why 48 hours? It seems like a long enough time.
> agent: Timeout on finishJob and onUploadChunk

- .github/dependabot.yml
It was not updating the packaging Dockerfiles which are in subdirectories
> Update dependabot.yml to include packaging Dockerfiles

- packaging/linux/scripts/after-install-and-upgrade.sh
An opportunistic tweak. There are probably other things that could be tweaked, but it's past 6PM where I am.
> packaging: Use pkill instead of ps-grep-awk-kill

- .buildkite/pipeline.yml
A new attempt at using Test Analytics via the collector plugin (see #1649).
For now the collectors are using a single TA token. Perhaps we should do it with multiple tokens like #1649 has?
> Use test-collector plugin

- clicommand/artifact_search.go
See issue https://github.com/buildkite/agent/issues/1886 for motivation for the change.
This felt like the easiest way to address it, although it was tricky to find a name for the option that matched the problem well. Alternative name suggestions would be appreciated and I would be happy to update the PR.
> feat: add flag to allow empty results with doing an artifact search

- status/status.go
> status: Handle user.Current error

- agent/agent_worker.go
We noticed today that many of our builds were failing with an `agent lost` comment.  
On inspection we found that they were failing after 4 minutes and 30 seconds... which is suspiciously similar to the timeout introduced in https://github.com/buildkite/agent/pull/1894 .  Sure enough, our failing builds were all running on the v3.43.0 build.
I think the issue is that the `ctx` with the timeout that is created for the `acquireJob` loop is ultimately passed to the call to `RunJob`.  
This PR renames the context with the timeout and uses it where it seems appropriate while passing the original `ctx` on to `RunJob`.
Please let me know if I've got it wrong.  Happy to iterate on this if I've misread!  Thanks.
> only use the ctx w/ timeout where necessary

- packaging/linux/scripts/after-install-and-upgrade.sh
Currently an upgrade via the debian package will send a TERM to all buildkite-agent processes and hope they restart. If they're run via systemd, a TERM will cause the agent to stop gracefully and exit with a 0 status. Our systemd unit is configured to [only restart on failures](https://github.com/buildkite/agent/blob/ef099a377634744decd66967fd0da4d9c1d2aa08/packaging/linux/root/usr/share/buildkite-agent/systemd/buildkite-agent.service#L13), so it won't restart automatically. (Otherwise the agent won't stop when asked to from the dashboard.)
Try to be smarter when restarting after an upgrade on debian-based systems with systemd. Most folks will be running the agent using systemd, so try to restart it nicely using systemctl. Fall back to the old behaviour.
Another option could be to …
> Restart with systemd

- EXPERIMENTS.md
We typcially document experiments in EXPERIMENTS.md.
> Document Kubernetes experiment

- templates/launchd.plist
- templates/launchd_local_with_gui.plist
Add a blank line, add System as a session type, and copy the change into the other template.
> templates: Tidyups from #1960

- agent/pipeline_uploader.go
- agent/pipeline_uploader_test.go
- api/pipelines.go
- clicommand/pipeline_upload.go
See the comments on https://github.com/buildkite/agent/pull/1927
> Refactor pipeline upload code in response to a review

- EXPERIMENTS.md
- clicommand/agent_start.go
This is the MVP of #1967, so that we have a workaround landed for #1929.
> Add `descending-spawn-priority` experiment.

- agent/artifact_uploader.go
https://github.com/buildkite/agent/commit/2223bcaf613f988bae2a12ce813af445900ef02a is missing an import.
> Fix missing import

- agent/api.go
- api/meta_data.go
- clicommand/meta_data_exists.go
- clicommand/meta_data_get.go
- clicommand/meta_data_keys.go
[Linear ticket](https://linear.app/buildkite/issue/PDP-581/support-querying-metadata-by-build-id-in-agent) 
Currently the agent supports looking up meta-data by job, but this can be awkward in triggered builds where you are trying to lookup meta-data on the original build.
Adding support for looking up meta-data by build on the agent side
Verification
You can test using artifacts. You will need to set up a job to trigger another job.
Below are examples for how to test for the get endpoint. Testing will also need to be carried out for the exists, and keys. 
The triggering pipeline (meta-data-pipeline-1) artifact should have this in its pipeline.yml:
```
steps:
- label: ":arrow_double_up::package: Generate artifacts"
command: "generate_artifacts.sh"
- wait
- label: …
```
> PDP-581 added agent support for getting the meta-data by build

- .buildkite/pipeline.release-experimental.yml
- .buildkite/pipeline.release-stable.yml
- .buildkite/pipeline.release-unstable.yml
They use the same script, but in different pipelines.
> Apply fix from #2048 to unstable and stable release pipelines

- bootstrap/bootstrap.go
When the checkout process errors out, it's usually to a command that we run failing. However, when these commands fail, it's usually with an unhelpful error like `exit status 128`, which isn't really helpful for diagnosing the actual error that occurred.
This PR updates the checkout process to wrap all of the errors coming out, making it easier to diagnose exactly where the problem actually is.
> Wrap errors in git checkout process

- .github/dependabot.yml
> Increase dependabot open PR limit 2 -> 10

- clicommand/lock_acquire.go
- clicommand/lock_do.go
I got my logic backwards in an earlier PR, then never tested it.
> lock acquire/do: fix timeout logic

- clicommand/agent_start.go
- experiments/experiments.go
Plus some minor tidyups:
* Sectionise and alphabetise constants
* Alphabetise Available map
* Separate state const block
> De-experimentify inbuilt-status-page

- clicommand/annotate.go
- clicommand/pipeline_upload.go
- internal/stdin/main_test.go
- internal/stdin/stdin.go
Package intended only for agent consumption? Into the square hole!
> Internalise stdin

- README.md
How do you think?
(ref: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#footnotes)
> Use github flavor footnote

- agent/artifact_batch_creator.go
- agent/artifact_uploader.go
In #2028 we applied a timeout to CreateArtifacts & UpdateArtifacts to get faster feedback when a single request stalled. The timeout was generous relative to our normal p99 response time, however it's proven too aggressive during occasional overload of that API.
This pull request keeps that timeout for the first 4 of 10 attempts, and then removes it for the following 6 attempts. This retains the fast feedback and retry in case the first request(s) stalled for some transient reason, but then reverts to the much longer default client/server timeout in case the API is consistently failing to respond in time.
Here's what manual testing looked like in a scenario with `sleep(20) then error` in the API for the first six CreateArtifacts requests:
And likewise for UpdateArtifacts:
Related:
- #2028
> CreateArtifacts & UpdateArtifacts: remove timeout after 4 attempts

- agent/job_runner.go
Fixes https://github.com/buildkite/agent/issues/1799
Combines `runner.output` writes with `tmpFile` instead of `allWriters` so that the temp file can get any line transforms like ansi-timestmap prefixes.
I'm not quite sure how to manually test or write an automated test for this change, currently going on intuition. I would appreciate any instructions for doing so.
> Update job log file to include line transforms

- status/status.html.tmpl
It's not an experiment anymore, but the rest of the yellow div is correct.
> De-experimentify wording on the status page

- experiments/experiments.go
> Include the version each experiment was promoted

- agent/agent_worker.go
- agent/integration/job_runner_integration_test.go
- agent/job_runner.go
in advance of implementing job signature verification, this PR does a little bit of no-op cleanup on the JobRunner
> JobRunner cleanup

- internal/pipeline/parser_test.go
- Add interpolation to group step parser test
- Add a block step
> Increase test coverage for new parser

- internal/pipeline/parser_test.go
- internal/pipeline/pipeline.go
- internal/pipeline/step.go
- internal/pipeline/steps.go
...including `Pipeline.Steps` and `GroupStep.Steps`.
> Normalise nil Steps to zero-length slice

- docs/git-mirror.md
This felt broadly useful, but I'm not 100% certain it belong here.
> Add some notes about git mirrors

- experiments/experiments.go
> Fix avoid-recursive-trap experiment not recognised

- agent/integration/job_runner_integration_test.go
I think racy access to `tae.calls` is being detected by the race detector.
> Fix data race in testAgentEndpoint

- .buildkite/pipeline.yml
- .buildkite/steps/tests.sh
1. Pass `-coverprofile` to the test command to produce coverage.
2. Convert `cover.out` to `cover.html` using `go tool cover`.
3. Upload the coverage using the artifacts plugin.
4. ...
5. Profit!
> Upload test coverage

- .buildkite/steps/publish-rpm-package.sh
I also thought it would be interesting to show the size of the directory that was synced from S3. 
All else is shell style tidyup.
> Force rm .repodata if createrepo_c --update fails

- .buildkite/steps/publish-rpm-package.sh
https://github.com/rpm-software-management/createrepo_c/blob/f4854bb1dcb952c7cfb5a6046166a4959b361b5c/src/cmd_parser.c#L511
> Work around createrepo_c requiring a regular file

- .buildkite/steps/publish-docker-image.sh
Instead of picking a particular v1 version.
(Re the last PR: I lost the race with auto-merge.)
> Use skopeo/stable:v1

- .buildkite/pipeline.release-experimental.yml
- .buildkite/pipeline.release-stable.yml
- .buildkite/pipeline.release-unstable.yml
- .buildkite/steps/publish-rpm-package.sh
On alpine it runs into a bunch of issues with dynamically linked libraries, and isn't in the default APK repo. In ubuntu though, it's in the default, and all of its dependencies get installed correctly
> Run createrepo_c on ubuntu

- internal/pipeline/parser_test.go
> Fix incorrect check in a test 😅

- .buildkite/steps/publish-rpm-package.sh
> createrepo_c -> createrepo-c

- agent/integration/job_verification_integration_test.go
- agent/verify_job.go
`jcs.Transform` doesn't like empty strings or `null`. This also changes the error strings to be a bit more direct about what was compared (instead of talking about "fields").
> Fix verifying jobs with no plugins

- agent/verify_job.go
Spare a thought for the poor saps that actually _do_ need to debug the job verification logic.
> Add debug logs in verifyJob

- go.mod
- go.sum
> Update bintest to v3.2.0

- agent/header_times_streamer.go
`sync.WaitGroup`'s Add and Wait methods are racy when called concurrently. There's a better way: channels.
> Fix race in header times streamer

- agent/integration/job_verification_integration_test.go
- go.mod
- go.sum
See https://github.com/buildkite/go-pipeline/pull/7
> Update version of go-pipeline to fix verification of plugins with null config

- agent/log_streamer.go
Process is called repeatedly with output (that are then subdivided into chunks), so warnedAboutSize should really be a field.
> Log the max size warning once

- agent/log_streamer_test.go
Fortunately this seems to be limited to the test.
> Fix data race in log_streamer_test

- go.mod
- go.sum
> Update go-pipeline to v0.3.2

- agent/agent_worker.go
- agent/artifact_batch_creator.go
- agent/artifact_searcher.go
- agent/pipeline_uploader.go
- agent/register.go
- api/github_code_access_token.go
- clicommand/meta_data_exists.go
- clicommand/meta_data_get.go
- clicommand/meta_data_keys.go
- clicommand/oidc_request_token.go
- clicommand/step_get.go
- internal/job/ssh.go
Take advantage of recently-shipped improvement in roko.
None, this is an opportunistic improvement.
Replace `Do` and `DoWithContext` with `DoFunc` or `DoFunc2`, where the intent of the code being retried is to produce some value.
> Use roko.DoFunc

- .buildkite/pipeline.release-stable.yml
- .buildkite/pipeline.release-unstable.yml
As in https://github.com/buildkite/agent/pull/2760 , updating the beta and stable release pipelines to use the correct role.
> Pass AWS creds into docker containers

- clicommand/git_credentials_helper.go
The git-credential helper only supports the `get` action, so we should exit from any other action as soon as we can.
[Slack convo](https://buildkite-corp.slack.com/archives/C071B119REG/p1715307176654929)
> Return earlier from non-get credential actions

- clicommand/agent_start.go
See: https://github.com/buildkite/agent/pull/2814#discussion_r1638354984
> Fix typo in "kuberentes"

- .buildkite/steps/publish-docker-images.sh
Sorry @DrJosh9000. Hopefully this is the last one.
Another fixup after ba0074c5e408ab7e9c1eb0e797d327cae38e8573. I forgot to fix the audience as well as the login url.
> Fix the OIDC login for Packages

- internal/job/hook/wrapper.go
- internal/tempfile/tempfile.go
Using a fixed path to contain all hook wrappers makes life hard for some users.
Fixes #2916 
* Make `tempfile.WithDir` accept paths that are absolute or relative (to `os.TempDir`).
* Create one temporary directory with `os.MkdirTemp` inside `NewWrapper`.
* Clean up by removing the whole temporary directory, rather than individual files.
> Write hooks into new tempdir

- go.mod
- go.sum
- internal/artifact/uploader.go
I moved the cheese.
Fixes dependabot.
> Fix zzglob import path

- clicommand/annotate.go
Discussed with @gilesgas just to enable emoji name as an example
> OLDMK-2904 uodaet annotation

- agent/agent_pool.go
Simplify.
* It's not important that we only return the first error - we can return all errors joined and `errors.Is` (used for changing the exit code in acquire mode, a few levels up the call stack) will continue to work - but it's better to report all errors.
* Conditionally sending on a channel makes balancing receives harder, which the old implementation worked around with a waitgroup and yet another goroutine that closed the channel after all workers finished. Always sending one value per worker means receiving one value per worker, which eliminates the waitgroup and extra goroutine.
* `errors.Join` does the Obviously Correct Thing with empty slices and nil errors.
Saw this again while investigating a bug, and I decided that I've had enough.
> Clean up worker pool implementation

- internal/replacer/replacer.go
- internal/replacer/replacer_test.go
Broaden the set of strings matched by `'\n'` to include any number of `' '` (not necessarily followed by `'\n'`).
It's easy to accidentally leak multiline secrets with the shell option `set -x`, or even just `echo ${MY_MULTILINE_SECRET}`.
https://linear.app/buildkite/issue/PS-446
* Handle `' '` in the input stream when matching `'\n'` by splitting into two match states at different positions. 
* Change a map `map[string]unit` to a string slice to restore scanning performance
> Fix redaction of multiline secrets printed as single lines

- agent/fake_api_server_test.go
Improve the accuracy of the error message.
Add a missing mutex lock/unlock.
Noticed by @pda on #3264
> fix: ISE message when json.Marshal fails

- agent/fake_api_server_test.go
I intend to use this in #3268 to have the `api.Client` perform a registration request, with server-specified `request_headers` in the response, and ensure those headers are passed in subsequent requests.
Related:
- #3268
- #3264
> `FakeAPIServer` handles agent registration: `AddRegistration(tok, resp)`

- agent/job_runner.go
This is helpful for log analytics for grouping.
> Add build URL to log fields

- clicommand/kubernetes_bootstrap.go
Fixes the handling of the bootstrap subprocess from `buildkite-agent kubernetes-bootstrap`.
Signal propagation (from Kubernetes, in this case) was not working, because the `Run` method of `process` blocks, and signal forwarding was set up afterwards.
https://linear.app/buildkite/issue/PIPE-1120/delays-in-k8s-job-deletion-reflected-in-buildkite-ui
- Put signal forwarding in a goroutine
- Rearrange existing code
- Use -1 exit code for failure to start subprocess (like JobRunner)
> Fix bootstrap subprocess handling

- clicommand/pipeline_upload.go
- clicommand/pipeline_upload_test.go
When interpolation was disabled, a pipeline would be uploaded twice.
Fixes #3358 
- Fix the bug
- Add new test
- Make all the other tests check outputs as a whole
> Fix regression in pipeline upload with no-interpolation

- clicommand/pipeline_upload.go
If multiple YAML documents are in a pipeline upload, only gather changed files once (for `if_changed` application). 
Noticed while reviewing existing code.
> Gather changed files list once

- clicommand/pipeline_upload.go
- clicommand/pipeline_upload_test.go
Make improvements to `if_changed`
- Enable `apply-if-changed` by default
- Lazy-load changed paths when `if_changed` is detected
- Log more error output when problems happen
- Log the diff base, merge-base hash, and the number of changed files on the happy path
https://linear.app/buildkite/issue/PIPE-1385
> if_changed improvements

- clicommand/pipeline_upload.go
Make the defaults more useful. `BUILDKITE_PIPELINE_DEFAULT_BRANCH` is usually set, and `BUILDKITE_PULL_REQUEST_BASE_BRANCH` is usually empty.
But when `BUILDKITE_PULL_REQUEST_BASE_BRANCH` is non-empty we probably want that instead. 
From this comment: https://github.com/buildkite/agent/pull/3387#discussion_r2204211893
Use `BUILDKITE_PIPELINE_DEFAULT_BRANCH` as the last of 3 env vars to use for `--git-diff-base`.
> Use BUILDKITE_PIPELINE_DEFAULT_BRANCH as a default git diff base

- clicommand/kubernetes_bootstrap.go
Allow `kubernetes-bootstrap`'s connection step timeout to be configurable via a `--kubernetes-bootstrap-connection-timeout` integer flag.
This is helpful in network unstable environment. 
part of PS-906
> PS-906: configurable kubernetes-bootstrap connection timeout

- CODEOWNERS
Fix codeowner file, so it ease my life not having to manually tag the team
> fix code owners

- clicommand/pipeline_upload.go
- cliconfig/loader.go
Like how we now accept multiple pipelines within a single file or stdin stream, let's accept multiple files passed as args.
https://linear.app/buildkite/issue/PS-978
- Change the loader to look for `arg:*`
- Process all files passed as non-flag args
> Allow multiple pipeline files for upload

- internal/job/executor.go
This PR is based on top of #3466.
Closes #3444.
When a polyglot hook uses `buildkite-agent env set` to update environment, executor config will not be refreshed. And this is against our expectation. 
This PR fixes it. 
A test case would be good but, however, after a few stab, I think a overall test setup refactor will be needed in order for that to happen. 
PS-1101
Peasant human coding
> PS-1101: refresh Executor config for Job API env change in polyglot hook

- clicommand/oidc_request_token.go
Based off of @samgaudet's excellent work in https://github.com/buildkite/agent/pull/3472
This PR introduces functionality to return Buildkite OIDC tokens wrapped in standard JSON expected by GCP for use in Workload Identity Federation Credentials. With this change in place, using GCP Workload Identity Federation with Buildkite is greatly simplified.
When using Workload Identity Federation in GCP with Buildkite, Workload Identity JSON credentials can be structured in several ways (see: [_External Account Credentials (Workload Identity Federation)_](https://google.aip.dev/auth/4117)). Notably, the most streamlined and secure way of configuring these credentials is to provide a `credential_source` of a command that returns a token (this nullifies the requirement to save the token anywhere …
> OIDC gcp format

- clicommand/pipeline_upload.go
Make `if_changed` detect when the diff base is the same commit as `HEAD` (e.g. on a build on `main` after merging a PR, or when committing directly to `main`). When that happens, extract the list of changed files from the most recent commit, which requires some fun `git log` flags.
Closes #3507. There are also some other reports.
`git rev-parse` both `diffBase` and `HEAD`, and if they are the same, use `git log --first-parent -1 --name-only --pretty='format:'` to get a list of changed files instead of `git diff`.
I did not use AI tools at all
> Improve if_changed when base=HEAD
