buildkite/agent.go
buildkite/job.go
buildkite/script.go
command/agent_start.go
commands.go
templates/bootstrap.sh

This change will allow the agent to automatically accept the RSA fingerprints when cloning from an ssh based git repository:

Option to automatically accept RSA fingerprints when git cloning.

---

buildkite/agent.go
buildkite/agent_registration.go
buildkite/job.go
command/agent_start.go
commands.go
templates/bootstrap.sh

This will allow you to store your scripts on Buildkite, and have the agent execute them (instead of having to commit them to your source repository).
Because this could be a potential security risk, this feature can be turned off with `--no-script-eval`

Allow scripts sent from Buildkite to be evaluated

---

templates/bootstrap.sh

Prevents builds from hanging if git needs to auth in some way.
This means if users don't have the correct keys set up, their build will just fail instead of hanging on username/password or other auth prompt.
> The credential subsystem is now friendlier to scripting
> When Git needs a password (e.g., to connect to a remote repository over http), it uses the credential subsystem to query any helpers (like the OS X Keychain helper), and then finally prompts the user on the terminal. When Git is run from an automated process like a cron job, there is usually no terminal available and Git will skip the prompt. However, if there is a terminal available, Git may hang forever, waiting for the user to type something. Scripts which do not expect user input can now set `GIT_TERMINAL_PROMPT=0` in the …

Add support for Git 2.3's GIT_TERMINAL_PROMPT

---

templates/bootstrap.bat

Sorry, there are a couple of changes in here:
1) Added some quotes around %BUILDKITE_BUILD_DIR% in case BuildKite is installed in Program Files. Who would put it there though, right? :)
2) Converted line endings to CRLF (sorry). I often only have notepad available on a server & this is a bit more user-friendly. I always run autocrlf false and trust contributors to do the right thing on a per-file basis, but if you guys use a different policy I can redo the PR.
3) %ERRORLEVEL% does not work the way you’d expect inside IF blocks (it’s expanded prior to the block being executed). This requires `SETLOCAL ENABLEDELAYEDEXPANSION` and the use of `!ERRORLEVEL!` inside the blocks. See http://stackoverflow.com/a/4368104/47636. Yes, we all learned something today.
This bootstrap is running okay on …

Build does not report failure on Windows

---

templates/bootstrap.bat

Windows artifact upload fails if the buildkite-agent path has a space in it

---

templates/bootstrap.sh

Reported by @alanjrogers, the line after `git submodule sync` can fail because the the sync is missing the `--recursive` that all the other submodule commands have.

Add --recursive to git submodule sync

---

templates/bootstrap.sh

This way you can have each pipeline step execute in a different environment via separate Dockerfiles, for example `BUILDKITE_DOCKER_FILE=Dockerfiles/ruby` and `BUILDKITE_DOCKER_FILE=Dockerfiles/php`

Add BUILDKITE_DOCKER_FILE to specify the Docker file

---

templates/bootstrap.sh

Now that we pipe to `cat` (as of 1c4241c3c9153dda168748c0821d927773aaf73b) any failure exit status codes in docker and docker-compose are masked. This change sets `pipefail` so non-zero exit statuses are bubbled through the command pipeline.

Catch Docker failures

---

README.md

This removes all the pre-1.0 readme content, bringing the focus of the docs to "how to contribute". The official user/usage docs will live at [buildkite.com/docs](https://buildkite.com/docs)

Remove all the pre-1.0 Readme content

---

templates/launchd.plist

Just setup a mac OS X machine with a new agent and had to make these changes to the template plist to get it to work.
- Fix incorrect raw github address for template `launchd.plist`
- Fix missing program arguments
- Fix incorrect env var `BUILDKITE_AGENT_ACCESS_TOKEN`
- Rename destination plist to `com.buildkite.buildkite-agent.plist`

Fix template launchd.plist

---

templates/bootstrap.sh

I'm all for the use of longer forms of command-line options in scripts, but in this case it breaks on Alpine Linux:
Alpine Linux uses Busybox' `grep`, which doesn't understand the long-form `--quiet` flag:
```
$ grep --quiet
unrecognized option `--quiet'
BusyBox v1.22.1 (2015-03-20 11:09:37 GMT) multi-call binary.
Usage: grep [-HhnlLoqvsriwFE] [-m N] [-A/B/C N] PATTERN/-e PATTERN.../-f FILE [FILE]...
Search for PATTERN in FILEs (or stdin)
-H    Add 'filename:' prefix
-h    Do not add 'filename:' prefix
-n    Add 'line_no:' prefix
-l    Show only names of files that match
-L    Show only names of files that don't match
-c    Show only count of matching lines
-o    Show only the matching part of line
-q    Quiet. Return 0 if PATTERN is found, 1 otherwise
-v    Select non-matching lines
-s …
```

Fix errors from non-GNU grep

---

install-beta.sh

At the moment the linux installer doesn't copy the config file into `~/.buildkite-agent`. This fixes that, plus:
* Cleans up the if statements
* Copies the dist config file to `~/.buildkite-agent/buildkite-agent.dist.cfg`
* Edits the token in the config file if `TOKEN` is set
* Adds a reminder if no `TOKEN` is set on a fresh install
* Removes `--token` from the "now you can start an agent" command
```
$ BETA="true" TOKEN=abc123 bash ~/Codez/buildkite/agent/install-beta.sh
_           _ _     _ _    _ _                                _
| |         (_) |   | | |  (_) |                              | |
| |__  _   _ _| | __| | | ___| |_ ___    __ _  __ _  ___ _ __ | |_
| '_ \| | | | | |/ _` | |/ / | __/ _ \  / _` |/ _` |/ _ \ '_ \| __|
| |_) | |_| | | | (_| |   <| | ||  __/ | (_| | (_| |  __/ …
```

Fix config file handling on the Linux installer

---

buildkite/header_times.go
buildkite/job.go

Currently, the agent uploads every single header time to the BK API every second. We can do better.
I've refactored and cleaned up the header time handling to stream the times to the BK API.

Stream header times to the Buildkite API

---

command/agent_start.go

Non-important change, but it was causing me to twitch whenever I saw it :grin:

Typo/spelling on 'configuration'.

---

api/buildkite.go

Pretty small change to ensure the Body is ALWAYS flushed, it seems the JSON decoder is only reading enough to satisfy the decoder and not triggering the final EOF on the stream.
From the golang http library documentation.
```
// The default HTTP client's Transport does not
// attempt to reuse HTTP/1.0 or HTTP/1.1 TCP connections
// ("keep-alive") unless the Body is read to completion and is
// closed. 
```
So this change makes sure that happens.

Added defer'd flush of the body to ensure connection reuse.

---

templates/bootstrap.sh

Allows using the agent in environments that don't have Perl, which the git submodule commands rely upon.
Related to #52

Add ability to disable git submodules

---

templates/bootstrap.sh

Problem:
On very large repositories with many contributors, branches tend to accumulate and `git fetch` have a lot of objects to download making it very slow.
And then the local cache tend to accumulate a lot of loose objects and we need to prune it.
Solution:
We can fetch only the commit we need (and the missing ancestors) with `git fetch origin SHA1`.

Fetch only the required commit

---

agent/artifact_uploader.go

I see the agent hanging occasionally after all artifacts have been uploaded. It appears the background goroutine that uploads state changes using the Buildkite API is waiting for more state changes.
Looking into this, I noticed that the `artifactsStates` map is accessed and modified in different goroutines without first acquiring a lock, which appears to be unsafe. See:
https://golang.org/doc/faq#atomic_maps
Adding `p.Lock()` and `p.Unlock()` fixes the hangs for me.
Note: This uses the pool's `sync.Mutex`. I think we only need a `sync.RWMutex`, which allows multiple parallel readers---but that would require a bigger change.

Use a lock when reading or writing to artifactsStates

---

templates/bootstrap.sh

This avoid pulling all the branch during the clone.
It does require Git `1.7.10` thought: https://github.com/Shopify/shipit-engine/blob/45d0225276715b6352159b043c3bb4aa07845c2a/lib/stack_commands.rb#L50-L53
@keithpitt @toolmantim for review please.

Use git clone --single-branch

---

install.sh

Currently the install script fallback to 386 unless the arch is x86_64.
As arm binaries are officially released, a simple case statement in the install script fix the issue.

add arm support for install script

---

packaging/linux/root/usr/share/buildkite-agent/buildkite-agent.cfg

This was removed in 80373be618fc6aacbda88f756e16dcc5c3725612, but is still required in 2.1.x agents. Without this, after `apt-get install buildkite-agent` you will _not_ be able to start the agent.

Add bootstrap-script path back to default config

---

agent/artifact_downloader.go
agent/artifact_uploader.go
agent/download.go
agent/gs_downloader.go
agent/gs_uploader.go
agent/gs_uploader_test.go
agent/s3_downloader.go
clicommand/artifact_upload.go

The Buildkite agent currently allows storing artifacts in an S3 bucket
with the `s3://` scheme. This change adds support for Google Cloud
Storage buckets with the `gs://` scheme. Details:
* GS authentication is handled using Google's OAuth2 library, which
searches for the credentials in various locations. See:
https://godoc.org/golang.org/x/oauth2/google#DefaultClient
* GS ACLs are similar to S3 ACLs. The default GS ACL is `publicRead`,
which is analagous to S3's `public-read`. I'd actually prefer if it
was safer and defaulted to `private` for both GS and S3, but I left
it this way for consistency.
* GS downloading is handled by reusing `download.go`, similar to S3
downloading. An `http.Client` field is now passed in via the
`Download` struct. This allows the GS code to pass in a client …

Add support for artifacts on Google Cloud Storage

---

process/process.go

I've been observing agents not successfully killing build jobs on timeout recently. The process of `SIGTERM`, wait 10 seconds the `SIGKILL` sounds fine. This fix should make that work as intended.

Send desired signal instead of always SIGTERM

---

templates/bootstrap.sh

Change the git fetch and checkout behaviour to be a little more explicit.
There are a few discrete scenarios which are commented. There's also an additional ability to specify your own refspec, as suggested in #237.
I've tested this in several scenarios, with and without clean checkouts:
* Building a master push using a github webhook
* Building "master" at "HEAD" using web ui
* Building a pushed tag with a commit unreachable from any head ref via webhook
* Building a "proposed" branch triggerd via push
* Building a "proposed" branch with "HEAD" triggered via web UI
* Building a pull request via webhook
* Building a pull request from a fork via webhook
* Building a weird ref using `BUILDKITE_REFSPEC` in env and commit `FETCH_HEAD` via web UI
Hopefully this will provide more resilient …

Bootstrap script fetch logic tweaks

---

agent/bootstrap.go
templates/bootstrap.sh

Prior to git 1.9.0, `git fetch --tags` would only fetch tags, not in addition to the default refspec. So replace it with an explicit set of refspecs.
Also, turn on verbose fetching for easier diagnostics.

Fix git fetch tags

---

agent/agent_pool.go
agent/job_runner.go
agent/log_streamer.go
api/chunks.go

This uses much less memory on the receiving end than processing multipart form uploads because rails. We're using http content-encoding for gzip compression, too, so can eventually transparently offload into a terminator instead of the app.

Log chunk as request body

---

templates/bootstrap.sh

At present the agent is eager in deleting volumes attached to containers, which is the right thing to do in general to save space.
For speed reasons, we use a persistent Named Volume (holding ruby gems) and that volume shouldn't be deleted. But docker doesn't natively provide a way to say that it's persistent. So we need a flag to tell the agent not to ask docker to delete volumes. Hence `BUILDKITE_DOCKER_COMPOSE_LEAVE_VOLUMES`.
In general this is dangerous because it's bad for disk space, so those using the flag need to acknowledge the risks.

Add BUILDKITE_DOCKER_COMPOSE_LEAVE_VOLUMES

---

scripts/utils/build-binary.sh

This doesn't seem to have much effect for windows or mac, but it stops linux from dynamically linking libc so we can restore Debian 7 compatibility. It doesn't seem to add a huge about of weight to the binary.
If all good I'll backport to 2-1-stable.

Static link

---

agent/agent_pool.go
agent/agent_worker.go
agent/api_client.go
agent/artifact_batch_creator.go
agent/artifact_uploader.go
agent/download.go
agent/job_runner.go
clicommand/meta_data_exists.go
clicommand/meta_data_get.go
clicommand/meta_data_set.go

This increases our HTTP response timeout to 1 minute, and decreases retry frequency for API calls from once every 1 second to once every 5 seconds.
This means the agent will now wait 10 seconds for a http connection, 60 seconds for a response, and then it'll wait 5 seconds before retrying. For network situations, or downtime, this means things will attempting to retry every 5 seconds instead of every second.

Increase timeouts

---

Dockerfile

We should recompile the agent with Golang v1.6 and do another stable release. The latest version of Golang has some performance & security fixes.
(btw, is this style of pull request a good idea? opening a pull request from my rando branch to the stable branch?)

Upgrade Stable to Golang 1.6

---

agent/pipeline_parser.go
agent/pipeline_parser_test.go
clicommand/pipeline_upload.go

Added support for POSIX like environment variable substitution. This fixes https://github.com/buildkite/agent/issues/205
We now support:
```bash
$REGULAR_ENV
${ENV_LIKE_THIS}
export ONES_WITH_DEFAULT_IF_NULL="" # this is "set" but it's value is null
${ONES_WITH_DEFAULT_IF_NULL:-this value will show}
${ONES_WITH_DEFAULT_IF_NULL-but this value won't}
${EVEN_REQUIRE_ONES?}
#=> $EVEN_REQUIRE_ONES: not set
export AND_CUSTOM_ERROR_MESSAGES="" # nulls are treated as empty
${AND_CUSTOM_ERROR_MESSAGES?y u no set me}
#=> $AND_CUSTOM_ERROR_MESSAGES: y u no set me
```
:warning: This change introduces a somewhat breaking change. Any customer who already have `$SOMETHING` and `${SOMETHING}` in their pipeline files will need to escape them to `\$SOMETHING` and `\${SOMETHING}`.
We should probably release …

Added support for environment variable substitution in pipeline files

---

install.sh

This PR proposes :
- BUILDKITE_INSTALL_ARCH be added for explicitly choosing an arch on install.sh
- Using `uname -m` instead of `uname -p` which can report false info.
Each commit includes detailed descriptions, I can split the commits to separate PR's if preferred.

Install arch flag

---

templates/bootstrap.sh

The buildkite bin might be /usr/bin on some systems, and then you end up with an unusual path. There's no need for ours to be at the front.
Closes #216

Move the buildkite bin to the end of $PATH

---

agent/bootstrap.go
clicommand/bootstrap.go
templates/bootstrap.sh

:rocket: #240 
> The default `git clean` flags are `-fdq`. It's useful to be able to configure this. For example, `-x` can be used to remove gitignore'd files. Or `-e` can be used to exclude specific directories.
>
> Introduce an environment variable `BUILDKITE_GIT_CLEAN_FLAGS` to control this behavior. This can then be set in an `environment` hook.

Add BUILDKITE_GIT_CLEAN_FLAGS

---

agent/bootstrap.go
templates/bootstrap.sh

As reported in #223, in both edge and stable if you run specify multiple commands without explicitly adding `&&` in the command, the job will still pass and all commands will be run. This is unexpected and incorrect.
This fixes the issue by ensuring the generated script includes the `set -e` bash flag to exit with an error as soon as any command fails.
Current badness:
Fixed goodness:
Fixes #223

Add `set -e` to ensure errored commands fail the job

---

templates/bootstrap.sh

Add `set -e` to ensure errored commands fail the job for 2.1 stable

---

.buildkite/pipeline.yml
scripts/build-debian-packages.sh
scripts/publish-debian-package.sh

@sj26 & @toolmantim paired on fixing our debian archives becoming corrupted. Turns out we were building the debian packages multiple times but they go in the same place on the archive so were overwriting each other and causing the wrong file sizes/hashes. So we build them once instead, then publish the same packages into each subsequent archive: experimental, unstable, stable.

Build debs once, publish in stages

---

clicommand/bootstrap.go

Unfortunately #270 was broken in that it didn't initialize `GitCleanFlags`, so `git clean` would error with:
```
$ git clean
fatal: clean.requireForce defaults to true and neither -i, -n, nor -f given; refusing to clean
```
This fixes it so it works as expected.

Make sure we initialize the GitCleanFlags

---

templates/bootstrap.sh

No idea what I was thinking with the initial version of this change, given the semantics were inversed and it was very broken on non-bash shells.

Fix bug I introduced with (BK)_(DC)_LEAVE_VOLUMES

---

templates/bootstrap.sh

Some people have more buildable services in their docker-compose.yml, and building images other than the specified in `BUILDKITE_DOCKER_COMPOSE_CONTAINER` takes unnecessary build time.

Build only the specified Docker image

---

templates/bootstrap.sh

This adds support for docker-compose 1.7 using the `down` support for removing networks and `rm --all` for remove adhoc containers. Closes #277
Also included:
* Adds `--pull` to the build command, so that it always attempt to pull a new version of any base images that exist
* Expands the `Running command` output group by defaults

Add docker-compose 1.7 support

---

packaging/linux/scripts/after-install-and-upgrade.sh
packaging/linux/scripts/after-remove.sh
packaging/linux/scripts/before-remove.sh

Tested on Amazon Linux, CentOS-6 and CentOS-7 (systemd). Have not tested upstart version != 0.6.5

Fix up init scripts for CentOS-6 and Amazon Linux

---

clicommand/bootstrap.go

The new default is to clean all files, including those in the `.gitignore`, using `git clean -fdqx`
This can be overridden using the config var or `BUILDKITE_GIT_CLEAN_FLAGS`

Ensure git clean removes gitignore'd files

---

agent/bootstrap.go
agent/bootstrap_test.go

Ports #293 to the golang bootstrap.
I've opted to keep the case, and not collapse down any leading or duplicate `-` characters to stop unexpected clashes. `my-agent` will be different to `My-Agent` (on Linux). Is that sensible?

Use a sanitized agent name for git checkout

---

scripts/utils/publish-debian-package.sh

SHA1 is being removed, and is already broken on Ubuntu 16.04:
https://wiki.debian.org/Teams/Apt/Sha1Removal
Fixes #295
Needs backporting to 2-1-stable

Use SHA512 for Debian signing

---

agent/agent_pool.go
agent/ec2_meta_data.go
clicommand/agent_start.go
packaging/github/linux/buildkite-agent.cfg
packaging/linux/root/usr/share/buildkite-agent/buildkite-agent.cfg

This adds a ` --meta-data-ec2` option to automatically populate the agent's meta-data with EC2 meta-data such as `aws:ami-id`, `aws:instance-id` and `aws:instance-type`. This will mean that buildkite/buildkite-aws-stack#67 and the like can just use `--meta-data-ec2`.
```
$ buildkite-agent start --token xxx --meta-data-ec2
_           _ _     _ _    _ _                                _
| |         (_) |   | | |  (_) |                              | |
| |__  _   _ _| | __| | | ___| |_ ___    __ _  __ _  ___ _ __ | |_
| '_ \| | | | | |/ _` | |/ / | __/ _ \  / _` |/ _` |/ _ \ '_ \| __|
| |_) | |_| | | | (_| |   <| | ||  __/ | (_| | (_| |  __/ | | | |_
|_.__/ \__,_|_|_|\__,_|_|\_\_|\__\___|  \__,_|\__, |\___|_| |_|\__|
__/ |
http://buildkite.com/agent                    |___/
2016-05-15 …
```

Add a --meta-data-ec2 flag

---

.buildkite/pipeline.yml
scripts/publish-to-s3.sh
scripts/utils/latest_version.rb

This publishes the buildkite agent binaries to download.buildkite.com. Each release will look like:
```
https://download.buildkite.com/agent/stable/2.1.10/buildkite-agent-darwin-386
https://download.buildkite.com/agent/stable/2.1.10/buildkite-agent-darwin-386.sha1
https://download.buildkite.com/agent/stable/2.1.10/buildkite-agent-darwin-amd64
https://download.buildkite.com/agent/stable/2.1.10/buildkite-agent-darwin-amd64.sha1
https://download.buildkite.com/agent/stable/2.1.10/buildkite-agent-freebsd-386
https://download.buildkite.com/agent/stable/2.1.10/buildkite-agent-freebsd-386.sha1
https://download.buildkite.com/agent/stable/2.1.10/buildkite-agent-freebsd-amd64
https://download.buildkite.com/agent/stable/2.1.10/buildkite-agent-freebsd-amd64.sha1 …
```

Publish binaries to download.buildkite.com/agent

---

process/process.go

We recently had a job marked as failed with status `-1`, but from the script output it seemed to have done just fine.
I believe it is due to the server trying to shutdown (which makes it hard to reproduce), but still there is something weird in the agent code.
The logs:
```
2016-05-18_18:35:43.55852 2016-05-18 18:35:43 DEBUG  GET https://agent.buildkite.com/v3/jobs/fa8da290-8a83-48b6-afa1-70c768cdea24
2016-05-18_18:35:43.58236 2016-05-18 18:35:43 DEBUG  ↳ GET https://agent.buildkite.com/v3/jobs/fa8da290-8a83-48b6-afa1-70c768cdea24 (200 OK 23.842189ms)
2016-05-18_18:35:46.58264 2016-05-18 18:35:46 DEBUG  GET https://agent.buildkite.com/v3/jobs/fa8da290-8a83-48b6-afa1-70c768cdea24
2016-05-18_18:35:46.59274 2016-05-18 18:35:46 DEBUG  ↳ GET …
```

Add logs to debug an edge case in getExitStatus

---

clicommand/meta_data_set.go

Introduces new parameter `--value-from-file` for metadata set. When this parameter exists it treats the value as a path to a file which is read. The contents of the file are then set as the metadata value.

Allow metadata value to be read from stdin to workaround issue #288.

---

agent/pipeline_parser.go
agent/pipeline_parser_test.go

This PR fixes 2 bugs with ENV interpolation:
- `${BUILDKITE_COMMIT}_${BUILDKITE_PARALLEL_JOB}` would be considered as 1 environment variable
- `$$ESCAPED_VAR` would result in `$$ESCAPED_VAR` after parsing - when it should have been `$ESCAPED_VAR`

Environment Interpolation Fixes

---

templates/bootstrap.sh

There were a few edge cases here which meant that we could be scanning every single time we run a job, and the ssh known hosts file would fill with duplicates.
These changes should make sure that we only scan for know hosts once, whether HashKnownHosts is set or not (see [ssh_config(5)](http://man.openbsd.org/ssh_config)).

Fix ssh keyscan

---

agent/bootstrap.go

This also fixes a case where we build a branch or tag and put the symbolic ref name into both the branch and commit field (like #338).

Commit fetch means we can checkout fetch head

---

clicommand/bootstrap.go

To run "command-less plugins" such as docker-compose (ones that override the command hook), currently you need to do this:
```yml
steps:
- name: ":docker: :package:"
command: ignored
plugins:
docker-compose:
build: app
```
If you leave out the command you get this when you run the step:
```
2016-06-15 20:53:46 FATAL  Missing command. See: `buildkite-agent bootstrap --help`
exit status 1
```
With this PR you're able to leave out the dummy command:
```yml
steps:
- name: ":docker: :package:"
plugins:
docker-compose:
build: app
```
(though currently you need to also add `type: script`, but there'll be another PR to infer that if there's a `plugins` property)

Don't require a command argument for the bootstrap

---

agent/bootstrap.go

This changes the plugin gear to expect hooks in a hooks dir instead of the repo root:
```
buildkite-plugins/docker-compose/
buildkite-plugins/docker-compose/hooks/
buildkite-plugins/docker-compose/hooks/command
```

Expect plugin hooks to live in a hooks dir

---

scripts/release-homebrew.sh
scripts/utils/update-homebrew-formula.rb

It looks like we might have manually fixed the homebrew recipe last time in https://github.com/buildkite/homebrew-buildkite/commit/dba6b14688555b4bb741599dda62340e32fcaf6f  but didn't fix it here, so this adds SHA256 updating to the homebrew recipe updater.
I had to move away from using `buildkite-agent artifact shasum` because it doesn't support 256 yet, so we just pull down the release artifact again and calculate it ourselves.

Fix the homebrew sha recipe updating

---

agent/plugin.go
agent/plugin_test.go

This means environment variables won't have config vars named `BUILDKITE_PLUGIN_DOCKER_COMPOSE_BUILDKITE_PLUGIN`

Remove -buildkite-plugin from the name

---

templates/bootstrap.sh

> [@porty] hello! we're currently using https://docs.docker.com/compose/extends/ to merge a base docker-compose file with a buildkite-specific one (agent v2.1.10) via `BUILDKITE_DOCKER_COMPOSE_FILE: "docker-compose.yml -f docker-compose.buildkite.yml"` (a bit of a hack)
> I see in v2.1.13 that env var is now being escaped, and so thats failing - is there a proper way to load more than one docker-compose file in a step?
>
> [@sj26] @porty: we did escape some more stuff so that commands are a little more locked down, yeah. unfortunately it stops hacks like yours, too — sorry!
> maybe you’d like to add the services you need for buildkite into your main compose and then specify which service you want as an entry point for builds
> or you could copy the services, but have to maintain two …

Support multiple docker compose files

---

scripts/release-homebrew.sh
scripts/utils/update-homebrew-formula.rb

I believe the `sha1` call in homebrew has been deprecated! (see: https://github.com/buildkite/homebrew-buildkite/issues/4)
This PR removes the auto-updating of it - next step will be to remove it entirely from the homebrew repo.
@toolmantim does this look OK to you?

`sha1` has been deprecated in latest homebrew

---

agent/bootstrap.go

`globalCommandHookPath` was referencing the local command hook path.

Make bootstrap actually use the global command hook if it exists

---

agent/agent_pool.go
agent/gcp_meta_data.go
clicommand/agent_start.go
packaging/github/linux/buildkite-agent.cfg
packaging/linux/root/usr/share/buildkite-agent/buildkite-agent.cfg

Add `--meta-data-gcp` flag that fetches metadata from Google Compute Engine and populates it as Buildkite agent meta-data. The following keys are used: `instance-id`, `machine-type`, `preemptible`, `project-id`, and `zone`.

Allow fetching meta-data from Google Cloud metadata

---

scripts/utils/build-binary.sh

We really want to ship an entirely static binary to make it as easy as possible for folks to run the buildkite-agent without worrying about glibc etc. So let's disable CGO entirely.
This means the system's networking configuration may not be entirely honoured. On *nix systems Go will read /etc/resolv.conf and use those dns servers, but otherwise skip any other name resolution mechanisms like mDNS. This includes losing Bonjour/mDNS on macOS.
At the moment this also means we lose process titles, but they've only been available on amd64 linux until now and we have [a pure Go solution to that in the works](https://github.com/buildkite/agent/pull/373).
For Windows, this shouldn't cause any change.
/cc @toolmantim

Disable CGO

---

clicommand/agent_start.go

As part of https://github.com/buildkite/docs/commit/18e02116a9ab29887ab7cf5cea6db21aedc341d4 I noticed that the ec2 and gcp options were the only ones without an environment variable equivalent. This adds the environment variable setting support to these options.

Add env vars for ec2 and gcp config options

---

scripts/utils/publish-debian-package.sh

The variable names following "Error: Missing ENV variable" in the error messages should not be interpolated, so that the missing variable can be identified.
Fixes #385

Fix escaping bug in publish-debian-package.sh

---

agent/agent_pool.go

When starting several agents in quick succession some of the agents fail to populate with the proper EC2 metadata for tags. I suspect it has something to do with grabbing IAM credentials and throttling on AWS side. Retries with some random delay should fix the problem.

retries for grabbing ec2 metadata

---

packaging/github/linux/buildkite-agent.cfg
packaging/github/windows/buildkite-agent.cfg

The buildkite-agent.cfg in the tar.gz for the v3 betas still contain the bootstrap.sh config line, and lack the plugins path. And because of this, if you install buildkite-agent via homebrew using `--devel` it doesn't include `plugins-path` in the config.
This was been updated:
https://github.com/buildkite/agent/blob/master/packaging/linux/root/usr/share/buildkite-agent/buildkite-agent.cfg
But these haven't:
https://github.com/buildkite/agent/blob/master/packaging/github/linux/buildkite-agent.cfg
https://github.com/buildkite/agent/blob/master/packaging/github/windows/buildkite-agent.cfg
Presumably because the bootstrap config line has already been updated in these files, it's safe to include this change here too.

Add plugins-path to the config

---

agent/bootstrap.go

Windows builds failed to report an error if it didn't occur
on the last command of the build. Batch files have no equivalent
for "set -e"; instead we need to check after each command for
the return value and exit if it is non-zero.
Fix for #391

Fix error detection on Windows

---

clicommand/pipeline_upload.go
envvar/interpolator.go
envvar/interpolator_test.go

It also now just talks strings instead of `[]byte`

Renamed the PipelineParser to be envvar.Interpolate

---

agent/pipeline_parser.go
agent/pipeline_parser_test.go
api/pipelines.go
clicommand/pipeline_upload.go

This PR is making a few big changes to how pipelines are uploaded to the BK API:
- Instead of uploading the pipeline files "as-is", we parse them first (either as YAML or as JSON) and upload them to the Agent API as JSON all the time. This gives us the benefit of catching JSON or YAML syntax errors before even hitting the Agent API
- Instead of doing an Environment Variable Interpolation across the entire pipeline as a whole, we recursively go through the entire config and do it for strings only, after the first parse. This solves many quoting issues (Fixes #346)
- When piping a pipeline in via STDIN, you must now tell the agent what format it's in `--format yaml` or `--format json`
- We now accept `.buildkite/pipeline.yaml` (not just `.yml`) files as default file. Apparently `.yaml` is …

Pre-process pipelines before uploading

---

agent/agent_worker.go

The normal agent loop uses a `select` statement to wait on two channels: The first channel receives a value at a regular ping interval, and the second channel receives a value to indicate we are stopping:
for {
a.Ping()
select {
case <-a.ticker.C:
continue
case <-a.stop:
a.ticker.Stop()
return nil
}
}
I believe there is a race condition here:
1. Suppose Job A is currently running, so we are inside `Ping()`.
2. A "graceful stop" signal is received, and a value is sent on the `a.stop` channel.
3. The ticker sends a new value on the `a.ticker.C` channel.
4. Job A finishes, so we exit `Ping()`.
5. The `select` statement executes with both channels ready, and [it chooses one at random](https://golang.org/ref/spec#Select_statements). Suppose it chooses the ticker, and we continue on to the next …

agent: Avoid starting a new job in graceful stop mode

---

agent/bootstrap.go

Spent some time trying to set up an agent on Windows and ran into this. Here's my VM showing that `ssh-keygen.exe` is in `C:\Program Files\Git\usr\bin` and didn't match the path traversal that the agent is trying to do. This is from Windows Server 2012 running in Vagrant:
Git was installed via Chef. Not sure that this is the right fix since the current path could be right for other install methods. Just wanted to attach some code in case it turns out to be right.

Update path to ssh tools for Windows

---

agent/bootstrap.go

This makes sure that agents with `--no-command-eval` switched on can't execute files outside the working directory (the repository checkout).
I also had to modify the chmod call to only chmod if the execute bit was missing, otherwise I got `Failed to mark "/usr/bin/true" as executable (Permission denied)`

No command eval working dir only

---

clicommand/artifact_upload.go
cliconfig/loader.go

@mcgain was trying to setup a custom s3 bucket for artifact uploads and noticed that `$BUILDKITE_ARTIFACT_UPLOAD_DESTINATION` is only respected in the bootstrap's default artifact uploader, and not when using `buildkite-agent artifact upload ...` manually. It seems the destination arg is not a normal flag and doesn't ingest environment variable values by default, so if the argument is not supplied positionally then it always uses the default buildkite artifact bucket. I've added support to our arg parser so that positional args can also fall through to environment variables, which doesn't seem to be available in the codegangsta cli package.
@mcgain, care to give it a go and confirm it's working now?

Artifact upload destination env

---

packaging/linux/root/usr/share/buildkite-agent/lsb/buildkite-agent.sh

@npaufler noticed that on Debian wheezy using the lsb init script the buildkite-agent doesn't stop correctly:
```
sj26@debian:~$ sudo /etc/init.d/buildkite-agent start
Starting buildkite-agent
sj26@debian:~$ cat /var/run/buildkite-agent.pid
6825
sj26@debian:~$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
...
root      6825  0.0  0.2  37160  1364 pts/1    S    11:52   0:00 su --login --shell /bin/sh buildkite-agent
999       6828  0.0  0.1   4188   576 ?        Ss   11:52   0:00 -su -c /usr/bin/buildkite-agent start
999       6832  0.0  1.6  14848  8560 ?        Sl   11:52   0:00 /usr/bin/buildkite-agent start
sj26      6838  0.0  0.2  16844  1284 pts/1    R+   11:55   0:00 ps aux
sj26@debian:~$ sudo /etc/init.d/buildkite-agent stop
Stopping …
```

Exec the command within the shell

---

agent/agent_configuration.go
agent/header_times_streamer.go
agent/job_runner.go
clicommand/agent_start.go
process/process.go

***Background:*** 
The issue in https://github.com/buildkite/feedback/issues/80 has become a showstopper for me. I am supporting a Buildkite based container building service which allows users to provide their own complex build scripts. There are often performance problems that must be diagnosed. Since I do not control the individual build steps I cannot add group header to their build output in order to get timing information. I require an option to timestamp each line of output so we can profile any part of the build.
I've tried ad-hoc solutions involving `ts` and `unbuffer` but they are not drop-in replacements, this feature is needed in the agent itself.
***Changes:***
This PR adds a `BUILDKITE_TIMESTAMP_LINES` environment variable. If set to one of ` 1, t, T, TRUE, true, True, 0, f, …

Add option to timestamp lines

---

agent/agent_configuration.go
agent/header_times_streamer.go
agent/job_runner.go
clicommand/agent_start.go
process/process.go

I've moved the option to a 2.4 release, so I'm reverting the change from the 2.3 branch to historical reasons.

Revert "Add option to timestamp lines" for 2.3

---

agent/header_times_streamer.go
agent/job_runner.go
process/process.go

**What:**
In https://github.com/buildkite/agent/pull/430 I introduced the line timestamp feature, but there is a bug where `^^^ +++` gets timestamped and consequently fails to expand the previous group. The PR resolves this issue.
**How:**
The [documentation](https://buildkite.com/docs/builds/managing-log-output) indicates `^^^ +++` can be used to expand a header group.
Currently this line will be time stamped because it does not pass the header regex. However, this line is not actually a header, and should not be reported as one to the Buildkite backend. Instead, a special check is made to avoid timestamping these special lines.
*Pros:* Fixes the bug!
*Cons:* Even more coupling between `header_times_streamer` and `process`.
**Review:**
@keithpitt

Do not timestamp header expansion directives

---

clicommand/meta_data_get.go

This allows peeps to supply a default to the `meta-data get` command - so instead of the command returning an error - it will return the supplied default.
```shell
❯ go run *.go meta-data get "buildkite:git:branch:lol" --agent-access-token xxx --job yyy --debug --endpoint "http://agent.buildkite.dev/v3" --default "lol"
2017-03-23 14:27:39 DEBUG  Debug mode enabled
2017-03-23 14:27:39 DEBUG  POST http://agent.buildkite.dev/v3/jobs/yyy/data/get
2017-03-23 14:27:39 DEBUG  ↳ POST http://agent.buildkite.dev/v3/jobs/yyy/data/get (400 Bad Request 271.648123ms)
2017-03-23 14:27:39 WARN   No meta-data value exists with key `buildkite:git:branch:lol`, returning the supplied default "lol"
lol%
```

`meta-data get --default` support

---

process/process.go

**Overview**
My Buildkite users have reported that ANSI escape codes are not always rendered properly, for example:
This PR resolves a memory corruption issue stemming from incorrect use of the `bufio.Readline` API.
**Details**
At first I assumed this was a bug related my change in https://github.com/buildkite/agent/pull/430, however re-running my minimal test case sometimes produced seemingly correct output:
I started investigating the buffering code inside `process.go` and found the cause for the random corrupted output. This is a trace:
**Iteration 1: Fill line buffer**
```
017-03-23 22:21:06 INFO   [LineScanner] Line is too long to read, going to buffer it until it finishes
"\x1b[?25l\r\x1b[K    2% |\u2589                               | 10kB 40.6MB/s eta 0:00:01\r\x1b[K    5% …
```

Fix buffer corruption

---

install.sh

FreeBSD's `uname -sm` returns `FreeBSD amd64` not `x86_64`, so we need 
to ensure that the agent installs the 64-bit version on 64-bit flavours.

freebsd: fix architecture detection

---

agent/agent_configuration.go
agent/agent_pool.go
agent/agent_worker.go
clicommand/agent_start.go
cliconfig/loader.go

When creating container-based schedulers and runners you often want the runner to exit after running the job (e.g. [hyper-buildkite-agent](https://github.com/toolmantim/hyper-buildkite-agent))
This adds a command line flag that causes the agent to shut down once it's completed a job.

Add --disconnect-after-job command line arg

---

agent/bootstrap.go

To go with the updated "Securing your Agent" documentation in buildkite/docs#101, this allows you to prevent plugin code being checked out onto the agent machine by doing whitelisting/validation in your global environment hook.

Run the global environment hook before checking out plugins

---

agent/plugin.go
agent/plugin_test.go

Github now uses `.git` on their HTTP git urls. For example, https://github.com/buildkite-plugins/docker-compose-buildkite-plugin.git instead of https://github.com/buildkite-plugins/docker-compose-buildkite-plugin.
If you use the HTTP version of plugin configuration, such as this:
```yml
steps:
- command: test.sh
plugins:
https://github.com/buildkite-plugins/docker-compose-buildkite-plugin.git#v1.1
config:
test/docker-compose.yml
```
you'll get environment variables with the extra `_GIT` in them. For example:
```bash
BUILDKITE_PLUGIN_DOCKER_COMPOSE_GIT_CONFIG=test/docker-compose.yml
```
instead of:
```bash
BUILDKITE_PLUGIN_DOCKER_COMPOSE_CONFIG=test/docker-compose.yml
```
This updates our plugin configuration gear to support the new `.git` URLs.

Add plugin support for HTTP repositories with .git extensions

---

agent/bootstrap.go

This let's the OS decide which shell to use to interpret the command. For example, Alpine Linux doesn't have /bin/bash, so if you try to run the generated command script inside Alpine Linux (via Docker) it fails. The fix for Alpine Linux is to install bash (in addition to the shell that already comes with it).
[This StackOverflow thread](http://stackoverflow.com/questions/5725296/difference-between-sh-and-bash) outlines some differences, but there's nothing I can see that pops out.
And I think letting the OS decide which shell to use, is probably a good idea.

Use /bin/sh instead of /bin/bash

---

templates/bootstrap.sh

Reverts buildkite/agent#449 - this should have been in 2-5-stable

Revert "Use /bin/sh instead of /bin/bash (2.1 stable)"

---

agent/agent_pool.go
api/agents.go
clicommand/agent_start.go
cliconfig/loader.go
main.go
packaging/github/linux/buildkite-agent.cfg
packaging/github/windows/buildkite-agent.cfg
packaging/linux/root/usr/share/buildkite-agent/buildkite-agent.cfg

There has been a long proposed change to the Buildkite Agent terminology and command line API for rename "meta-data" to "tags".
This would change:
```bash
buildkite-agent start \
--meta-data docker \
--meta-data postgres=9 \
--meta-data postgres=9.4 \
--meta-data queue=runner \
--meta-data queue=docker
```
to:
```bash
buildkite-agent start \
--tag docker \
--tag postgres=9 \
--tag postgres=9.4 \
--tag queue=runner \
--tag queue=docker
```

Rename meta-data to tags

---

agent/bootstrap.go
packaging/linux/root/usr/share/buildkite-agent/hooks/post-artifact.sample
packaging/linux/root/usr/share/buildkite-agent/hooks/pre-artifact.sample
packaging/linux/root/usr/share/buildkite-agent/hooks/pre-exit.sample

This extends our [list of hooks](https://buildkite.com/docs/agent/hooks) to add another hook: `pre-exit`. The `pre-exit` hook runs before the command exits, allowing you to perform cleanup tasks.
`post-artifact` isn't suitable for performing general cleanup tasks, because it's only run if an artifact upload pattern has been specified.

Add `pre-exit` hook support

---

shell/environment.go
shell/environment_test.go

Now handles cases like:
```
declare -x HTTP_PROXY="http://proxy.example.com:1234/"
declare -x LANG="en_US.UTF-8"
declare -x LOGNAME="buildkite-agent"
declare -x SOME_VALUE="this is my value"
declare -x `
declare -x SOME_OTHER_VALUE="this is my value across
new
lines"
declare -x OLDPWD2
```
Where `OLDPWD` is totally valid, but doesn't look like an environment variable. I had to rewrite the parser to get it to work, but it's much cleaner and easier to read now.

Added more test cases and rewrote the `export -p` parser

---

shell/command.go
shell/environment.go
shell/lookpath.go
shell/lookpath_windows.go

We had a regression in Windows with some of the environment path handling (pretty much, all the things broke). This PR changes:
- `lookPath` needed to respect file extensions such as `.exe`, `.bat`, etc.
- `env.Get`, `env.Set`, etc need to ignore key case on Windows
So everything should be working again!

Fix `lookPath` and `env.Get` on Windows

---

agent/agent_pool.go
clicommand/agent_start.go

This addresses #491. TL;DR is that AWS often takes quite some time to apply tags to a running instance, specifically when in an Autoscaling Group.
**Update**
Based on feedback this has changed to be the default behaviour with a timeout to opt-out of. This means if you enable `tags-from-ec2-tags` then we will wait up to 15 seconds for tags (any tags) to be made available. If you don't set tags, but you set `tags-from-ec2-tags` YOU WILL WAIT 15 SECONDS.

Wait for EC2 tags to be available before registering the agent

---

agent/aws.go
agent/ec2_meta_data.go
agent/ec2_tags.go
agent/s3.go

This creates a session for the ec2 metadata and tags api calls, nil is no longer ok.
Also, I noticed that there is a regression where the new sdk needs `AWS_REGION` or `AWS_DEFAULT_REGION` set, otherwise it fails. I added a heuristic similar to what we used previously, e.g if it's running in AWS then use that region.

Hotfix breakages from new aws sdk

---

templates/bootstrap.sh

Show the fetched commit sha when performing a git fetch for a pull request head. For a successful case this looks like:
For a problematic case this looks like:
This should help us determine whether stale pull request heads are the cause of these "reference is not a tree" issue, and potentially give us a workaround.
I'll add the same behaviour to the beta agent once this is merged.

Debug output during git fetch for pull request

---

agent/plugin.go
agent/plugin_test.go

If you use booleans in your plugin config YAML (such as the `verbose: true` flag in the [docker-compose plugin](https://github.com/buildkite-plugins/docker-compose-buildkite-plugin)) you get a warning printed after your build output:
The only way to specify a boolean at the moment is with the string version (`"true"`).
This adds boolean handling, so it sets an env var value of `"true"` for `true` and `"false"` for `false`. 
For example:
```yaml
steps:
- plugins:
docker-compose#v1.4.0:
run: tests
verbose: true
```
becomes:
```bash
BUILDKITE_PLUGIN_DOCKER_COMPOSE_VERBOSE=true
```
…and:
```yaml
steps:
- plugins:
docker-compose#v1.4.0:
run: tests
verbose: false
```
…becomes:
```bash
BUILDKITE_PLUGIN_DOCKER_COMPOSE_VERBOSE=false
```

Fix boolean plugin config parsing

---

bootstrap/bootstrap.go

Add submodule remotes to known_hosts as part of the checkout process. 
Fix for #503

Add submodule remotes to known_hosts

---

templates/bootstrap.sh

Hooks are invoked using the `source` keyword in `bootstrap.sh`. Before they are sourced, they are made executable. I believe this is unnecessary:
```
Wed Aug  2 06:58:06 UTC 2017
```
This unnecessary `chmod` is causing me some trouble when mounting my hooks on a read only filesystem.
Firstly, this error appears before every hook:
> chmod: changing permissions of '/buildkite/hooks/environment': Read-only file system
Secondly, the UI indents things weirdly:
Lastly, here's a cat in a sink:

Stop making hook files executable

---

bootstrap/bootstrap.go

https://github.com/buildkite/agent/issues/507
The `Fetch and checkout commit` codepath (the last one) is the one that I actually saw the problem affect and this change fix, but the other paths look like they might get caught by the same scenario.
I left the `refs/pull/…/head` and `commit-sha` fetches unchanged because I figure that they wouldn't need the pruning.

Prune when fetching with a refspec

---

.buildkite/pipeline.yml
Dockerfile
docker-compose.override.yml
docker-compose.release.yml

This adds a local Dockerfile that will compile the agent during development. 
It doesn't aim to replace https://github.com/buildkite/docker-buildkite-agent

Add a dockerfile for local development

---

bootstrap/bootstrap.go
bootstrap/knownhosts.go
bootstrap/shell/shell.go

I broke checkout of plugins with versions in #530 with a bad merge. This fixes it as well as cleaning up a few other things I noticed.

Fix plugin checkout from bootstrap rewrite

---

.dockerignore
Dockerfile
docker-compose.override.yml
docker-compose.yml

The docker container for the buildkite-agent wasn't working, I suspect because the volume mount was clobbering the binary that was built.
This cleans it up and also sets up the command so that it connects to our local dev environment when in development (e.g when the .override.yml is loaded).

Get local docker container working

---

Dockerfile

This bumps the docker container to the latest golang, which means our binaries get built with it. Impact should be absolutely minimal.

Use latest golang 1.9

---

bootstrap/bootstrap.go
bootstrap/git.go
bootstrap/knownhosts.go
bootstrap/shell/shell.go

I think that the api we came up with for `shell.Run` and `shell.RunAndCapture` taking a string and then shell splitting it internally is too risky. It means we are relying on %q to do shell quoting for us amongst other things. It also seems less "go-like".
This goes back to passing slices of strings around, for better or worse. Feels?

Revert to a string slice passing api for shell.Run

---

agent/gs_uploader.go

Problem
---
- The URL for artifacts uploaded to GCS are api links.
- Following the link in browser yields an XML error page.
- The URL buildkite puts is under `storage.googleapis.com` but to leverage the oath prompt mentioned above users need to access objects under `storage.cloud.google.com`.
- I couldn't find anything from buildkite's doc equivalent to BUILDKITE_S3_ACCESS_URL for Google Cloud.
Alternatives
---
- When a user clicks a link in browser, you should use `storage.cloud.google.com`.
- This flow is for humans, not machines - so it should be optimized for that experience
- When a user fetches a link via API, you should use `storage.googleapis.com`
- This flow is for machines, not humans - so it should be optimized for that experience
This change would be simple but allow for us …

Add BUILDKITE_GCS_ACCESS_HOST for GCS Host choice

---

templates/bootstrap.sh

Useful for preventing hostile hooks in the repository from escaping whatever
chroot/container/etc mechanism may be in use around the build commands.

Disallow local hooks if BUILDKITE_NO_LOCAL_HOOKS is set.

---

bootstrap/knownhosts.go

[Hostname()](https://golang.org/pkg/net/url/#URL.Hostname) returns Host without any port number.
This shouldn't clash with #561 looking at the diff, but should be complementary.
Closes #564.

Fix ssh keyscan for urls with ports

---

agent/s3.go

When using a custom artifact bucket which constructs an S3 client the agent can segfault when falling through to obtaining AWS credentials for an instance role from EC2 meta-data because it's missing a Client. Looking deeper into how it's done within the aws-sdk it [looks like they use RemoteCredProvider](https://github.com/buildkite/agent/blob/fix-artifact-segfault/vendor/github.com/aws/aws-sdk-go/aws/session/session.go#L460) which also supports ECS, so I've switched to that.

Fix custom artifact bucket segfault

---

bootstrap/bootstrap.go

Currently we show a LOT of headers in the 3.x agent. This removes "Running hook" headers if the header doesn't exist.

Only show "Running hook" if one exists

---

agent/pipeline_parser.go
agent/pipeline_parser_test.go

Previously a nil env would result in system environment being added. This changed recently and since then pipeline upload hasn't received system environment.
🤦🏼‍♂️

Fix bug where pipeline upload doesn't get environment passed correctly

---

process/process.go

👋 
This may be too much of a kludge for you folks but at Discord we've been frustrated by the inability to cancel Windows jobs for ages. This fallback seems to work and I wonder if you are interested in merging it until a proper long-term fix is available?
Related issues: https://github.com/buildkite/agent/issues/213 https://github.com/buildkite/agent/issues/345
For any drive-by readers I've hosted build 2.6.6 + this fix over on [our fork](https://github.com/discordapp/buildkite-agent/releases/tag/discord-v2.6.6-1). YMMV, caveat emptor, etc.

fallback to TASKKILL on windows

---

bootstrap/knownhosts.go

I forgot to support this in the initial implementation, this adds support for hashed hostnames.

Support hashed hostnames in .ssh/known_hosts

---

bootstrap/bootstrap.go
bootstrap/hook.go
bootstrap/hook_test.go
bootstrap/integration/hooks_integration_test.go
bootstrap/shell/shell_test.go
vendor/github.com/lox/bintest/mock.go
vendor/github.com/lox/bintest/proxy/compiler.go
vendor/github.com/lox/bintest/proxy/proxy.go
vendor/github.com/lox/bintest/proxy/server.go
vendor/vendor.json

It's common in v2 agent hooks to change directories and expect it to affect subsequent hooks, for instance you might want to change the working directory in a `pre-command` hook for a monorepo. 
This PR makes that happen.

Pass working dir between hooks

---

vendor/github.com/buildkite/interpolate/parser.go
vendor/vendor.json

There was a parser bug in the new expansion interpolator (https://github.com/buildkite/interpolate). This caused infinite loops when trying to interpolate certain strings like `\` or `$`.

Bump interpolate library. Closes #585.

---

clicommand/pipeline_upload.go

Some example 422 responses on pipeline upload:
```
WARN   POST https://agent.buildkite.com/v3/jobs/<uuid>/pipelines: 422 One of the steps you provided was invalid: can't be blank, The step type supplied is not supported (Attempt 1/5 Retrying in 1s)
WARN   POST https://agent.buildkite.com/v3/jobs/<uuid>/pipelines: 422 One of the steps you provided was invalid: The reason provided to `skip` is too long. The maximum length is 70 characters (Attempt 1/5 Retrying in 1s)
```
These will never succeed on retry, so save some time by bailing early.
 

Don't retry pipeline uploads on 422 responses

---

process/process.go

**Problem**
In https://github.com/buildkite/agent/pull/438 I added a `regex` which insures the timestamp option (`--timestamp-lines=true`) does not prefix header expansion directives (`^^^ +++`). At some point since that PR this feature has broken again, and timestamps are being added therefore failing to expand headers.
**Solution**
Modify the `regex` to accept optional trailing whitespace.
**Steps to reproduce**
Run agent as follows:
> ./buildkite-agent start --build-path=/tmp --debug --token "FOOBAR" --tags=queue=my-debug-queue --timestamp-lines=true
With this simple pipeline:
```
#!/usr/bin/env bash
set -e
echo "Hello world"
echo "--- My first group"
echo "foobar"
echo "--- My second group"
echo "foobar"
echo "^^^ +++"
echo "--- My third group"
echo "foobar"
```
The second group will …

Match header expansion with trailing whitespace

---

agent/artifact_uploader.go
agent/artifact_uploader_test.go

This fixes an issue raised by @patrobinson:
>:wave: we updated to v2.6.7 recently and it seems while previously uploading an artifact that didn’t exist, not it causes a fatal error:
```$ buildkite-agent artifact upload log/\*\;\ tmp/capybara/\*\*/\*\;\ mkmf.log
2017-11-23 22:54:21 FATAL  Failed to upload artifacts: file does not exist
🚨 Buildkite Error    0s
Unable to upload artifacts
```
This was introduced when we moved to zglob in https://github.com/buildkite/agent/commit/7e1320bbbcdec75fc98beb2600e63308b12c1333.

Fix a regression where artifact uploader returns error on no match

---

agent/s3_uploader.go
vendor/github.com/AdRoll/goamz/s3/s3.go

Removes our wholesale buffering of s3 uploaded artifacts into memory by using PutReader (which is what goamz is doing under the hood anyway), and patches an issue introduced by newer Golang's net/http which was fixed upstream in https://github.com/goamz/goamz/pull/135. 
From [net/http docs](https://golang.org/pkg/net/http/):
> ContentLength records the length of the associated content.
>
> For client requests, a value of 0 with a non-nil Body is  also treated as unknown.
This is not an issue in master (v3 beta) because we've replaced goamz with the official aws-sdk.

S3 streaming and zero size fixes

---

packaging/github/linux/buildkite-agent.cfg
packaging/github/windows/buildkite-agent.cfg
packaging/linux/root/usr/share/buildkite-agent/buildkite-agent.cfg

As part of v3, we updated the defaults for `git-clean-flags` to add `-x`. It doesn't look like this is reflected in the packaging default configs. This updates them.

Update buildkite-agent.cfg to show new defaults for git-clean-flags

---

.buildkite/pipeline.yml
scripts/build-yum-packages.sh
scripts/publish-rpm-package.sh

When we moved to different pipelines, I missed that the yum package build step conflated build and publish. This breaks currently, as the beta and stable pipelines don't have access to artifacts created as part of the experimental build.

Build yum packages in the main pipeline

---

clicommand/agent_start.go
packaging/github/linux/buildkite-agent.cfg
packaging/github/windows/buildkite-agent.cfg
packaging/linux/root/usr/share/buildkite-agent/buildkite-agent.cfg

Automatically detects the path to the running binary and uses that as a default for the bootstrap-script path. This makes it a little easier to develop against as `go run` will work.

Use a default value for bootstrap-script

---

agent/artifact_uploader.go
agent/artifact_uploader_test.go

This also brings in a revamped test for the uploader that I've been working on for windows compatibility. 
Closes #619.

Fix bug where a failing glob would cause later globs to be ignored

---

process/process.go
process/process_test.go
scripts/tests.sh

This adds test coverage for `process.Process` and fixes a race that is caused by the jobRunner calling `process.Output()` in go routine: https://github.com/buildkite/agent/blob/e3fa0d1ed2f46fd001382586dfcd478bed97ce99/agent/job_runner.go#L259-L273
The fix is a `bytes.Buffer` that is wrapped with a RWMutex. 
Originally part of https://github.com/buildkite/agent/pull/599.

Fix race condition in process.Process

---

bootstrap/bootstrap.go
bootstrap/integration/hooks_integration_test.go

Adds a environment variable to cause the bootstrap to refuse to run local hooks. 
See https://github.com/buildkite/agent/pull/524.

Port BUILDKITE_NO_LOCAL_HOOKS from #524

---

bootstrap/shell/shell.go

Ooops. Actually implement the branch logic that was supposed to be core in #625.

Actually apply the Stdout/Stderr flags in shell.executeCommand

---

.buildkite/pipeline.windows.yml
.buildkite/pipeline.yml
.dockerignore
Dockerfile-windows
README.md
docker-compose.windows.yml
scripts/tests.bat
scripts/tests.sh

This adds a step that runs the tests on a Windows 2016 w/ Containers instance in another asynchronous pipeline. This means we can still see windows failures while we iterate on fixing them.
For the actual infrastructure, I created a hand-rolled m4.large windows instance running Windows 2016 Server. Will replace with something more scalable when we need it.

Add a windows testing step

---

bootstrap/git.go
bootstrap/integration/checkout_integration_test.go

Previously `git remote get-url origin` was used to determine the origin url for submodules. This was only introduced in git 2.7, so it caused errors on older installations (e.g Ubuntu 14.04). 
This replaces it with `git config --get remote.origin.url`, which from what I can tell should be backwards compatible and acomplish the same thing.
Closes #602.

Support older git versions with submodules

---

env/export.go
env/export_test.go

See bug reported in https://github.com/buildkite/agent/pull/569.

Fix bug where env export had trailing \r on windows

---

bootstrap/git.go
bootstrap/git_test.go
bootstrap/knownhosts.go

This change handles parsing urls like `file:///C:/Users/vagrant/repo`.

Fix parsing of git urls with windows volumes in them

---

Dockerfile-windows
docker-compose.windows-dev.yml
docker-compose.windows.yml

This took me ages, it's now a working environment for mounting in code from macOS all the way through to a VMWare-based windows VM. Makes iterating on windows stuff much easier.

Add a windows-dev docker-compose for development

---

process/process.go

Turns out github.com/mattn/go-shellwords mangles windows paths. `C:\scripts\bootstrap.bat` becomes `C:scriptsbootstrap.bat`.

Handle windows paths in process.Process

---

mime/mime.go

We have a lot of these :) I can't find a good central authority for default mime types, but at least python will detect `text/plain`, so we won't be blazing a trail.
```
Python 2.7.13 (default, Dec 18 2016, 07:03:39)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import mimetypes
>>> mimetypes.guess_type('foo.log')
('text/plain', None)
```

Add log extension with type of 'text/plain'

---

.buildkite/pipeline.yml
docker-compose.yml
scripts/junit.sh
scripts/tests.sh

Currently the go test output gets mangled by our header detection. This uses richgo and also grabs the junit xml output.

Format go test output and output junit xml

---

bootstrap/hook_test.go
bootstrap/integration/bootstrap_tester.go
bootstrap/integration/docker_integration_test.go
bootstrap/integration/hooks_integration_test.go
bootstrap/integration/main_test.go
bootstrap/integration/plugin_integration_test.go
bootstrap/shell/shell_test.go

Now that there is a windows test suite and dedicated agent, this fixes all of the broken tests.
I don't love how we have to generate test scripts for windows/nix in the integration tests, but it was the simplest way forward. When #636 lands, we can possibly ditch them, although I think exercising our code with windows batch files is probably worthwhile.

Fix broken tests for windows

---

agent/gs_uploader.go

Closes #634 
This makes the default filenames more sensible when downloading from GCS in a browser:
I have tested this with directory trees and files with spaces in the name, they are handled correctly.

Set Content-Disposition on uploads to GCS

---

clicommand/annotate.go
clicommand/pipeline_upload.go

I broke pipeline uploads from stdin in #636. I removed the previous `IsStdin` technology in favour of  https://godoc.org/golang.org/x/crypto/ssh/terminal#IsTerminal, but I neglected to account for them having opposite meanings. 😓

Fix incorrect polarity on IsTerminal check

---

bootstrap/hook.go

If a disk fills up or for some other reason we fail to write this hook file contents the bootstrap just plods along anyway, running an empty script file. So check for errors during the write. Also a couple of other little tweaks nearby.

Check hook script write

---

.buildkite/pipeline.windows.yml
.buildkite/pipeline.yml

Due to recent issues with our windows instances being flakey, this moves things back to an asynch pipeline trigger of the windows-agent pipeline.

Move windows agent tests back to asynch

---

agent/plugin.go
agent/plugin_test.go

I noticed that this silently proceeds with the current agent:
```
steps:
- name: ":hammer: :golang:"
plugins:
golang-build#1a1e0cd:
build: main.go
package: github.com/lox/parfait
targets:
- version: 1.10.0
goos: linux
goarch: amd64
```
The issue is the complex map and array combination. There is no actual error, just a console output of:
```
Unknown type map[string]interface {} map[version:1.10.0 goos:linux goarch:amd64]
```
This PR addresses that, as well as generally cleaning up and simplifying the plugin config encoding.

Support (and test) more complex types in plugin config

---

agent/agent_configuration.go
agent/job_runner.go
bootstrap/bootstrap.go
bootstrap/config.go
bootstrap/docker.go
bootstrap/integration/docker_integration_test.go
clicommand/agent_start.go
clicommand/bootstrap.go
process/format.go

Currently the agent guesses the shell based on your operating system, either `/bin/bash` on nix or `cmd` on windows.
This allows for the shell used for interpreting `$BUILDKITE_COMMAND` to be configured. 
IMO eventually we should default to `/bin/sh`, but for backwards compat, we will go with `/bin/bash`.
This controversially also ditches the behaviour where we write a shellscript for each command to be executed.

Allow the shell interpreter to be configured

---

bootstrap/integration/bootstrap_tester.go
bootstrap/shell/shell.go

This just makes it possible to show bootstrap output in the integration tests when `DEBUG_BOOTSTRAP=1`.

Add back bootstrap output debugging with env DEBUG_BOOTSTRAP

---

agent/plugin_test.go

Interested to see how you feel about this specific usage of the golang subtest / table-driven test approach @keithpitt.

Refactor plugin tests to use a table-driven style

---

clicommand/annotate.go
clicommand/pipeline_upload.go
stdin/main_test.go
stdin/stdin.go

This goes back to how we used to handle stdin, with a simple `stdin` package and a basic golang check vs `golang.org/x/crypto/ssh/terminal`.
It also adds tests!
Closes  #655.

Fix stdin detection on windows

---

templates/bootstrap.bat

Seems submodule checkout is missing in 2.6 but it is available in non-windows version.
https://github.com/buildkite/agent/issues/52.
I'd personally prefer to disable submodule by default but I've enabled it following the non-windows implementation.

add submodule checkout to windows agent

---

bootstrap/bootstrap.go

Otherwise scripts must have a shebang, or they fail silently. It's the difference between ./my_script and bash -e -c "./my_script". This is currently broken in beta 40.
Note: bash is smart enough to not create another shell when the only argument to -c is another shell script. 👌🏻

Run scripts via the shell, rather than invoking with exec

---

bootstrap/integration/checkout_integration_test.go
bootstrap/knownhosts.go

This skips trying to ssh-keyscan urls that aren't git/ssh.

Only keyscan git/ssh urls

---

bootstrap/bootstrap.go
bootstrap/integration/checkout_integration_test.go

The agent is currently incorrectly detecting newly created checkout dirs as corrupt (#574). Not a huge impact, but creates noisy output with `git-revparse` on every checkout.
This moves the corrupt detection into the defaultCheckout method, so that it's retried and also so that you can opt-out of it by overriding the checkout hook.

Prevent incorrect corrupt git checkout detection on fresh checkout dir creation

---

agent/job_runner.go

Follow on from #680 and #643. Changes the env-file format to KEY="VALUES" with values in the quotes escaped. 
This won't be compatible with docker (see the horror of https://github.com/moby/moby/issues/12997), but it's the generally accepted standard (https://github.com/bkeepers/dotenv/blob/master/lib/dotenv/parser.rb and https://github.com/joho/godotenv/blob/master/godotenv.go, for example) and it's easy to parse with standard shell tools.

Quote and escape env-file values

---

agent/agent_configuration.go
agent/job_runner.go
clicommand/agent_start.go
packaging/github/linux/buildkite-agent.cfg
packaging/github/windows/buildkite-agent.cfg
packaging/linux/root/usr/share/buildkite-agent/bootstrap.sh
packaging/linux/root/usr/share/buildkite-agent/buildkite-agent.cfg
scripts/utils/build-github-release.sh

This adds a bootstrap.sh shim that gets installed at the same location as the old v2.x bootstrap that prints a warning and then runs `buildkite-agent bootstrap`. This should mean that users that upgrade from v2 -> v3 don't run into problems because their config still refers to the v2 bootstrap.sh.

Handle upgrading bootstrap-path from old 2.x shell script

---

agent/agent_pool.go
bootstrap/bootstrap.go
clicommand/agent_start.go

Fixes https://github.com/buildkite/agent/issues/674

Enabling `no-command-eval` will also disable use of plugins

---

agent/pipeline_parser.go
agent/pipeline_parser_test.go
vendor/github.com/buildkite/yaml/NOTICE
vendor/github.com/buildkite/yaml/README.md
vendor/github.com/buildkite/yaml/apic.go
vendor/github.com/buildkite/yaml/decode.go
vendor/github.com/buildkite/yaml/emitterc.go
vendor/github.com/buildkite/yaml/encode.go
vendor/github.com/buildkite/yaml/go.mod
vendor/github.com/buildkite/yaml/resolve.go
vendor/github.com/buildkite/yaml/scannerc.go
vendor/github.com/buildkite/yaml/writerc.go
vendor/github.com/buildkite/yaml/yaml.go
vendor/github.com/buildkite/yaml/yamlh.go
vendor/vendor.json

In #668 we made some changes to the underlying YAML library which have caused a regression where bools, ints, floats and null get juggled to strings before being uploaded as JSON.
This passes through those types and panics if an unhandled type is encountered.
Closes https://github.com/buildkite/agent/issues/695.

Preserve types in pipelines

---

bootstrap/integration/docker_integration_test.go

This brings the integration tests for docker inline with the batch file generation we re-introduced in #692.

Fix failing windows docker tests

---

agent/agent_configuration.go
agent/job_runner.go
clicommand/agent_start.go

The v2 bootstrap used to support `BUILDKITE_DISABLE_GIT_SUBMODULES` (via #168). 
This exposes that option (also `BUILDKITE_NO_GIT_SUBMODULES`).

Expose no-git-submodules config and arg to start

---

install.ps1
install.sh

This adds a powershell install script so that we can have users do windows installs with:
```powershell
$env:buildkiteAgentToken = "my_token"
$env:buildkiteAgentBeta = 'true'
Set-ExecutionPolicy Bypass -Scope Process -Force
iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/buildkite/agent/master/install.ps1'))
```

Windows install script

---

.buildkite/pipeline.release-experimental.yml
.buildkite/pipeline.release-stable.yml
.buildkite/pipeline.release-unstable.yml
.buildkite/pipeline.yml
Dockerfile
Dockerfile-windows
packaging/docker/linux/Dockerfile
packaging/docker/linux/entrypoint.sh
scripts/build-docker-images.sh
scripts/publish-docker-images.sh

Currently docker images are build via an async trigger to a pipeline that builds from https://github.com/buildkite/docker-buildkite-agent.
That repository builds images for all our versions (beta, stable and edge), regardless of what was actually built. 
This moves the docker packaging and building into the agent pipeline and only builds images for the current agent version. The following tags are created:
* For beta releases: 3.0-beta.42.2243 is tagged as beta, 3.0-beta.42, 3.0 and 3
* For edge releases: 3.0-beta.42.2243 is tagged as edge and edge-build-2243
* For stable release: 2.6.10 is tagged as stable, latest, 2.6.10, 2.6 and 2
Once this is in place, we can probably entirely remove the old https://github.com/buildkite/docker-buildkite-agent repo.

Build docker image as part of agent pipeline

---

agent/agent_configuration.go
agent/job_runner.go
bootstrap/bootstrap.go
bootstrap/config.go
clicommand/agent_start.go
clicommand/bootstrap.go

This adds a `no-local-hooks` config for the agent. Global hooks can still set `BUILDKITE_NO_LOCAL_HOOKS` on a case-by-case basis.

Add an agent config for no-local-hooks

---

bootstrap/bootstrap.go
bootstrap/git.go
bootstrap/integration/checkout_integration_test.go

Currently we run a lot of git operations that deal with submodules, regardless of whether there are submodules or not. These are particularly slow on windows.
This change only runs git submodule operations if there is a `.gitmodules` file.

Only run git submodule operations if there is a .gitmodules

---

.buildkite/pipeline.release-stable.yml
.buildkite/pipeline.release-unstable.yml
scripts/extract-agent-version-metadata.sh
scripts/github-release.sh
scripts/release-homebrew.sh
scripts/upload-release-steps.sh

Previously we were doing the github release and homebrew release only in the beta pipeline, which meant that when we released 3.0.0 it shipped even before the stable release pipeline was unlocked, which was very unexpected (for me).
This looks at the pipeline and skips the github and homebrew step depending on whether the version is a pre-release or not.

Upload github release and homebrew in beta/stable pipelines

---

install.ps1

Hi guys,
I discovered a typo in the naming convention of an environment variable ($env:buildkiteAgentTags) which is missing the letter 'd'.
Mark.

Fixed typo in line 5 - Missing 'd' in buildkite

---

scripts/release-homebrew.sh

The next version of macOS will [not fully support 32-bit binaries](https://developer.apple.com/news/?id=06282017a), but we're still shipping a 32-bit buildkite agent via Homebrew. This improves the script a little and adds portability, mostly so I could test it on a darwin system, then changes the arch to amd64.

Homebrew 64-bit binaries

---

agent/s3_uploader.go
agent/s3_uploader_test.go
mime/mime.go

This reverts #494, is it creates a confusing behaviour where when you uploading a gzipped artifact and then download it in a later step the file gets un-gzipped.

Don't set Content-Encoding on s3 upload

---

agent/artifact_uploader.go

I did this in a script, to upload some JUnit xml files:
```bash
buildkite-agent artifact upload *.xml
```
and it failed with this error message:
This had me very confused for a few hours, until I realised that there was a second argument to upload called "upload destination" — I had assumed that the error message on upload destination was that I had misconfigured my agent, or it was a backend problem.
What I needed to do was:
```bash
buildkite-agent artifact upload "*.xml"
```
This PR tries to provide a less confusing error message if people accidentally provide a second argument to the `artifact upload` command.

Try to help people that forget to quote their upload globs

---

Dockerfile-github-release
packaging/docker/linux/Dockerfile

Per buildkite/feedback#348, it's all on the 🥫

Bump our Docker image base to alpine v3.7

---

agent/pipeline_parser.go
agent/pipeline_parser_test.go
clicommand/pipeline_upload.go

This allows for interpolation to be disabled in `buildkite-agent pipeline upload`.
Closes #715.

Support `--no-interpolation` option in `pipeline upload`

---

bootstrap/shell/shell.go

The move to a golang bootstrap in 3.0 has meant that we miss out on a few things that the previous bash bootstrap was giving us that we didn't realize. 
In this PR I am setting `TERM` when a tty is created and `PWD`. The other minimum env that a shell gets is usually `PATH`, `HOME` and `HOSTNAME`, but these are up to `login` to set, which for us I think is in the systemd config or similar. 
I verified these were a thing with: 
```
docker run --rm alpine:3.3 env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=978593e25f81
HOME=/root
```
```
docker run --rm -it alpine:3.3 env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=032e49df3771
TERM=xterm
HOME=/root
```
```
docker run --rm -it alpine:3.3 sh -c env
HOSTNAME=dfd4924645b5
SHLVL=1 …
```

Set TERM and PWD for commands that get executed in shell

---

bootstrap/bootstrap.go
bootstrap/integration/checkout_integration_test.go
vendor/github.com/buildkite/bintest/README.md

We've never used this information, and it's useless anyway because we're doing detached checkouts so all it returns is:
* (HEAD detached at FETCH_HEAD)
or
* (no branch)
Turns out it can take a long time to run on big repos to tell us nothing, so just remove it.

Remove buildkite:git:branch meta-data

---

agent/api_client.go
agent/api_proxy.go
agent/api_proxy_test.go
agent/job_runner.go
api/auth.go

Currently we pass jobs `BUILDKITE_AGENT_ACCESS_TOKEN`, which is a per-agent-connection session token that is derived from the Agent Registration Token. This token is then used by agent commands that run within jobs, like `buildkite-agent pipeline upload` and the `artifact` and `meta-data` sub-commands. 
The downside with this approach is that the access token can be easily stolen by untrusted jobs (see https://github.com/buildkite/feedback/issues/360). 
This PR implements a proxy that listens on a unix socket or a localhost http port and proxies through to the upstream https://agent.buildkite.com. This should radically improve the security profile, as if it's a unix socket then it's not possible to access externally, or exfiltrate. If it's http based, you need access to whatever it's …

Pass jobs an authenticated unix socket rather than an access token 

---

scripts/build-rpm-package.sh

Allow package to be matched as `buildkite-agent-<major version>` ie
`yum install buildkite-agent-2`

Add a virtual provides to the RPM package

---

agent/agent_pool.go
clicommand/agent_start.go
cliconfig/loader.go
vendor/github.com/urfave/cli/CODE_OF_CONDUCT.md
vendor/github.com/urfave/cli/CONTRIBUTING.md
vendor/github.com/urfave/cli/MAINTAINERS.md
vendor/github.com/urfave/cli/README.md
vendor/github.com/urfave/cli/app.go
vendor/github.com/urfave/cli/command.go
vendor/github.com/urfave/cli/flag.go
vendor/github.com/urfave/cli/help.go
vendor/vendor.json

Currently, `buildkite-agent start --tags "a=1,b=2"` sets a single tag of `a=1,b=2`. This is a shortcoming of the upstream urfave.cli library (see https://github.com/urfave/cli/issues/62) which expects `--tags "a=1" --tags "a=2"`.
This adds a normalization for --tags and --experiments that makes them behave as expected.

Fix broken list parsing in cli arguments --tags and --experiments

---

bootstrap/bootstrap.go
bootstrap/integration/hooks_integration_test.go
bootstrap/integration/plugin_integration_test.go
bootstrap/shell/shell.go

Propagate exit code > 1 out of failing hooks

---

process/process.go

It turns out that the bufio.Scanner doesn't handle really long tokens, so we need to do it ourselves.
@keithpitt, yes I know, you told me so.
Closes #775.

Revert "Replace bufio.Reader with bufio.Scanner"

---

EXPERIMENTS.md

This adds an `EXPERIMENTS.md` which lists agent experiments available.

Experiments docs and experiment cleanup

---

vendor/github.com/kr/pty/mktypes.bash
vendor/github.com/kr/pty/pty_darwin.go
vendor/github.com/kr/pty/pty_dragonfly.go
vendor/github.com/kr/pty/pty_freebsd.go
vendor/github.com/kr/pty/pty_linux.go
vendor/github.com/kr/pty/pty_openbsd.go
vendor/github.com/kr/pty/pty_unsupported.go
vendor/github.com/kr/pty/ztypes_openbsd_amd64.go
vendor/vendor.json

This corrects "unsupported" on OpenBSD.  Hasn't been tested for regression, although the diff between vendor hashes includes only a fix for leaky file descriptors, and OpenBSD support:
https://github.com/kr/pty/pull/57
https://github.com/kr/pty/pull/58

Updated github.com/kr/pty for OpenBSD support.

---

bootstrap/bootstrap.go

We previously removed the checkout dir when `git remote set-url` fails or when `git clone` fails, but we don't on `git clean`. If there are corrupted submodules, then `git clean` will fail, leaving a corrupted working dir. 
This adds the `remote checkout dir on error` behaviour to `git clean` as well.

Remove the checkout dir when git clean fails

---

bootstrap/integration/bootstrap_tester.go
bootstrap/integration/hooks_integration_test.go

This tests how the `pre-exit` hooks operate after a cancel. In short, they work.

Add a test for pre-cancel hooks after cancel

---

clicommand/agent_start.go

By default plugins are disabled when no-command-eval or no-local-hooks is set. This allows a way around that.
I kind of hate the syntax of `--no-plugins=true`, and I hate even more the ternary nature of this, in that we only look at the `false` value if it's specifically set vs just the default value. Suggestions welcomed.

Allow --no-plugins=false to force plugins on

---

process/process.go

`/T` will make `taskkill` kill all the child processes as well.  This should improve the cancellation behavior. (#794) 
Please let me know if I should file a separate issue.

Cancellation on Windows: Pass `/T` to `taskkill`

---

agent/job_runner.go
bootstrap/bootstrap.go

We frequently have people try and set things like `BUILDKITE_GIT_CLEAN_FLAGS` in their pipeline global environment or per-step environment and get very confused why it doesn't work.
The reason it doesn't work is that we override certain environment variables for each build in the job runner to ensure they are correct as they are security sensitive: https://github.com/buildkite/agent/blob/c9645249f076beef3cebce34dc9980fe8c54d502/agent/job_runner.go#L264-L276
We do allow certain environment variables set by hooks to override these values, but we completely ignore values from the pipeline environment. 
~~This change rewrites the original values so they are available in the bootstrap if the user wants them, for instance `BUILDKITE_GIT_CLEAN_FLAGS` becomes `BUILDKITE_X_GIT_CLEAN_FLAGS`~~. The …

Warn in bootstrap when protected env are used

---

bootstrap/bootstrap.go
clicommand/bootstrap.go

Another take on #798, allows specific phases of the bootstrap to be executed.
```
$ buildkite-agent bootstrap \
--job "llamas" \
--repository "$PWD" \
--commit "HEAD" \
--branch "master" \
--agent "my-agent" \
--organization "buildkite" \
--pipeline "agent" \
--pipeline-provider git \
--build-path /usr/local/var/buildkite-agent/builds \
--phases "plugin,command" \
--command "echo hello world"
~~~ Running commands
$ echo hello world
hello world
```

Allow specifying which phases bootstrap should execute

---

bootstrap/bootstrap.go
clicommand/bootstrap.go

When running a bootstrap manually with just the checkout phase you need to be able to pass in the `BUILDKITE_BUILD_CHECKOUT_PATH` of where you have checked code out. This allows that, and also ensures that directory has been changed to at the start of the command phase. 
It also only uploads artifacts after the command phase, it doesn't make much sense to upload artifacts in bootstrap invocations where there is only a checkout phase.

Respect pre-set BUILDKITE_BUILD_CHECKOUT_PATH

---

clicommand/annotate.go

The `buildkite-agent annotate --help` output isn't quite correct. The command takes an annotation body as an arg, or reads from a pipe. It does not accept file paths.
@bjeanes is this better?

`annotate` takes body as an arg, or reads from a pipe

---

packaging/linux/root/usr/share/buildkite-agent/systemd/buildkite-agent.service
packaging/linux/root/usr/share/buildkite-agent/systemd/buildkite-agent@.service

Prompted by https://github.com/buildkite/agent/issues/476#issuecomment-417940614, this makes two changes:
* Increase `TimeoutStopSec` to 5mins from 10secs. This is the time between the initial `SIGTERM` and the final fatal `SIGKILL`. This gives the agent time to finish it's job.
* Set `KillMode` to `mixed`, vs the default of `control-group`. This means that the initial `SIGTERM` is sent to `buildkite-agent` directly, but the final `SIGKILL` to the control group. The agent [already sends shutdown signals to it's control group](https://github.com/buildkite/agent/blob/master/bootstrap/shell/signal.go#L19), so it can handle it.

Allow more time for systemd graceful stop

---

agent/agent_pool.go
agent/pipeline_parser.go
agent/pipeline_parser_test.go
agent/plugin/definition.go
clicommand/pipeline_upload.go
yamltojson/yaml.go

As reported in #728, the order of plugins in a pipeline don't respect source order in some cases. What was happening here was that the order was getting lost when converting to JSON. 
This PR implements a custom JSON serializer that reads the ordered YAML parse tree. It ends up being radically simpler and the code reads a bit better I think. 
Closes #728.

Ensure pipeline parser maintains map order in output

---

bootstrap/bootstrap.go

A race condition was reported in #763 where the concurrency lock for plugin checkout is only created after the plugin directory is created. 
This moves the lock earlier, which should prevent the problem.

Add plugin locking before checkout

---

bootstrap/bootstrap.go

It appears that with #827 we've introduced a bug where if the plugin directory doesn't exist the agent will never be able to acquire the checkout lock. The result is races with output like:
```
--
  | # Trying again in 1s...
  | # Could not acquire lock on "/usr/local/var/buildkite-agent/plugins/github-com-buildkite-plugins-docker-buildkite-plugin-v1-4-0.lock" (open /usr/local/var/buildkite-agent/plugins/969463144: no such file or directory)
  | # Trying again in 1s...
  | # Could not acquire lock on "/usr/local/var/buildkite-agent/plugins/github-com-buildkite-plugins-docker-buildkite-plugin-v1-4-0.lock" (open /usr/local/var/buildkite-agent/plugins/800153511: no such file or directory)
```
This PR fixes the issue by ensuring that the `PluginsPath` exists prior to acquiring the lock.

Ensure plugin directory exists, otherwise checkout lock thrashes

---

agent/pipeline_parser.go
agent/pipeline_parser_test.go

As part of #824 we accidentally introduced #829 due to a simplified heuristic around detecting pipeline.yml files with top-level arrays of steps.
This fixes that issues and adds some tests to prevent a recurrence. 
Closes #829.

Fix issue where top level steps failed to parse

---

agent/agent_worker.go

When running the latest version on arm systems I get the following:
```
_           _ _     _ _    _ _                                _
| |         (_) |   | | |  (_) |                              | |
| |__  _   _ _| | __| | | ___| |_ ___    __ _  __ _  ___ _ __ | |_
| '_ \| | | | | |/ _` | |/ / | __/ _ \  / _` |/ _` |/ _ \ '_ \| __|
| |_) | |_| | | | (_| |   <| | ||  __/ | (_| | (_| |  __/ | | | |_
|_.__/ \__,_|_|_|\__,_|_|\_\_|\__\___|  \__,_|\__, |\___|_| |_|\__|
__/ |
http://buildkite.com/agent                    |___/
2018-10-09 08:29:05 NOTICE Starting buildkite-agent v3.5.2 with PID: 16
2018-10-09 08:29:05 NOTICE The agent source code can be found here: https://github.com/buildkite/agent
2018-10-09 08:29:05 NOTICE For questions and support, email us at: hello@buildkite.com …
```

fix: agent panics on arm

---

packaging/docker/alpine-linux/Dockerfile
packaging/docker/ubuntu-linux/Dockerfile

The result of a discussion in [this PR](https://github.com/buildkite/docs/pull/321). This sets `BUILDKITE_AGENT_CONFIG` to `/buildkite/buildkite-agent.cfg` in the Alpine + Ubuntu images to bring the remainder of the Buildkite Agent configs into `/buildkite/`.

Set BUILDKITE_AGENT_CONFIG in Docker Images

---

Gemfile.lock

This is a `bundle update` for the ruby dependencies that are causing a github security alert. 
We could probably ditch the few ruby scripts at some point.

Bundle update for ruby dependencies

---

.buildkite/steps/publish-docker-image.sh
packaging/docker/alpine-linux/Dockerfile

Update the docker image base to `alpine:3.8` to update packages and try and clear the spurious vulnerability warning on docker hub. 
See https://github.com/buildkite/agent/issues/841 for context.

Bump alpine to 3.8 in docker image

---

bootstrap/bootstrap.go

There are several ways a git repository checkout can become corrupted that are hard to detect (have tried). This manifests as failures from one of the several git commands we call, either the `git remote set-url`, or the `git clean` or the `git checkout`, etc. Previously we dealt with this problem by removing the checkout directory on certain failures, but we keep discovering new ones.
We retry the checkout process if it fails, so this removes the checkout after the first failure.

Remove the checkout dir if the checkout phase fails

---

process/process.go

The comment was always "3 seconds" in e73bcb9f6
The timeout was bumped from 5 to 10 in 231c783a1

Update kill timeout comment to 10 seconds

---

.buildkite/steps/build-docker-image.sh
packaging/docker/alpine-linux/Dockerfile
packaging/docker/alpine-linux/buildkite-agent.cfg
packaging/docker/ubuntu-linux/Dockerfile
packaging/docker/ubuntu-linux/buildkite-agent.cfg

This adds `/buildkite/buildkite-agent.cfg` to our docker images, and also example hooks.
Closes https://github.com/buildkite/agent/issues/846.

Add buildkite-agent.cfg to docker images

---

.buildkite/Dockerfile-windows
.buildkite/docker-compose.windows.yml

I was a bit heavy handed in https://github.com/buildkite/agent/pull/843. This adds back the parts needed to run our windows tests.

Add back windows docker things in .buildkite/

---

agent/agent_pool.go
agent/agent_worker.go
agent/api_client.go
api/buildkite.go
clicommand/agent_start.go

This adds a flag that lets us optionally disable http2 for communicating with the Agent API. This is useful for proxies that don't support http2.

Add a flag to disable http2 in the start command

---

scripts/publish-debian-package.sh

deb-s3 uses the aws-sdk gem which happily uses aws credentials from the environment or instance roles. I've verified that deb-s3 can manage apt.buildkite.com from bastion, so removing this should just work, then we can get ride of these last explicit aws creds. 🕵️‍♂️

Use instance role credentials for deb-s3

---

process/process.go
process/process_test.go

Chatting with @sj26, we sometimes miss out on exit signals for killed processes because we call `wait()` in the start loop but also in the kill loop to monitor if the kill worked. 
This ditches that and just uses a channel internally to monitor of the process has exited or not. 
Future work would be to replace `IsRunning()` which is a busy-wait with a blocking call to `Done()`.

Use a channel to monitor whether process is killed

---

.buildkite/Dockerfile
.buildkite/docker-compose.yml
.dockerignore

This will hopefully provide at least some caching for downloading of go modules on every build.

Add a cache volume for go modules

---

agent/agent_pool.go
agent/agent_worker.go
agent/job_runner.go
clicommand/agent_start.go
go.mod
go.sum
metrics/metrics.go
vendor/github.com/DataDog/datadog-go/LICENSE.txt
vendor/github.com/DataDog/datadog-go/statsd/README.md
vendor/github.com/DataDog/datadog-go/statsd/statsd.go
vendor/github.com/DataDog/datadog-go/statsd/udp.go
vendor/github.com/DataDog/datadog-go/statsd/uds.go

This adds a very minimal implementation of metrics collection for the Datadog agent. 
It's controlled by two config entries:
```
metrics-datadog = true|false
metrics-datadog-host = localhost:8125
```
Currently it streams metrics in real-time as they are collected. The following metrics are collected, in the format of `[metric type], [name], [tags]`:
Batch is done, we batch 10 metrics commands presently before sending them. 
I'd love feedback on what metrics to collect and how I'm collecting them!

Metrics collection for Datadog

---

bootstrap/bootstrap.go

Currently our checkout retry logic will try and retry on cancellation. This prevents that happening by detecting if the reason for cancellation was that we didn't get an exitcode from the checkout process (e.g because it was sent a `SIGTERM` and lacks a signal handler).

Don't retry checkout on cancel

---

agent/agent_pool.go
clicommand/agent_start.go

Inspired by the long dormant https://github.com/buildkite/agent/tree/lol-workers and the need for high-concurrency agents for testing lockfiles, I added a hidden ~~`--workers`~~`--spawn` flag that specifies how many concurrent workers to run. 
Have been giving it a workout with `-race` on and have sorted out the various leaks.

Add a `--spawn` option to spawn multiple parallel agents

---

clicommand/agent_start.go

... because I'm OCD enough that `BuildkiteAgent` struck me as inconsistent with `buildkite-agent` of most other usage sites. The user is kebab-case, the other search paths on other platforms are kebab-case, I couldn't think of a reason for Windows to be snowflake.

Add another search path for config file on Windows

---

clicommand/pipeline_upload.go

This resolves `BUILDKITE_COMMIT` (which can be `HEAD` or `FETCH_HEAD`) to an actual commit before interpolation into a pipeline that is being uploaded.
Closes https://github.com/buildkite/agent/issues/456.

Resolve BUILDKITE_COMMIT before pipeline upload

---

agent/agent_configuration.go
agent/job_runner.go
clicommand/agent_start.go
process/process.go
process/process_test.go

This makes the time between `SIGTERM` and `SIGKILL` when a job is cancelled configurable. 
This allows people who have workloads with things like `packer` and `docker-compose` (which can often take 20-30 seconds to gracefully shutdown) to configure when they are forcefully killed. The alternative is often having to write cleanup scripts outside of the agent.
Ideally, this would be a setting which could be configured at a step/yaml level to and passed down to the job runner vs the blunt-force agent-wide config.

Add a configurable cancel-grace-period

---

clicommand/pipeline_upload.go

Accidentally omitted this from #871.

Trim newline from output of git rev-parse

---

bootstrap/config.go
bootstrap/config_test.go

Hooks should be able to export `$BUILDKITE_REPO` to change the git clone/fetch uri. The most compelling use case is for local mirrors of git repos, for caching purposes.

Allow hooks to change git repo url

---

metrics/metrics.go

Add a default port to metrics-datadog-host

---

bootstrap/git.go
bootstrap/integration/checkout_integration_test.go
bootstrap/knownhosts.go

Currently we use a git submodule foreach to try and get the url of all our submodules so that we can figure out if any need ssh keyscanning. This is unfortunately completely flawed as none of them exist until after we call git submodule update.
This uses the git config command to parse the .gitmodule file instead.
Closes https://github.com/buildkite/agent/issues/825.

Use .gitmodules for determining what hosts to keyscan

---

clicommand/agent_start.go
clicommand/bootstrap.go
packaging/docker/alpine-linux/buildkite-agent.cfg
packaging/docker/ubuntu-linux/buildkite-agent.cfg
packaging/github/linux/buildkite-agent.cfg
packaging/github/windows/buildkite-agent.cfg
packaging/linux/root/usr/share/buildkite-agent/buildkite-agent.cfg

Turns out that a second -f is needed to force `git clean` to remove .git subdirectories.
From https://git-scm.com/docs/git-clean:
> Git will refuse to delete directories with .git sub directory or file unless a second -f is given.
The big question here is whether this counts as a breaking change 🤔 I am leaning towards no, as I think we thought that this was the behaviour of the existing flags, so I view this as fixing a bug. 
Closes https://github.com/buildkite/agent/issues/865.

Change git-clean-flags to cleanup submodules

---

.buildkite/Dockerfile-windows
.buildkite/docker-compose.windows.yml
.buildkite/pipeline.windows.yml
.buildkite/pipeline.yml
process/process_test.go

For months our asynchronous windows tests have been broken. This unbreaks them, and moves them back into the main pipeline. They take 4 minutes to run, so this makes our tests slower, but it means we won't be able to break them in future.

Fix broken docker environment for windows tests

---

EXPERIMENTS.md
utils/path_test_windows.go

On windows, absolute paths start either with \ or with c: (as in, drive-letter then colon)

Add tests exposing a paths issue.

---

agent/agent_worker.go
agent/job_runner.go
process/process.go
process/process_test.go
process/utils.go
process/utils_windows.go

Previously `process.Process.Kill()` handled our graceful shutdown behaviour, e.g first interrupt the sub-process, wait 10 seconds and then kill it. 
It turns out that windows support is a lot more complicated, so this moves that functionality to `agent.JobRunner.Cancel()`, which delegates to `process.Process.Interrupt()` and then `process.Process.Terminate()`.
This should be functionally identical to the current behaviour, just with some code moved around to better support future changes like #879.

Move graceful kill behaviour out of process.Process

---

agent/plugin/plugin.go
agent/plugin/plugin_test.go
bootstrap/bootstrap.go

This change allows plugin paths to be relative to the checkout, so you can commit plugins along side code. The thinking is this provides a straight-forward way to lock-down what plugins are used and it has the nice upside of making it easier to iterate on plugins and code that are evolving. 
```yaml
steps:
- label: "Test with vendored docker plugin"
plugins:
- "./.buildkite/plugins/docker":
image: "hello-world"
```
Some more context on the background is at https://forum.buildkite.community/t/verifying-the-integrity-of-third-party-plugins/158/18. 
In terms of implementation, this adds an additional phase `vendored-plugin` that occurs in the bootstrap after `checkout`. This means that vendored plugins can't have `pre-checkout` or `checkout` hooks and that vendored plugins `environment` hook …

Support vendored plugins

---

process/process_test.go
process/utils_windows.go

It turns out Windows has no concept of parent/child processes, beyond storing the PID of the process that created it. This means that trying to walk a process tree to cancel a job can leave sub-processes orphaned if a subprocess in the hierarchy dies, as you can't walk that tree past the dead process. For instance in:
`bash.exe (pid 1)` -> `bash.exe (pid 2)` -> `sleep.exe (pid 3)`
If pid 2 dies, pid 3 remains, but killing pid 1 won't be able to traverse down to pid 3.  
The best we can do is create processes inside a "console group" and then send break / ctrl-c events to that group. 
Context:
https://github.com/buildkite/agent/pull/795
https://github.com/golang/dep/issues/862
https://github.com/golang/go/issues/17608
https://github.com/golang/go/issues/6720 …

Use windows console groups for process management

---

agent/agent_pool.go
clicommand/agent_start.go
clicommand/global.go
logger/log.go

Turns out I broke `--no-color` in #880. This returns it.

Respect color settings in logger

---

install.sh

The RPi reports `uname -sm` as `Linux armv6l`, this PR adds a match for `armv6l` for checking prior to `armv6` to resolve arch to `arm` instead of `armhf` in `install.sh`.
I'm not sure this is the only way to fix it / there might be other things wrong / still needs to be tested.
Closes #475.

Fix for #475

---

bootstrap/git.go
bootstrap/git_test.go
bootstrap/knownhosts.go
bootstrap/knownhosts_test.go

This is a PoC to improve compatibility with ssh aliases which don’t conform to our special-casing behaviour.
For any incoming ssh host, this asks `ssh` for what host it will connect to. This allows `ssh-keyscan` to connect to that host, rather than whatever the alias name is, which may or may not match.
It also supersedes the older behaviour wherein our special-case aliases were stripped, and on agents which are already correctly configured, should work the same.
~I haven’t been able to get the test suite working to confirm this works, but I figured putting the sketch up would be better than doing nothing! 😃~
I’ve updated this to pass, and add new, tests, and it’s looking good!
For reference, `ssh -G` appears to have been added in OpenSSH in 6.0 (released April 22, 2012, sadly no source …

Resolve ssh hostname aliases before running ssh-keyscan

---

utils/path_windows_test.go

@petemounce I renamed the test so that it would run as a test.
I wasn't sure what you intended with the `filepath.Join`, are you saying that `C:\programdata\buildkite-agent` should normalize to `C:programdata\buildkite-agent`? I know either works in windows, but I wasn't aware of a reason the latter should be preferred. 
See https://github.com/golang/go/issues/11551 for some context on the weird ways that golang handles file paths.

Correct tests introduced in #881

---

agent/job_runner.go

Currently we wait a max of 50 seconds on each chunk before trying to upload it. If chunks are failing to upload, the main reason would be a problem with Buildkite. Presumably if they're failing to upload, finishing a job and starting a new one will also have the same problem (at which point we're just throwing chunk data away, to get more, and probably throw them away too).
This change tweaks the retry rules so we don't give up on chunks. It does handle cases that BK returns a 422, which "is" a successful chunk upload (whether or not we actually stored it is another thing), but a 422 does mean communications were successful, and Buildkite did "the right thing"

Retry forever to upload job chunks

---

bootstrap/bootstrap.go
clicommand/bootstrap.go

Currently the bootstrap will exit with whatever exit code it gets from the subprocesses it kills after cancellation. Following bash's example, it now removes its signal handler and SIGTERM's itself (arguably, it should use the signal it received, but this was easier initially). This shows up as consistently as a -1 in the UI.

Terminate bootstrap with unhandled signal after cancel

---

agent/artifact_uploader.go

This fixes a segfault in the artifact uploader that was introduced in #894.
```
panic: runtime error: invalid memory address or nil pointer dereference
--
  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xb869ae]
  |  
  | goroutine 1 [running]:
  | github.com/buildkite/agent/agent.(*ArtifactUploader).upload(0xc0000897c0, 0xc0000821f0, 0x1, 0x1, 0x2, 0x2)
  | /code/agent/artifact_uploader.go:204 +0xade
  | github.com/buildkite/agent/agent.(*ArtifactUploader).Upload(0xc0000897c0, 0xc0000897c0, 0x1e)
  | /code/agent/artifact_uploader.go:67 +0x1ee
  | github.com/buildkite/agent/clicommand.glob..func5(0xc0000f1080)
  | /code/clicommand/artifact_upload.go:95 +0x2cc
  | github.com/urfave/cli.HandleAction(0xcbacc0, 0xef4980, 0xc0000f1080, 0x0, 0xc0000853e0)
  | …
```

Fix a seg-fault in the artifact uploader

---

.buildkite/Dockerfile-windows
.buildkite/pipeline.yml
bootstrap/hook_test.go

The new Windows Server 2019 docker images are smaller and more capable. I've updated our agents to use them, so this matches that.

Use new Windows Server 2019 docker images

---

bootstrap/bootstrap.go
bootstrap/integration/checkout_integration_test.go

This allows hooks to unset or empty `BUILDKITE_REPO` to conditionally skip checkout entirely.

If BUILDKITE_REPO is empty, skip checkout

---

agent/api_proxy.go
agent/job_runner.go
bootstrap/knownhosts_test.go
bootstrap/shell/tempfile.go

Well, TIL that it's possible for golang's `os.TempDir` to not exists. Our windows agents are failing to create temp files. 
See https://golang.org/pkg/os/#TempDir and then the [actual implementation](https://golang.org/src/io/ioutil/tempfile.go) of `io.TempFile`.

Ensure TempDir exists

---

clicommand/agent_start.go
clicommand/bootstrap.go
clicommand/global.go

We follow a linux process model where any environment that is available to `buildkite-agent start` gets passed down to `buildkite-agent bootstrap` and then onto the actual job environment.
This includes env used for configuring those commands, for instance things like `BUILDKITE_AGENT_TOKEN` and other more minor things like `BUILDKITE_AGENT_TAGS`. These filter down to the execution environment for jobs, which creates a really wide API that is hard to keep up to date in docs. 
This change filters out any environment used for command config. They are unset, which means they need to be explicitly set by the job runner that creates the environment for the job.
Note that things other than env used for config are still passed down from the parent environment.

Filter env used for command config out of environment

---

agent/job_runner.go
process/process.go
process/process_test.go

Another small refactor related to #919, this splits the single writer to `Stdout` and `Stderr`.

Split process writer to stdout/stderr

---

agent/job_runner.go
bootstrap/hook_test.go
bootstrap/shell/shell.go
bootstrap/shell/shell_test.go
process/process.go
process/process_test.go

Following on from #919 and #920, this uses `process.Process` inside of the shell abstraction which lets us use it's superior process terminating technology rather than what is build into the golang `exec` package.

Use process.Process inside of the shell abstraction

---

bootstrap/git.go

Use a Scanner vs splitting on `\n` for line parsing in `resolveGitHost()`. This should better deal with different line ending types.
I'm hoping this fixes https://github.com/buildkite/agent/issues/925, I wasn't able to reproduce the issue locally, but I have seen it before.

Use a bufio.Scanner for parsing git -G output

---

.buildkite/Dockerfile
README.md
bootstrap/bootstrap.go
bootstrap/config.go
bootstrap/shell/shell.go
bootstrap/shell/shell_test.go
clicommand/bootstrap.go
go.mod
go.sum
vendor/github.com/buildkite/bintest/README.md
vendor/github.com/buildkite/bintest/proxy.go
vendor/modules.txt

This fixes a race condition that occurred when `bootstrap.Cancel()` was called.
It also brings back the behaviour mentioned in https://github.com/buildkite/agent/issues/922 of sending a `SIGTERM` to commands that the bootstrap executes vs `SIGKILL`.
Closes #922.

Fix a race condition in cancellation

---

agent/job_runner.go
process/scanner.go

As pointed out in #929, we are buffering line output before flushing it to log chunks. This is a regression that impacts things like rspec that output lots of dots before they output a newline.
The regression was a result of me simplifying some code so that the same codepath was used whether `--timestamp-lines` was turned on or off. 
At this stage, it's just too hard to support `--timestamp-lines` and not buffer lines (as we need to only add timestamp prefixes to non-headers), so this PR brings back the two code paths and fixes #929 at the expense of more code and being a bit gross.

Flush output immediately if timestamp-lines not on

---

agent/agent_pool.go
agent/gcp_labels.go
clicommand/agent_start.go
packaging/docker/alpine-linux/buildkite-agent.cfg
packaging/docker/ubuntu-linux/buildkite-agent.cfg
packaging/github/linux/buildkite-agent.cfg
packaging/linux/root/usr/share/buildkite-agent/buildkite-agent.cfg

Adds support for a new configuration field `tags-from-gcp-labels` that pulls the GCP instance labels and turns them into agent tags. This is the same functionality as `tags-from-ec2-tags` in AWS.
I tested this manually and seems to work fine. However, this is my first time updating the agent, so please shout if there are additional tests that need writing, docs that need updating, etc. I am happy to update.

Add support for new config field: tag-from-gcp-labels

---

clicommand/pipeline_upload.go

In the case of server problems, we should give the Agent API a bit more time to recover, and to successfully accept a pipeline upload, before giving up and failing the pipeline upload job (and build) — which results on user intervention being required.
This increases the retry interval, and total number of retries, in the case of 5xx errors on pipeline uploads from 5 seconds to 5 minutes.
I think it's a good tradeoff to save user intervention and a failed build status, at the cost of the pipeline upload step taking much longer to run than usual in the case of server problems (such as downtime, maintenance windows, or unusually high load).

Increase pipeline upload retries on 5xx errors

---

.buildkite/Dockerfile-windows
.buildkite/docker-compose.windows.yml
.buildkite/pipeline.yml
bootstrap/integration/checkout_integration_test.go
bootstrap/shell/shell_test.go
process/process_test.go

Windows tests seem to be have not running for a while 🤔
This rolls in the vendor changes from #934 and also ensures that the correct shell is used in windows.

Use vendors and bash.exe for running windows tests

---

agent/agent_configuration.go
agent/agent_pool.go
agent/agent_worker.go
agent/api_client.go
clicommand/agent_start.go
clicommand/global.go
logger/log.go

This adds `--disconnect-after-idle-timeout=<seconds>` to the `start` command. The idea is to have a a script that runs on agent shutdown that scales in the host.

Support disconnecting agent after it's been idle for a certain time period

---

packaging/linux/root/usr/share/buildkite-agent/systemd/buildkite-agent.service
packaging/linux/root/usr/share/buildkite-agent/systemd/buildkite-agent@.service

This brings in recent improvements we've made to the systemd unit from the Elastic Stack.
See https://github.com/buildkite/elastic-ci-stack-for-aws/pull/545 and https://github.com/buildkite/elastic-ci-stack-for-aws/pull/521

Restart agents on SIGPIPE from systemd

---

clicommand/agent_start.go
clicommand/annotate.go
clicommand/artifact_download.go
clicommand/artifact_shasum.go
clicommand/artifact_upload.go
clicommand/global.go
clicommand/meta_data_exists.go
clicommand/meta_data_get.go
clicommand/meta_data_set.go
clicommand/pipeline_upload.go
clicommand/step_update.go

All the CLI commands each had their own selection of the global and api flags. This unifies how they are processed and handled.

Centralize api and global cli flags

---

agent/arty_uploader.go

without the de-reference to the base u.iURL, any long list of uploads will be uploaded as something like:
```
https://artifactory.com/artifactory/buildkite-artifacts/ca88d9b6-62e9-4393-acf1-99940d150f1b/cov5/1.html/buildkite-artifacts/ca88d9b6-62e9-4393-acf1-99940d150f1b/cov5/2.html/buildkite-artifacts/ca88d9b6-62e9-4393-acf1-99940d150f1b/cov5/3.html/buildkite-artifacts/ca88d9b6-62e9-4393-acf1-99940d150f1b/cov5/4.html/buildkite-artifacts/ca88d9b6-62e9-4393-acf1-99940d150f1b/cov5/5.html/buildkite-artifacts/ca88d9b6-62e9-4393-acf1-99940d150f1b/cov5/6.html/buildkite-artifacts/ca88d9b6-62e9-4393-acf1-99940d150f1b/cov5/7.html/buildkite-artifacts/ca88d9b6-62e9-4393-acf1-99940d150f1b/cov5/8.html/buildkite-artifacts/ca88d9b6-62e9-4393-acf1-99940d150f1b/cov5/9.html/buildkite-artifacts/ca88d9b6-62e9 …
```

updating uploader to NOT write a mega-long url into the artifact

---

agent/agent_configuration.go
agent/agent_pool.go
agent/agent_worker.go
agent/integration/job_runner_integration_test.go
agent/job_runner.go
agent/register.go
agent/tags.go
api/agents.go
clicommand/agent_start.go

This is another take on #954 that reduces the diff somewhat. 
The aim here is to decouple the AgentPool from the creation of AgentWorkers and registration. This allows better composition and pushes the construction of dependencies up to the caller, which is the cli command level.
The only practical difference in how things work here is that there is a single signal handler for the whole AgentPool vs one for each AgentWorker. This shouldn't have anything other than aesthetic difference.
Registration and fetching of tags are now different things too, and the results are passed into things that need them.

Move AgentWorker construction and registration out of AgentPool

---

agent/arty_uploader.go

side-effect we found from the previous patch update : the artifact uploader was using the wrong URL to PUT to, this PR is to use the proper URL for uploading 😅

update artifatory uploader to use the right PUT url

---

packaging/docker/alpine-linux/Dockerfile

The new docker-compose version introduces a dependency on gcc when installing. To avoid this, we'll pin to the previous version for now.
https://github.com/docker/compose/issues/6617

Pin docker-compose to 1.23 to avoid extra deps

---

agent/tags.go
agent/tags_test.go

Looks like we introduced a bug in https://github.com/buildkite/agent/pull/956 where we extracted tag collection into `agent.TagFetcher`. 
This fixes the issue and adds a minimal test. I'm going to follow up with some more extensive tests on the tags collection, as part of the intention behind the extraction was to make it more testable 😓
Closes #967.

Fix bug where host tags overwrite other tags

---

agent/tags.go
agent/tags_test.go

In a similar vein to #969, this was a bug introduced in #956. 
This fixes an issues where tags weren't correctly being loaded from ec2 tags and metadata and adds tests around it. 
Closes #968.

Fix bug where ec2 tags arent added correctly

---

agent/agent_worker.go

I discovered a race condition where `ctrl-c` wouldn't stop the agent if pressed exactly at the right time (just after registration, but before pings start).

Fix race condition between stop/cancel and register

---

agent/api_client.go
clicommand/agent_start.go
clicommand/bootstrap.go
clicommand/global.go
logger/log.go

Unfortunately #962 set the default log level back to `debug`. This fixes that issue, but in the course of that I came to wonder whether we should be showing `notice` level messages, especially the first few when the agent starts:
I suspect we want a default level of `notice`, which is what this PR does.
Closes #973.

Set default logger level to notice

---

agent/tags_test.go
go.mod
go.sum
vendor/github.com/davecgh/go-spew/LICENSE
vendor/github.com/davecgh/go-spew/spew/bypass.go
vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
vendor/github.com/davecgh/go-spew/spew/common.go
vendor/github.com/davecgh/go-spew/spew/dump.go
vendor/github.com/davecgh/go-spew/spew/format.go
vendor/github.com/stretchr/testify/LICENSE
vendor/github.com/stretchr/testify/assert/assertion_format.go
vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
vendor/github.com/stretchr/testify/assert/assertion_forward.go
vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
vendor/github.com/stretchr/testify/assert/assertions.go
vendor/github.com/stretchr/testify/assert/forward_assertions.go
vendor/github.com/stretchr/testify/assert/http_assertions.go
vendor/modules.txt

The order of tags is random, due to golang's maps behaviour. This uses `assert.ElementsMatch` to do an order insensitive comparison.

Fix flakey tags test

---

agent/agent_configuration.go
agent/agent_pool.go
agent/api_client.go
api/buildkite.go
clicommand/agent_start.go
clicommand/annotate.go
clicommand/artifact_download.go
clicommand/artifact_shasum.go
clicommand/artifact_upload.go
clicommand/bootstrap.go
clicommand/global.go
clicommand/meta_data_exists.go
clicommand/meta_data_get.go
clicommand/meta_data_set.go
clicommand/pipeline_upload.go
clicommand/step_update.go
cliconfig/loader.go
logger/field.go
logger/log.go
logger/log_test.go

This adds a `--log-format` option to `buildkite-agent start` that allows for `json` output for better integration with structured logging systems.
```bash
$ buildkite-agent start --debug --log-format=json
{"ts":"2019-03-31T22:51:28+11:00","level":"NOTICE","msg":"Starting buildkite-agent v3.10.2 with PID: 3282"}
{"ts":"2019-03-31T22:51:28+11:00","level":"NOTICE","msg":"The agent source code can be found here: https://github.com/buildkite/agent"}
{"ts":"2019-03-31T22:51:28+11:00","level":"NOTICE","msg":"For questions and support, email us at: hello@buildkite.com"}
{"ts":"2019-03-31T22:51:28+11:00","level":"INFO","msg":"Configuration loaded from: /usr/local/etc/buildkite-agent/buildkite-agent.cfg"}
{"ts":"2019-03-31T22:51:28+11:00","level":"DEBUG","msg":"Bootstrap command: buildkite-agent …
```

Support log output in json

---

agent/tags.go
agent/tags_test.go

Looks like this might have been a bug introduced in [#970](https://github.com/buildkite/agent/pull/970/files#diff-64fc4f8002c51b533bf973bd314f0ed4R104). Not a huge deal since we can get around it by setting a custom tag in the config in the meantime.

Allow applying ec2 tags when config tags are empty

---

agent/arty_uploader.go

It's that time of the week again!
But really, this time it's not BREAKING functionality so long as we're uploading properly, but the upload is not appending the JOB ID as we would expect in the documentation. This fix will explicitly place artifacts in the path specified through BUILDKITE_ARTIFACT_UPLOAD_DESTINATION, where now it would only respect the repository name.

need to put the Artifactory specific path in addition to repository

---

agent/agent_configuration.go
agent/agent_worker.go
agent/integration/job_runner_integration_test.go
agent/job_runner.go
clicommand/agent_start.go

This resulted in an empty agent endpoint url in v3.11.0.
Reverts buildkite/agent#987

Revert "Refactor AgentConfiguration into JobRunnerConfig"

---

clicommand/global.go

We introduced a regression in #966 where logging output went to stdout. Previously it was stderr. 
This should also fix the bk cli step.

Send logging to stderr again

---

agent/agent_pool.go
agent/agent_worker.go

Closes #985.
I don't love the addition of a monitor object into `AgentWorker.Start`, but it was the simplest approach that didn't require massive structural changes to how AgentPool and AgentWorker interact. I tried about 3 different ways of doing that, all of which led to pretty sweeping changes. 
Would welcome suggestions of alternate approaches!

Only trigger idle disconnect if all workers are idle

---

agent/tags.go
agent/tags_test.go

Fixes a bug where specifying `--tags-from-host` and `--tags-from-gcp-labels` only returns host tags. 
Not sure how I missed this in https://github.com/buildkite/agent/pull/969.

Prevent host tags from overwriting aws/gcp tags

---

agent/agent_worker.go
api/agents.go

We introduced a bug in #985 where the wrong return param from the register API was checked and the idle monitor never detected all the agents idle.
Closes #1003.

Fix bug where disconnect-after-idle stopped working

---

packaging/docker/ubuntu-linux/Dockerfile

`docker-compose#1.21` binary seems to have issues with the `COPY` command doing docker builds.
```
❯ /tmp/dc-bad build fakeapp
Building fakeapp
Step 1/10 : FROM openjdk:8-jre-slim
---> 87285d0871fd
[...]
Step 7/10 : COPY target/scala-*/*-assembly-*.jar ./fakeapp.jar
ERROR: Service 'fakeapp' failed to build: COPY failed: no source files were specified
```
I tried both the `docker-compose` from `pip` and from the GH releases page and they behave differently,  the `pip` one does not have this issue.
Use `docker-compose#1.24` which does not seem to have the issue
```
❯ /tmp/dc build fakeapp       
Building fakeapp
Step 1/10 : FROM openjdk:8-jre-slim
[...]
Step 7/10 : COPY target/scala-*/*-assembly-*.jar ./fakeapp.jar
---> fafdb06a39b4
[...]
Successfully built ce7218161c4b
Successfully tagged …
```

Update Ubuntu docker image to docker-compose 1.24

---

agent/agent_configuration.go
agent/agent_worker.go
clicommand/agent_start.go
cliconfig/loader.go

Originally the agent had two disconnect settings: `disconnect-after-job`, which caused the agent to disconnect after a job, and `disconnect-after-job-timeout` which was a timeout prior to receiving a job that if no job was received by would cause the agent to disconnect. 
We subsequently added `disconnect-after-idle-timeout` which disconnects the agent after it's been idle at any time, either before or after a job. 
This PR deprecates `disconnect-after-job-timeout` and suggests using `disconnect-after-idle-timeout` instead, as it simplifies a lot of code paths. Functionally, they are very similar.

Deprecate disconnect-after-job-timeout

---

bootstrap/bootstrap.go

At present, buildkite sets the executable bit on any script it attempts to
execute as part of a job.
This is actually quite hazardous as there may be files that are valid
interpreter scripts, but are dangerous to run -- by having this behaviour, it
actually subverts any good that no-command-eval can achieve by leaving another
potentially gaping hole which we can't turn off!
It's also relatively unnecessary - git, by default, tries to store the state of
the execute bit into the repo.  We should not subvert this if the user doesn't
want us to.
This patch adds a flag that can disable this behaviour, so, if you're security
minded, and you really need to be able to ensure that arbitrary files in your
repo cannot be invoked, without use of a whitelist, you have the ability to do
so!

Don't force set the executable bit on scripts to be set

---

agent/arty_uploader.go

Path parsing for any Windows path was resulting in a %20 being injected into the URL, and would fail to upload in some cases to Artifactory.

update path parsing to support windows

---

agent/gs_uploader.go

We store our BK-generated artifacts in a private GCS bucket, but want to expose those artifacts to internal users via HTTPS.  For this we use a GCS->HTTPS proxy that sits in the middle, checking user authorization, and only allowing our users through.
However, the buildkite-agent artifact URL generation func appears to be hard-coded to insert the GCS bucket name into the path of the URL it generates.  This is necessary when talking directly to GCS, since the URLs to use look like `https://storage.googleapis.com/$BUCKET_NAME/$FILE_PATH`.
However, our proxy only talks to one bucket, and thus the URLs used to talk to it do not include the unnecessary bucket name - it generates URLs of the format `https://$ARTIFACT_PROXY_HOST/$FILE_PATH`.  Thus, this hard-coded insertion into the URL prevents …

Fix assumption that custom GCS hosts use the same path format as GCS.

---

agent/arty_downloader.go
agent/arty_uploader.go

This compliments PR(https://github.com/buildkite/agent/pull/1013) for windows upload, both need to be merged for artifactory to work properly.

update path parsing to support windows artifact download 

---

agent/arty_uploader.go

This adds checksums so that Artifactory doesn't complain in this screen:

Add checksums for artifactory uploaded artifacts

---

agent/agent_configuration.go
agent/job_runner.go
clicommand/agent_start.go
clicommand/annotate.go
clicommand/artifact_download.go
clicommand/artifact_shasum.go
clicommand/artifact_upload.go
clicommand/bootstrap.go
clicommand/global.go
clicommand/meta_data_exists.go
clicommand/meta_data_get.go
clicommand/meta_data_set.go
clicommand/pipeline_upload.go
clicommand/profiler.go
clicommand/step_update.go

This makes it easy to get profiling traces for different agent commands. 
```bash
buildkite-agent start --profile memory
go tool pprof /var/folders/kk/2wmv_tq14m907m49pr66t1hh0000gn/T/profile511809002/mem.pprof
top5
```

Add profile option to all cli commands

---

agent/form_uploader.go
agent/form_uploader_test.go

Turns out my fix in #1033 had a race condition in it where the main go routine would race to write form fields with the go routine that write the files. 
This fixes it, and adds a test like I should have done in the first place.

Fix bug where file upload hangs and add a test

---

api/meta_data.go
clicommand/meta_data_keys.go
main.go

Implement a `buildkite-agent meta-data keys` command for listing meta-data keys:
E.g:
```bash
buildkite-agent meta-data keys # default delimited by newlines
buildkite-agent meta-data keys --delimiter ';'
```
You can use it to enumerate meta-data like:
```bash
#!/bin/bash
set -euo pipefail
buildkite-agent meta-data keys | while read -r key; do
echo "$key: $(buildkite-agent meta-data get "$key")"
done
```
/cc @toolmantim

Add meta-data keys command

---

clicommand/meta_data_keys.go

Remove the `--delimiter` option from the new `meta-data keys` command and output a trailing newline. 
See discussion in https://github.com/buildkite/agent/pull/1039 for context.

Remove delimiter from meta-data keys command

---

bootstrap/bootstrap.go

This change moves plugin parsing earlier in the bootstrap phase which means we can avoid showing lots of headers for builds that don't have plugins or vendored plugins.

Make plugin parsing less verbose

---

agent/plugin/plugin_test.go

This makes the plugin tests slightly easier to maintain and read.

Move plugin tests to table-driven tests

---

agent/agent_worker.go
agent/job_runner.go
clicommand/agent_start.go
process/process.go
process/process_test.go
process/signal.go
process/signal_windows.go

Currently the agent sends a `SIGTERM` to the bootstrap on user cancellation of a job. 
This adds `cancel-signal` which accepts signals in the form of `SIGTERM`, `SIGHUP`, etc.
The default will remain `SIGTERM` until the next major version and then it will be `SIGINT`. 
/cc @DazWorrall

Allow signal agent sends to bootstrap on cancel to be customized

---

bootstrap/bootstrap.go

Regardless of how we decide to fetch it, the choice of what to checkout is always the same: `FETCH_HEAD` if `b.Commit` is `HEAD`, and `b.Commit` otherwise.
Fixes #1063 -- "explicit `b.RefSpec` supplied" is the only branch whose behaviour is changing here, and only when `b.Commit` is `HEAD`.

Separate the fetch and checkout decisions

---

agent/agent_worker.go

The agent mistakenly logged the last successful ping time instead, when an error occurred.

Correctly log last successful heartbeat time.

---

agent/s3_uploader.go
agent/s3_uploader_test.go

This uses a new ENV variable BUILDKITE_S3_SSE_ENABLED in line with the
existing enviroment variables.
Currently validate of this value is optimised for feedback, being limited
to covering the case of encryption at rest. If this accepted the full
range of options supported by S3 it would be difficult to validate
as it requires a how load of KMS infrastructure and permissions.
Also extracted the existing flag and wrote some tests for it and the new
option.

Added feature to enable encryption at rest for artifacts in S3.

---

clicommand/pipeline_upload.go

Golang doesn't execute deferred calls on system exit, so this removes one found in the pipeline upload command. 
This allows `--profile` to be used with `--dry-run`.

Avoid os.Exit in pipeline upload command

---

api/jobs.go
api/steps.go
clicommand/step_get.go
clicommand/step_update.go
main.go

Currently `step update` works by updating a step associated with a job. This means you can't update steps that aren't commands (blocks, waits, etc).
This change switches the arguments for `step update` from `--job` to `--step`. `BUILDKITE_STEP_ID` is the value it uses as a default.
As a bonus, you can now pass in `--step key` (instead of an ID), since it's a bit of a pain to figure out the ID of another step in the pipeline.

Updates to `step update` and added `step get`

---

agent/gs_downloader.go

Behind our firewall, the default google client will explode when performing some operations. This PR is to address that issue by allow us to authenticate during the download process with the client. By not using the default client, we're able to download protected artifacts and bypass the firewall restriction.
Let me know if we have any problems/questions, and thanks!

allow gs_downloader to use GS_APPLICATION_CREDENTIALS

---

bootstrap/bootstrap.go

If multiple plug-ins provide one, we have to exit the loop early for
this hook.
Fixes #1052

Only execute the "command" hook once.

---

agent/agent_configuration.go
agent/agent_worker.go
clicommand/agent_start.go

This feature can optionally be enabled via the `--health-check-addr addr:port` flag or the equivalent `BUILDKITE_HEALTH_CHECK_ADDR` environment variable.
When enabled, the agent starts an HTTP server on the given `addr:port` that can be used for pull-based health checks, like [Google Cloud's instance group autohealing](https://cloud.google.com/compute/docs/instance-groups/creating-groups-of-managed-instances#monitoring_groups). This allows the instance group to automatically detect when a VM isn't running a healthy Buildkite agent and recreate it.
It exports two endpoints:
- `/`: This is an overall status page for the agent itself.
- `/agent/<spawn_id>`: This is the status page of the agent worker with the numeric index `spawn_id`, starting from 1. If you use `--spawn=N`, there will be …

Let the agent serve a status page via HTTP.

---

agent/job_runner.go

We introduced a bug in #1084 that causes panics on job accept based on the timing of goroutine execution. 
Fixes #1092 and #1094.

Fix a race condition that causes panics on job accept

---

agent/artifact_downloader.go
agent/artifact_searcher.go
api/artifacts.go
clicommand/artifact_download.go
clicommand/artifact_shasum.go

By default, jobs that are retried are excluded from `buildkite-agent artifact download` searches. This adds support for searching retried jobs when downloading/shasumming with a new `--include-retried-jobs` CLI argument.

Add --include-retried-jobs to artifact download/shasum

---

bootstrap/bootstrap.go
bootstrap/git.go

This avoids destroying the build working directory on certain errors, including git checkout failures. Re-clones can be expensive! 
Closes #1088.

Avoid destroying the checkout on specific git errors

---

EXPERIMENTS.md
agent/job_runner.go
go.mod
process/prefixer.go
process/prefixer_test.go

Currently, we calculate timing information in the Buildkite UI by sending a stream of timestamps from when headers are output. This can lead to some weird bugs with time skew and at best shows time elapsed between headers.
This change uses invisible ANSI control codes at the start of every line to send more granular timing information to Buildkite, which allows for magically toggling in the UI:
This also disables sending header timing information. 
The aim is for this to be the default in 4.0.

Add ansi timestamp output experiment

---

agent/ec2_meta_data.go
agent/ec2_meta_data_test.go
agent/gcp_meta_data.go
agent/gcp_meta_data_test.go
agent/tags.go
agent/tags_test.go
clicommand/agent_start.go

This patch enhances the integration of the agent with EC2 and GCP meta-data endpoints by allowing for arbitrary fetching of tag name & meta-data path suffix pairs.
This new functionality is intended to be additive only and can be used via two new flags, on for AWS and one for GCP; `--tags-from-ec2-meta-data-paths`, `--tags-from-gcp-meta-data-paths`.
```
--tags-from-ec2-meta-data-paths "omg=spot/termination-time"
```
This patch also deprecates the `--tags-from-ec2` & `--tags-from-gcp` flags in favour of `--tags-from-ec2-meta-data` && `--tags-from-gcp-meta-data` respectively for consistency. The deprecated flags are not removed yet, but would be in v4.

Allow fetching arbitrary tag=suffix pairs from GCP/EC2 meta-data

---

process/prefixer.go
process/prefixer_test.go

Currently the ANSI timestamps don't show up certain output (like docker) that uses creative ANSI control characters for cursor movements.
This detects things like `\x1b[K` which clears the current line and includes the ANSI timestamp technology.

Detect ansi clear lines and add ansi timestamps

---

.buildkite/Dockerfile-windows

This reverts commit 77e0ecad3bfa816118b9f28c8f1793a9ce2c99af.
It broke our CI environment which is Windows Server 2019.

Revert "bump to servercore 1909"

---

bootstrap/bootstrap.go

If you execute multiple commands, e.g:
```yaml
steps:
-label: "My commands" 
commands:
- ./process1
- ./process2
```
then we join them together in a single bash shell as `/bin/bash -e -c './process1\b./process2`, which has the side effect of creating an intermediate shell in between the bootstrap process and your commands. By default, most shells won't automatically propagate signals to subprocesses, so when the job is cancelled the signal gets lost in this intermediate shell. 
This could be manually fixed by adding a trap as the first command:
```yaml
steps:
-label: "My commands" 
commands:
- trap "kill -- \$\$" TERM QUIT INT
- ./process1
- ./process2
```
That ends up kind of noisy and for those not versed in shell voodoo, confusing. 
This PR automatically adds this into non-script …

Propagate signals in intermediate bash shells

---

agent/agent_configuration.go
agent/agent_worker.go
agent/api.go
api/agents.go
api/jobs.go
clicommand/agent_start.go

This change adds a new `--acquire-job` option to `buildkite-agent start`. You use it like this:
```sh
buildkite-agent start --token "xx" --acquire-job "f6f1a0c9-3431-451d-942d-846dfd1fb623"
```
When the agent boots, instead of doing the normal "ping until you find work" routine, it'll specifically ask Buildkite if it can acquire the job provided (acquire is the word we use to describe an agent self-assigning and accepting a job). Once the job has been acquired, it'll run the job and exit when it's finished.
If it fails to acquire the job, it'll just bail:
In an original cut of this code I just had it as `buildkite-agent start --job`, but I didn't really mean much in context of other stuff. For example, we've got `disconnect-after-job` which is a verbose argument, so I figured …

Job Acquisition Technology™️

---

.buildkite/pipeline.yml
.buildkite/steps/build-docker-image.sh
.buildkite/steps/extract-agent-version-metadata.sh
.buildkite/steps/publish-docker-image.sh
.buildkite/steps/publish-docker-images.sh
.buildkite/steps/upload-release-steps.sh
packaging/docker/centos-linux/Dockerfile
packaging/docker/centos-linux/buildkite-agent.cfg
packaging/docker/centos-linux/entrypoint.sh

Creates a `buildkite/agent` docker image based on `centos:7.7.1908`.
Sadly, image size came out to be 757MB, compared to 466MB for the current `3.16.0-ubuntu` image. Suggestions for further size reduction welcome.
A couple of notes:
- `openssh-client` is `openssh-clients` on CentOS
- `crontabs` package is what provides `/bin/run-parts` used in the entrypoint
- CentOS does not provide `jq`, but EPEL does
- Both CentOS and EPEL have rather old docker versions, installing from `docker-ce` directly

Building a CentOS 7.x Docker image

---

bootstrap/bootstrap.go
bootstrap/hook.go
bootstrap/shell/shell.go

This adds the ability to write native powershell hooks for windows pipelines so that executing a batch file to call a powershell script is unnecessary.  The hook still creates a batch file to handle any new environment variables and pass the exit status properly.

add powershell support for hooks

---

packaging/docker/centos-linux/entrypoint.sh

On Debian, `run-parts` is an actual program. On RHEL and derivatives, it's an assimilation of the same implemented in Bash.
```sh
$> /bin/run-parts --exit-on-error /somedir
Not a directory: --exit-on-error
```

run-parts on CentOS does not have --exit-on-error

---

clicommand/annotate.go

Change the "Successfully annotated build" log level from Info to Debug on the `buildkite-agent annotate ...` command.
In this context, a successful exit status and the absence of error messages should be enough to indicate that "it worked". This improves the signal to noise ratio of build logs.
This log message was added during initial implementation, so I don't think there's any historic need/request that we'd be breaking.

clicommand/annotate: demote success log from Info to Debug

---

CHANGELOG.md
agent/agent_worker.go
agent/artifact_uploader.go
agent/arty_downloader.go
agent/gs_downloader.go
agent/job_runner.go
agent/s3_downloader.go
api/jobs.go
bootstrap/bootstrap.go
bootstrap/shell/lookpath.go
bootstrap/shell/lookpath_windows.go
bootstrap/shell/shell.go
clicommand/artifact_download.go
clicommand/artifact_shasum.go
clicommand/pipeline_upload.go
clicommand/step_get.go
clicommand/step_update.go
cliconfig/loader.go
env/environment.go
packaging/linux/scripts/after-install-and-upgrade.sh
process/signal_windows.go
scripts/latest_version.rb
utils/path.go

Fix "it's" that should be "its", and a few "its" that should be "it's", plus one that should be neither.
These were mostly in internal code comments, but also some user-facing docs (CHANGELOG and CLI usage output).
FYI the low-tech way I did this:
```
rg --glob '!vendor' "it's" -l | xargs sed -i '' -e "s/it's/its/g"
git add -p     # manually decide
git restore .  # restore the ones I chose not to add
```

The great "it's" purge

---

bootstrap/bootstrap.go
bootstrap/integration/bootstrap_tester.go
bootstrap/integration/plugin_integration_test.go

In #1135 (and released in v3.18.0) a bug was introduced where plugins hooks were being incorrectly skipped. This fixes the bug by ensuring that the hook exists in the plugin, before checking it for duplicate execution.
This now executes correctly and uploads the artifact:
```yml
steps:
- command: "echo 'foo' > bar.txt"
plugins:
- docker#v3.5.0:
image: bash
- artifacts#v1.2.0:
upload: bar.txt
```
The following pipeline was also tested, and outputs the expected warning on execution of the second `docker` plugin:
```yml
steps:
- command: "echo 'foo' > bar.txt"
plugins:
- docker#v3.5.0:
image: bash
- docker#v3.5.0:
image: bash
- artifacts#v1.2.0:
upload: bar.txt
```
Fixes #1152 
---
_Edit by @pda_: I didn't quite understand the bug, so I dug into the code; here's my summary:
* If any plugin …

Fix plugin execution being skipped with duplicate hook warning

---

.buildkite/pipeline.yml

I'm 90% sure I have the dependencies right.
It's a shame that it adds so much noise to the pipeline YAML, but I think it's worthwhile.
Here's the non-step-dependencies DAG before:
and after adding step dependencies:
Critically, it pushes the Windows build off the critical path, saving 5-15 minutes:

build pipeline uses step dependencies (DAG)

---

clicommand/meta_data_exists.go
clicommand/meta_data_get.go
clicommand/meta_data_keys.go
clicommand/meta_data_set.go

The agent API for working with metadata requires a job ID, but under the hood the data is stored on the build not the job.
The help text for the flags wasn't as clear on that as it could be.
Related: https://github.com/buildkite/docs/issues/631

Clarify that metadata is always stored at the build, not the job

---

agent/pipeline_parser_test.go
clicommand/pipeline_upload.go

There was a report of pipeline statement `if: build.env("ACCOUNT") =~ /^(foo|bar)$/` resulted in error `Pipeline parsing of "" failed (Expected identifier to start with a letter, got /)`.
It turns out the `$` in the regexp is actually being interpreted as invalid [Environment Variable Substitution](https://buildkite.com/docs/agent/v3/cli-pipeline#environment-variable-substitution).
This PR;
(a) makes the error less mysterious; `parsing of "(stdin)" failed` rather than `parsing of "" failed` 
(b) adds a test demonstrating this case with and without env substitution enabled. 
I'm not actually sure the test is valuable, but it runs in 68 microseconds on my machine, so maybe not a burden to keep around.

Test & error message re. dollar sign escaping in pipeline conditional regexp

---

.buildkite/docker-compose.yml
.buildkite/pipeline.yml
.buildkite/steps/build-debian-packages.sh
.buildkite/steps/ruby-env
scripts/build-debian-package.sh

This step requires an environment with ruby (to use the fpm gem). Historically we've used the "queue=deploy" targeting to ensure it runs on an agent that happens to have ruby.
However, we'd like to be able to run this step on a standard elastic stack environment, which only has the bk agent binary, awscli, and docker.
This changes the step to launch a docker container with ruby for
the parts that need it.
I considered using the docker-compose plugin for the whole step like other parts of the pipeline, however there's a reasonable amount of existing shell code used here and I wasn't sure how it would interact with the plugin. In the end, I optimised for the least disruption to what was already there.

Alter debian package build step to work on agents without ruby

---

.buildkite/Dockerfile-windows

Windows builds of the agent have started failing, and all the failed jobs use the following digest of the windows/servercore image:
sha256:47bb7fe42f88823f3e54c03cefa2f20e3d7cff8a1a051878af2f45f6b6afef65
The last green windows build used this digest:
sha256:23e7bb473261f12307e82d0cd52a1bcbad4bc64c00e889cee344401d0c3de3d3
According to [docker hub](https://hub.docker.com/_/microsoft-windows-servercore), microsoft updated this image at:
02/11/2020 18:12:05
The timezone of that stamp is unclear but it's with 24 hours of when our builds started failing. Maybe locking us back to the older digest will help?

Lock our windows builds to a specific image digest

---

.buildkite/pipeline.yml
.buildkite/steps/build-rpm-packages.sh
scripts/build-rpm-package.sh

This step requires an environment with ruby (to use the fpm gem). Historically we've used the "queue=deploy" targeting to ensure it runs on an agent that happens to have ruby.
However, we'd like to be able to run this step on a standard elastic stack environment, which only has the bk agent binary, awscli, and docker.
This changes the step to launch a docker container with ruby for the parts that need it.
I considered using the docker-compose plugin for the whole step like other parts of the pipeline, however there's a reasonable amount of existing shell code used here and I wasn't sure how it would interact with the plugin. In the end, I optimised for the least disruption to what was already there.
PR #1165 is a matching change for building debian packages.

Alter rpm package build step to work on agents without ruby

---

.buildkite/pipeline.release-experimental.yml
.buildkite/pipeline.release-stable.yml
.buildkite/pipeline.release-unstable.yml

The "deploy" queue currently runs on the bastion, and we're trying to move things off that so it can be shut down.
publishing to s3 requires the buildkite-agent (to fetch metadata) and awscli (to push to s3), both of which are available on the elastic stack agents that process the "deploy-production" queue.
There's a good chance the agents won't have IAM permissions for pushing to the bucket, but we can address that if it happens.

run "publish to s3" steps on the new deploy-production agents

---

.buildkite/pipeline.release-experimental.yml
.buildkite/pipeline.release-stable.yml
.buildkite/pipeline.release-unstable.yml

The agent that used to process the "deploy" queue is now processing the "deploy-legacy" queue. That agent is deprecated and we're working on shutting it down.
Steps that used to run via the "deploy-production" queue should now target the "deploy" queue, which is an elastic stack.
/cc @chloeruka

shuffle agent targeting rules for the release pipelines

---

.buildkite/pipeline.yml

At the moment, we can trigger an edge release even if the tests fail on windows.
Here's what the agent pipeline looked like pre-DAG:
It may have been intentional to move the windows tests off the critical path,so opening this for discussion

require tests to pass on windows before we trigger an edge release

---

CHANGELOG.md
packaging/docker/alpine-linux/buildkite-agent.cfg
packaging/docker/centos-linux/buildkite-agent.cfg
packaging/docker/ubuntu-linux/buildkite-agent.cfg
packaging/github/linux/buildkite-agent.cfg
packaging/github/windows/buildkite-agent.cfg
packaging/linux/root/usr/share/buildkite-agent/buildkite-agent.cfg

No examples of `buildkite-agent start` nor samples of `buildkite-agent.cfg` mention the `--spawn` nor `spawn=1` options, respectively. But its so much nicer than manually curating half a dozen `buildkite-agent start` processes, their PIDs, etc. Let's advertise it some more.

add 'spawn=1' with comment + default to all .cfg templates

---

.buildkite/pipeline.release-experimental.yml
.buildkite/pipeline.release-stable.yml
.buildkite/pipeline.release-unstable.yml
.buildkite/steps/publish-to-s3.sh

In PR #1170 (and then c6de240) I jumped through some hoops to get the publishing to S3 to work without the "deploy-legacy" queue.
It worked, but the result was pretty messy.
This changes that step to launch within a docker container with all the tools we need, so the scripts can assume the tools are on the path.

use deploytools to publish to s3

---

agent/agent_worker.go
agent/job_runner.go
api/jobs.go
go.mod
go.sum
process/process.go
process/signal.go
process/signal_test.go
process/signal_windows.go

This is a follow-on to #890, and I believe the final missing piece before we have signal handling 👌🏻in the agent. 
To differentiate between the agent stopping and other types of cancellation, we now send two new parameters to `job.finish` in the agent API:
* `signal`. This tracks the operating system signal that the bootstrap was terminated with. This is useful for figuring out whether a failed command was due to it actually failing or whether it was terminated with a signal.
* `signal_reason`. This is `agent_stop` for agent stopping or `cancel` for agent cancellation.
I'd suggest that we add support for retrying on strings like `agent_lost` or `agent_stopped` as well as numeric exit codes. Given lots of previous agents erroneously returned an exit code of `255` we should probably …

Track reason why bootstrap was cancelled

---

.buildkite/steps/build-docker-image.sh
.buildkite/steps/extract-agent-version-metadata.sh
.buildkite/steps/publish-docker-images.sh

Historically, we've used a private docker hub area to hold images that may eventually be released as public images on https://hub.docker.com/r/buildkite/agent.
These days we're using ECR a lot more though, and managing authentication for that is much easier. It's one less secret for us to handle.
The agents that currently run this step don't auto-login to ECR, so we need to do so manually.

stage docker images in ECR rather than docker hub

---

clicommand/artifact_download.go
clicommand/artifact_upload.go

Based on https://github.com/buildkite/docs/pull/643 we figured the usage documenation regarding artifact destination wasn't clear. This updates the `--help` text for `buildkite-agent artifact upload` and `... download`, which will also eventually end up on https://buildkite.com/docs/agent/v3/cli-artifact#uploading-artifacts
Closes #1176

Artifact help doc destination tweaks

---

.buildkite/pipeline.release-experimental.yml
.buildkite/pipeline.release-stable.yml
.buildkite/pipeline.release-unstable.yml
.buildkite/steps/publish-docker-images.sh

The `deploy-legacy` queue is deprecated, and we're slowly moving steps off it.
There's two parts to publishing:
1. pulling the staged images from ECR
2. pushing the images to docker hub
For (1), the agents processing the new deploy queue are an elastic stack, and the instance roles in use have permission to pull from ECR. They also can use plugins, so we can use the ECR plugin to handle logins for us.
For (2), we need to manually pull the credentials from SSM and call "docker login". The agent that previously ran this step had a hook that handled docker hub authentication, but that's not our preferred approach any more.

publish images to docker hub using the deploy queue

---

.buildkite/pipeline.release-experimental.yml
.buildkite/pipeline.release-stable.yml
.buildkite/pipeline.release-unstable.yml
.buildkite/steps/publish-debian-package.sh
scripts/publish-debian-package.sh

The `deploy-legacy` queue is deprecated, and we're slowly moving steps off it.
The new `deploy` queue is processed by agents in an elastic stack, which has a few implications:
* most of the tools we need (like gnupg and ruby) aren't available by default, so we have to use a docker container with the tools we need
* sensitive values (like gpg keys) aren't stored on the new agents, so we need to fetch them from AWS SSM
Some bonus highlights:
* I pushed the `dry_run` logic to later in the scripts, to after the point where we configure gnupg. This lets us verify the gnupg setup in dry runs
* The gnupg keys are never written to disk - they only exist in a docker tmpfs volume

Migrate publishing of deb package to the new "deploy" queue

---

.buildkite/pipeline.yml

This will enable releases again. Edge releases will happen automatically, beta and stable releases still require a human to unblock.
Over the past few days a few release steps have move to new agents, so this will help confirm the release process still works on the new agents.

set DRY_RUN: false

---

.buildkite/pipeline.release-experimental.yml
.buildkite/steps/publish-rpm-package.sh

The "deploy-legacy" queue is deprecated, and we're slowly moving steps off it.
The new "deploy" queue is processed by agents in an elastic stack, which means most of the tools we need (like createrepo_c) aren't available by default. We can use a docker container with the tools we need.
Some highlights to call out here:
1. createrepo_c is available in the alpine package repositories (lucky!), so we install it each time
2. createrepo_c requires a full local copy of the rpm repository. The elastic stack agents processing the "deploy" queue don't have persistent local disk, so each time this step runs we have to re-download the full archive. It's currently ~9Gb and takes ~90 seconds to download. It's inefficient, but the time is probably tolerable given this doesn't run *that* often
3. …

migrate publishing of rpm packages to the new "deploy" queue

---

.buildkite/pipeline.release-stable.yml
.buildkite/pipeline.release-unstable.yml

In PR #1180 we moved rpm publishing to the deploy queue for experimental releases. That's working well, so this makes the same change for unstable (beta) and stable releases.

unstable and stable rpm publishing should run on the deploy queue

---

.buildkite/pipeline.release-stable.yml
.buildkite/pipeline.release-unstable.yml

In PR #1187 I moved unstable/stable rpm publishing to a new queue. Unfortunately, I forgot to also set the ENV var that sets the target S3 bucket for the rpms.

set RPM_S3_BUCKET bucket env var for unstable/stable releases

---

.buildkite/pipeline.release-stable.yml
.buildkite/pipeline.release-unstable.yml
.buildkite/steps/check-changelog.sh
.buildkite/steps/github-release.sh
.buildkite/steps/release-homebrew.sh

The `deploy-legacy` queue is deprecated, and we're slowly moving steps off it.
This moves the final two release steps off the `deploy-legacy`:
1. creating a release on github, using our [github-release binary](https://github.com/buildkite/github-release)
2. updating https://github.com/buildkite/homebrew-buildkite with the new version
Both steps are relatively straight-forward. All the required tools are in the deploytools image and they both require the same credential (a github API  token), so I've migrated them at the same time.
I've tested them both in dry-run mode and I'm fairly confident they'll run successfully on the new agents. However, it's hard to be 100% sure until we're ready for a real release.

Create github and homebrew releases using the deploy queue 

---

bootstrap/bootstrap.go

Without a checkout dir, which is also the working directory, exec-ing hooks will fail, and hooks like pre-exit will fail to run.
This also makes sure that checkout always happens with a present checkout directory, instead of into a potentially missing directory only on subsequent retries.
Fixes #1191.

Make sure checkout dir exists after checkout failure

---

README.md

Since #1117 merged, compilation is only possible on Go 1.11+

Update the README now that we're not vendoring dependencies

---

.buildkite/Dockerfile-windows
.buildkite/docker-compose.yml
README.md
go.mod

1.14 was released a few weeks ago, let's see if the agent pipelines likes it

bump Go to 1.14 for tests and compilation

---

.buildkite/docker-compose.yml

buildkite-agent 3.21.0 was built with go 1.14, which triggers a runtime panic in some situations where an mlock fails: https://github.com/golang/go/issues/37436
This bumps the docker sha to one containing 1.14.2, which correctly doesn't panic in those situations. 
Crash log is here: https://gist.github.com/zifnab06/afe1a89992e6374b9ebc42d38e119734
Either downgrading to 3.20.0-3264 (built with 1.13) or rebuilding 3.21.0 using go 1.14.2 resolves this.
If you really want to reproduce this, we're running buildkite-agent in a 16.04 (xenial) lxc container on a 20.04 (focal) host using kernel 5.4.0-29-generic (which maps to upstream 5.4.30).

Increase golang version due to runtime panic

---

go.mod
go.sum

Update buildkite/interpolate to get https://github.com/buildkite/interpolate/pull/7 /cc @ticky 
`${VAR:-127}` will now resolve to `127` if `VAR` isn't set.
Delta commit log on buildkite/interpolate:
*   07f35b4 Merge pull request #7 from buildkite/bash-compliant-substring-parsing Jessica Stokes 2 hours ago
|\
| * 24225d9 Update substring parser to comply with Bash's rules Jessica Stokes 10 days ago
|/
* 973457f Add an empty go.mod file Lachlan Donald 1 year, 7 months ago
* cfbed48 Update README to reflect current code Lachlan Donald 1 year, 7 months ago
* c1c376f Merge pull request #4 from buildkite/expose-identifiers-from-parse-tree Lachlan Donald 2 years, 3 months ago
* ad3fc26 Add a interpolate.Identifiers() for getting identifiers from a string Lachlan Donald 2 years, 3 months ago

buildkite/interpolate updated; ability to use numeric default

---

clicommand/agent_start.go
clicommand/annotate.go
clicommand/artifact_download.go
clicommand/artifact_shasum.go
clicommand/artifact_upload.go
clicommand/meta_data_exists.go
clicommand/meta_data_get.go
clicommand/meta_data_keys.go
clicommand/meta_data_set.go
clicommand/pipeline_upload.go
clicommand/step_get.go
clicommand/step_update.go

While the upload path normalisation logic added in #1211 worked in unit tests, it turns out the subcommand wasn't actually accepting the experiment flag, only `buildkite-agent start` was.
This updates all other subcommands to read the experiment values, even if they don't themselves currently implement an experiment. This permits experiments such as that added in #1211 to exist within in-job commands such as `artifact upload`.
Given that there currently are no end-to-end tests of the subcommand mechanism, should some be added? What shape would that take?
Tested by looking at the output of this (fake, expected to error out) command:
```bash
BUILDKITE_AGENT_ACCESS_TOKEN=fake \
BUILDKITE_JOB_ID=fake-uuid \
BUILDKITE_AGENT_EXPERIMENT=nomalise-upload-paths \
buildkite-agent artifact upload \ …
```

Accept `--experiment` flags in all buildkite-agent subcommands

---

agent/tags.go
agent/tags_test.go

Problem:
The Buildkite agent is trying to get GCP metadata before the network is ready on the VM
Solution:
This wraps the call (TagsFromGCPMetaData) in a retry, giving it the same treatment as we do for [TagsFromEC2MetaData](https://github.com/buildkite/agent/blob/master/agent/tags.go#L87) 
Still to do:
- Tests [ ]

Wrap calls for GCP metadata in a retry

---

bootstrap/bootstrap.go

This changes the default for the `git-mirrors` experiment to fetch only the branch vs a full `git remote update`. As reported in #1100, this can be a hugely expensive operation in large repositories.
---
_@pda update:_ Closes #1100 — this is the same idea, but without being user configurable.

Fetch only branch vs remote update

---

.buildkite/docker-compose.yml

There's no specific fixes we need, just keeping up to date

Update go used in test+builds from 1.14.2 to 1.14.4

---

env/environment.go
env/environment_test.go

The environment is captured before and after each hook runs; changes are detected and propagated to the rest of the build.
The current implementation does not detect newly introduced environment variables with an empty value.
This is due to the way Go's `map` type works; the key and value are statically typed, and accessing a key that does not exist returns the zero-value of the value type. That means for a `map[string]string` accessing a string key that doesn't exist returns `""`; the zero-value of `string` is an empty string.
When a newly introduced `FOO=""` environment is detected, it's empty-string value is compared to the pre-hook `env["FOO"]` which returns the empty string; this appears unchanged, so it's not included in the diff.
This is a problem if a hook attempts to declare a …

Hooks can introduce empty environment variables

---

.buildkite/pipeline.yml

Apple switched from Intel Core Duo (32-bit) to Core 2 Duo (64-bit) around 2006. Nothing running darwin since then needs a 32-bit i386 build. Our usage stats show that nobody is using darwin-386 builds of buildkite-agent v3.x. AFAIK the latest macOS (10.15 Catalina) won't run 32-bit binaries at all. And upcoming Macs are shifting to arm64.
There's no big gain from dropping this, but no real reason to keep it either.

Stop building i386 for darwin after 14 years of amd64 Mac hardware

---

install.sh

Upcoming macOS computers [will use the `arm64` architecture](https://developer.apple.com/documentation/xcode/building_a_universal_macos_binary). On such machines, our install script will currently fall through to attempting to fetch a `darwin-arm` binary, which does not exist. This future version of macOS allows `arm64` Macs to run `amd64` binaries through an emulation layer called Rosetta 2, and thus `darwin-amd64` is the most appropriate binary type for these machines until golang supports native `darwin-arm64` (see golang/go#38485).
This updates our install script to special-case the arm64 architecture when the platform is darwin, emit a message to the user, and proceed more or less as expected.

Fetch amd64 binaries on Apple Silicon Macs

---

install.sh

This splits up our UNAME to fetch the system and machine names separately.
Currently, the logic which normalises these remains the same, but it now additionally reports the non-normalised values so we can make better decisions about Agent platforms.

Send the reported system and machine names when fetching latest release

---

system/version_dump.go

On macos, windows and linux the agent registration request includes some basic info on the operating system. Version, distribution, etc. This data is used only for metrics on what environments the agent is used in.
We publish official binaries for some BSD systems (FreeBSD, OpenBSD, NetBSD and dragonfly), however we haven't been submitting any OS versions so we have a poor understanding of how often these operating systems are used.
This change includes the output of `uname -a` in agent registration requests on those operating systems.
I checked to see if the BSDs use `/etc/os-release` or similar, but it seems there's no consensus. FreeBSD look like [they  might be adding it in the next release](https://reviews.freebsd.org/D22271), the others seem not to have it (based on googling).
We …

submit basic OS info when registering from a BSD system

---

.buildkite/steps/build-rpm-packages.sh
scripts/build-rpm-package.sh

To address #1162 I'm tossing together a naive package builder codepath for RPM using our linux `arm64` binary to upload with the architecture `aarch64`. From googling, this appears to be the canonical architecture nomenclature for Red Hat based systems to refer to modern ARM processors. 
Please let me know if there's more that might need to be done, of particular concern is `scripts/build-rpm-package.sh` which possibly might need other adjustments to support ARM directly. I'd like to merge this ASAP to test it on an agent. I also think @jnewbigin has offered to do some testing if they see this 😄

Experimental: Build RPM package for ARM64 architecture (aarch64)

---

bootstrap/config.go
bootstrap/config_test.go

Add functionality to support `BUILDKITE_CLEAN_CHECKOUT` being set via hooks, and some fancy reflections to handle the conversion of the string value of this environment variable to a boolean.

allow CleanCheckout to be set via hooks

---

bootstrap/bootstrap.go

A bit of meditative tidying for `bootstrap/bootstrap.go`:
* explain the RedactLengthMin const in a code comment
* early return instead of indent, when it makes sense
* prefer `if` initialisation statement, when it makes sense
Best viewed with whitespace changes ignored (`&w=1`)

trivial bootstrap/bootstrap.go code style fixes

---

agent/download.go
agent/form_uploader.go
api/client.go

I've been staring at logs from the agent in HTTP Debug mode a whole bunch recently. I noticed the request logs always started like this:
2020-07-20 21:05:15 DEBUG  ERR: %!s(<nil>)
POST /v3/jobs/3a242e02-9ff7-4a2e-8e80-939bc30231c8/artifacts HTTP/1.1
Host: agent.buildkite.com
User-Agent: buildkite-agent/3.23-beta.1.x (linux; amd64)
.... and the response logs started like this...
2020-07-20 21:05:16 DEBUG
ERR: %!s(<nil>)
HTTP/1.1 201 Created
Transfer-Encoding: chunked
Cache-Control: max-age=0, private, must-revalidate
The potential error that we're trying to log is almost always going to be nil. Serialising the request/response into bytes will almost never fail.
I was unreasonably irritated by the little `%!s(<nil>)` for every request, so I've added some conditionals to make the log output …

avoid passing nils to Printf() during HTTP Debug mode

---

clicommand/agent_start.go
clicommand/global.go

This method dynamically fetches a list of all the environment variables that can be used to configure the agent, and removes them from the environment so they're not passed down to child processes (like the bootstrap used to run a job).
It's implemented using reflection on the flag structs from the `ufave/cli` package we use for CLI structure. It checks the EnvVar field on the flag struct, which works just fine with `ufave/cli/v1`. However, that field doesn't exist any more in `ufave/cli/v2` and this method has started silently failing since we upgraded to v2 in #1233.
In commit 1, I changed the method to fail loudly if the flag structs don't have the EnvVar field we expect. This would've made the issue obvious when #1233 was first proposed.
In commit 2, I update the method to work with …

Fix unsetting of agent config env to work with ufave/cli/v2

---

agent/agent_worker.go
agent/job_runner.go
clicommand/agent_start.go

Depends on #1250.
`BUILDKITE_AGENT_DEBUG` is already passed down to the job environment, and this expands that behaviour to also include `BUILDKITE_AGENT_DEBUG_HTTP`.
This is desirable because the build-agent binary is often used with jobs (eg. for artifact uploading/downloading) and from time to time it can be helpful to see precisely what those HTTP requests look like.

Enable BUILDKITE_AGENT_DEBUG_HTTP in jobs if it's enabled in the agent process

---

bootstrap/bootstrap.go

Problem: `git show HEAD` fails when there is a file called 'HEAD' in the
repository root, complaining about ambiguous reference
Solution: call `git show` without 'HEAD' argument, which will always show
the HEAD commit

Fix checkout when there is a file called HEAD in the repository root

---

.buildkite/pipeline.yml
.buildkite/steps/build-docker-image.sh
.buildkite/steps/extract-agent-version-metadata.sh
.buildkite/steps/publish-docker-images.sh
packaging/docker/sidecar/Dockerfile
packaging/docker/sidecar/buildkite-agent.cfg

This replaces https://github.com/buildkite/buildkite-sidecar and the keithduncan/buildkite-sidecar Docker Hub repository by tagging `buildkite/agent:X-sidecar` directly at the source.
Something I haven’t yet included is the [environment hook](https://github.com/buildkite/buildkite-sidecar/blob/master/agent/hooks/environment) that I used to print `BUILDKITE_ABOUT_*` variables in the build log. I’ve found that useful for my builds but I’m not sure whether to include for all sidecars?
cc @chloeruka @pda

Add sidecar Dockerfile and build steps

---

packaging/linux/root/usr/share/buildkite-agent/buildkite-agent.cfg

Noticed as I was filling out my config file for Datadog that there descriptions with most buildkite-agent options.
Since this might be an option few know about or some people may need to use, took a swing at filling in the blanks here, and provided a link to read on.
Let me know what you think!

Provide example dogstatsd integration options

---

bootstrap/integration/checkout_integration_test.go

Updates `git show HEAD` mock arguments to match changes from #1223 (70001925411ad1c459c47b00b217aba5027e126b, merged as f6d8056c6cdc6c2c82e5064013dd98067354185c) which introduced a trailing `--` to disambiguiate HEAD ref from HEAD file.

bootstrap/integration `git show` mock args updated.

---

.buildkite/docker-compose.yml

There's a few security and bug fixes. I'm not sure any of them impact us, but there's no harm in using the latest point release.
I noticed the bump was available because 1.14.7 fixes CVE-2020-16845, an [interesting sounding DOS vulnerability](https://groups.google.com/forum/m/#!msg/golang-announce/NyPIaucMgXo/GdsyQP6QAAAJ).
$ docker run -it golang:1.14@sha256:d31a307a7e42116adb00d8d70971dbf228460904dd9b6217e911d088aa4b650c
root@6fd0b4080736:/go# go version
go version go1.14.4 linux/amd64
$ docker run -it golang:1.14@sha256:174e1be71bd2aa8c65d6c17be0e5c0f8bc4e4ec03e82a5f57aad0b8acf22ef7f
root@45cef25b927c:/go# go version
go version go1.14.7 linux/amd64

bump build environment from go 1.14.4 to 1.14.7

---

.buildkite/steps/upload-release-steps.sh

In #1218 we added a new docker image to the build and release, but we forgot to pass the meta_data through to the release pipeline. This resulted in the release pipeline failing - eg:
https://buildkite.com/buildkite/agent-release-edge/builds/294#8d50db3e-781c-4690-9378-f1ddf83988be

pass sidecar docker image to release pipeline

---

agent/job_runner.go

In rare cases (like a server without much memory left), it possible starting the bootstrap child process can return an error:
```go
if err := r.process.Run(); err != nil {
```
We handle the error, however we've had reports that the job may be reported as passed rather than failed. Here's two screenshots demonstrating what it can look like:
This part is suspicious:
> Exited with status 0
In this failure case the process never started, so it doesn't have an exit code. This PR synthesizes a `-1` exit status to ensure the job is marked as failed.
`-1` is an overloaded exit status though, so we also send along a "reason" string. That's not displayed in the web UI yet, but at least we have a permanent record of what causes the `-1` and job failure.

Job should fail when process.Run() -> err

---

agent/form_uploader.go
agent/form_uploader_test.go

Buildkite provides a default artifact storage option that happens to be stored on S3. Each artifact is uploaded as a signed POST, which has a limit of 5Gb.
At the moment, artifacts that exceed this limit are uploaded 10 times (thanks to retries). On each attempt the full file contents is uploaded, only to be rejected by S3 at the end. What a waste of bandwidth and time.
This change ensures artifacts that exceed 5Gb display an error before starting the file upload. This isn't a perfect solution, as the retry logic kicks in and there's 10 retries. They complete quickly though, and no bandwidth is wasted.
The error message is long, but I thought it might be helpful to point to the other artifact storage options we support (like customer owned S3 buckets) where artifacts > 5Gb may work fine. …

fail fast when uploading an artifact > 5Gb to the default s3 bucket

---

agent/artifact_uploader.go

This adds a `Successfully uploaded "[file]"` log line to the agent output when a file has been successfully uploaded.
We would like to add this as several of our (internal) customers have misread these log lines, incorrectly assuming that the artifact was not successfully uploaded.

add successful logging statement to artifact uploader

---

agent/artifact_uploader.go

The current non-debug output during artifact uploads looks like this:
--- Uploading artifacts
$ buildkite-agent artifact upload log/*.log
2020-06-23 17:46:52 INFO   Found 1 files that match "log/*.log"
2020-06-23 17:46:52 INFO   Creating (0-1)/1 artifacts
2020-06-23 17:46:52 INFO   Uploading artifact 4941dcd3-665d-445b-86b0-8d552b86dd53 log/foo.log (2275 bytes)
Without debug logging, there's no output once the uploads start, and if the upload process hangs for any reason it can be hard to see (based on log output only) where things have become stuck.
This adds a single Info-level log line when all artifacts have successfully been uploaded, so it's obvious when that process has
completed. Any stalled builds after that point will be easier to attribute to a non-artifact uploading issue.
I …

Add some extra debug logging during artifact uploads

---

experiments/experiments.go

Two parts, both rather superficial…
----
Simplify the implementation of `experiments.IsEnabled()`. Go's `map` type returns the zero-value of its value type for missing keys; so `map[string]bool` returns `false` for missing keys.
That means we don't need any extra logic to check for the existence of the key.
----
The rest of the PR is mostly var renaming to make the implementation of Enabled() clearer.
Idiomatic Go uses `ok` to indicate whether a key _existed_ in a map, e.g. `value, ok := experiments["foo"]`.
Whereas we were using it to refer to the boolean _value_ of the `map[string]bool` in the context of a range,
i.e. `for key, ok := range experiments`.
And `var enabled []string` as the accumulator list of enabled experiments is problematic because `enabled` isn't exclusively plural; …

Refactor experiments local var naming

---

clicommand/annotate.go
clicommand/meta_data_set.go
clicommand/pipeline_upload.go

As noted in https://github.com/buildkite/docs/pull/806 - the `file` arg is optional, and so should be wrapped in square brackets in the help text.

Add optional brackets to file arg

---

agent/artifact_batch_creator.go

PR to address some small errors I noticed while spelunking the artifacts commands:
- Typo corrected `theseArtiacts` -> `theseArtifacts`
- Fix `[go-vet] api.ArtifactBatch composite literal uses unkeyed fields` by keying all the struct fields in use.

Fix: typo, resolve composite literal warn

---

agent/artifact_downloader.go
agent/artifact_searcher.go
api/artifacts.go
clicommand/artifact_search.go
clicommand/artifact_shasum.go
main.go

Currently the `buildkite-agent artifact download` command runs an API search for artifacts on a build matching a pattern and then subsequently downloads those files. The search phase of this is useful to have and having a separate subcommand resolves a couple of CS tickets.
Additional fields have been added to the `artifact` struct to make the output from search more useful. A `search` subcommand has been added to `buildkite-agent artifact` which takes the signature:
```sh
$ buildkite-agent artifact search [options] <query>
```
The output from this command is a flexible printf statement not unlike [unix find's -printf directives](https://man7.org/linux/man-pages/man1/find.1.html). By default it lists the job ID, artifact path and timestamp of each artifact  separated by newline (aiming to …

Add artifact search subcommand

---

go.mod
go.sum

In PR #1233 we upgrade this library to v2, but then reverted it in PR #1286 after discovering the upgrade lead to a breaking change in our CLI.
It seems we're stuck on v1 for now, but we may as well update to the latest v1 release. This takes us to a version with formal go mod support.

update github.com/urfave/cli to the latest v1 release

---

bootstrap/integration/git.go

Here's a test failure I experienced repeatably in ad-hoc Windows testing, but wasn't showing up in CI Windows testing:
```
C:\pda\agent>go test ./bootstrap/integration -run TestPreExitHooksRunsAfterCommandFails
--- FAIL: TestPreExitHooksRunsAfterCommandFails (3.24s)
panic: exit status 128 [recovered]
panic: exit status 128
goroutine 21 [running]:
testing.tRunner.func1.1(0x207a3e0, 0xc0002acfa0)
c:/go/src/testing/testing.go:1057 +0x310
testing.tRunner.func1(0xc0000c0900)
c:/go/src/testing/testing.go:1060 +0x43a
panic(0x207a3e0, 0xc0002acfa0)
c:/go/src/runtime/panic.go:969 +0x176
github.com/buildkite/agent/v3/bootstrap/integration.(*BootstrapTester).ExpectLocalHook(0xc000332000, 0x20d8c35, 0x8, 0xc0003700a0)
C:/pda/agent/bootstrap/integration/bootstrap_tester.go:214 +0x467 …
```

Windows integration tests: git file path quirk fix

---

install.sh

Following on from #1237, with new discoveries!
Turns out that in many cases, Apple Silicon Macs will in fact run Bash in amd64 mode, which in turn means the reported architecture is amd64, even though it's an Apple Silicon Mac. Homebrew has worked around this in Homebrew/brew#7995, and we more or less follow their lead here.
This makes it so that we _always_ show our little notice on Apple Silicon Macs, whether their shell is in amd64 or arm64 mode.

Improve Apple Silicon Mac support

---

.buildkite/pipeline.bk-test.yml
.buildkite/pipeline.yml

This adds more virtual Buildkite steps to the "bk cli" test. Initially intended for testing the bk CLI against the Agent, this is also a handy way for us to check we haven't broken any Agent CLI arguments.
So, this adds a test which uses the meta-data subcommand with a default set, and a suite of tests which exercise the annotate subcommand.
It also renames it so it’s a little more visible in the timeline, as I completely missed that this step even existed! 😅

Expand the CLI test step

---

agent/artifact_uploader_test.go
bootstrap/integration/checkout_integration_test.go

Some tests have been mysteriously flaky (particularly on Windows, but that may be a red herring), failing without an error message. Somehow, https://github.com/buildkite/agent/pull/1294 has revealed the error messages:
```
=== Failed
  | === FAIL: bootstrap/integration TestCheckingOutLocalGitProject (7.00s)
  | mock.go:248: Unexpected call to git "rev-parse", "HEAD"
  | mock.go:255: More invocations than expected (1 vs 7)
  |  
  | === FAIL: bootstrap/integration TestCheckingOutShallowCloneOfLocalGitProject (7.69s)
  | mock.go:248: Unexpected call to git "rev-parse", "HEAD"
  | mock.go:255: More invocations than expected (1 vs 7)
```
I believe this is being caused by `TestWithResolvingCommitExperiment` in `bootstrap/integration/checkout_integration_test.go` running with `t.Parallel()` and …

Fix flaky tests: experiments and parallel tests don't mix

---

scripts/build-binary.sh

The `BUILD_VERSION` arg was not being properly set because the
package/import path changed with the v3 agent.
Without:
```
scripts/build-binary.sh linux amd64 1
pkg/buildkite-agent-linux-amd64 --version
buildkite-agent version 3.23.1, build x
```
With:
```
scripts/build-binary.sh linux amd64 1
pkg/buildkite-agent-linux-amd64 --version
buildkite-agent version 3.23.1, build 1
```

Fix build script

---

agent/integration/job_runner_integration_test.go
bootstrap/bootstrap.go
bootstrap/git_test.go
bootstrap/integration/artifact_integration_test.go
bootstrap/integration/bootstrap_tester.go
bootstrap/integration/checkout_integration_test.go
bootstrap/integration/command_integration_test.go
bootstrap/integration/docker_integration_test.go
bootstrap/integration/hooks_integration_test.go
bootstrap/integration/main_test.go
bootstrap/integration/plugin_integration_test.go
bootstrap/knownhosts_test.go
bootstrap/shell/shell.go
bootstrap/shell/shell_test.go
bootstrap/ssh_test.go
go.mod
go.sum
process/process.go
process/process_test.go

This builds on @sj26's [great investigation](https://github.com/buildkite/agent/pull/1270) identifying that `buildkite-agent meta-data set buildkite:git:commit` should take the commit message via stdin, not argv. Otherwise a very large commit message may exceed the system argv limit,
resulting in: `fork/exec /usr/local/bin/buildkite-agent: argument list too long`.
The key to this approach is `func (s *Shell) WithStdin(r io.Reader) *Shell` — it avoids threading our new `stdin` through multiple layers and variants of `Run()` etc.
The initial “package process supports Stdin” and “bootstrap/shell.Shell.WithStdin() to pass stdin to commands.” commits in this PR are self-contained with a test each, which I think demonstrates there's no blocking/closing issue with passing the `io.Reader` to our …

buildkite:git:commit meta-data via stdin; avoid Argument List Too Long

---

agent/job_runner.go
agent/job_runner_test.go
logger/buffer.go
logger/buffer_test.go

Truncate the `BUILDKITE_MESSAGE` commit message passed to the bootstrap process to 64 KiB so that large commit messages won't stop execution.
Follow-up to #1302, which enabled large commit messages to be pushed from the agent to Buildkite via `buildkite-agent meta-data set buildkite:git:commit`, but which uncovered this other bottleneck for message size.
The 64 KiB figure was chosen somewhat arbitrarily; but it is…
* half the per-env limit of modern linux
* quarter the shared limit of macOS
* a tiny fraction of the modern Windows limit
* double the [limit of Windows circa 2010](https://devblogs.microsoft.com/oldnewthing/20100203-00/?p=15083) (if this becomes a problem, we can reduce it for that platform)
Here's some ENV limits I've researched/discovered (see notes below):
```
// macOS …
```

Truncate BUILDKITE_MESSAGE to 64 KiB

---

bootstrap/bootstrap.go
bootstrap/integration/checkout_integration_test.go

When `git-mirrors` (currently an experiment) is enabled, export a `BUILDKITE_REPO_MIRROR=/path/to/mirror/repo` environment variable. This makes it easy to mount the mirror as a volume in docker containers, so that `git` within the container can access the git reference repository data.
The name `BUILDKITE_REPO_MIRROR` was chosen to reflect the existing `BUILDKITE_REPO` environment variable.
This environment variable enables transparent support for `git-mirrors` in our [docker plugin](https://github.com/buildkite-plugins/docker-buildkite-plugin) and our [docker-compose plugin](https://github.com/buildkite-plugins/docker-compose-buildkite-plugin):
- https://github.com/buildkite-plugins/docker-buildkite-plugin/pull/167
- https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/pul …

git-mirrors: set BUILDKITE_REPO_MIRROR=/path/to/mirror/repo

---

system/version_dump_windows.go

While running the agent on Windows 10 I noticed we were submitting the version as "Windows version 6.2", which [maps to windows 8](https://en.wikipedia.org/wiki/List_of_Microsoft_Windows_versions).
According to MSDN, the GetVersion call we're using [always reports windows 8 for compatibility reasons](https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getversion):
> GetVersion may be altered or unavailable for releases after Windows 8.1.
> Instead, use the Version Helper functions. For Windows 10 apps, please see
> [Targeting your applications for
> Windows](/windows/win32/sysinfo/targeting-your-application-at-windows-8-1).
>
> With the release of Windows 8.1, the behavior of the GetVersion API has changed
> in the value it will return for the operating system …

Update the way we detect windows versions

---

bootstrap/bootstrap.go
bootstrap/git.go
bootstrap/git_test.go

When constructing the `git checkout` command, the sometimes-user-specified branch name should never be considered flags/options by `git`. It's not possible to terminate arg parsing with `--` because that has special meaning to `git checkout` — it indicates the following names are files, not refs. So, the ref must be validated. There's a [`git check-ref-format`](https://git-scm.com/docs/git-check-ref-format) subcommand which roughly does that. Rather than shelling out to git, this patch introduces a simple `gitCheckRefFormat(ref)` implementation to verify the ref doesn't start with a hyphen. This could be replaced with shell-out or a more thorough implementation if that feels worth doing.
With branch set to `--foo`…
* Before: `git checkout -f --foo` → `error: unknown option 'foo'`.
* …

gitCheckout() validates branch, plus unit tests

---

agent/agent_worker.go
agent/job_runner.go

I noticed a log like the following agent output. A user clicked cancel on buildkite.com, the agent detected the request and attempted to stop the job process, but then continued to believe the job was still running for days (until the server was stopped):
> 2020-09-29 17:13:51 DEBUG  GET https://agent.buildkite.com/v3/jobs/fc8a2db9-c642-44f6-8d1f-61ece6b37b1f
> 2020-09-29 17:13:51 DEBUG  ↳ GET https://agent.buildkite.com/v3/jobs/fc8a2db9-c642-44f6-8d1f-61ece6b37b1f proto=HTTP/1.1 status=200 Δ=203.896ms
> 2020-09-29 17:13:51 INFO   myagent-1 Canceling job fc8a2db9-c642-44f6-8d1f-61ece6b37b1f with a grace period of 10s
> 2020-09-29 17:14:01 INFO   myagent-1 Job fc8a2db9-c642-44f6-8d1f-61ece6b37b1f hasn't stopped in time, terminating
> 2020-09-29 17:14:01 DEBUG  myagent-1 [Process] …

Log error messages when canceling a running job fails

---

CHANGELOG.md
clicommand/agent_start.go
clicommand/agent_start_test.go

This will be useful for ensuring graceful shutdowns and cleanup when the
agent is integrated with other systems, like k8s.
This only runs once per agent, regardless of the number of workers. It looks for a `shutdown` script in the hooks directory on the agent.
Question:
- Does anything special need to be done for Windows?

Add an agent-wide shutdown hook

---

bootstrap/bootstrap.go
hook/hook.go
utils/file.go

_This is a refactor extracted from #1322, to reduce the size/scope of that pull request._
Introduces a new package `hook`, and extracts `bootstrap.(*Bootstrap).findHookFile()` → `hook.Find()` like so:
```diff
-// package bootstrap
-func (b *Bootstrap) findHookFile(hookDir string, name string) (string, error)
+// package hook
+func Find(hookDir string, name string) (string, error) {
```
This allows code outside package `bootstrap` to resolve hook files, including the `.BAT;.CMD;.PS1` Windows search strategy.
To support this refactor, our file-existence helper has been extracted to the existing package `utils`:
```diff
-// package bootstrap
-func fileExists(filename string) bool
+// package utils
+func FileExists(filename string) bool
```

Refactor: extract bootstrap.findHookFile() → hook.Find()

---

agent/job_runner_test.go
clicommand/agent_start.go
clicommand/agent_start_test.go
logger/buffer.go
logger/buffer_test.go

#1275 introduced a `shutdown` hook, which runs as the agent is shutting down. This is the first hook we've added which doesn't run as part of the `bootstrap` process for a job.
The current implementation looks for a `$HOOKS/shutdown` file, and runs it directly as a shell command, which assumes it's a bash script due to the lack of a file extension. Windows users are more likely to specify a shutdown hook as a batch or PowerShell file.
I've done some refactoring in #1324, #1325 and to extract some hook code from package `bootstrap` into a new package `hook`.
This pull request uses the new `hook.Find(dir, name)` function to give `shutdownHook()` the same search logic as bootstrap hooks; that means on Windows `shutdown.bat`, `shutdown.cmd` and `shutdown.ps1` files are considered. …

shutdown hook on Windows supports Batch & PowerShell

---

go.mod
go.sum
process/signal_windows.go

The syscall package in the stdlib has a frozen interface, however `golang.org/x/sys` continues to evolve. Some of the windows APIs that we're manually accessing via syscall now have go-ish wrappers in sys/windows that are a bit nicer to work with.
There should be no functional difference from this change.
This is extracted from #1321, which I expect to take some time to mature. This little bit is totally mergable though!

use golang.org/x/sys/windows instead of syscall, where we can

---

process/process.go
process/signal.go
process/signal_test.go
process/signal_windows.go

Imagine a windows process tree like this:
1000 buildkite-agent.exe start
└─ 1001 buildkite-agent.exe bootstrap
└─ 1002 cmd.exe
└─ 1003 python.exe
└─ 1004 python.exe
It's reasonably common in windows for a process to end and orphan its children, leaving a tree like this:
1000 buildkite-agent.exe start
└─ 1001 buildkite-agent.exe bootstrap
└─ 1002 cmd.exe
└─ 1004 python.exe
Then the bootstrap might end, leaving the orphan process hanging around after the job has completed. Oops.
On UNIX systems we avoid this by creating a progress group, so any process that starts during job execution is tidied up when the bootstrap process finishes.
Here I've introduced win32 Job Object to achieve a similar effect on Windows. This has two noteworthy impacts:
1. The bootstrap process created to run a …

Use a win32 Job Object to manage job termination on windows

---

system/version_dump_windows.go

This value is required to disambiguate between desktop windows (like windows 7, 8 and 10) and server windows (like server 2012, 2016 and 2019).
Ref: https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ns-wdm-_osversioninfoexw#remarks

add productType to the OS telemetry we send from windows

---

clicommand/agent_start.go
clicommand/agent_start_test.go
clicommand/global.go

This pull request pipes the output of the new shutdown script (#1275) into the main logger.
The shutdown hook output is written directly to `os.Stdout`:
(The :skull: is my shell warning that the program terminated without a trailing newline)
The shutdown hook output is pipes to the logger, with a prefix of `shutdown` to identify where it came from:
I had some issues with color creeping in despite `--no-color` being passed. All fixed:
Here's the `shutdown` hook I was using:
```
$ cat tmp/hooks/shutdown
#!/bin/bash
echo "hello stdout from shutdown hook"
echo >&2 "hello stderr from shutdown hook"
echo -n "no line ending here"
```
It would be nice to refactor the `io.Writer`→`logger.Logger` pipe gear out of `shutdownHook()` so it can be used elsewhere. That'll need a bit of finesse to …

shutdown hook: pipe output lines to main logger

---

bootstrap/bootstrap.go
bootstrap/integration/checkout_integration_test.go
clicommand/agent_start.go
clicommand/bootstrap.go

The mirror clone can't operate without it as subsequent steps will fail if they are performed on a full checkout. I think I mentioned this in the original issue, but I think this is a better default.
Fixes #1319

Add --mirror flag by default for mirror clones

---

packaging/docker/ubuntu-linux/Dockerfile

Upgrade the ubuntu release we use when packaging the agent docker image. We're currently using the previous LTS release (18.04) and this bumps it to the latest LTS release from earlier this year (20.04).
I built and ran the image locally and it worked fine.

Upgrade docker ubuntu to 20.04 focal

---

packaging/docker/alpine-linux/Dockerfile
packaging/docker/sidecar/Dockerfile

Alpine 3.8 was released in June 2018 and last updated in December 2018. Bumping to 3.12 means we'll get newer versions of supporting libraries and programs like jq, tzdata, docker client, bash, git and ca-certificates.
We can also switch to installing docker-compose from a package - alpine 3.12 ships with docker-compose 1.25.4.
I've also bumped the alpine version we use while building the sidecar docker image, although it's only a stage on the way to the final image and should have no user visible impact.
Like the similar ubuntu bump in #1312, this has the potential to surprise some users when  they get newer tools versions at the same time as upgrading to a new agent version though. However, with our current docker tagging strategy that's unavoidable and it's probably better for us to …

bump alpine docker image from alpine 3.8 to 3.12

---

.buildkite/docker-compose.yml

There's no driving reason to upgrade, but 1.15 has been out for a couple of months and has a few bugfix releases. Maybe it's ready for us to try?

upgrade from golang 1.14 to 1.15

---

install.sh

Enable the install script to use the arm64 binary when uname reports that the machine is aarch64.

install: use the arm64 binary for aarch64 machines

---

.buildkite/pipeline.yml
.buildkite/steps/build-apple-silicon-binary.sh
scripts/build-binary.sh

This adds a new build step that compiles a native agent for Apple Silicon. I think. I don't have one to test on.
Cross compiling for Apple Silicon requires `GOARCH=arm64` and `GOOS=darwin`, which is a valid combination on unreleased version of go and will be valid in the upcoming 1.16 release.
We currently compile using go 1.15, so this new step uses gotip to install the latest unreleased golang. That probably means the darwin-arm64 binary it spits out should be considered experimental.

Use gotip (pre 1.16) to compile a native executable for Apple Silicon

---

bootstrap/bootstrap.go
bootstrap/integration/checkout_integration_test.go
bootstrap/integration/git.go

This fixes a regression that was introduced in https://github.com/buildkite/agent/pull/1112 which means git-mirrors doesn't work with PRs from forks

Handle pull requests with git-mirrors

---

install.sh

The inverse of #1289, enabling actual Macs to download actual (future) binaries enabled by #1339

Allow downloading Apple silicon Mac builds

---

.buildkite/pipeline.yml

This will mean all release steps have no publicly visible effect. This will enable @ticky and I to confirm the proposed changes to the homebrew release script will work as we hope.
Once we've finished changing the homebrew release script, this commit can be reversed.

enable DRY_RUN in the build pipeline

---

.buildkite/steps/release-homebrew.sh
scripts/update-homebrew-formula.rb

This attempts to add arm64 build support to the release-homebrew step
Depends on buildkite/homebrew-buildkite#19, and needs some testing!

Support for arm64 releases in release-homebrew step

---

.buildkite/pipeline.yml
agent/version.go

We temporarily enabled DRY_RUN mode while @ticky and I prepared a change to the homebrew release script (#1346). That change has merged, so we can allow real releases again.
I've also bumped the version back down to match the current release so the CD pipeline won't try to release new experimental versions that have low value.

go back to allowing real releases

---

.gitignore
packaging/docker/alpine-linux/Dockerfile
packaging/docker/centos-linux/Dockerfile
packaging/docker/ubuntu-linux/Dockerfile

This basically replaces #1214 as it seems to be abandoned and we would really like to see the Docker Compose version upgraded.
This PR upgrades de `tini` and `docker-compose` binaries to their newest versions on Ubuntu & CentOS. It also replaces the deprecated `docker.io` package with the installation method described on https://docs.docker.com/engine/install/ubuntu/ for Ubuntu.
The big difference with this PR in comparison to #1214 is the bare inclusion of Docker's CLI packages. No longer is the whole Docker engine included, as I suspect most people will just bind mount the socket inside the Docker container. Please let me know if this is undesirable somehow, then I will add the engine back.
Centos is also bumped from 7.x to 8.x, the current stable release.

Use Docker CLI packages, update Docker Compose, and update centos to 8.x

---

clicommand/agent_start.go

Homebrew for ARM Macs will support installation into the /opt/homebrew prefix, instead of /usr/local.
This patch updates our path code to accept both on Apple silicon, but only the former in amd64 builds, allowing for two installations on the same machine if desired.
Fixes #1353

Add support for the /opt/homebrew prefix

---

agent/s3.go
clicommand/artifact_upload.go

Allows BuildKite pipelines to upload artifacts using AssumedRoles.
Closes #1357

S3 uploader: load BUILDKITE_S3_SESSION_TOKEN

---

go.mod
go.sum

Will fix build regression introduced in #1273 due to https://github.com/DataDog/dd-trace-go/issues/753

Use dd-trace-go >= v1.27.1 to fix multiplatform build

---

agent/artifact_uploader.go
agent/artifact_uploader_test.go
clicommand/artifact_upload.go
test/fixtures/artifacts/links/folder-link
test/fixtures/artifacts/links/terminator/terminator2.jpg

Currently when specifying `artifact_paths:` in a step if the path contains a symbolic link the path pointed to by the symbolic link isn't followed and those files are excluded from the upload.
This PR updates the behavior of the artifact uploader to follow symbolic links if they are present in the glob path.

Have ArtifactUploader follow symlinks

---

.buildkite/image-builder/bootstrap.ps1

_This is not a code change since this bootstrapper is managed manually (for now)._ 
The build is currently broken because (my hypothesis) the symlink changes introduced in 029676f131e776a2f580d38cd6ccf94a815067c8 were expected to work on Windows. We need to enable `core.symlinks` to correctly checkout the symlinks on the Windows platform ([here's a StackOverflow](https://stackoverflow.com/questions/5917249/git-symlinks-in-windows/59761201), here be dragons). This _does_ expect that Windows checkouts are run as Administrator, _unless_ [developer mode](https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/) is already activated on Windows Server Core AMIs (probably not?)

Use core.symlinks to attempt symlink testing on Windows

---

.buildkite/docker-compose.yml

Bump us to the latest release candidate just for darwin/ARM64 builds for Apple silicon. We're still waiting on a stable 1.16 release, but this is probably very close.

Use golang 1.16rc1 for darwin/ARM builds

---

packaging/linux/scripts/before-remove.sh

`systemctl disable` doesn't accept wildcards (unlike start/stop/etc) but:
> Note that this removes all symlinks to matching unit files, including manually created symlinks, and not just those actually created by enable or link.
https://www.freedesktop.org/software/systemd/man/systemctl.html#disable%20UNIT…
so we can disable the template and that should remove all symlinked instances.
Fixes #1370.

systemctl disable via template and symlinks

---

agent/pipeline_parser.go
agent/pipeline_parser_test.go

`PipelineParser` no longer loads system env by default. There is no non-test code relying on the default.
The only real caller of `PipelineParser` is `clicommand/pipeline_upload.go`, which manually passes a (potentially modified) system environment.
The only other caller is `agent/pipeline_parser_test.go`, and defaulting to system environment in tests makes them fragile. Currently they're breaking due to `BUILDKITE_TRACE_CONTEXT` leaking in from outside.
So, this PR defaults `PipelineParser` to an empty environment, and adjusts the tests accordingly. It also normalises PipelineParser syntax/whitespace in the tests, which accounts for many lines of code — I recommend viewing 347ae27fcafca2910b72ab1064634789c92a8bfd separately.
Before:
```
pda@paulbookpro ~/bk/agent $ …
```

pipeline_parser_test decouple from environment

---

clicommand/agent_start.go

This allows using the special token `%spawn` in the agent name, which will locally substitute the spawned worker index.

Allow using the spawn index in the agent name

---

.buildkite/docker-compose.yml
.buildkite/pipeline.yml

1.16.0 was released today. It includes official support for cross compiling for macos m1 systems, so we can remove the special case that built that particular binary using a pre-release of go.
I used [dfresh](https://github.com/realestate-com-au/dfresh) to get the correct image sha:
```
$ dfresh resolve golang:1.16
golang:1.16@sha256:f3f90f4d30866c1bdae90012b506bd5e557ce27ccd2510ed30a011c44c1affc8
```

switch to golang 1.16 for running tests and compiling binaries

---

agent/ec2_meta_data.go
clicommand/agent_start.go

When the agent is started with the --tags-from-ec2-meta-data flag it collects a default set of agent tags by querying the instance metadata service.
This adds a new tag to the default set - aws:instance-life-cycle. The tag value will be either "on-demand" or "spot", which can be useful to debugging."on-demand" or "spot", which can be useful to debugging.
The instance-life-cycle metadata key was [added in IMDSv2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html). I'm not 100% sure what will happen if the agent runs on an instance with only IMDSv1. I added the new code at the end of the method, so I suspect the new tag will just be missing on those agents.
Here's the output starting an agent built with this branch:
$ ./buildkite-agent start …

collect instance-life-cycle as a default tag on EC2 instances

---

agent/plugin/plugin.go
agent/plugin/plugin_test.go

Experimental - see https://forum.buildkite.community/t/native-support-for-golang-plugins/776/5
tl;dr:
Exposes two new environment variables to plugins:
* `BUILDKITE_PLUGIN_NAME` - The "env key compatible" version of the current plugin name - that's what's being used to construct the `BUILDKITE_PLUGIN_<name>_<param>` variables
* `BUILDKITE_PLUGIN_CONFIGURATION` - JSON string holding the current plugin's configuration (as opposed to all the plugin configs as found in `BUILDKITE_PLUGINS`

Export current plugin name and Configuration

---

agent/version.go

Bumping this to be higher than the current released version will mean our build/release pipeline starts releasing each main build as an experimental release that's available to customers.

bump agent version to include -pre

---

agent/version.go
agent/version_test.go

The current version string isn't valid and doesn't parse on the Buildkite end, so `3.28.0.pre` agents cannot register
This fixes the version string to be valid, and adds a note about valid version strings to version.go

Fix the current beta version

---

agent/job_runner.go

`buildkite-agent start` has a `--no-pty` flag which prevents the bootstrap from being run as a PTY process.
Seperately, `buildkite-agent bootstrap` has a default-true `--pty` flag which determines whether commands run _within_ the bootstrap are run as PTY processes.
Presumably, `buildkite-agent start --no-pty` should propagate to `buildkite-agent bootstrap --pty=false`, but that was not happening. That meant that builds running under `buildkite-agent start --no-pty` invoked a bootstrap as a non-PTY process, but the bootstrap invoked commands in PTY mode. On systems with no PTY capability (e.g. AWS Lambda) that was causing severe errors:
This pull request propagates the flag into the bootstrap via the internal `BUILDKITE_PTY` environment variable.
Here's that previously failing build step:

Propagate --no-pty to the bootstrap --pty flag

---

.buildkite/Dockerfile-compile
.buildkite/docker-compose.yml
.github/dependabot.yml

This configures dependabot to propose updates to the golang version we use, but at most once per week.
The nice thing about this is we can continue to provide precise docker image digests so builds are deterministic (no failures when a docker tag is mutated with an unexpected change), but we'll also be prompted to start using golang security updates.
Unfortunately dependabot doesn't support docker compose files, so I had to add some indirection and move the base image details into a Dockerfile.

Configure dependabot to propose update to the golang version we build with

---

agent/job_runner.go
bootstrap/bootstrap.go
bootstrap/config.go
bootstrap/shell/shell.go
clicommand/agent_start.go
clicommand/bootstrap.go

Currently bootstrap sends a `SIGTERM` to commands when it, itself, is interrupted.
This adds `cancel-signal` which accepts signals in the form of SIGTERM, SIGHUP, etc.
This is the same config that `start` accepts, and is based on the PR that added that feature: https://github.com/buildkite/agent/pull/1041
Finally, `start` passes its `cancel-signal` to `bootstrap`, to prevent having to customize the `bootstrap-script`.

Allow signal bootstrap sends to commands on cancel to be customized

---

clicommand/agent_start.go

`https://github.com/buildkite/agent/v3` is a 404. It should be `https://github.com/buildkite/agent`.

Fix source code link

---

packaging/docker/alpine-linux/buildkite-agent.cfg
packaging/docker/centos-linux/buildkite-agent.cfg
packaging/docker/sidecar/buildkite-agent.cfg
packaging/docker/ubuntu-linux/buildkite-agent.cfg
packaging/github/linux/buildkite-agent.cfg
packaging/github/windows/buildkite-agent.cfg
packaging/linux/root/usr/share/buildkite-agent/buildkite-agent.cfg

`%spawn` was introduced in 8f6ee24646d4e1f028845fab6fa987d4cebdc68e / https://github.com/buildkite/agent/pull/1377 and is resolved client-side via `buildkite-agent start --spawn <n>`. 
`%n` is resolved server-side and is considered soft-deprecated.
This PR changes the default configuration files to use `%spawn` rather than `%n`.
This has some potential for mischief if people are running multiple agents with the same name as separate processes, rather than using `--spawn`. For example `name=%hostname-%spawn` with multiple agent processes per machine. Or, if `%hostname` is replaced with a fixed value like `name=acme-%spawn` across multiple machines. In those cases, `%n` would resolve to a different number for each process, while `%spawn` would resolve to `1` in each process.
In the case of …

Use new client-side %spawn not server-side %n in default configs

---

bootstrap/bootstrap.go
bootstrap/redactor.go
bootstrap/redactor_test.go

Currently the `output-redactor` only applies to `Shell.Writer`, so the output of programs run via the shell are redacted. However `Shell` also has a `Logger` which is used to show the command being run, and — importantly — to show environment variable changes after hooks run. Those environment variable changes may contain secrets, e.g. if `BUILDKITE_REPO` is changed by a hook to include a secret token in the URL.
This PR applies the redactor to `Shell.Logger` too (assuming it's a `shell.WriterLogger`, which is true except in tests). This actually requires setting up a second redactor instance, because shell's default logger outputs separately to `os.Stderr`. To manage two redactors instead of one, a `type RedactorMux []*Redactor` is introduced to multiplex `Flush()` and `Reset()` commands …

output-redactor: redact shell logger, including changed env vars

---

.buildkite/steps/test-bk.sh

I noticed this while digging into something unrelated, and assume we might want to be running these tests with the latest bk cli release?

Update bk cli test to use the latest release (1.0.0 -> 1.2.0)

---

clicommand/agent_start.go

`AWS_SECRET_ACCESS_KEY` is a commonly used environment variable which holds credentials that should be redacted, but wasn't matched by the existing defaults `*_PASSWORD,*_SECRET,*_TOKEN`.
Likewise, for custom S3 artifact destinations, `BUILDKITE_S3_SECRET_KEY` is used.
I don't think we should try to match everything under the sun in the default config, but AWS is a big one.

Add *_ACCESS_KEY & *_SECRET_KEY to default redactor-var

---

bootstrap/shell/shell.go
bootstrap/shell/test.go

The bootstrap process runs a lot of shell scripts - all hooks and plugins are implemented as shell. Previously the bash path on non-windows was hard coded to /usr/bin, while on windows we search the path for it.
This unifies the behaviour and searches the path on not-windows (macos, linux, etc) as well.
This could be desirable in a number of situations, but one particular use case is on macos where the system bash (/bin/bash) is 3.x and newer versions can be installed elsewhere on the path by homebrew.
Note that the agent does have a `--shell` flag, which can also be set by `BUILDKITE_SHELL` env var. This controls the shell executable that's used to execute the command phase of a job. I considered looking for a way to use that config option in the plugin/hook execution as well. However, …

search the path for bash when the bootstrap wants to run a script

---

agent/job_runner.go
clicommand/agent_start.go

Currently we start the bootstrap process without an explicit working directory. Presumably the operating system assigns it one, maybe the same as the main agent process?
We've seen an example of a customer build where the default working directory for the bootstrap didn't exist. This results in a fatal exception and the job fails to run: https://github.com/buildkite/agent/blob/bed05dda2d7bfb888d80c621af827ee2bce39144/bootstrap/shell/shell.go#L62-L65
Our process abstraction supports setting an explicit working directory for the child process, so we may as well use it: https://github.com/buildkite/agent/blob/bed05dda2d7bfb888d80c621af827ee2bce39144/process/process.go#L127-L132
I've opted to use the agent build path, which should be a directory that exists. There's no real reason for the …

Explicitly set a working directory when we start the bootstrap

---

go.mod
go.sum

We're were using a fork of gopkg.in/yaml.v2 (v2.1.1) with a patch to fix ordering of Maps when used in conjunction with named anchors ([this PR](https://github.com/go-yaml/yaml/pull/331)).
Upstream is now at v2.4.0, however the Maps+anchors patch hasn't been merged. We've updated our fork to be v2.4.0+the patch, and this will start using that new version.
The [list of changes between v2.1.1 and v2.4.0 is fairly small](https://github.com/go-yaml/yaml/compare/v2.1.1...v2.4.0
), but it includes a number of parsing bugs that could result in a panic, like the 3 commits linked [here](https://github.com/go-yaml/yaml/issues/323). I've confirmed this fixes a panic reported by one of our customers while uploading a pipeline.yml.

Use an updated version of our gopkg.in/yaml.v2 fork

---

agent/version.go

We've merged a few bug fixes since 3.28.1, and I'm keen to offer a pre-release version to a few customers so they can confirm the fixes ahead of a formal 3.29.0 release.
I've carefully followed the pre-release version format we used for 3.28.1-beta.1 to avoid a repeat of the build issues I caused a few weeks ago (see PR #1385)

bump version to 3.29.0-beta.1

---

.buildkite/pipeline.yml
install.sh

I am going to submit mips64le architecture，The main reasons are:
1、The mips64le architecture is also the mainstream cpu architecture (amd64, arm64), which is used by many users;
2、Golang supports cross compilation, and mips64le is officially supported;
Therefore, I hope that the release package also supports the mips64le architecture, which is convenient for more users.
Build result：
Signed-off-by: houfangdong houfangdong@loongson.com

support mips64le architecture target.

---

.buildkite/pipeline.yml
install.sh

A customer is keen to run the agent on IBM Z systems. It's an officially supported architecture for go, so in theory this should just work. Only one way to find out!

add s390x as a target architecture

---

agent/version.go

The build pipeline will recognise this as a pre-release version and start publishing it through our experimental channels (apt, yum,
binaries on s3).
I've carefully confirmed this version format matches the requirements!

bump version to 3.30.0-beta.1

---

agent/tags.go
clicommand/agent_start.go

ref https://github.com/buildkite/agent/issues/1420
Currently we have `wait-for-ec2-tags-timeout` config that waits for an EC2 instance's resource tags when buildkite-agent starts, but we don't have an equivalent config that waits for EC2's meta-data tags.
Add a config `wait-for-ec2-meta-data-tags-timeout` to set timeout waiting for ec2 meta-data tags when starting agents.

Add wait ec2 metadata tag timeout config

---

agent/s3_uploader.go
agent/s3_uploader_test.go

If a user passes a destination with a trailing slash, the artifact url ends up with a double slash in it (between the bucketPath and artifact path).
This trims the trailing slash before setting the bucketPath, so the rest of the code doesn't have to account for whether it has a trailing slash or not.
See also: https://github.com/buildkite/agent/issues/1145

Trim trailing slash from the bucketPath

---

.github/dependabot.yml

We don't need to update to every new docker image with the same version, we're mostly interested in getting the golang version bumps. Getting them only once per month is fine.

drop dependabot frequency from weekly to monthly

---

clicommand/agent_start.go

I'm [in the process of adding](https://github.com/creack/pty/pull/117) pty support on NetBSD to the upstream dependency - which I note has also changed location.
Meanwhile, this is a tweak to the default shell location that allows the agent to run with no configuration (other than token).

Use /usr/pkg/bin/bash as default shell on NetBSD

---

go.mod
go.sum
process/pty.go

This Go module has been moved to creak/pty, the latest release of which adds support for NetBSD (following on from #1430).

Replace kr/pty with creack/pty

---

clicommand/agent_start.go

Previously, the built-in bootstrap subcommand was called using the raw value of `os.Args[0]`, which meant it could fail if the path was relative to the current working directory, as jobs run in a build-specific directory.
This patch updates it to use `filepath.Abs` to resolve an absolute version of that path, so, for example, calling `.buildkite-agent/bin/buildkite-agent` from the user's home directory would no longer fail to run jobs.
It also treats an error resolving this path as fatal, though looking at the code for it this should only really happen if the current working directory is deleted, but given this happens at agent start that is extremely unlikely.
Fixes #1439

Resolve the absolute path to the buildkite-agent binary for bootstrap

---

clicommand/agent_start.go
metrics/metrics.go

Datadog has added support for the ["Distribution"](https://docs.datadoghq.com/metrics/distributions/) type of metric.
As a summary, the existing "timing" types in Datadog calculate things
like average, min, max, p95 on the client itself.  Therefore, it only
has visibility in what the client has access to. In the context of a
build job, this means that, in most cases, average == min == max == p95,
because they'll only be one job per flush interval.
A Distribution, instead, calculates all of these metrics server side at
the Datadog level itself. This makes it possible to aggregate metrics
across a wide variety of clients or sources. For example, you could have
a hundred Buildkite agents submit their job duration as raw data to
Datadog. Datadog will take the responsibility of calculating all …

Option to send Datadog Metrics as Distribution

---

agent/job_runner.go
api/jobs.go

We would like to also send how long a job was queued for when a job is
acquired by the agent to Datadog. This will empower teams to validate
that their clusters are not causing jobs to queue for "too long" (for
the users definition of that) on the assumption that all jobs will
eventually execute on an agent. Note that this :see_no_evil: that jobs
get stuck indefinitely.
This is not a complete Pull Request as we are waiting for our friends in
the Buildkite team to add the actual "scheduled_at" time to the acquire
job API, which will enable this pull request to actually calculate how
long the job was sitting in the queue for.

Send queue metrics to Datadog when job received

---

clicommand/step_get.go

Over in https://github.com/buildkite/docs/pull/989 I'm adding some clarification on getting a step outcome. I've tweaked this example to prevent people using `label` to reference the step. 
But in these examples, which step is used, the current one I think? Is this often used? Or would we be better off adding step `key` or `id` to these as well? 
```
$ buildkite-agent step get --format json
$ buildkite-agent step get "retry" --format json
```

Clarify step get usage

---

clicommand/agent_start.go

We need the path to start the bootstrap as a child process. We've previously detected it using os.Args[0], however there are some edge cases where that doesn't work (eg #1439).
We think os.Executable() might be a more reliable way to detect the path.

Use os.Executable() to detect path to the agents own binary

---

bootstrap/bootstrap.go
bootstrap/bootstrap_test.go
bootstrap/redactor.go
bootstrap/redactor_test.go
cliconfig/loader.go

This will remove the `output-redactor` experiment flag and enable it all the time.
I have read through the redactor source code and added a couple more comments to help me understand it. It appears sound to me. I identified one issue which I added a test for to verify where if two needles share a prefix the shortest one will be redacted while the tail of the longer will be printed. This seems unlikely to occur in practice.
I have also ensured support for an empty list of redacted vars throughout so that (once the flag is changed) a lack of vars to redact will act as the switch to disable the `Redactor` being added to the log stream processing. This gives us an escape hatch should there be any issues.
Updated docs are in https://github.com/buildkite/docs/pull/1073

Remove the experiment flag from output redactor

---

README.md
docs/macos.md

This updates and documents our OS and architecture promises to be current in terms of end-of-lifed operating systems. It also expands on the Docker section under installing to discuss the tagging system and lists the Docker base operating systems we build on top of.

Update architecture and OS support policy

---

agent/job_runner.go
clicommand/agent_start.go

Swap two more instances of `os.Args[0]` with `os.Executable()` for a more reliable way to locate the binary.
Follow up to https://github.com/buildkite/agent/pull/1444

Fix two more instances of os.Args[0]

---

bootstrap/bootstrap.go

Otherwise that folder becomes the highest priority path
and hides others futher down.
For example buildkite-agent might be in /usr/bin but you
have /usr/local/bin/cc that you expect to find.
If we added to the front of PATH, we'd hide that cc.
Fixes #1464.

Add BUILDKITE_BIN_PATH to end, not start, of PATH

---

.buildkite/pipeline.yml
.buildkite/steps/build-debian-packages.sh
scripts/build-debian-package.sh

The debian repository was missing some connections to properly package
up the `ppc64le` binary and deploy it to the apt repository.  This adds
the necessary pipes to get the bits flowing.
Closes #1472

[build] Add `ppc64le` packaging to Debian repository

---

.buildkite/pipeline.yml
.buildkite/steps/build-debian-packages.sh
.buildkite/steps/build-rpm-packages.sh
README.md
scripts/build-debian-package.sh
scripts/build-rpm-package.sh

Update DEB and RPM packaging to include ppc64(le). These architectures are community supported but we already build them so including them in our packaging is an easy win.
Fixes #1393

More architecture packaging

---

agent/job_runner.go

This provides a place to examine the proposed job environment before using as a process environment.
Notes on the todos I wrote up for this below.

Add pre-bootstrap hook which can green light the Job env before it is loaded into a process env

---

bootstrap/redactor.go
bootstrap/redactor_test.go

This was missed while reviewing the redactor code. I focused on the string indexing and arithmetic and completely missed that the skip table only covered bytes 0b0000_0000 through 0b1111_1110 allowing this out of range indexing.
Fixes #1478

Fix redactor table size

---

bootstrap/bootstrap.go

Whether the command errors or not, we always attempt to upload the artifact paths indicated in the `artifact_paths` command step property.
While we discussed only attempting an upload following a successful command (and phase) execution, changing this would be a backwards incompatible change. Instead, we decided to bypass the artifact exit code reporting when _both_ command and artifact upload errored. We still eventually exit with a non-zero code, but we preserve the command’s exit code so that any automatic retry attributes are applied.
Fixes #1099

Don’t override the command exit code when artifact_paths also fails

---

agent/artifact_uploader.go
bootstrap/bootstrap.go

To help diagnose instances where an artifact is not uploaded to customer configured storage, add logging when determining where to put the artifacts.
```
2021-08-17 09:36:42 INFO   Found 1 files that match "/etc/hosts"
2021-08-17 09:36:42 INFO   Uploading to default Buildkite artifact storage
2021-08-17 09:36:42 INFO   Creating (0-1)/1 artifacts
2021-08-17 09:36:43 INFO   Uploading artifact a9153a78-7122-41d9-9833-d627331005cc etc/hosts (750 bytes)
2021-08-17 09:36:45 INFO   Successfully uploaded artifact "etc/hosts"
2021-08-17 09:36:47 INFO   Artifact uploads completed succesfully
```
Fixes #1467

Add logging when creating artifact Uploader

---

.buildkite/steps/tests.sh
bootstrap/bootstrap.go

The multi-step plug-in clone needs to be fail safe. If the procedure is aborted at any point, there must not be a directory visible in the file system at the expected location, otherwise clone will not be re-attempted.
Using a temporary directory in the plugins path, and renaming the temporary directory to the final location, should avoid this. This carries the hazard that a failed checkout will linger in the plug-ins directory un-removed, but I have decided that the benefit is worth this 'directory leak'. There exists a general problem of files left behind by an aborted bootstrap process. We can use fixing that as an opportunity to fix this too.
Fixes #1193

Fix plugin error causing use of master branch

---

agent/s3.go

Use the provided region to discover the actual region.
This handles the cross region case where a pipeline’s `AWS_DEFAULT_REGION` points somewhere other than the bucket region.
Fixes https://github.com/buildkite/agent/pull/new/keithduncan/artifact-cross-region

Discover artifact bucket region using S3 manager API

---

README.md

With the [addition](https://github.com/buildkite/agent/pull/1501) of the Linux arm64 tests to our pipeline we can now commit Linux arm64 to "guaranteed to work".

Linux arm64 moving up in the world

---

clicommand/annotation_remove.go

From Slack:
```
oleg avdeev Today at 11:31 AM
Is there a way to make agent CLI to not retry on API error? if I do buildkite-agent annotation remove , if there is no annotation it retries 5 times with some backoff. In my scenario I just need it to remove the annotation if it exists, so i do `buildkite-agent annotation remove || true , which works but takes ~10s due to retries
```
This adds `410 Gone` as a status to not retry any more when removing an annotation.

Don't retry deleting annotations that are already deleted

---

bootstrap/bootstrap.go
env/environment.go
env/environment_test.go
hook/scriptwrapper.go
hook/scriptwrapper_test.go

A work in progress to support `unset` in hooks and propagate those to subsequent hooks and phases. The primary use case for this being AWS credentials stored in environment variables.
Fixes #1471

Change the environment diff algorithm to support removed keys

---

agent/artifact_downloader.go
agent/artifact_downloader_test.go

[Documentation](https://buildkite.com/docs/agent/v3/cli-artifact#downloading-artifacts-description) for `buildkite-agent artifact download` states:
> If the last path component of matches the first path component of your , the last component of is dropped from the final path. For example, a query of 'app/logs/*' with a destination of 'foo/app' will write any matched artifact files to 'foo/app/logs/', relative to the current working directory. 
> To avoid this behaviour, use a argument with a trailing slash. For example, a query of 'app/logs/*' and a destination of 'foo/app/' will write the matched artifact files to 'foo/app/app/logs/', relative to the current working directory.
`Download.getTargetPath` does behave in this way [here](https://github.com/buildkite/agent/blob/4d7e6819c11a18442 …

ArtifactDownloader: retain destination trailing slash

---

bootstrap/redactor.go
bootstrap/redactor_test.go
hook/scriptwrapper.go

This shook out from the docker-compose plug-in which exposes a command hook but also [exits](https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/6d94eaa362963f93c908560f27e254444625a4a4/hooks/commands/run.sh#L147), naughty. The combination of supporting [removed](https://github.com/buildkite/agent/pull/1488) environment variables, and a bug in the redactor produced a panic.
The redactor did not support being passed an empty list of needles, something we handled at [set up time](https://github.com/buildkite/agent/blob/61a06503fe330d93f00415c99d841215d82f8b4f/bootstrap/bootstrap.go#L1836-L1839) but missed at [reset time](https://github.com/buildkite/agent/blob/61a06503fe330d93f00415c99d841215d82f8b4f/bootstrap/bootstrap.go#L436). This is tested for in …

Fix empty command hook afterEnv breaking redactors

---

agent/artifact_downloader.go
agent/artifact_downloader_test.go
clicommand/artifact_download.go

Sorry @jonathan-brand in doing some testing I discovered that this is a backwards incompatible change that I’m going to have to revert.
I fooled myself into thinking it was fine because of the unit testing and docs I wrote in https://github.com/buildkite/agent/pull/1446 so felt this was a small change. What I failed to spot was that even though the unit tests do behave in this manner, on an integration basis the `filepath.Abs` was normalising both the trailing and non-trailing slash cases in to the non-trailing slash case. Exposing this distinction up can break pipelines and scripts that are passing a tailing slash path but weren’t previously receiving the trailing slash behaviour.
I do think we should expose this escape hatch for artifact downloads! But it will have to be behind a flag …

Revert "ArtifactDownloader: retain destination trailing slash"

---

bootstrap/bootstrap.go
bootstrap/integration/hooks_integration_test.go
bootstrap/integration/plugin_integration_test.go
hook/scriptwrapper.go
hook/scriptwrapper_test.go

An early exit hook would revert the shell to the bootstrap’s working directory which is the `builds` dir and not the specific build being worked on. This was because the `beforeWd` didn’t hold the value of the `beforeWd` but instead `os.Getwd()`.
To handle this case I have removed that otherwise unused variable from the `ScriptWrapper` struct, and we are now detecting the hook early exit case based on an absence of an `afterEnv` and return an error. The bootstrap handles that error by continuing on.
This matches the previous behaviour where we would: get a blank afterEnv and do nothing with it (since we didn’t support propagating removed vars up into the shell env), and get an empty string for the "new" working directory which because it wasn’t absolute we [append that empty …

Fix early exit hook wd change

---

.buildkite/steps/build-docker-image.sh
clicommand/agent_start.go

When running multiple agents on the same host, it is recommended to use the --priority flag if you want to force load to be balanced evenly across the hosts (https://buildkite.com/docs/agent/v3/prioritization).
The --spawn flag allows for easily registering multiple agents on the same host, greatly simplifying the operational overhead of running multiple agents.
However, --spawn and --priority can't be mixed.
This pull request proposes a general approach to combine the two flags to allow for the ease-of-use of --spawn and also solve the load balancing problem for which --priority is being suggested for. The solution is to automatically assign a --priority to each spawned agent based on the internal agent index.
I'm happy to contribute further to this (tests, etc.) as soon as there is a …

Combine --spawn and --priority flags

---

bootstrap/bootstrap.go
bootstrap/bootstrap_test.go
clicommand/agent_start.go
clicommand/global.go
clicommand/pipeline_upload.go
redaction/redactor.go
redaction/redactor_test.go

Work in progress with @eleanorakh and @pzeballos to catch and prevent pipeline uploads from including interpolated redacted vars.
Fixes #1469

Reject pipeline uploads containing redacted vars

---

agent/s3.go

If present this environment variable is used unconditionally and must be set to the region of the S3 bucket. Dynamic region discovery is bypassed completely owing to unreliability of the API.
This matches the secrets bucket algorithm in https://github.com/buildkite/elastic-ci-stack-s3-secrets-hooks/pull/54.
cc https://github.com/buildkite/elastic-ci-stack-for-aws/issues/937

Allow BUILDKITE_S3_DEFAULT_REGION to be used for unconditional bucket region

---

bootstrap/bootstrap.go
bootstrap/integration/bootstrap_tester.go
bootstrap/integration/command_integration_test.go

Insert a leading `'call '` for commands on Windows in the generated batch script per #1538 
I’ve also added a work in progress test for this functionality that I expect to fail pending finishing it off.
Fixes #1538

Support multiple commands on Windows

---

system/version_dump.go

I noticed we have a few agents connected from aix/ppc64. That's not a GOOS/GOARCH we compile for, but it's a platform supported by go and I assume an enterprising customer has built it themselves.
For our own metrics, it'd be nice to have some visibility into the AIX version when customers run the agent, similar to what we get from Windows, Linux and the BSDs. I don't have an AIX system handy to test on, but multiple sites I found via google suggest `oslevel -s` is where it's at.
While I was editing this file I checked the [full list of GOOS values support in go 1.17](https://gist.github.com/asukakenji/f15ba7e588ac42795f421b48b8aede63). We cover all the important ones, and a few have no evidence of ever being used by our customers (like android, ios and js). Solaris is interesting though …

report OS versions when running on AIX and Solaris

---

install.ps1

Given the buildkite-agent runs arbitrary code as administrator, we should lock down access to the agent's files. I've opted to only change the acls if we're creating the installation directory for the first time and just warn if the directory already exists and is world accessible. If I was being fancy, I'd probably only warn for world write permissions (and allow read permissions) but I'm not an expert on windows acls or powershell so I'm not sure I can figure that out how to do that in a reasonable length of time.
I have tested that a clean install with this script blocks read access from an unprivileged user but an administrator can still run the agent.
Installing with this script over the top of a previous install from `main` gives:
```
PS C:\Users\Administrator> iex ((New-Object …
```

Lock down file permissions on windows

---

agent/artifact_batch_creator.go

Previously, when attempting to batch-create artifacts, if the agent API returned a 500 error, we would just sorta say 'okay' and never try again, emitting a somewhat confusing log message of:
```
POST https://agent.buildkite.com/v3/jobs/<some job id>/artifacts: 500 (Attempt 1/10 retrying in 10s)
``` 
... and then a failure message with no retries.
This PR makes it so that when we run across a 500 when trying to batch-create some artifacts, we retry the operation, as the logs imply we should. also, 500s can be (though are not always) transient, so retrying them is a good idea regardless.
Closes #1565
Closes PIP-219

Retry 500 responses when batch creating artifacts

---

.buildkite/pipeline.yml
scripts/build-binary.sh

This updates the pipeline configuration to use [the `matrix` feature](https://buildkite.com/blog/announcing-build-matrix), which reduces repetition significantly.
One negative effect is that this may make builds take slightly longer, as in-build dependencies are now on the entire build matrix and not individual steps.

Use build matrix feature to simplify pipeline [PIP-200]

---

.github/dependabot.yml

It would be nice to slowly bump the various dependencies we have, to avoid situations like #1573 where a key dependency is nearly 2 years out of date.
On the other hand, we don't want to be overwhelmed by tiny bumps all the time.
Here's one way we could walk that path. Allow dependabot to open PRs with updates, but not more than 2 per week. I'm not wedded to these values, but I thought I'd start with a strawman.
The dependabot [config options are documented here](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#open-pull-requests-limit).
/cc @pda @moskyb

enable dependabot for go.mod

---

go.mod
go.sum

I'm not aware of any bugfixes or changes that we need urgently, but it's approaching 2 years since we last upgraded (PR #1234) and we don't want an important dep like this to trail too far behind. Mainly because the longer the lag, the harder it might be to get back to current.
Once this merges I might investigate whether it's worth enabling dependabot for go modules so the bumps can happen semi-regularly.
Note that I've confirmed the agent still builds, but I have not confirmed artifact uploading to AWS bits still work: artifact uploading to custom buckets, artifact downloading, and fetching ec2 tags.
/cc @pda @moskyb

update github.com/aws/aws-sdk-go to the latest v1 release

---

agent/agent_worker.go

This should minimize job "waiting for agent" time without
changing overall load on Buildkite servers.
Related: https://forum.buildkite.community/t/decrease-wait-time/1922

Ping immediately after completing a job

---

clicommand/artifact_shasum.go

Minor improvements to the help / usage text of `buildkite-agent artifact shasum --help`, plus some related tweaks to error messages.
- Explain the the hash was generated during upload and stored with Buildkite.
- Clarify that exactly one artifact must be matched by the search term.
- Remove misguidance that hashes for multiple artifacts may be printed.
- General copy fixes.

Help / usage / errors for buildkite-agent artifact shasum improved

---

agent/artifact_downloader.go
agent/artifact_downloader_test.go
agent/artifact_searcher.go
api/artifacts.go
clicommand/artifact_search.go
clicommand/artifact_shasum.go

The Artifact Search API endpoint supports filtering the search to `finished` artifacts, so that incomplete uploads are not included.
`buildkite-agent artifact download` and `buildkite-agent artifact shasum` probably want to apply that filter, otherwise they're likely to get stuck trying to download artifacts that don't exist.

artifact download (and shasum) only search for finished uploads.

---

agent/download.go
agent/job_runner.go
bootstrap/bootstrap.go
bootstrap/shell/tempfile.go
clicommand/agent_start.go

Buildkite Agent creates directories on the filesystem for a few reasons:
- if started with a `--build-path` that doesn't exist,
- when downloading artifacts,
- when checking out the codebase to be built,
- when checking out plugins,
- when checking out git mirrors,
- for various temporary files.
This pull request changes the mode passed to `os.MkdirAll` from `0777` to `0770`.
Note that the specified mode is masked by [umask](https://en.wikipedia.org/wiki/Umask) before the directory is created.
The default umask of most systems is `0022`, or at the very least `0002`.
$ echo "$(uname): $(umask)"
Darwin: 022
$ for img in archlinux debian ubuntu centos alpine; do echo -n "$img: "; docker run --rm $img sh -c umask; done
archlinux: 0022
debian: 0022
ubuntu: 0022
centos: 0022
alpine: 0022
Given …

Create directories only accessible by current user and group

---

bootstrap/git.go

Use [`net.JoinHostPort(host, port)`](https://pkg.go.dev/net#JoinHostPort) instead of `fmt.Sprintf("%s:%s", host, port)` to support IPv6 etc.
An existing test (`TestResolvingGitHostAliasesWithFlagSupport`) does cover this change.

use net.JoinHostPort not fmt.Sprintf

---

.buildkite/pipeline.yml
.buildkite/steps/test-go-fmt.sh
agent/download_test.go
agent/form_uploader_test.go
agent/s3.go
agent/version_test.go
bootstrap/bootstrap_test.go
bootstrap/integration/plugin_integration_test.go
bootstrap/shell/lookpath.go
bootstrap/shell/signal.go
clicommand/annotation_remove.go
clicommand/artifact_download.go
clicommand/pipeline_upload.go
env/environment.go
env/environment_test.go
hook/scriptwrapper.go
hook/scriptwrapper_test.go
logger/init_windows.go
mime/generate.go
process/pty.go
process/signal.go
process/signal_windows.go
redaction/redactor.go
system/version_dump.go
tools.go
utils/path_windows_test.go

**🤔 Problem:** Go fmt isn't evenly applied across this repo, leading to messy diffs when adjusting files that haven't had the formatter run across them, especially when (like me) you have format-on-save enabled.
also, code formatting is pretty uncontroversial (he says, opening a can of worms).
**✅ Solution:** 
- Add a step in CI ensuring `go fmt` has been run across all of the files in the project
- Run `go fmt` across all of the files in the project, to stop the above step from complaining

Make `go fmt` mandatory

---

clicommand/pipeline_upload.go
redaction/redactor.go

**🤔 Problem:** In https://github.com/buildkite/agent/pull/1523, we made it so that the `buildkite-agent pipeline upload` command would reject any pipeline yaml that had sensitive values in it. We shipped this as part of [v3.34](https://github.com/buildkite/agent/releases/tag/v3.34.0). This is an awesome security feature, and prevents a bunch of footguns, but unfortunately it's a breaking change, and we accidentally shipped it as part of a minor release.
**✅ Solution:** This PR reverts default redaction behaviour to how it was previously, with some slight changes:
- The newer behaviour (rejecting a pipeline upload if there's juicy secrets in it) is available with the `--reject-secrets` flag
- Even when the `--reject-secrets` flag isn't used, the command issues a warning that:
- There are …

Make secret value rejection on pipeline upload optional

---

bootstrap/bootstrap.go
bootstrap/config.go
bootstrap/shell/shell.go
clicommand/pipeline_upload.go
packaging/linux/scripts/after-install-and-upgrade.sh

so this PR was originally meant to fix [this particular instance](https://github.com/buildkite/agent/commit/732dc43b2530b9d4ce2633f5243cf5d54ee42adc#diff-4cfc709d07ebef6d3ace1658e50b325bdf115a978e2b4d6e6b2b388279c453a1R103) of `the the`, but apparently it's a pretty common occurence within the agent codebase 😅
This PR takes all of the instances of `the the` in the agent repo and replaces them with just the single definite article

Replace all instances of `the the` with just one `the`

---

agent/artifact_uploader.go
agent/artifact_uploader_test.go
api/artifacts.go
clicommand/artifact_shasum.go
clicommand/artifact_shasum_test.go

Begin to shift from SHA-1 to SHA-256 for artifact checksums.
- `buildkite-agent artifact upload` will calculate and submit both SHA-1 and SHA-256.
- `buildkite-agent artifact shasum --sha256` will print the SHA-256 hash (or error if there isn't one).
_Currently_ there's no server-side support for `sha256sum` in the API, so the uploaded SHA-256 will not be stored, and the `--sha256` option on `buildkite-agent artifact shasum` will always fail. But that support would be added if/when this PR merges.

Artifact SHA-256 checksum alongside existing SHA-1

---

agent/artifact_uploader.go
agent/artifact_uploader_test.go
api/artifacts.go
clicommand/artifact_shasum.go
clicommand/artifact_shasum_test.go

Basic test coverage for the `buildkite artifact shasum` command.
We don't have an established way to test our CLI invocations, and I think the way we wire up `github.com/urfave/cli` would need substantial refactoring to make it possible.
So instead, this pull request extracts a ` func searchAndPrintSha1Sum(…)` from the CLI action and tests that. The main API interaction, output and logging is covered by the test.
I'm interested in shifting from SHA-1 to SHA-256, so some coverage would be valuable.

Test `buildkite artifact shasum`, refactor for testability.

---

.buildkite/pipeline.yml

**🤔 Problem:** A recent change to buildkite's buildkite setup changed it so that only a subset of buildkite agent queues have access to ECR. this is a useful security change, but unfortunately, the docker builds for the agent run on the default queue
**✅ Solution:** Move our docker builds to the `elastic-builders` queue, which has access to ECR.

Run docker builds on the elastic-builders buildkite queue

---

CHANGELOG.md
agent/version.go

It got lost in git in the last PR, https://github.com/buildkite/agent/pull/1591, which mean that because there wasn't a new version, the release process didn't kick off.

Bump version for 3.35.0

---

redaction/redactor.go

This change removes the warning for an unredacted variable if said variable is empty (e.g. there is nothing to be redacted anyway).
We have a few variables that can be empty; each of these produces an insane amount of warnings in each lifecycle execution:
(^ this is only one variable and only a subset of lifecycles)

fix: don't warn about unredacted vars if var is empty

---

agent/download.go
agent/job_runner.go
bootstrap/bootstrap.go
bootstrap/shell/tempfile.go
clicommand/agent_start.go

Reverts buildkite/agent#1580
#1580 broke docker workflows for quite a few users, so we'll need to take another pass at folder permissions sometime in the future, in such a way that it doesn't break existing behaviour.

Revert "Create directories only accessible by current user and group"

---

.buildkite/pipeline.yml
.buildkite/steps/tests.sh
bootstrap/bootstrap.go

**🤔 Problem:** In bootstrap.go, we were accessing a variable `ctx` in a goroutine, but further down in the function, the `ctx` variable was being wrapped with a different context and rebound to the wrapped context, so the goroutine was referring to a variable that didn't exist anymore.
It's worth noting that this race condition has been rearing its head more often recently, and i'm not entirely sure why - the code causing the race has been in place for almost 2 years, so i can only think that until recently we weren't often calling `ctx.Done()` on the bootstrap process? but that also doesn't make much sense, because that context should have `Done()` called on it every time the bootstrap exits successfully.
So, in short, i'm not 100% sure what's going on, but this change should hopefully …

Fix race condition in bootstrap.go

---

CHANGELOG.md
agent/version.go

This PR also includes the changelog for 3.35.1, because of git reasons (tl;dr i did something that i shouldn't have done and it messed things up, but only a little bit)

Bump version + changelog for 3.35.2

---

CHANGELOG.md
agent/version.go

Due to a variety of git shenanigans, the changelog and version updates in the [`3-35-stable`](https://github.com/buildkite/agent/tree/3-35-stable) branch never came through to the main branch. This PR cherry picks those commits from the `3-35-stable` branch and adds them to the main branch (once it's merged)

Bring changelogs for 3.35.x series into main

---

agent/agent_configuration.go
agent/job_runner.go
clicommand/agent_start.go

Adds a new agent config option `--enable-job-log-file`.
When set, all logs for a job are written to a temporary file and exposed to the job via an environment variable `BUILDKITE_JOB_LOG`.
This log file can be used by post-command, pre-exit, and exit hooks to analyze the logs without having to fetch them via API (which is slower, and subject to race conditions). One use-case we have for this is log failure analysis of the command-step to enable dynamic retries.
This temporary file is deleted when the job finishes.

add option to enable job log file

---

agent/download.go
agent/job_runner.go
bootstrap/bootstrap.go
bootstrap/shell/tempfile.go
clicommand/agent_start.go

> nb: i'm not a unix expert, please correct me if i'm wrong in here
In UNIX-like operating systems (for example, Linux and macOS), all files have a set of permissions, represented by 3 sets of 3 bits of data. Each set of 3 bits (called a triad, which is also the binary representation of an octal digit) represents the permission set of a class of user. Each bit in the triad represents an **operation** (read, write, execute) that can be done by a class of users. One triad each is allocated for 
- The **user** - the user who created the file, or someone who has taken ownership of it since
- The **group** - the group that created the file
- The world - everyone else who's not that user, or part of the group
Each of these permission bits with the triad allows control over the operations that …

Create all directories with 0775 permissions

---

clicommand/agent_start.go

**This PR:** Cleans up a bit of wording around the `--disconnect-after-idle-timeout` and `--disconnect-after-job` flags, noting that when set to 0, `--disconnect-after-idle-timeout` means "don't disconnect idle agents".
Closes #1598

Clear up usage instructions around --disconnect-after-idle-timeout and --disconnect-after-job

---

.github/dependabot.yml
packaging/docker/alpine-linux/Dockerfile
packaging/docker/sidecar/Dockerfile
packaging/docker/ubuntu-18.04-linux/Dockerfile
packaging/docker/ubuntu-20.04-linux/Dockerfile

We currently use Alpine 3.12 in our Alpine release images (which are the defaults, ie if you run `docker pull buildkite/agent`, it'll give you an image based on alpine). 3.12 is [EOL as of yesterday](https://alpinelinux.org/releases/), and is also different to the alpine that we use in the build process, so we should try to keep these in line.
This PR:
- Updates the version of Alpine we use from 3.12 to 3.15.4, the latest available
- Formats all of the dockerfiles in `packaging/docker` (my editor autoformatted the two i changed, so i figured it was best to do them all)
- Adds the `packaging/docker` dir to the list of things that dependabot should check for updates for - this means that hopefully this won't happen again :)

Use Alpine 3.15.4 in agent release images

---

clicommand/agent_start.go

Before this change, the isSet method returns false even though the fields are set in the config file. Now the config file is honored.
Now I can disable repository hooks but enable plugins.

Fix no-plugins handling

---

clicommand/agent_start.go

We recently [merged a PR](https://github.com/buildkite/agent/pull/1579) that had been opened before we had CI checking that gofmt was being fulfilled, and so wasn't rejected on that basis. This PR fixes that formatting error.

Fix go fmt

---

clicommand/agent_start.go
clicommand/annotate.go
clicommand/annotation_remove.go
clicommand/artifact_download.go
clicommand/artifact_search.go
clicommand/artifact_shasum.go
clicommand/artifact_upload.go
clicommand/bootstrap.go
clicommand/global.go
clicommand/meta_data_exists.go
clicommand/meta_data_get.go
clicommand/meta_data_keys.go
clicommand/meta_data_set.go
clicommand/pipeline_upload.go
clicommand/step_get.go
clicommand/step_update.go
cliconfig/loader.go
logger/level.go

**🤔 Problem:** Some of the time, users of the buildkite-agent might not necessarily want or need all of the logs we're spitting out, either for cost reasons (storing logs can get pricy) or for readability reasons (i don't necessarily care about everything the agent is doing all the time.
**✅ Solution:** Add a cli flag, `--log-level` and an accompanying envar `BUILDKITE_AGENT_LOG_LEVEL`, to set the level of the logger on the agent. Now, if I set `--log-level error`, the buildkite agent logger will only output logs of level error or higher. This flag is enabled for all CLI commands, except `bootstrap`.
This PR is best read commit-by-commit.

Log levels

---

clicommand/global.go

A bit of code that was accidentally included in #1635 causes the agent to panic with a nil pointer dereference, because we're calling a method on a logger that doesn't exist.
This PR removes that log call. Oy vey.
Fixes #1652

Fix nil pointer deref when using --log-format json

---

bootstrap/shell/export_test.go
bootstrap/shell/shell.go
bootstrap/shell/shell_test.go

It is unlikely that anyone will care about how much time a command
took more than about 5 significant digits:
- If you are expecting a command to take a few milliseconds, maybe you
care down to the microsecond.
- If you are expecting a command to take a few hours, maybe you care
how many minutes or seconds, but I very much doubt you care about how
many microseconds.
By default, Buildkite reports durations with extreme precision, which
can be distracting. Instead, round off durations so that at most 5
digits are present in the displayed duration.
Here's what the displayed output looks like, both before and after, for builds of different durations:
```
before: 1µs
after:  1µs
before: 10.07µs
after:  10.07µs
before: 100.47µs
after:  100.47µs
before: 1.00059ms
after:  1.0006ms
before: …
```

bootstrap/shell: round off command durations

---

.buildkite/steps/upload-release-steps.sh

Currently, we don't do any real pre-releasing for the agent. We have three release "streams", `edge`, `beta`, and `stable`, but we only really ever use them when making a stable release, which is underutilising them, IMO.
This PR repurposes the `edge` release stream, and makes it so that whenever we successfully merge to main, we'll publish the `edge` release stream with whatever's in main at that time. The main benefit of this is that it makes it easier for customers to get at new features prior to their full release, whether that's because they like to live dangerously, or if they're acceptance testing something for us.
To use this release stream, customers can use the plug `edge` into the `BuildkiteAgentRelease` parameter in the elastic stack. I would argue that all of our agent builds …

Release Agent Edge any time a main build completes

---

bootstrap/integration/hooks_integration_test.go

It doesn't work, and hasn't for ages :/

Skip pre-exit on cancel test on darwin

---

agent/pipeline_parser.go
agent/plugin/plugin.go
agent/plugin/plugin_test.go
bootstrap/bootstrap.go
bootstrap/config.go
bootstrap/shell/shell.go
bootstrap/tracing.go
clicommand/pipeline_upload.go
env/environment.go
env/environment_test.go
env/export.go
env/export_test.go

The main reason behind this refactor is the `*Environment.ToMap()` method. The implication behind the naming of this method is that it returns a copy of the environment in a map representation, but what it actually does is just return the underlying map that Environment is implemented on top of. This is used in a variety of ways across the codebase, and we actually reach into Environment's pockets andmodify this underlying map a fair bit. This in mind, so it makes sense (to me, anyway) to remove the confusingly-named middleman.
One possible drawback of this approach is that it makes it easier to accidentally "manually" set a k/v pair in th env, ie by calling `env["foo"] = "bar"`, buuuuuuuuuuuut it was already pretty easy by calling ToMap(), so i'm happy with this tradeoff, but I'd be very …

Refactor env.Environment from wrapping a map to being a map

---

clicommand/bootstrap.go

A recent upgrade to the documentation spellcheck picked up this error. This change upstreams the correction made in the docs repo.
https://github.com/buildkite/docs/pull/1585

Fix bootstrap usage capitalization of "Buildkite"

---

clicommand/global.go

The description from the docs around the the `-log-level` option doesn't include the rest of the possibles values: https://buildkite.com/docs/agent/v3/cli-pipeline#options
This was raised by a customer.
That doc section gets automatically generated from this code.
I'm adding the rest of the possibles values according to https://github.com/buildkite/agent/blob/main/logger/level.go#L19

Update log-level description

---

agent/download.go
agent/job_runner.go
bootstrap/bootstrap.go
bootstrap/shell/tempfile.go
clicommand/agent_start.go

We've tried [a bunch](https://github.com/buildkite/agent/pull/1580) of [solutions](https://github.com/buildkite/agent/pull/1616) to make file permissions for directories created by the agent a bit more restrictive, so that other processes can't subtly change what the agent is doing, but every time we've tried, it's broken docker workflows for our customers because of docker namespace remapping, and the fact that docker (rightly!) recommends that users don't use the root user inside containers.
This PR reverts all changes to directory permissions, and goes back to letting the umask dictate what permissions files get. This means that in most cases, things will get assigned 0755 perms, but this can be overridden by the user.

Okay, I give up, everything has 777 permissions again.

---

go.mod
go.sum
metrics/metrics.go

This PR updates our direct usage of the datadog-go library to v5.1.1. Our go.mod file still includes v4.8.2, as it's an indirect dependency (our tracing integration -> dd-trace-go -> datadog-agent/pkg/obfuscate -> datadog-go v4.8.2)

Update datadog-go to v5.1.1

---

bootstrap/shell/shell.go

Noticed this potential issue while reading through this code. Due to how the flock library will set always return (false, err) this code wouldn't print other lock errors since it would always hit the first branch. This flips the logic to make sure the err is checked first then falls through when the more typical case of the lock being held by someone else most of the time. gofrs/flock will never return (true, err): https://github.com/gofrs/flock/blob/master/flock_unix.go#L158

Reverse error checking logic to make sure lock errors are logged

---

env/export.go
env/export_test.go

When we run hooks as part of a build, the agent pulls [some malarkey](https://github.com/buildkite/agent/blob/1a9c92c951fe9c962f4b0be4229f1eeeb6faf35d/hook/scriptwrapper.go) to capture the environment variables added by that hook.
As part of this process, the agent uses the bash `export -p` builtin to export the environment of the current process in a form that can be run as a script. The output looks kinda like:
```Bash
declare -x COLOUR="chartreuse"
declare -x FLAVOUR="spicy"
declare -x TEXTURE="abrasive"
```
We then parse this output into our `env.Environment` type, and use that to construct a diff between what the env looked like before the hook was run, and what it looked like afterward.
The issue here was that this parsing process didn't know how to (or that it should) unescape a …

Unescape backticks when parsing env from export -p output

---

.buildkite/docker-compose.yml
scripts/ruby-env

When running multiple jobs on the same machine, they use the same docker network by default, which means that the two running jobs can run into a race condition where they both create a docker network with the same name, leading to a build failure (see https://buildkite.com/buildkite/agent/builds/4420#0181ba48-c82c-4b92-bac9-5bff1743a373).
~~This PR adjusts the build script to add a random number to the end of the docker network name, meaning that we have a 32767x lower chance of a network name collision~~
This PR uses the COMPOSE_PROJECT_NAME environment variable set to the job ID of the build we're running to avoid network name collisions

Use non-conflicting docker networks

---

env/export.go
env/export_test.go

Previously, if a line in the output of `export -p` contained multiple options on the `declare` call (eg, there was an array in there - `declare -ax ARRAY=("red", "green", "blue")`), env.FromExport() would have some very weird behaviour - it could eat variables entirely, leading to them being unset in the build that the agent ran - more context for buildkite staff [here](https://3.basecamp.com/3453178/buckets/23112918/messages/5089354108#__recording_5089608441), but the TL;DR is that a hook was exporting an array variable, and it was causing other variables - important ones like `PATH` and `PWD` - to go missing.
**This PR:** Teaches env.FromExport to be able to introspect the args passed to each `declare` call, and allows it to ignore anything that it won't be able to parse. At the moment, …

Don't blow up when a hook exports an array

---

CHANGELOG.md
agent/version.go

`CHANGELOG.md` curated from `ghch --format=markdown --from=v3.36.1 --next-version=v3.37.0`
`baseVersion` updated to `"3.37.0"`.

Prepare v3.37.0 release

---

README.md

Listing the OS/arch that we don't fully support probably takes more space than it's worth.
And, add some clarity that we don't offer official support for these Tier 3 targets.

README briefer/clearer re. Tier 3 platforms

---

.buildkite/pipeline.yml
bootstrap/shell/shell_test.go
race/disabled.go
race/enabled.go

**This PR:** 
- Makes the test step with the race detector enabled hard-fail
- Skips the current failing race test - the logic here is that we don't want to add any further data races to the code. The only one that currently gets caught by the race detector is a bug in a library we use for testing, and we don't want new data races to get missed because this step is currently soft-failing

Better race testing
